### ISSUE TITLE
deleting logged in user causes persistent errors

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#1031]
PHP Warning:  Illegal string offset 'name' in /usr/local/etc/inc/auth.inc on line 245
PHP Warning:  Illegal string offset 'name' in /usr/local/etc/inc/auth.inc on line 245
PHP Warning:  Illegal string offset 'scope' in /usr/local/www/system_usermanager.php on line 917
PHP Warning:  Illegal string offset 'name' in /usr/local/www/system_usermanager.php on line 924
PHP Warning:  Illegal string offset 'descr' in /usr/local/www/system_usermanager.php on line 926
PHP Warning:  Illegal string offset 'uid' in /usr/local/etc/inc/auth.inc on line 516
PHP Warning:  Illegal string offset 'scope' in /usr/local/www/system_usermanager.php on line 936
PHP Warning:  Illegal string offset 'name' in /usr/local/www/system_usermanager.php on line 938
PHP Warning:  Illegal string offset 'name' in /usr/local/etc/inc/auth.inc on line 245
PHP Warning:  Illegal string offset 'uid' in /usr/local/etc/inc/auth.inc on line 516
PHP Warning:  Illegal string offset 'name' in /usr/local/etc/inc/auth.inc on line 485
PHP Warning:  Illegal string offset 'uid' in /usr/local/etc/inc/auth.inc on line 590
PHP Warning:  Illegal string offset 'name' in /usr/local/www/system_usermanager.php on line 169

**Comment by ShaRose** [comment]
I recently had this issue and I should note that I found a workaround which should help locate the bug: I found that when you remove a user, it still leaves a blank user entry in the configuration file.

The fix is to ssh in, use your favorite text editor to open /conf/config.xml, search for "<user/>", and remove that line. After that, restart the web interface and the problem seems to be resolved.

**Comment by fichtner** [comment]
Still cannot reproduce this properly in my tests. What am I doing wrong?

**Comment by fichtner** [comment]
@ShaRose  (explicit ping)

Can you verify that System: Configuration: History diff for configs shows a discrepancy between empty user tag or being flushed correctly? Thanks!

**Comment by ShaRose** [comment]
As posted in IRC, Yes, I was able to verify that it was saving an empty user tag. I also verified the cause of the bug is if the user has a moment of stupidity and deletes himself. Was able to verify behavior in a LiveCD vm. Also validated that deleting other logged in users is fine: It's only if you do it to the currently logged in user that the bug manifests.

Underlying bug may be caused by how it does history: the log entry actually used the name of the deleted user. Either way the easiest and sanest fix is 'Don't show the delete user button for the currently logged in user'. Or maybe a helpful error message reminding them that deleting yourself is probably not what you actually intended.

**Comment by fichtner** [comment]
<img width="1115" alt="screen shot 2016-07-23 at 6 22 08 pm" src="https://cloud.githubusercontent.com/assets/1915288/17078958/89aa7200-5102-11e6-853b-c56fddbdd08b.png">

**Comment by va176thunderbolt** [comment]
I stumbled on this issue, which still persists.

To reproduce, create system with user "bob"
Backup system
Delete user "bob" and add user "fred" setting him as a admin
Log in as user Fred
Restore backup created above.

I worked around the issue by:
1) Deleting user "fred" from /etc/passwd (not sure if it's necessary, but I did it anyway)
2) Deleting user fred's config in the /conf/config.xml

In multi-admin environment, it's common to restrict use of the root account, and create individual accounts for each admin to track who made what changes. I stumbled into this while restoring some backups into a vm image to do some forensic work.
