### ISSUE TITLE
unbound: add CNAME support

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#1041]
PTR was also asked for, maybe we should make the framework more flexible...

via: https://forum.opnsense.org/index.php?topic=3246.0

**Comment by AdSchellevis** [comment]
@fichtner we can include the unbound cname tag, but its not very likely that it will actually work. From what I can find.

> 
The only time your entry will be returned is if the client queries for a CNAME, which in practice means it'll probably be returned quite rarely


(source https://www.bentasker.co.uk/documentation/linux/279-unbound-adding-custom-dns-records)

The information on the unbound mailing list:
http://unbound.net/pipermail/unbound-users/2009-March/000509.html

Add the tag any way? or close the issue?

**Comment by fichtner** [comment]
Let's keep it on 17.1, wait for feedback. It should be possible to add this in the advanced settings to collect valuable information of how that works out from the actual client side and that will likely decide in the end :)

**Comment by fichtner** [comment]
don't really need this it seems

**Comment by MarkNBroadhead** [comment]
Lack of alias/cname support in unbound is the only thing keeping me on pfsense. I'd really like this to be implemented.

**Comment by MarkNBroadhead** [comment]
I believe it should either be in [services_unbound.php](https://github.com/pfsense/pfsense/blob/master/src/usr/local/www/services_unbound.php) or [services_unbound_host_edit.php](https://github.com/pfsense/pfsense/blob/master/src/usr/local/www/services_unbound_host_edit.php).

The implementation is in services_unbound_host_edit.php in the section, "Additional Names for this Host", which allows configuration of aliases (cnames).

**Comment by fichtner** [comment]
Nope.

https://github.com/pfsense/pfsense/search?utf8=✓&q=cname&type=
https://forum.netgate.com/topic/110680/dns-cname-records-posible-with-unbound/5

**Comment by MarkNBroadhead** [comment]
@fichtner You are right. PfSense's implementation does not create CNAMES although it appears to do just that. It create multiple A records all tied to one IP address in configuration and in the UI, creating the convenience of a CNAME without CNAME support. I will open a different feature request for this to be added as it is terribly useful.

Your search in source for "cname" returns no results because the PfSense implementation referred to these other hosts "aliases". The implementation is in the file I linked. 

![image](https://user-images.githubusercontent.com/7092769/53543312-84b3ba80-3adf-11e9-825b-a07d5b955bd6.png)

**Comment by fichtner** [comment]
@MarkNBroadhead we have this as well :)services: unbound dns: overrides
