### ISSUE TITLE
apinger exits when no useable targets but is not restarted

### ISSUE THREAD

**Issue by enoch85** [opnsense/core#1057]
```
Jul 9 01:45:12	apinger: No usable targets found, exiting
Jul 9 01:45:12	apinger: Starting Alarm Pinger, apinger(59842)
Jul 6 00:56:04	apinger: No usable targets found, exiting
Jul 6 00:56:04	apinger: Starting Alarm Pinger, apinger(10525)
```

![deepinscreenshot20160709025129](https://cloud.githubusercontent.com/assets/4511254/16705077/2a1eadb6-4580-11e6-9650-aa42c21e06b4.png)

```
Versions	OPNsense 16.1.18-amd64
FreeBSD 10.2-RELEASE-p19
LibreSSL 2.3.6
```

It seems like apinger doesn't get restarted after a failure. Exactly the same issue is reported [here](https://forum.pfsense.org/index.php?topic=71908.0) on pfSense.

Is this something that is known?

**Comment by fichtner** [comment]
We do have a new development home for apinger: https://github.com/opnsense/apinger

Truth is the pfSense patches made apinger a lot worse:

* Original apinger uses static raw sockets and privilege drops so it doesn't have to reconfigure. That breaks now using apinger as a gateway monitor because it needs to pin a route, which it can't if it uses the best one available.
* Due to privilege drop, apinger is not capable of reconfiguring itself after initial startup.
* Since the privilege is dropped, not separated, apinger cannot execv() and reload.

From a service perspective, apinger needs to reconfigure itself properly, see:

https://github.com/opnsense/apinger/issues/2

I have ideas to amend the apinger issues, but they take time and dedication and help in testing.

Closing this issue in favour of the one posted above. Let's take the discussion and questions there. :)
