### ISSUE TITLE
New user did not access to opnsense shell 

### ISSUE THREAD

**Issue by ali-reza-zareian** [opnsense/core#1062]
hi 
When a new user is created with this scenario ,they don't  access to opnsense shell if they login in to console.

1. create new voucher database
2. create new group without any member and privilege(named mygroup)
3. create new user that is member of mygroup only.(named public)
4. add privileged access to shell for public user

Now public user can login to console but FreeBSD shell is appeared.
[Test in 16.7.rc1]

thanks

**Comment by fichtner** [comment]
Only the root user can execute the opnsense shell menu.

In order to do this with an arbitrary user, it needs "admin" privileges, which add "wheel" group privileges underneath. Then in /usr/local/etc/sudoers select your preferred "wheel" group allowance. Afterwards, you can wheel to the root shell using:

# sudo su
