### ISSUE TITLE
firmware: auto-reinstall of packages suffering from ABI breakage

### ISSUE THREAD

**Issue by fraenki** [opnsense/core#1083]
Just upgraded a box from 16.1.18 to 16.7 and had the same issue as described in #565. The fix was (again) to forcefully reinstall the relayd package.

Shouldn't this package automatically be upgraded/reinstalled, especially when upgrading to a new major release?

**Comment by fichtner** [comment]
No. No excuses here, just facts. Skip forward for questions on how to solve this within OPNsense. :)

FreeBSD offers two ways to deal with this:

1. Refresh *all* packages after an ABI bump (obviously not an ABI bump but it happens all the time from 10.1, 10.2, 10.3...), or
2. Build all packages from the last compatible supported version and hope everyone migrates over before the build host is never than the last user host.

Both of them are not so pretty.

So for OPNsense we have the same problem and we could assemble a list, but we can never be sure about all the required auto-reinstalls unless we see the breaks happen after upgrade, unless we don't want to end up refetching/reapplying all packages all the time.

The worst part is over since having a GUI for this reinstall operation, but we should proceed with a smarter fix on our way to 17.1. Open for further input :)

**Comment by fraenki** [comment]
FWIW, on plain FreeBSD I always reinstall all packages when doing major upgrades. While _this_ wasn't a major FreeBSD upgrade (only 10.2 -> 10.3) it was a major upgrade for OPNsense. IMHO it's OK to reinstall all packages in this case. 

And we're currently well below 200 packages on regular installations so this wouldn't hurt too much I guess.

**Comment by fichtner** [comment]
Ok, thanks, well get this done one way or another. This will be a hard requirement for going to FreeBSD 11 eventually. :)

For reference, this already works:

    # opnsense-update -fp

**Comment by fichtner** [comment]
This will be fixed when upgrading to 17.1, as we are adopting a broader upgrade schema in those cases
