### ISSUE TITLE
"console vidconsole is invalid" when booting UEFI

### ISSUE THREAD

**Issue by backerman** [opnsense/core#1091]
When booting system, /boot/loader outputs the above message to video and loader does not show the boot menu on the video output.

Root cause: On a UEFI system, the console specification should be "comconsole,efi" instead of "comconsole,vidconsole"; changing /boot/loader.conf appropriately fixes this.

I'm using OPNsense 16.7-amd64.

**Comment by fichtner** [comment]
Hi Brad,

Is this a VGA/CD-ROM install with the console flipped on afterwards?


Thanks,
Franco

**Comment by fichtner** [comment]
How about making 'Secondary Console' configurable individually, adding efi to the mix. How does that sound?

**Comment by Table-09** [comment]
WHAT IS THE SOLUTION?????

I AM ON CURRENT VERSION, ENABLED COM AS SECONDARY, AND NOW THIS WORTHLESS PILE OF CRAP WILL NOT BOOT.

I CANNOT EDIT THIS ON LINUX

ITS STUCK ON THE SCREEN "VIDCONSOLE IS INVALID" 

KEYBOARD DOES NOTHING
RESTARTING DOES NOTHING
CANNOT CHANGE ANYTHING
BOOTED INTO WINPE NOTHING
BOOTED INTO LINUX - NOTHING
UNSCREWED EVERYTHING AND PLUGGED THE DRIVE INTO DESKTOP - NOTHING
PLUGGED INTO DEDICATED UBUNTU MACHINE - NOTHING
PLUGGED INTO DEDICATED ARCH LINUX MACHINE - NOTHING

WHAT IS THE POINT OF COM OR ANY OF THIS WHEN YOU CANNOT REVERT THESE CHANGES??????
THIS LITERALLY BREAKS OPNSENSE, I HAVE TO COMPLETELY WIPE AND DO A BRAND NEW INSTALL AGAIN BECAUSE THERE IS NO DOCUMENTATION ON THIS ERROR

WHY CAN I NOT CHANGE THIS BACK? IT MAKES NO SENSE FOR ONE OPTION TO ENABLE A SECONDARY PORT SHOULD CAUSE THIS TO HAPPEN.

**Comment by Table-09** [comment]
can someone PLEASE explain how to edit the config of opnsense????

I don't understand how I'm expected to ssh into something that is stuck in pre-boot
I can't edit the config  file or access the disk in windows mac or linux

the fact that it's so easy to enable this and yet when I search google for keywords "VIDCONSOLE INVALID" nothing comes up other than this github.

**Comment by jeyrb** [comment]
Still happening in 2025, with twist that boot halts completely. Too many times for me, more zfs faffing than I ever want to do, I'm out, back to Unifi gateway

**Comment by fichtner** [comment]
Efforts to reach affected users were made in 2016 as far as I can see. At the moment there are no plans to work on this given the few people reporting this over the years.
