### ISSUE TITLE
ADSL (WAN: PPPoE) time based forced disconnect possible? 

### ISSUE THREAD

**Issue by rmx-it** [opnsense/core#1146]
Hi,
is it possible in opnsense 16.7 to implement an cronjob to do the forced disconnect at a given time?
I'd prefer to do the disconnect outside of the working hours...

Greetings
...
Mike

**Comment by fichtner** [comment]
Hi Mike,

There is a interface reset target for Cron. Right now it's missing a way to gracefully select the interface instead of hardcoding it. Bigger issue is the disconnect: reconnect/reconfigure is the normal use case, but in this case it sounds like t's not an on-demand connection and/or there is no idle time set in the interface settings?


Cheers,
Franco

**Comment by rmx-it** [comment]
Hi,
all I want is to stay (nearly) allways on and to do the forced reconnect during night time.

In former times I used mpd5 directly and enabled the webconsole:

    ....
    set user admin <Passwd> admin
    set web self 127.0.0.1 5006
    set web open
    ....

Then one could use curl to gracefully manage the PPPoE connections:

To close:

    curl "http://admin:<Passwd>@localhost:5006/cmd?link%20Lmypppoe&close"

To open:

    curl "http://admin:<Passwd>@localhost:5006/cmd?link%20Lmypppoe&open"

**Comment by fichtner** [comment]
Yes, the "interface reset" cron job (system: settings: cron) will do that for you. The only thing you need to add is the interface name from the config entry (unique internal identifier: wan, lan, opt1, etc.)

**Comment by rmx-it** [comment]
Hi,
I'll try.

Thanks!

Greetings
...
Mike

**Comment by rmx-it** [comment]
Hi,
yes. Seems to work.

Thanks!

Greetings
...
Mike
