### ISSUE TITLE
Feature Request: Add local networks alias

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/core#1241]
Add an alias which contains all local networks like lan network, dmz network to simplify working with networks where wan net is also an RFC 1918 network, so I can say "not local networks" in floating rules.

**Comment by AdSchellevis** [comment]
@fabianfrz I'm not a big fan of those auto generated rules, mainly because you need to probe the real interfaces to know the networks... A rebuild of the filter code is currently in progress, I rather don't add new complex hooks in now.

**Comment by fabianfrz** [comment]
@AdSchellevis shouldn't that be possible from the config.xml?
It should not be hard to generate it because the alias is just "* net" except the wan networks (which should be easy to detect as they should have an gateway which is also in the configuration)

for example
internal_networks = { lan net, dmz net}

so a firewall rule can be created which has the destination ! internal_networks (which should be the internet + private network of the provider)

**Comment by AdSchellevis** [comment]
@fabianfrz not sure if I follow you correctly, but what happens when one (or more) of the extra networks connect to the internet too? (multi wan)
I have no problem with adding some simple logic to the aliases for selecting (only static) nets for specified interfaces (a bit like selecting countries), I'm just not convinced that we should add an alias "internal networks" by default (and I don't want to probe networks either).

**Comment by fabianfrz** [comment]
in case of multiple wan connections, any of those connections and are not internal. As an internal network I consider any network, which is administratively fully under the administrators control.

**Comment by AdSchellevis** [comment]
Maybe its better if you write some (pseudo) code to demonstrate how the alias should be populated, I think your missing something. I really want to avoid adding a lot of magic, but if it's something simple and always functions, why not.

**Comment by fabianfrz** [comment]
```ruby
def internal_network_list
  internal_networks = []
  interfaces.each do |interface|
    next if interface.is_wan_interface?
    internal_networks << get_network_address_from_interface(interface)
  end
  return internal_networks
end
```

**Comment by AdSchellevis** [comment]
In my opinion this construction has exactly the issues I mentioned in my first comment.
1) You don't know which interfaces the customer uses as wan (other then the "wan" interface)
2) You need to probe the interfaces to determine the actual addresses (due to dhcp type interfaces).

**Comment by fabianfrz** [comment]
1. It should be possible because this interface has a gateway where in case of IPv4 0.0.0.0/0 is routed to - also known as the default gateway (visible in the configuration as "defaultgw"="1")
2. This is a single ifconfig call

**Comment by AdSchellevis** [comment]
I don't think we're going to agree here, because of a very different view on the subject. 

The logic you need to build here has some assumptions in it which doesn't always have to be true, and that's why I don't think we should add this (policy based routing for example).

From an architectural point of view its not a very good idea to clutter all together, because of events leading to changes which then automagically need to propagate over different parts of the system (dhcp change, leading to changes in your aliases, which then needs a reload of your filter or some other component). 
This kind of behaviour is exactly what we tried to avoid all the time (clean-up a lot of it), so I'm not to enthusiastic pulling new ones in.

Maybe we could solve some of this using a plugin registration to manage "dynamic" aliases which transfers the responsibility to a another service which is in charge of your alias.

**Comment by fabianfrz** [comment]
So keep it as it is for now (and I will have to create this alias by hand)?

**Comment by AdSchellevis** [comment]
I'm afraid so, I don't mind keeping the issue open for some time until we can think of a better solution which matches all criteria.

When there's time we could add some plugin option for the aliases, so you can add some script for your "local networks"...

**Comment by AdSchellevis** [comment]
timeout due to inactivity

**Comment by SecT0uch** [comment]
This feature could be very useful. Or even an "Internet" alias.
Would it be possible to reconsider it ?

**Comment by x-jokay** [comment]
You can add an alias `RFC1918` yourself :wink:

![RFC1918](https://user-images.githubusercontent.com/18613935/95655371-17636a80-0b07-11eb-928b-8823f655b457.png)
