### ISSUE TITLE
(Proxy) NAT-Rules

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/core#1242]
The (proxy) NAT-rules should be reworked because each interface can lead to four rules:
- IPv4 coming in on interface x on port 80 redirect to 127.0.0.1:http_proxy_port
- IPv4 coming in on interface x on port 443 redirect to 127.0.0.1:https_proxy_port
- IPv6 coming in on interface x on port 80 redirect to [::1]:http_proxy_port
- IPv6 coming in on interface x on port 443 redirect to [::1]:https_proxy_port

Maybe this rules can be automatically generated from the proxy configuration.
It would be also a good idea to support the selection of multiple interfaces in the Port-Forwarding rules.

**Comment by AdSchellevis** [comment]
It sounds like a good idea to support multiple interfaces for the nat rules, as long as they might convert to additional rules in the actual rule set.

I'm reworking the filter logic. Given the fact that interfaces might vanish (due to missing forced constraints) it looks like a better plan to use additional rules for the interfaces.
