### ISSUE TITLE
deciding what to do with get_possible_listen_ips()

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#1257]
Hi Ad,

Since you did the interface plugin hook work, can you take a look at this function? It seems to duplicate code (OpenVPN!) and do things some other function can probably do too?

Thanks,
Franco

**Comment by AdSchellevis** [comment]
ok, this smells, both get_possible_listen_ips() and get_possible_traffic_source_addresses() are weird and confusing.

The functions return an ip address or an interface name, which is quite confusing to start with.
Both are not very heavily used, but fixing this properly could get complicated (because the interface name is translated into the current ip later on).

Most usages would probably be better of when using the current ifconfig output, storing the interface and hoping the service will restart on state changes is generally not a very good idea.

I will join both together for now, so we can choose a proper behaviour later. (personally I vote for ditching the option to bind to interface names and use ifconfig to know what to use, but there is user impact there).

**Comment by fichtner** [comment]
Migration made no difference, so that's good. This will likely move to 17.7, no larger experiments now. :)

**Comment by fichtner** [comment]
Related to a change in https://github.com/opnsense/core/commit/f344e9d4471a0353a9be82dad1979c7791e40502 -- finally decided to ditch this in favour if a simpler "Interface expand all IPs" approach we have been introducing here and there over the years.

**Comment by fichtner** [comment]
os-snmp is the only plugin and is scheduled for removal in 19.1

**Comment by fichtner** [comment]
os-snmp no longer uses the function... let the fun begin!
