### ISSUE TITLE
bug prevents editing Interfaces

### ISSUE THREAD

**Issue by ryoku-cha** [opnsense/core#128]
trying to open the edit page for one of the Interfaces (LAN, WAN, ...)
(for example -> https://<opnsense-ip>/interfaces.php?if=lan)
results in the following error:
"Fatal error: Cannot create references to/from string offsets nor overloaded objects in /usr/local/www/interfaces.php on line 68"

this may have been caused by the latest upgrades (which included many php packages)

**Comment by fichtner** [comment]
Done. :)

**Comment by YordanYordanov** [comment]
The issue seems to occur in services_wol_edit.php too:

System Information:
FreeBSD 10.0-RELEASE-p16 #0 d6e2a1a(master): Sat Jan 17 14:23:30 CET 2015     root@sensey:/usr/obj/usr/src/sys/SMP
OPNsense 15.1.9-3505b0423 (amd64)
OpenSSL 1.0.1m 19 Mar 2015

PHP Errors:
[14-Apr-2015 22:24:50 Europe/Sofia] PHP Fatal error:  Cannot create references to/from string offsets nor overloaded objects in /usr/local/www/services_wol_edit.php on line 46

**Comment by AdSchellevis** [comment]
Found it, should be fixed with https://github.com/opnsense/core/commit/f1a31bd0a141900b532dae80c6a60233f50ca0ad
