### ISSUE TITLE
Exception URL list for Captive Portal

### ISSUE THREAD

**Issue by jolentes** [opnsense/core#1289]
**As** an Administrator
**I would like** to enter as list of domains or URL's that bypass the captive portal
**so that I** can allow access to selected Website / Services without the user being authenticated.

**Comment by AdSchellevis** [comment]
@jolentes you can only whitelist ip and mac addresses, captive portal doesn't inspect the traffic on layer 7 (although you can combine a captive portal with a transparent proxy to whitelist addresses).

**Comment by fichtner** [comment]
There was a ticket to combine aliases with IPFW, this may be a long term solution?

**Comment by fichtner** [comment]
(URL as in host names/domains)

**Comment by jolentes** [comment]
Does whitelisting in the transparent proxy bypass the captive?

**Comment by AdSchellevis** [comment]
@jolentes forget my last comment, thinking about this again, it won't work. you need the ip addresses to whitelist.

@fichtner Aliases won't really solve anything, it still needs addresses. If your service is hosted on a machine which hosts more domains, you can not distinct them.
Aliases would make administration simpler, but looking at the way ipfw and pf implement the concept it will be almost impossible (or functional with constraints) to fix this properly in userspace.

**Comment by fabianfrz** [comment]
@AdSchellevis, it would be possible to whitelist URLs when using the captive portal by joining the transparent proxy with the captive portal implementation via `ICAP`. However this may work really bad because websites are using resources from many 3rd party servers which will probably make the page load but the resources (js, images, css) are missing.

**Comment by AdSchellevis** [comment]
@fabianfrz I don't see a scenario where this will work really well, our captive portal solution won't support this (wrong layer when traffic hits). I vote for closing this issue,  other solutions might be possible, but will always have disadvantages which will make standard implementation quite useless in my opinion.

**Comment by fabianfrz** [comment]
@AdSchellevis That is exactly what I mentioned in my post with 3rd party stuff. This cannot work well as long as the pages use 3rd party content (for example content delivery networks) without white listing them too.

So I would also suggest to **close** it because it is usually unmaintainable for administrators without an own open source project maintaining such a white list. I know this from my own computer using the Firefox add on `RequestPolicy`.

**Comment by jolentes** [comment]
Ok, I understand that Captive Portal and URL filtering happen on different layers.
But I am still looking for a solution of my problem: In general users on my wireless network shall be required to use vouchers to gain internet access. But at the same time I want selected apps (e.g. Slack or WhatsApp) on their smartphone to connect to theirs required servers.
I understand that websites load stuff from a lot of different domains, but normally apps don't do this in such a big variaty.

So I still need a possibility to bypass the captive portal for selected target services and not source devices.
What could be alternatives to a whitelist?

**Comment by AdSchellevis** [comment]
Most of the times those apps use multiple addresses to host their content, you could try to lookup the known addresses for the endpoints they use and put those in the whitelist (you could even consider some scripting to dig those addresses and update the corresponding ipfw table with the addresses found, although that won't be something we're going to develop for the standard CP, because of the likeliness of misconfiguration/interpretation issues).

A layer 7 / filtering solution isn't possible given our architecture.

At the moment, I need to close this issue as being unsupported. To discuss custom support solutions, please use our forum or look at our website for commercial options.
