### ISSUE TITLE
Limiter: [ No (valid) config.xml found, attempting last known config restore.]

### ISSUE THREAD

**Issue by andyalonzo** [opnsense/core#130]
When i attempt to create a new limit and Apply changes it does not save and then i see this notice: [ No (valid) config.xml found, attempting last known config restore.]

**Comment by AdSchellevis** [comment]
The gui part should be fixed with https://github.com/opnsense/core/commit/f89ab7ffc3e6d0fd69c4e07fd9d2195fedc10380.
But because the custom patches for dummynet have issues and L7 filtering is broken, most of the shaper features are non functional at the moment.

I will close this issue, because we have https://github.com/opnsense/core/issues/53 and https://github.com/opnsense/core/issues/99 open for the backend / kernel related issues.

**Comment by andyalonzo** [comment]
Thanks for reply.
