### ISSUE TITLE
Update IPSec manual

### ISSUE THREAD

**Issue by sachaz** [opnsense/core#1307]
https://docs.opnsense.org/manual/how-tos/ipsec-s2s.html#firewall-rules-site-a-site-b
the rules are autogenerated

**Comment by AdSchellevis** [comment]
Yes, we know, but we rather keep this in the documentation because in future versions these rules may be dropped. There's a lot of obscure code which we're restructuring and we rather try to minimize the number of automatic generated rules (there's always interpretation in the way things work now, it's better to make choices explicit).
