### ISSUE TITLE
Access trough WAN IF blocked 

### ISSUE THREAD

**Issue by jstrebel** [opnsense/core#131]
Access trough WAN Interface is blocked despite the "correct" settings in: Interfaces:WAN Block private Networs is "unchecked" and Block bogon Networks as well unchecked.
SW:15.1.8.4
Regards Jakob

**Comment by fichtner** [comment]
I'm assuming you have a LAN too. WAN only setups work due to the anti-lockout rules being moved to the WAN interface. These are probably needed on top of the "Block private networks". I'll report back in a bit.

**Comment by fichtner** [comment]
Hi Jakob, WAN traffic to the GUI is blocked by a default drop all rule, which is expected. You do not want to disable the private network drop in order to gain access. Instead, add a rule that passes IPv4 TCP for destination "WAN Network" with port 443 (and 80 if you want the HTTP redirect to work). Is it alright to close the issue?

**Comment by fichtner** [comment]
Assuming this is resolved. :)
