### ISSUE TITLE
Multi-WAN with two PPPoE uplinks - default route is set only for one

### ISSUE THREAD

**Issue by dvlskh** [opnsense/core#1315]
Hi,
Versions: OPNsense 16.7.11_1-amd64
Two PPPoE uplinks. In the section **System: Gateways: All** only one gateway can have flag **Default** and default route is installed only for this gw. In this case multi-wan failover and/or load-balancing is not works as expected.

**Comment by fichtner** [comment]
Hi there,

You have the same upstream gateway for both links?


Cheers,
Franco

**Comment by dvlskh** [comment]
Hi Franco.
No, upstreams are different. I have configured Multi-WAN as described in the OPNsense docs ( https://docs.opnsense.org/manual/multiwan.html ) and have found that for failover setup I do not need use policy routing - just to make sure that 'System: Settings: General-> Gateway switching' option is turned on. But when my primary uplink is down (cable removed from modem) default gateway switching have strange behavior. Right now I trying to figure out how it works ...

Regards,
Dmitry

**Comment by fichtner** [comment]
Hi Dmitry,

Ok, it's a start. :) Can you make sure gateway monitoring is actually switched on for both gateways in their individual settings?


Cheers,
Franco

**Comment by dvlskh** [comment]
Hi Franco,
My mistake is my guess that bring ethernet-interface down from the OPNsense WebGUI is the same as removing cable from modem. %) When I really remove this cable or shutting down port on the switch - everything works as expected - OPNsense switch default route from failed gateway to active one.

Sorry for wrong bug report and for disturbing you.

Regards,
Dmitry

**Comment by fichtner** [comment]
Hi Dmitry,

No worries, thanks for reporting back! :)


Cheers,
Franco

**Comment by mimugmail** [comment]
@fichtner Was Gateway switching moved to a different location? I setup a firewall today and have the same issue but with static WANs, default gateway doesn't switch and I have no idea

**Comment by mimugmail** [comment]
Firewall - Settings - Advanced ... thanks

**Comment by fichtner** [comment]
@mimugmail It did so we can phase it out slowly. Why do you need the option?

**Comment by mimugmail** [comment]
https://forum.opnsense.org/index.php?topic=5942.0

I have two wans, two gateways, one default. When line of default gateway goes down it doesn't switch.
With this option enabled it works. Why do you want to kill this feature? :)

**Comment by GuybrushX** [comment]
I recently needed this feature "Allow Default Gateway Switching" to run multi WAN setup with OpenVPN.
So please don't remove this feature or make clear how this is supposed to work without this option.

Some details about the setup:
OPNsense 18.1 something
LAN: connected to ADSL line with a fixed IP -> Backup
WAN: connected to SDSL line with a fixed IP -> Primary but offline atm

- I created a Tier-based Gateway Group: WAN -> Tier 1, LAN -> Tier 2 to have a passive failover configuration which is working
- According to pfSense docs you need to configure OpenVPN to listen on Localhost and create port forwardings for all WAN interfaces: https://doc.pfsense.org/index.php/Multi-WAN_OpenVPN
- Only after enabling this Firewall -> Advanced -> "Allow Default Gateway Switching" Feature OpenVPN was working with the LAN interface (because it is active right now so the failover did work)

Without that option the default gateway of the WAN interface is used and therefore there is no route to connecting VPN clients. You could also see this in the OpenVPN logs that a connection was established but the server couldn't answer since it tried to use the WAN gateway (default gateway, but offline).

Important note for the Client Export files:
The OpenVPN Client Export is not working with the automatic host names based on firewall rules. I had to add the "remote Host/IP 1194 udp" myself to the .ovpn configuration file. I would expect to find at least the WAN address but you can edit it manually or I think you can use the "Advanced parameters" box at the end.
