### ISSUE TITLE
[Bug] 17.1 Shell broken

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/core#1322]
Hi,

on the beta, the login is broken. It shows the IP addresses but no login prompt. Disabling the login on the shell via the web configuration GUI did not make a difference.

The shell works as expected using SSH.

Here is how it looks:
![virtualbox_opnsense_02_01_2017_11_49_53](https://cloud.githubusercontent.com/assets/3713914/21588022/ace7c456-d0e2-11e6-8a3f-703ab1339406.png)

**Comment by fichtner** [comment]
This is an upgrade, right? Check your console settings, it says "serial" but that is wrong.

**Comment by fabianfrz** [comment]
This is a virtual machine (virtual box) - so gave this option a try.

**Comment by fabianfrz** [comment]
BTW: ctrl+c has no effect

**Comment by fichtner** [comment]
I don't know. It says 17.1.b_60 on LibreSSL, which means it's 10.3 underneath. The console setting is wrong, just double-check from the System: Settings: Administration page. It must be set to VGA.

**Comment by fabianfrz** [comment]
OK, this worked - however I have no idea how it has changed to this setting. This is my development VM where I don't do any changes except testing my pull requests. That's strange.

**Comment by fichtner** [comment]
The problem is that the GUI for a long time forced the default of "serial" without the "serial enabled" flag. I removed the superfluous  "serial enabled" flag handling, which triggered this.

This was never broken in a new install or on factory reset. But saving anything from System: Settings: Administration would write "serial", which is obviously wrong.
