### ISSUE TITLE
Feature Request: GUI option to change state timeout of UDP

### ISSUE THREAD

**Issue by techie2300** [opnsense/core#1330]
I run a very busy NTP server and there is a lot of open states on my firewall. I would like to be able to change the state timeout of a particular firewall rule in order to optimize the FW to handle thousands of request a second.  

The option is available in PF and fabian kindly asked me to create a feature request:

https://www.openbsd.org/faq/pf/options.html

Thanks. I hope you will consider (and that I have done it the correct way).

**Comment by fichtner** [comment]
Hi @techie2300,

How does " aggressive" setting work for you?

The issue is the "set timeout" option has a lot of configuration potential. It will be difficult to provide all in a flexible way. Can you look through the options under "OPTIONS" section in the following document?

https://www.freebsd.org/cgi/man.cgi?query=pf.conf

I'm favouring adding "interval" and "frags" only with "interval" being the more interesting for your use case, but only of "aggressive" is not enough.


Cheers,
Franco

via: https://forum.opnsense.org/index.php?topic=4203

**Comment by techie2300** [comment]
Hi Franco,

To be honest I cant really tell the difference with the two different
settings. Currently there is 600.000+ open states on the device and I
didn't notice any real differences in the number of open states after
changing from normal to aggressive. I haven't detected any problems either.

The other suggestion on the firewall rule. I cant change a firewall rule
when it is created from the NAT forward port. I tried to create a new rule
and move that before the other one and changed the option "state type" to
"none" - but I could not detect any difference.

I am by no means a firewall optimization expert. but "interval" seems
interesting to try. I can see the default time is 10 in OpenBSD (cant seem
to find the default for FreeBSD), but it would be interesting to try.

Br,
Thomas

**Comment by AdSchellevis** [comment]
@techie2300 you can easily try the settings manually by editing the /tmp/rules.debug file and reloading it using:

`pfctl -f /tmp/rules.debug
`

Changing the rule to disable state tracking (state type "none") sounds like the best solution for your use-case (add a new rule, disabling the old one).
If the number of new states keeps increasing, logically it's either being matched by another rule first or the states match another protocol/port.
Don't forget to flush states when changing state behavior, it's otherwise pretty difficult to spot if changes have lead to improvements.

**Comment by AdSchellevis** [comment]
timeout due to inactivity
