### ISSUE TITLE
firewall rules based on vpn users

### ISSUE THREAD

**Issue by neubian** [opnsense/core#1371]
We've evaluated a lot of different firewall distros, and this is a feature that is extremely useful in our business and the businesses we support.  In 2017, it really does seem like a "must have".

pfSense has issue # 1205  https://redmine.pfsense.org/issues/1205

We've done quite a bit of Phalcon work, so while I can't make any deadline promises, I'd like to start a discussion on how to get this designed, and then my company can proceed with the code to make it happen.

**Comment by AdSchellevis** [comment]
@neubian The firewall code is still a lot of legacy code from our parent project, although we've done quite some restructuring on it already.
The user interface is also still legacy (non phalcon) php code, which relies on the legacy backend.

To be able to implement big structural changes here, we really need to restructure the internals first.
For 17.1, we've already implemented the first steps into a new model for plugging dynamic firewall rules (https://github.com/opnsense/core/tree/master/src/opnsense/mvc/app/library/OPNsense/Firewall)
The next step here is to align the user defined rules into the same standards, so we can ease the rule generation a lot and clear the view.

For NAT rules, the same treatment should apply (planned https://github.com/opnsense/core/issues/1326)

There's still quite a lot of work to do (development and a lot of testing), so don't expect this to materialise before our 17.7 release.

When that's done we can begin to think about restructuring the UI to phalcon as well (don't expect this to materialise before 2018).
 
Adding new functionality to the legacy firewall code could be possible, as long as the impact is not too high, our priority lies in hardening the internals first, to minimise impact of new features later.

Then about the user based rules, your actual question, at the network the concept of a user doesn't really exists and always seeks for a translation into an address to be able to filter it on osi layer 3 (the method on how this works, may very on technology).
Since we don't have a model for this yet, it has do be designed, which is where it should start I guess, you could definitely help there by proposing a design, which we can discuss here.
If we keep the impact low on existing code, it might be implemented in the legacy code, if it requires 
too much changes, it should wait until the rest is restructured.

Eventually, when committing code, try to keep the changes which interact with existing code as small as possible, which makes it easier for us to review and accept. We're all quite busy.

**Comment by djGrrr** [comment]
Technically this is already possible when using OpenVPN server, as you can use client specific overrides to give each client (based on certificate common name) a static ip address. From there, you can create firewall rules with the source address set to the static ip address for the client in order to do client specific rules

**Comment by AdSchellevis** [comment]
timeout due to inactivity
