### ISSUE TITLE
Incomplete alias table definition potentially resulting in FW hole

### ISSUE THREAD

**Issue by kernins** [opnsense/core#1396]
Aliases containing only fqdns are defined as `table <foobar> persist` (without `{}`), which could lead to stalled entries in table in case it existed before the change (editing existing alias scenario)

from man pf.conf(5):
>The contents of a pre-existing table defined without a list of addresses to initialize it is not altered when pf.conf is loaded.
>A table initialized with the empty list, { }, will be cleared on load.

1. create new alias of type host, fill some IP and save
2. reference that alias from at least one fw rule (as IP only aliases declared w/o `persist` flag and will be dropped by kernel if unreferenced)
3. check actual table contents with `pfctl -t _name_here_ -T show`, it should be correct
4. edit your alias, change IP to some FQDN (resolving to different IP), save-aplly
5. check table contents again, now both old IP and new entry(ies) for FQDN are all there

**Comment by AdSchellevis** [comment]
@kernins this indeed looks buggy, it looks like this was supposed to flush the contents of the alias after loading, but wasn't triggered.

It looks to me that we should initialise it with an empty list {} and drop the the flush, this commit should fix it https://github.com/opnsense/core/commit/067f0982b7c91a52fcfc3cbf7a3c4a210ff2a7cb.

@fichtner can you double check if I'm not missing something here?

**Comment by fichtner** [comment]
I refactored this at least twice, trying to keep the original intent in place. It's good to see this workaround being removed finally as I was unable to wrap my head around it before. If it works, all the better. No objections.

**Comment by kernins** [comment]
Indeed, your commit fixes the issue, and the code also looks much cleaner now

Btw, it also fixes potential race condition between filterdns reloading and table-flush statements being executed)

**Comment by kernins** [comment]
Nah, its not that simple. It also clears the table on FW rules reload, but filterdns doesn't then refill it, probably due to aliases aren't "dirty" in this case.

It seems  `{}` should only be added when aliases are "dirty" (edited)

**Comment by AdSchellevis** [comment]
but if it only flushes when dirty, it would have the same issue for other dns entries already in the list if I'm not mistaken.
We probably have to invalidate the entries in filterdns for these situations, but I'll have to look into this further.

**Comment by AdSchellevis** [comment]
Ok, tested some more, the problem is that this only "kind of works" when there are addresses **or** fqdn's in the alias.... but when fqdn's are used, they will never cleanup the way it's build.

In my opinion we should either restart filterdns with the filter and flush the alias or reset the alias on load with the proper content, because there is no way of knowing that the contents of the alias are still sane.
The question is what the time needed for filter reload will be when aliases contain a large amount of fqdn entries, pf does resolve, but I'm not sure about the speed there.

It would be good to loose more garbage from the code here, this whole area unfortunately is still quite messy.

**Comment by kernins** [comment]
>but if it only flushes when dirty, it would have the same issue for other dns entries already in the list if I'm not mistaken
Why? The issue here seem to be in filterdns *thinking* it is already done its job (contents of its conf not changed) and so not reloading. Keeping table contents intact in fw-only reload scenario should be safe, if I'm not missing something.

>In my opinion we should either restart filterdns with the filter and flush the alias or reset the alias on load with the proper content, because there is no way of knowing that the contents of the alias are still sane.
>The question is what the time needed for filter reload will be when aliases contain a large amount of fqdn entries, pf does resolve, but I'm not sure about the speed there.

As you already mentioned, re-resolving all fqdns on each filter reload is sort of brute-force approach and may have noticeable impact with large lists. Local unbound cache could help here, but first-timers still could be lengthy to resolve. Also with filterdns I think it could still be possible to encounter some new border cases leading to inconsistency, the whole multiple-loose-writers design with configurator and filterdns both altering table contents while knowing nothing about each other's data seem fundamentially wrong to me. Feeding fqdns directly to pf looks much more robust in that sense, however this would be one-time resolve lacking periodic updates capability to catch possible changes in dns records.

I think, to do it properly, first we need some custom fqdn-dictionary service, which would maintain fqdn->ip map, handle periodic refreshes to keep it up to date, send out update events and provide API to query its map. So when alias containing fqdn is created/edited, that service gets notified, reloads fqdn list and immediately starts resolving new entries, possibly with feedback for user in UI. Existing entries are all periodically refreshed on schedule basis. After all new entries are resolved or scheduled update detected some changes, it should send out fqdn-map-updated event to notify any concerned parties.

PF management and table reloads should be exclusive right and responsibility of another entity, which among other things will listen to and act upon that fqdn-map-updated events. 
While doing full filter reload it could actively query fqdn-dictionary service to instantly get fqdn->ip map containing all currently resolved entries, and then build pf table defs based on alias list and fqdn-map superposition. If all fqdns were resolved at that moment, this will result in complete table definitions and atomic pf reload. Otherwise remained entries will be pushed into table by means of receiving and handling fqdn-map-updated event.

Optionally dictionary service could implement sort of max-wait-time policy for its API, so client could specify how much time it is willing to wait in case not yet all fqdns are resolved.

However, all this is a bit out of bugfixing scope)
What do you think?

**Comment by AdSchellevis** [comment]
> Why? The issue here seem to be in filterdns thinking it is already done its job (contents of its conf not changed) and so not reloading. Keeping table contents intact in fw-only reload scenario should be safe, if I'm not missing something.

It doesn't seem to cleanup old values, so any change in the list automatically seems to result in more items in the list. (for example, when changing www.nu.nl to www.ad.nl both will end up in the list)

There are more issues in this whole area, which eventually could justify building a new services to keep track of the table contents. The way it is now, on initial boot the filter would try to fetch the initial contents on load, which also is not a good idea in terms of architecture.

Writing the proper solution is indeed too big to do at the moment in terms of time and the coding quality in the current setup.
Pushing the initial values in the ruleset might break loading (I tested that to be sure),  so for the short-term we have two options:

1) revert to what it was
2) reload filterdns on changes

I would vote for two, because it will lead to a cleaner ruleset, but will cost more time for all entries to flow into the table again.
 
Eventually we should make sure the administration of the table contents is separated, but that's more of a longer term goal (first cleanup what's there and then add a new service).

**Comment by kernins** [comment]
>It doesn't seem to cleanup old values, so any change in the list automatically seems to result in more items in the list. (for example, when changing www.nu.nl to www.ad.nl both will end up in the list)

Of course, but I was talking about aliases-unchanged case. When they are changed, yes, tables need to be fully reset.

>I would vote for two

Agreed, it is still better than possibility of having incorrect table contents virtually indefinitely.

It might also be a good idea to change WAN-related rules to use tables, and reload only that tables when IP changes, not the whole ruleset. This could help to keep full reloads at minimum even on instances with dynamic WAN connection.
