### ISSUE TITLE
Feature Request: Advanced QoS based on DPI

### ISSUE THREAD

**Issue by BenSchweikert** [opnsense/core#1397]
Dear all,
an advanced detection on what kind of traffic is produced to filter it efficiently to the corresponding QoS pipe would be great. L7 is in my opinion deprecated and never worked very good. nDPI might be an option on realizing this.
Even more with nDPI denying of certain webpages like Facebook or youtube would be possible.

BR
Ben

**Comment by fichtner** [comment]
Hi Ben,

L7 hasn't existed in OPNsense since 2015. :)

I agree that nDPI is the best thing to go forward, however, as far as I know it's not easily possible to integrate it into QoS for easy policy management based on protocol/application properties.

It would certainly require an effort to bring a third packet filter framework into the mix in order to filter according to all those properties and the means to do userspace/kernel decisions in tandem. Suricata does this with the netmap framework already, but Suricata is an IPS so it only drops. QoS or similar techniques require shaping algorithms and queues, which we would have to implement in userspace.

Another way to go forward would be the dummynet framework, which may be able to deliver the required complexity.

So far, this is only theory and not a concrete plan. All comments are welcome to move this forward. Leaving this open as a future feature ticket. :)


Cheers,
Franco

**Comment by BenSchweikert** [comment]
Hello Franco,
I totally agree with you that this cannot be a "just do it" task/feature. I am quiet unused to *BSD, but I know linux well (for an hobby enthusiast) and had been a developer for a linux FW for some time. All I could find about nDPI is, that it is working with iptables and a netfilters kernel module. I could not find anything comparable for PF or IPFW. The Dummynet approve sounds to me definitely the most promising choice. 
Any further ideas?

Yes, please keep this open as a "future feature ticket".

Greets,
Ben

**Comment by BenSchweikert** [comment]
Another idea which came to my mind and would like to discuss is using a docker container containing a small Linux like alpine with the xtables netfilter patches.

E.g. for traffic going from inet to LAN:
The container acts as a gateway somewhere between LAN and traffic leaving wan. It needs a static ip which can be addressed. 

This way the whole DPI story could be handled as a plugin and the FW itself could be untouched.

Please feel free to discuss this idea.

Cheers
Ben

**Comment by fabianfrz** [comment]
@BenSchweikert I think this is a bad idea because iptables is afaik EOL. The current Linux firewall is nftables. However, it should be supported as well: https://wiki.nftables.org/wiki-nftables/index.php/Supported_features_compared_to_xtables

Docker will not work because it is using a shared kernel - which means that the container is still running on a FreeBSD kernel - and will have PF or IPFW as packet filtering framework. Note that docker on FreeBSD is still experimental.

**Comment by elico** [comment]
@BenSchweikert
An NDPI or any network routing system should not be running as a docker container since it cannot have it's own kernel and will be binded to the host one.

@fabianfrz 
iptables is not really EOL and nftalbes is just an addition of "API" to the same system with a bit of "remixing" in it.
Basically iptables will stay stable for at-least 5 years for production systems.
And if someone is capable to add nDPI to iptables then nftables would be pretty simple task but will require some learning curve.

**Comment by AdSchellevis** [comment]
timeout due to inactivity
