### ISSUE TITLE
Different Boot Menu when booting from USB

### ISSUE THREAD

**Issue by pgassmann** [opnsense/core#1408]
It should be quickly visible that the system is booting from the USB Stick. The initial Bootmenu (Single User, Multiuser, Reboot, ...) looks exactly the same from USB as from the installed system.

The boot message (on serial) after selecting USB as boot devide was some cryptic output then "Booting from Harddisk...", then showing the known bootscreen.

This mislead me to believe that the system was not booting from USB but from the installed.

expected behaviour:

- "Booting from USB" instead of Harddisk
- Bootmenu clearly marked with "Installer" resp. "Installer/LiveCD"

**Comment by fichtner** [comment]
It's really not easy to detect an install media up-front during early boot. We'd have to label it install media to start with, which poses problems when installing ending in additional if / else flip flops for something we don't really have to worry about from an architectural standpoint.

The web GUI makes it pretty clear since 17.1.4, the console will also prompt for the "installer" user. I would hope this is a good first step and we can build on that as opposed to early boot / boot loader screen?


Cheers,
Franco

**Comment by pgassmann** [comment]
Is it the same boot menu that the install medium uses that is copied to the final installation?

I assumed that the install media has its own boot sequence files. Then they could simply be different from the ones that are copied in the install process.

**Comment by fichtner** [comment]
Hi Philipp,

This is exactly right. The contents is cloned to the target system during install. We do not have any install media separation... The only difference from installed systems (and the Nano image) vs. install media is that their partition is read-only so that it knows it can offer the installer. But you can also start the installer from installed systems, creating new clones of the current system.

As of 17.7-RC1, we have two banners after boot, one in the console, the other in the GUI. Though there is no SSH banner indication at the moment...

<img width="633" alt="screen shot 2017-07-12 at 9 46 14 am" src="https://user-images.githubusercontent.com/1915288/28107244-38cce420-66e7-11e7-9e08-65f92fc8e605.png">

<img width="1291" alt="screen shot 2017-07-12 at 9 47 38 am" src="https://user-images.githubusercontent.com/1915288/28107251-3bf223ea-66e7-11e7-8274-9ef6cb189b1b.png">

What do you think would make it clearer?


Cheers,
Franco

**Comment by pgassmann** [comment]
Thank you for the clarification.

Perhaps you could display the device path and model instead of just "Harddisk". 

> Booting from Disk /dev/usb1 "Kingston 32G" 

or whatever information is available about the disk on FreeBSD at that stage.

```
(example on linux)
hdparm -I /dev/sda
/dev/sda:

ATA device, with non-removable media
	Model Number:       INTEL SSDSCKKF512H6 SATA 512GB
```

**Comment by fichtner** [comment]
I think we can show the root partition's device, in the installer case it has "_install" appended, in the DVD case it's "/dev/iso9660/OPNSENSE_INSTALL".

That only leaves the question where to display the message as the boot is pretty verbose and early prints get flushed out.

**Comment by fichtner** [comment]
this is how it will look like

<img width="722" alt="screen shot 2017-07-23 at 4 03 36 pm" src="https://user-images.githubusercontent.com/1915288/28499925-956a30ac-6fc0-11e7-8982-06c967da06a3.png">
