### ISSUE TITLE
Feature: hardware off-loading control per interface

### ISSUE THREAD

**Issue by phpb-com** [opnsense/core#1431]
It would be good to have per interface control of the hardware off-loading. Since most of the people will likely run IPS on wan, it is not necessary to turn-off off-loading on all of the interfaces. I would like to have it still "on" on the local internal interfaces. What do you think?

**Comment by phpb-com** [comment]
I think that adding "Network Interfaces Hardware Control" section in Interface > [Interface] will be the most intuitive, while retaining global settings for off-loading in the same place. If there are no objections I would like to take a shot at adding that.

**Comment by AdSchellevis** [comment]
I'm not entirely sure it's a good idea to change this to a per interface option, because we've seen more issues with offloading in the past (strange link issues etc.).
Do you have a specific use-case where offloading really helps? 
It might be an option to support an override on a per interface basis, as long as we have defaults for all like it is now (I really want to keep our defaults the way they are now).

**Comment by phpb-com** [comment]
That is my idea to have global off-loading control as is and only add per interface override. I do also think that keeping global default as is, is important.
