### ISSUE TITLE
Traffic shaping upload limiting broken again

### ISSUE THREAD

**Issue by tkald** [opnsense/core#1439]
In 17.1.2 traffic shaper upload limits don't work again. It was working in 17.1.1.
I do have gateway group routing on firewall rules present.

**Comment by fichtner** [comment]
Firewall: Settings: Advanced: check "Use shared forwarding between packet filter, traffic shaper and captive portal". Changed in 17.1.2 to a non-default.

**Comment by tkald** [comment]
Thank you, It did the trick :)

**Comment by fichtner** [comment]
Glad to hear, closing :)

**Comment by tkald** [comment]
Ok, now I have again issues described in [https://github.com/opnsense/core/issues/1410](url)

**Comment by fichtner** [comment]
It's going to be either... or at the moment. The network stack can't handle shared packet filter forwarding very well as it was tailored around the paradigm of pf does what it wants as long as the rest of the stack doesn't see it. Fixing the "obvious" is difficult and I suspect the complexity of the issue was one of the reasons this was never being worked on before.

**Comment by tkald** [comment]
I, see...
I suppose I can get away with "Allow default gateway switching" and default gateway in fw rules?
