### ISSUE TITLE
Request to add DynDNS Hoster

### ISSUE THREAD

**Issue by gertfriend** [opnsense/core#1452]
Would it be possible to add regfish.de as DynDNS-Hoster?
The URL would be: http://dyndns.regfish.de/?fqdn=<domain>&ipv4=%IP%&forcehost=1&token=<token>
token is an ID with numbers and letters.
Thank you.

**Comment by fabianfrz** [comment]
Because this is a simple URL, you could use "custom" for this in mean time. Also the service offers TLS with a valid certificate but you may run into problems with OPNsense running using `LibreSSL`.
See #1411 and #1422 for further information about TLS related issues.

There is also a ticket for a larger change of the dynamic DNS services: #1420
