### ISSUE TITLE
[FR] Allow aliases for hosts to use a url with fqdns

### ISSUE THREAD

**Issue by L1ghtn1ng** [opnsense/core#1482]
I would like to block the connections to these domains  https://openphish.com/feed.txt

but currently its not possible as from the help 

```
Hosts

Enter as many hosts as you would like. Hosts must be specified by their IP address or fully qualified domain name (FQDN). FQDN hostnames are periodically re-resolved and updated. If multiple IPs are returned by a DNS query, all are used.
 ```

So I would like another type URL table (URLs) where it can parse this https://openphish.com/feed.txt with and with out the http/https prefix.

**Comment by AdSchellevis** [comment]
@L1ghtn1ng the list contains url's and not domains as far as I can see, you probably better use the proxy to filter those. You could split the domain parts, but since those lists can get pretty filled with names which are hard to resolve, it would definitely have side affects in terms of filter (re)loading issues.
Fetching large lists of (possibly) bad resolving domains is not a very good plan, at least not the way the alias handling is constructed now.

for reference, the affected code, https://github.com/opnsense/core/blob/17.1.3/src/etc/inc/filter.inc#L213-L268

**Comment by gertfriend** [comment]
@AdSchellevis But would it be possible for a list of Domains in a Textfile. So i host a txt file on my webserver with domainnames inside, for example:
www.domain.com
mail.domain.com
webmail.domain.com
Or would it be possible to integrate this Aliastype?

**Comment by AdSchellevis** [comment]
@gertfriend that's already supported, using the "url table" type, although for large lists I won't recommend it (reasons mentioned earlier).

**Comment by gertfriend** [comment]
@AdSchellevis thank you for your fast answer. I have other two questions.
I saw that the "URL Table" will be updated once a day, thats OK but the domainnames, will they be updateded also resolved once a day or will they be resolved like the Settings in Firewall -> Settings -> Alias Resolve Interval?
And the other question, i saw, that the resolved Url-IPs in pfTables won' t be flushed, so there are many IP-Addresses in that aren't valid anymore. Shouldn't there be a Cronjob to flush the resolved Aliases in a periodic time lag?
Thank you.

**Comment by fichtner** [comment]
@gertfriend 

* you can set up a custom cron interval for alias refresh under system: settings: cron
* there are some cleanups on the development version regarding flushing the alias table content--I'm not fully sure they will help yet but we are aware of the issue and trying to solve it

**Comment by AdSchellevis** [comment]
timeout due to inactivity
