### ISSUE TITLE
Cannot edit firewall rule for NAT linked rule

### ISSUE THREAD

**Issue by tidus888** [opnsense/core#1502]
I just realize an issue while trying to make some advance setting for firewall rules.

Firewall Rules created by NAT/Port Forward don't have the "edit" button.

I am unable to make changes such as maximum connection, etc.

**Comment by fichtner** [comment]
Sorry, this is intended. You can set the nat rule not to create a linked firewall rule and add a rule yourself. The issue is the linked rule is mostly defunct and causes issues when it is being editable.

It's a limitation we want to remove eventually, but it takes work to get there building upon a solid foundation of a programmatic firewall rules model which is under development.
