### ISSUE TITLE
web proxy: yoyo ACL https download writes garbage to disk

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#1510]
Hi Ad, do you know what's wrong? I could only verify for now :(

https://forum.opnsense.org/index.php?topic=4893.0

**Comment by AdSchellevis** [comment]
Oo it's gzipped... which won't get unpacked by request.raw
![image](https://cloud.githubusercontent.com/assets/9783985/24466573/a37cfb4e-14b1-11e7-98da-7e97449525f8.png)

As soon as I have some time I'll try to prepare a fix.

**Comment by fichtner** [comment]
doesn't http take care of this? if this already happens then what happens with chunked encoding??

**Comment by fabianfrz** [comment]
just use `zlib` for that. Python has a module for that:
https://docs.python.org/2/library/zlib.html

**Comment by AdSchellevis** [comment]
i know, it's just a time constraint.

**Comment by AdSchellevis** [comment]
please be aware that the list mentioned in the forum (https://pgl.yoyo.org/as/serverlist.php?hostformat=squid-dstdom-regex&showintro=0&mimetype=plaintext) isn't compatible with our system, because it's a regexp and not a domain list (https://pgl.yoyo.org/as/serverlist.php?hostformat=plain&showintro=0&mimetype=plaintext)

**Comment by fichtner** [comment]
thanks for fixing 👍  I'll coordinate with the user
