### ISSUE TITLE
No console access after upgrade from 15.1.9 to 15.1.9.2

### ISSUE THREAD

**Issue by MNMtm** [opnsense/core#152]
Again, after upgrading from 15.1.9 to 15.1.9.2, the console output is turned off after issueing a factory defaults in console menu. There is still console output on first reboot after factory defaults, but at the point that the console menu should appear, there is no console output anymore. The last thing that appears are the configured interfaces. Doing a reboot again, there's no console output since the boot loader.

**Comment by fichtner** [comment]
The bug fixed in #145 is fixed in 15.1.9.2. However, the fix applies to package removal time, which in this case won't take effect until 15.1.9.2 is on the system. The behaviour is expected. Further info was attached to the commit message at https://github.com/opnsense/core/commit/55db8dab0f19c5a9e882957087571f650608cfec

After applying 15.1.9.2, the default config needs to be bootstrapped safely in order to invoke the correct behaviour from that point on. A full fix won't be possible until 15.1.10 is released and the system is reinstalled cleanly. The bootstrap fix described afterwards is quick and permanent.

I have uploaded a standard serial default config.xml for you to be applied before factory reset once 15.1.9.2 is installed:

    # cd /usr/local/etc
    # fetch https://pkg.opnsense.org/snapshots/config.xml
