### ISSUE TITLE
system: optional swap file setting

### ISSUE THREAD

**Issue by Woi** [opnsense/core#1554]
My OPNsense 17.1.x [1] reliably goes out of service once a week, due to ` /etc/periodic/weekly/320.whatis` running out of memory [2,3]. This unfortunately affects other processes, too [3]. Services killed vary, but usually either `dhcpd` and/or `unbound ` are affected, leaving my clients in a "nothing works any more" scenario. 

I'm running OPNsense with just basic services on an [Alix 2D13](https://www.pcengines.ch/alix2d13.htm) with 256 MB RAM. While this doesn't meet the [minimum hardware requirements](https://docs.opnsense.org/manual/hardware.html#hardware-requirements), I thought I report this anyway, because it might help making OPNsense more robust. Also Alix is still is a very wide spread platform for running firewall appliances. However a "Won't fix" totally legitimate.

Should you decide to have a look on this, I like to share some thoughts beside the obvious "fixing" `whatis`:
* Could the (most crucial) services made survive out of memory situations?
* Could crashed services be restarted?
* Shouldn't OPNsense inform about critical situations? (I have a working email notifications configuration, but no email was sent. Neither to inform about the out of swap warning, nor to inform about the crashed services).

[1]
OPNsense 17.1.4-i386
FreeBSD 11.0-RELEASE-p8
LibreSSL 2.4.5

[2]
```
# grep weekly /etc/crontab
# Perform daily/weekly/monthly maintenance.
15	4	*	*	6	root	periodic weekly
```

[3]
```
Apr 22 04:21:48 gw kernel: pid 18529 (makewhatis), uid 0, was killed: out of swap space
Apr 22 04:21:58 gw kernel: pid 167 (python2.7), uid 0, was killed: out of swap space
Apr 22 04:22:10 gw kernel: pid 165 (python2.7), uid 0, was killed: out of swap space
Apr 22 04:22:16 gw kernel: pid 95618 (dhcpd), uid 136, was killed: out of swap space
```

**Comment by fichtner** [comment]
Hi @Woi,

    Could the (most crucial) services made survive out of memory situations?

ALIX and 256 is the bare minimum. You're using the Nano image, which has no swap space. You can add a swap file:

https://www.freebsd.org/doc/handbook/adding-swap-space.html

Maybe this could be a feature we could add in the future via the GUI? But we don't want to enable it by default because it wears down the SD card and the swap space of a file can't be used to dump the kernel crashes.

As the only example of protected services, there is sshd:

https://github.com/opnsense/core/commit/0afa03c7

Which, incidentally, was added for ALIX/WRAP low memory configurations in 2015. We haven't received another request since, which may or may not indicate the need for such further "protection".

Additionally, protecting more services will help to create impossible situations, killing other jobs more vividly. To circle back: adding swap space may be all you need to do. With the 17.1 Nano images space isn't a big problem with those systems anymore. :)

    Could crashed services be restarted?

That's tricky without a watchdog, avoiding to run into situations where the box is in denial about what it can and can't do and just restarting things all the time.

    Shouldn't OPNsense inform about critical situations? (I have a working email notifications configuration, but no email was sent. Neither to inform about the out of swap warning, nor to inform about the crashed services).

There is a new plugin for Monit coming out with 17.1.5, maybe it can do this. SNMP can do this as well. The "notification system" that is in OPNsense is very rarely used and not very well implemented. It has been scheduled for removal / replacement, wanting to look for alternatives. Maybe Monit is one of those as it happily also deals with e.g. notification mails out of the box. But it's hard to say without someone doing the work.


Cheers,
Franco

**Comment by Woi** [comment]
> add a swap file
Thanks for pointing out, my problem is gone now. It also was a nice surprise to have a swap bar on the system information panel of the dashboard, without doing anything. Regarding to panel swap is rarely used and if so just a few MB.
However for anybody who might stumble on this: with the `/etc/fstab` line from the FreeBSD handbook swap was disabled after boot. `md42   none   swap   sw,file=/usr/swap0   0   0` worked for me.

> a feature we could add in the future via the GUI?
> We haven't received another request since
Since I seem to be the only one with this problem and taking into account how easy this can be done manually, I think adding a GUI option is a waste of time. But maybe documenting it in the OPNsense handbook would be worth it? Is there a way to participate with documentation, as this can already be done with code and translations?

> Monit coming out with 17.1.5 [...]. The "notification system" is very rarely used and not very well implemented. 
Monit looks promising. I'll give it a try.

**Comment by fichtner** [comment]
hi @Woi,

Thanks for checking back. I think we should add a GUI switch for the swap file. it may come in handy  and it's not too much work. I will try to get this done in time for 17.7.


Cheers,
Franco

**Comment by Woi** [comment]
Nice and thanks for your support. Since my issue is solved, it's your ticket now.

**Comment by fichtner** [comment]
@Woi I humbly accept this ticket :)
