### ISSUE TITLE
mvc: the service control indicator button is misleading

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#1562]
It should not have any ":hover" properties so that users are not confused by its lack of functionality.

**Comment by fraenki** [comment]
I think the main issue here is that the button looks exactly like the old "service control" feature that can be found on many legacy pages.

Some suggestions:
- use different icons; maybe just a large red/green dot (instead of the play/stop buttons)
- add a (hover) text that reads "service is running" or "service is not running"

**Comment by fichtner** [comment]
maybe a coloured dot right after the title? black (or hidden), green, red. simple but powerful?

**Comment by fraenki** [comment]
> maybe a coloured dot right after the title?

Sounds good!

**Comment by sjorge** [comment]
Best to not hide the dot to keep the flow consistent?

**Comment by fichtner** [comment]
Finally found the time to do this. It is a bit different and tricky to pull off, but now it looks like a button but doesn't do anything other than show the status (for both MVC and Legacy).
