### ISSUE TITLE
Package request: snort

### ISSUE THREAD

**Issue by Cryphic** [opnsense/core#1649]
Would really like to have this i am changing from pfsense to this #

**Comment by AdSchellevis** [comment]
We're using suricata for IDS/IPS, if there's a specific feature missing, it might be a good idea to specify your requirements.

**Comment by Cryphic** [comment]
are you able to use Snort rules on suricata?
i like how simple Snort is With its supress lists and ip lists with easy syncs.
Super easy to setup. Also it has IP reputation system and if i would use suricata it would probably be big mess with snort rules 
with snort's package theres no need to mess with things just hit it up with oink and check things. I hope it get's added maybe other people want it too but scared to ask or something.

**Comment by fabianfrz** [comment]
The rules are having the same format, however there are fields mandatory which are not in snort.

**Comment by Cryphic** [comment]
Also i wonder if it has Emerging threads & Sourcefire OpenAPPID

**Comment by AdSchellevis** [comment]
have you tried our system?

**Comment by Cryphic** [comment]
not yet going to move after pf 2.5

**Comment by fabianfrz** [comment]
ET Open is supported. The others can be simply copied into the corresponding directory. The IDS is under `Services > IDS` if you want to try it inside of a VM.

**Comment by Cryphic** [comment]
As couple year's user on snort i don't like changes

**Comment by Cryphic** [comment]
but i could give it a shot someday maybe or just upgrade to opn and see what to do

**Comment by AdSchellevis** [comment]
we have a different approach in developing new functionality, trying to keep things more consistent for our core functionality and avoiding overlapping features. Suricata at our end is very easy to use and update with the rulesets supplied, that's why snort won't be in our system (same functionality).

We do offer a framework for people to develop their own plugins, but to be honest, I really won't encourage to invest a lot of time there.... it's better to support one solution good then two a bit ;)

Let's close this for now, feel free to open an issue in our plugins repository, but if you're not planning to work on it yourself I don't think it will gain a lot of traction.

**Comment by AdSchellevis** [comment]
for reference, if someone want to add the snort rules into our automated system, it's quite easy to add a definition file, like https://github.com/opnsense/plugins/blob/master/security/intrusion-detection-content-pt-open/src/opnsense/scripts/suricata/metadata/rules/pt-research.xml
