### ISSUE TITLE
[FR] Add a "Backup machine" button to HA setup and add automagic FW rules

### ISSUE THREAD

**Issue by mimugmail** [opnsense/core#1650]
Hi,

I was thinking about making the HA setup a bit smoother. What about a new button in HA setup to tell the system it's the backup machine? With this knowledge we could automagic add a FW rule in the sync interface to accept inbound 443 for config sync. 

Perhaps this saves guys new to OPN some headache setting up a HA env?

**Comment by AdSchellevis** [comment]
Hi Michael, 

I'm not sure we should cross reference the firewall from there, if it's unclear to users that you need to open up the web interface, we could also choose to add a clear note there.

Before you know, we're trying to add a lot of overlapping functionality in different parts of the system, which will make it very difficult to maintain in the long run.
Ideally we should have a wizard template using api calls, but that's at the moment not a very easy goal to reach. 

I'm still working on cleaning up the remains of the firewall, so it will use our pluggable system, eventually we would want to migrate (parts) of the ui as well and expose the api functionality to the user. It's just still quite some work, mainly because all is so cluttered together... 

Best regards,

Ad

**Comment by mimugmail** [comment]
@AdSchellevis Ah, you mean like the Wizard for OpenVPN. Ok, this would be really nice.

**Comment by AdSchellevis** [comment]
well, in functionality, yes, in implementation, no. it should be detached from the logic, which isn't very easy to do now.

**Comment by mimugmail** [comment]
Ok, so in the meantime it would be nice to extend the help here ..

![image](https://cloud.githubusercontent.com/assets/20438689/26300706/30b2edd2-3edf-11e7-94ea-85d4d131eb52.png)


.. that for a backup machine this has to be empty and a firewall rule for incoming port 443 is needed?

**Comment by AdSchellevis** [comment]
certainly! can you prepare a commit?

**Comment by fichtner** [comment]
please no markup in the help text ;)

**Comment by fichtner** [comment]
exclamation marks are also bad style

**Comment by mimugmail** [comment]
@fichtner I can remove exclamation marks but I'm not sure if the localization will work when it's removed

**Comment by fichtner** [comment]
It looks good, the previous style was what I saw so I just added the comment. We don't need to change it. :)

**Comment by mimugmail** [comment]
Closed by #1651
