### ISSUE TITLE
Gateway bug

### ISSUE THREAD

**Issue by sachaz** [opnsense/core#1732]
Hi,

I have 2 wan interfaces: wan1 wan2 with gw1 gw2.
GW1 is the default gateway.
If I disable LAN1, GW2 becomes the default one => ok
If I reenable LAN1, GW1 becomes the default gateway => ok
If I set GW2 as default gw or/and I disable GW1, GW1 stays the default one => nok

**Comment by fichtner** [comment]
Hi,

I presume you are using gateway switching feature? May I ask why?

We have fixes for 17.7 here, but eventually gateway switching will be removed as we don't think it's necessary and prone to such issues.


Cheers,
Franco

**Comment by sachaz** [comment]
Thanks for your reply.
As far I know I haven't enabled  gateway switching, where can I check to be sure ?

**Comment by fichtner** [comment]
On the latest version it is under firewall: settings: advanced

**Comment by sachaz** [comment]
Ok I can confirm it's not enabled

**Comment by fichtner** [comment]
I'll try to reproduce, thanks.

**Comment by bergfink** [comment]
I have a very similar issue: 2 Gateways in a transfer Network on the WAN side. When changing the default Gateway in the WebGUI the routing table changes but the LAN Traffic (NAT) and the Traffic from  the Firewall itself still use the old Gateway. Only pure routed traffic (DMZ) is using the new Gateway. Tested with Version 17.7.6

**Comment by fichtner** [comment]
@bergfink It can't be both a bug that default switching keeps your connections alive or that it kills them... if you want a specific behaviour you have to configure it accordingly :)

also see https://github.com/opnsense/core/issues/1865

@sachaz please also check that issue, maybe this is the same problem

**Comment by bergfink** [comment]
Just to clarify - I made new connections to test e.g. traceroute and others - in this case neither the wan IP nor the WAN IF changes so connections have no need to be kept alive - only the route changes. To sum up - the IP packets just go a different way through the public internet, the endpoints stay the same.

**Comment by bergfink** [comment]
Do we need to wait for 18.1 for this to work? There doesn't seem to be a setting to fix this.

**Comment by fichtner** [comment]
@bergfink you should start by explaining your setup and settings. if you have a firewall running (not routing platform mode) the actual outcome can be radically different. You should mention the use of gateway groups, default gateway switching, whether or not this is unexpected behaviour from your side for outgoing connections or incoming ones, etc...

I can't possibly say what "18.1" will fix if we don't know what is actually broken. :)

**Comment by bergfink** [comment]
I thought I explained it. My setup is: Firewall, one WAN IF and two Gateways in the same Network as the WAN IF. (WAN 1.2.3.4/24 GW1 1.2.3.1 GW2 1.2.3.2). No Gateway groups, Enable Gateway switching is tested and doesn't help. I expect the traffic follows the active/current routing table. The goal is to switch between the gateways using the routing plugin.

**Comment by fichtner** [comment]
You've explained the setup, now you explained your settings. So far so good. Your setup already differs to the point that you don't have two WAN IFs. What is "routing plugin" -- the Quagga plugin?

Since you require NAT, the firewall is on, which means all existing connections should remain with gateway 1. Do you use any explicit gateway rules? Does a freshly started ping after the gateway switch use the correct gateway?

**Comment by bergfink** [comment]
Yes, with "routing plugin" I mean Quagga, but it's currently disabled. 

> Since you require NAT, the firewall is on, which means all existing connections should remain with gateway 1.

This is actually the problem - if GW1 can't be used anymore (routing table changes) the connection should not remain with it.

> Do you use any explicit gateway rules?

If you mean "policy based routing" with gateway rules - then no.

> Does a freshly started ping after the gateway switch use the correct gateway?

I tested with traceroute from the firewall and from a NATed host - both stay with the old gateway.
From a DMZ host it works.

**Comment by fichtner** [comment]
WAN will still have a fixed gateway unless you go to:

Firewall: Settings: Advances and enable the option "Disable force gateway".


Cheers,
Franco

**Comment by bergfink** [comment]
Even if there is no upstream-gateway configured for the WAN-interface?

I´ll test with that setting enabled but I have to wait for a less busy time to do so.

**Comment by fichtner** [comment]
Is your WAN DHCP?

**Comment by bergfink** [comment]
No, all static

**Comment by bergfink** [comment]
Sidenote: are we going off topic here? For me the core of the problem is the same (Gateway configuration is changed but does not apply to all traffic), thats why I posted here. I thought I was loosing my mind when the routing table looked correct and a route-query produced the expected result but my traceroute did not....

**Comment by fichtner** [comment]
I'd say yes as OP talks about issues with multi-wan, yours is about multi-gw on single-wan.

Can you also try to grep your rules for:

    # grep route-to /tmp/rules.debug

I suspect the firewall just sets the gateway anyway and we simply need to find out why.


Cheers,
Franco

**Comment by bergfink** [comment]
I did a limited test with "Disable force gateway" and it looks promising. "Limited" because I did not change the default-gateway but only tested a network-route and policy based routing via FW-Rules to redirect specific parts of the NATed traffic to GW2. This did not work before but it does work now so this could be it.

With "Disable force gateway" enabled the only rule with a "route-to" is my test-rule for policy based routing.

With "Disable force gateway" disabled I see a rule labeled "let out anything from firewall host itself" that has a "route-to" pointing to GW1. That rule matches anything going out on the WAN-IF with a destination outside the WAN-Network.

**Comment by bergfink** [comment]
pass out log from {any} to {any} keep state allow-opts label "let out anything from firewall host itself"
pass out log  route-to ( WANIF 1.2.3.1 ) from {WANIF} to {!(WANIF:network)} keep state allow-opts label "let out anything from firewall host itself"

These are the only "pass out" rules that would affect traffic going out the WANIF in rules.debug, the second one is only present if "Disable force gateway" is not checked. I am not quite sure yet how this rule would affect routed traffic from DMZ differently from NATed traffic from LAN-Interface

**Comment by fichtner** [comment]
I can confirm that this is the issue. It looks like the force gateway rule is greedy and does not respect the gateway choice of the respective interface. It also flip-flops to the one that is not disabled if there is more than one for the respective interface.

**Comment by bergfink** [comment]
Thanks for your effort and pointing me to the setting.
Out of curiosity: What is the advantage of the force-gateway rule?
The help in the WebGUI makes me think it should only affect traffic originating from the firewall itself, is that not the case?

**Comment by fichtner** [comment]
It helps non-tech savvy users to retain a functional network especially when creating multi-wan configs so that each link uses its own upstream instead of going out another (default) way. It came from our heritage and we are not completely satisfied with it. After internal discussion, however, we will keep the code as it is and think about a more explicit replacement of the gateway functionality underneath to avoid such problems in the future.

**Comment by fichtner** [comment]
Feature exists, no need to keep this open. :)
