### ISSUE TITLE
Zerotier official package

### ISSUE THREAD

**Issue by obrienmd** [opnsense/core#1775]
Would you consider adding Zerotier as a package with GUI configuration? 

https://forum.opnsense.org/index.php?topic=5015.0

**Comment by AdSchellevis** [comment]
@dharrigan seems to be working on it https://github.com/opnsense/plugins/tree/master/net/zerotier

**Comment by obrienmd** [comment]
Yikes, sorry I missed that :(

Closing...

**Comment by AdSchellevis** [comment]
@obrienmd no problem, lots of things going on here, hard to keep up :)

**Comment by fichtner** [comment]
It'll be in 17.7.1 officially. 😊

**Comment by obrienmd** [comment]
Sweet. Looking forward to giving it a test!

**Comment by obrienmd** [comment]
Wow... Nice. Works awesome from initial testing, shows up in interface assignments and all.

I'm curious, if I bind , say OPT4 to this interface and set up routing over it (OSPF, BGP, etc.), will it "change" upon reboot enough to break things given it's "dynamic" (for lack of a better term)?

**Comment by dharrigan** [comment]
Hi,

Thanks. It's still a work in progress and I welcome the feedback to make it better - I think from my testing there is an issue when binding to an interface, that somehow it doesn't quite work. 

The plugin should store its zerotier configuration (i.e., the network association) so that on reboot the interface will come back up again (and rejoin the zerotier network). 

Let me do some more testing on binding to interfaces (I may need some help from the OPNsense core team on this one). 

Do let me know how it goes for you! Don't forget to backup your OPNsense configuration beforehand :-)

-=david=-

**Comment by obrienmd** [comment]
Sorry, I need to move this grousing over to plugins :)
