### ISSUE TITLE
DHCP leases put a wrong interface with bridges

### ISSUE THREAD

**Issue by demarchidaniele** [opnsense/core#1803]
Hello, 
      I am using OPNSense 17.7.1_2 on a PC with 4 NICs and a PCIe 802.11 card.
The need is to create a unique WiFi area with internal 802.11 card and external AP on a different floor.
For this reason I've created a bridge of WiFi 802.11 card and one of the NICs.

Bridge "WiFi_HOME" = CARD_80211 + CARD_LAN2
CARD_80211 = No IP, Work as AP
CARD_LAN2 = No IP -> will be connected to 2nd floor AP (not present at the moment)

Bridge WiFi_HOME = Static IP 192.168.2.1

I've configured DHCP on WiFi_HOME with range 192.168.2.21 ... 192.168.2.199.

DHCP assign correctly IPs but when I look in Services->DHCP->Leases I note that the interface is not correct.

I expect to see the interface called WiFi_HOME near every 192.168.2.* address, but I see CARD_LAN2 (that is still not connected).

With this situation I am not able to get a working STATIC MAPPING because CARD_LAN2 doesn't appear on DHCP configuration since CARD_LAN2 doesn't have a static IP.

Am I doing something wrong?

**Comment by bolle732** [comment]
I think I have the same problem, but the report above is a little bit confusing.

My example (used since around version 16.7):
Have an ethernet device named 'LAN' and a wireless device named 'WLAN0'. Bridge the with the name 'BRIDGE0'. Assign a fixed IP to 'BRIDGE0' and enable the DHCP server on it. Before some resent update of OPNsense, the DHCP leases has been listed on the correct device 'BRIDGE0'. Making them static worked fine and they has been listed under the correct DHCP server instance.

About 2 weeks ago, I've upgraded my OPNsense installation from 17.1 to 17.7.11. After this upgrade, the old DHCP leases are still assigned on the correct bridge interface 'BRIDGE0'. But new leases are listed on ethernet interface 'LAN'. After making a new lease static, you can't edit it any more. This is due to the fact, that the 'LAN' interface is part of the bridge and doesn't has a DHCP server itself.

I've checked the configuration files. Old static leases are in the file '/var/dhcpd/etc/dhcpd.conf'. But I couldn't find the new ones. Non static leases are still in the file '/var/dhcpd/var/db/dhcpd.leases'.

So, to me, it seems that something fundamentally has changed in regards to DHCP leases. Does anyone have a hint how to clean up this mess?
