### ISSUE TITLE
UI - Left menu collapsing inconsistently

### ISSUE THREAD

**Issue by reetp** [opnsense/core#181]
OPNsense 15.1.10.2-amd64	

I noticed whilst looking at various menus that the left menu would refresh and collapse and I was left trying to remember which section I had been in. No breadcrumb available either.

Try Firewall, then click Aliases, then select a tab. The left menu collapses. This happens in a number of places.

Firewall, NAT seems to work correctly, as do some other sections.

Happy to test any mods.

**Comment by AdSchellevis** [comment]
Thanks for creating the issue, it should be fixed in https://github.com/opnsense/core/commit/b546fe050ed94f989afecd672b411c7f0fa9c333 
We rewrote the menu system to make it compatible with both the new and the legacy code and make it more transparent to manage it's contents (it's one component now using it's own xml definition).

If you find any more glitches, just let us know.

**Comment by reetp** [comment]
I can confirm that this seems to have fixed it. Will let you know if I find anything else !
