### ISSUE TITLE
Python and php-cgi isolation

### ISSUE THREAD

**Issue by ffries** [opnsense/core#1842]
i don't know opnsense framework very well, but it seems that python and php-cgi are running under root account. Is that the case and are there reasons for that?

**Comment by fabianfrz** [comment]
@ffries configd should run as root as it is the daemon for privileged actions. In contrast to that, PHP should not be run as root in long term but it still has to because not all privileged actions are extracted to configd.

As you can see, all plugins can run without root privileges. However if you check out the "etc/inc" directory, you may get in trouble if PHP would run without root privileges.

**Comment by fabianfrz** [comment]
@fichtner please tag as question

**Comment by fichtner** [comment]
Also see, https://github.com/opnsense/core/issues/1695 -- we should continue discussion there and close this, ok?

**Comment by ffries** [comment]
Sure, this is a double-post, sorry.
