### ISSUE TITLE
List users and create VPN accounts via API?

### ISSUE THREAD

**Issue by youhackme** [opnsense/core#1864]
Hello,

First, thank you for creating such a great tool. 

We actually have a specific need to allow certain users to create VPN accounts. Is this functionality available through an API endpoint? I'm unable to find documentation regarding this. 

Thanking you in advance. :)

Hyder

**Comment by AdSchellevis** [comment]
There’s no API endpoint available, but you could investigate the use of radius and use the freeradius plugin. I expect you can create users there from the API in the plugin

**Comment by fichtner** [comment]
@mimugmail can you confirm freeradius plugin has API to fetch user list and add / remove them? That would be a nice solution indeed...

**Comment by mimugmail** [comment]
@fichtner I'm not the API specialist, but since it's build plain MVC there shouldn't be a problem with it.
@youhackme you want to use it for OpenVPN? Beware that the authentication script for radius is very limited, only user/pw is supported. If you need extra attributes for every user you'll have some trouble :)

**Comment by mimugmail** [comment]
@youhackme Perhaps also relevant for you:
https://forum.opnsense.org/index.php?topic=6116.msg25680#msg25680

If it fits please close the issue 👍

**Comment by youhackme** [comment]
Hey thanks for your feedback guys. Unfortunately, radius is not a good fit for our scenario. I'm closing this issue.
