### ISSUE TITLE
Unable to start proxy 

### ISSUE THREAD

**Issue by gitmod** [opnsense/core#195]
Hi,

I updated the firmware to test the new proxy feature but it can't start. In forward-proxy configuration page, proxy port is 3128 and proxy interfaces is empty, I tried em0 and WAN.

2015/05/22 08:50:32 kid1| ERROR: No forward-proxy ports configured.
2015/05/22 08:50:32 kid1| Finished loading MIME types and icons.
2015/05/22 08:50:32 kid1| storeDirWriteCleanLogs: Starting...
2015/05/22 08:50:32 kid1|   Finished.  Wrote 0 entries.
2015/05/22 08:50:32 kid1|   Took 0.00 seconds (  0.00 entries/sec).
FATAL: No HTTP, HTTPS, or FTP ports configured
Squid Cache (Version 3.5.3): Terminated abnormally.
CPU Usage: 0.077 seconds = 0.032 user + 0.045 sys
Maximum Resident Size: 79408 KB
Page faults with physical i/o: 0

System (virtual machine with virtualbox with one network internface):
OPNsense 15.1.10.2-amd64
FreeBSD 10.1-RELEASE-p9
OpenSSL 1.0.1m 19 Mar 2015 

Updates 	
At Fri May 22 08:51:14 UTC 2015 no updates found.

**Comment by AdSchellevis** [comment]
I think your interfaces use dhcp to obtain an ip address and because squid needs to bind to an address (which is not in the configuration) it can't start. The solution might be to set a static ip on the interface you're using.

If your interface has a static ip and it is still not working, can you post some additional information like interfaces and perhaps a snapshot of the proxy part of your config.xml?

**Comment by gitmod** [comment]
Hi,

You'are right my interface use dhcp. I configured a static IP but squid is still not working correctly.
It seems that ACLs page is not working correctly,  each zone contains values like "first, contains, page, where, propValues" it looks like php code :)
![opnsense-proxy-acl](https://cloud.githubusercontent.com/assets/2040775/7811842/b86f8df8-03ad-11e5-9bc3-ce9322ab3382.PNG)

**Comment by AdSchellevis** [comment]
It actually was javascript code :-) issue with iterating a list of items, sometimes it seems to work so we didn't notice it before.
commit https://github.com/opnsense/core/commit/f4055efd1cb8a54ac6e2dd53df92752c3501102a should fix the issue.

**Comment by oleksandrmeleshchuk-epm** [comment]
Hi,
can someone please clarify why Squid is unable to use interfaces which are configured to receive IP-address using DHCP client?
Right now I'm facing same error, when Squid is unable to start on the interface which is having DHCP client enabled (there is no way to switch interfaces to the Static IP), from the Cache logs I can see message like (screenshot attached)
![image](https://user-images.githubusercontent.com/57523242/134472042-4d892d5e-9cbc-40fa-9555-01d10b89d952.png)

1. Squid service is able to start on the LocalHost interface, but in this case service wouldn't be reachable fro the LAN and VPN servers clients.
2. Squid is able to start while skipping interface selection - which is strange, as in this case where will it access connections?:) Checked connection to the Squid ports (3128, 3129) at all IP's which are assigned to the instance - none of them where successfull.

Regards

**Comment by fichtner** [comment]
Redirects can’t really handle shifting IP anyway. Localhost works. Just add a redirect (port forward).

**Comment by oleksandrmeleshchuk-epm** [comment]
Ok, so there is no functionality right now in OpnSense which allows to parse IP's of the Assigned interfaces.
Is there a way to run Squid in OpnSense on 0.0.0.0 rather than on a specific interface IP, as this will be more user friendly rather than creating NAT rule to the loopback interface (which creates issues with the correct working Squid ACL)?

**Comment by AdSchellevis** [comment]
currently not (usually it's not recommended anyway), a redirect doesn't mangle source addresses anyway so why would you want to bind to something that's not static. (localhost binding + redirect is a best practice advised by quite some vendors)

**Comment by oleksandrmeleshchuk-epm** [comment]
So in this case ACL functionality is pointless in the OpnSense configuration as any kind of restrictions to the Squid service should be done by the FW or NAT rules.

**Comment by AdSchellevis** [comment]
euh, no, but if that's how you think it works, I don't mind.  ACL's are usually matching source addresses, in case of a changing destination there wouldn't be any sensibel matching anyway.

We left all relevant pointers in this already closed issue, best of luck trying things out on your end.

**Comment by fre4ki** [comment]
Hi guys,

I have the same issue.

I‘m using just a WAN interface for a VPS from provider. It has a static WAN address but it has to be configured as DHCP. The VPS is acting as a Central VPN Gateway between sites.

I understand this is a squid issue, as i‘m just able to select static addresses instead of OPNsense logical interfaces. Maybe there is a better workaround for that?
