### ISSUE TITLE
Bug OTP 

### ISSUE THREAD

**Issue by bigops** [opnsense/core#1984]
Looks like the OTP is not working when we select 8 as the number of digits.  FreeOTP supports 8 digit authentication token, but the QR code generates only a 6 digit token.  Trying to add the seed manually generates a 8 digit code but is not authenticated by OPNsene.  

Also the algorithm used for the TOTP seed generation seems to be SHA1 (160 Bits) which is not secure.  It should be at-least SHA 256

**Comment by AdSchellevis** [comment]
The qrcode helper only supports 6 digit numbers for google-authenticator (or similar) at the moment, the problem is that you don't know for which service a user is generating the codes for at that point in time https://github.com/opnsense/core/blob/17.7.8/src/www/system_usermanager.php#L875-L895

Maybe we could add different buttons for different types of hashes, but most people use google-authenticator or something similar which doesn't support anything other then 6 digit sha1.

Choosing the hashing standard should in theory not be very complex (if I read the rfc correctly), it should land somewhere around here https://github.com/opnsense/core/blob/17.7.8/src/opnsense/mvc/app/library/OPNsense/Auth/TOTP.php#L103

SHA1 by itself is indeed not secure, but my my knowledge there are no known weaknesses in using the standard TOTP variant which is using it. (most vendors, also the commercial ones, use the standard implementation)

**Comment by bigops** [comment]
I think that explains why the QR Code is not working.   After adding the seed manually I am now able to successfully authenticate with a 8 digit code.  Rather than having a separate button for the QR code you can also consider a message stating the code is generated for 8 digits and does not work in GA.    To comply with the new RFC it would be ideal if the settings screen can have an option for SHA256/512 so if someone uses standards based authenticator like FreeOTP you can have the option.  It could be the feature for a future release

**Comment by bigops** [comment]
As commented by AdSchellevis the current QR code generator is non functional if the TOTP digits are set for 8.  While looking for solutions for a QR code generator which is compatible with 8 digits the FreeOTP implementation is working perfectly and it has an option to generate codes for various options.  It would be a good feature if this is ported to OPNSense so that 8 digit codes can be supported  

https://github.com/freeotp/freeotp.github.io

**Comment by fabianfrz** [comment]
The URL generated there looks like this:
otpauth://hotp/asdf?secret=eyy5vq6pizgiz2wprftva6nsgkwmbfjq&algorithm=SHA256&digits=8&period=60&counter=0

So the parameters might be appended.
