### ISSUE TITLE
NTP: Seperate between client and server

### ISSUE THREAD

**Issue by weust1979** [opnsense/core#2012]
Currently, there is no way in the general settings of OPNsense to set the time or date, either manually or using NTP.
There is a Service for NTP server, but you can't set local client settings there. Perhaps what you set there is used for local as well, but not sure.

I would like to propose the following two things:

1. Create a NTP client part under General Settings to set the local time and date.
Configuration settings should be either Manually, NTP (with the ability to specify time servers) or Disabled.
Disabled is for example with running as a VM, and the integration tools handle the time for the VM using the host the VM runs on.

2. Modify the Service for NTP Server so it can be fully disabled. Right now, if you don't select an interface the help specifices that not selecting means a wildcard is used.
The only way to stop the service is by stopping it, but that's not really disabling the service.

**Comment by fichtner** [comment]
2 has been possible for ages, just remove all time servers. 1 I'm not sure about, it would need a bit of cross-checking with ntpd operation (no use setting time if ntpd is running)

**Comment by weust1979** [comment]
The experience I have with setting up NTP was that you have two daemons.
One for running NTP Client, and another for running the server part.
That was years ago, and before (on Linux) when systemd took over.

Removing all time servers doesn't mean the service/daemon stops?
Will give that another look tonight.

**Comment by fichtner** [comment]
It's true that it takes both roles. I'm not sure what the best approach is in splitting that functionality, but we can figure this out on our way to 18.7. 18.1 we have to give some stability now.

See here https://github.com/opnsense/core/issues/332 :)

**Comment by weust1979** [comment]
Thatnks for 332 :-)

I just wanted to put the request in. Make my thoughts clear on the matter.
18.7 is fine. Wasn't expecting for 18.1.

**Comment by psychogun** [comment]
This would be great to have, as I am experiencing troubles using Chrony instead of NTPD; the firewall itself, I noticed, is drifting- not synchronizing with anything. 

Some information here: https://github.com/opnsense/plugins/issues/2162

So, my goal is to have OPNsense synchronize time with NTS. And this is accomplished by using Chrony. Whatever happens on the LAN side of things, the clients will just use their default servers / and or DNS host overrides pointing to an interface which is serving time on the firwall (which is not NTS, but hey, who can you trust- if not your own firewall).

Anyways.

- [x] Chrony synchronizes NTP with NTS.

- [x] Chrony serves the LAN side which is manually configured in the "Allowed Networks section" (who do I have to ask if I want to have a shiny drop-down menu here?)

- [x] Clients on LAN gets time from the LAN address on port 123.
- [ ] The firewall itself.

Now, how do I get the firewall to synchronize, with itself? Well, by pointing to a Time Server which is local (in the Network Time section)? And then start NTP daemon. 

But guess what, the port :123 is already in use by Chrony, and NTPD can not start. 

This would be a minor problem, if I could only start a NTP **client** (??)

```
[test@opnsense ~]$ sudo ntpdate -v 192.168.1.1
10 Jan 03:16:06 ntpdate[56714]: ntpdate 4.2.8p12-a (1)
10 Jan 03:16:06 ntpdate[56714]: the NTP socket is in use, exiting
```

```
[test@opnsense ~]$ date
Sun Jan 10 03:20:22 CET 2021
[test@opnsense ~]$ sudo ntpdate -v -u 192.168.1.1
10 Jan 03:20:56 ntpdate[41007]: ntpdate 4.2.8p12-a (1)
10 Jan 00:15:26 ntpdate[41007]: step time server 192.168.1.1 offset -11136.467989 sec
[test@opnsense ~]$ date
Sun Jan 10 00:15:29 CET 2021
```

> -u      Direct ntpdate to use an unprivileged port for outgoing packets.

This situation is currently solved by using a cron. 
```
[test@opnsense /usr/local/opnsense/service/conf/actions.d]$ more actions_ntpdate.conf 
[start]
command:/usr/local/sbin/ntpdate -u 192.168.1.1
parameters:
type:script
message:ntpdate -u 192.168.1.1
description:ntpdate -u 192.168.1.1
```

```
[test@opnsense /usr/local/opnsense/service/conf/actions.d]$ sudo service configd restart
Stopping configd...done
Starting configd.
[test@opnsense /usr/local/opnsense/service/conf/actions.d]$ sudo configctl ntpdate start
OK
```

Although, doing this - the Network Time widget on the Dashboard does not work  - "No active peers available". 

This integration with the Chrony plugin might need some more work. Or am I doing something which it is not intended for.. . 


Regards to issue https://github.com/opnsense/core/issues/332 - this should be in the "Full Help" section. It is not clear, atleast not coming from pfSense over to OPNsense ;)

**Comment by fichtner** [comment]
Looks like the "trick" was initially documented, but removed later due to server edit duplication https://github.com/opnsense/core/commit/0d70b4a9dbde2889063fba177a06f5fb139d87f4#diff-7cf0b0c2d1faa70f4d40e9a5c1927c5d8d0b1552f3eb91d0e2ebef69f9726ed0R457

We should probably offer the use of a periodic ntpdate. There is no real client mode to ntpd itself.

**Comment by psychogun** [comment]
@fichtner 

Thank you for your feedback.
