### ISSUE TITLE
18.1rc2 - frr start fails due to watchfrr_enable not being set

### ISSUE THREAD

**Issue by rootwyrm** [opnsense/core#2100]
Observed at startup:
`Cannot 'start' watchfrr. Set watchfrr_enable to YES in /etc/rc.conf or use 'onestart' instead of 'start'`

FRR fails to start as a result. Inspecting `/etc/rc.conf.d/frr` shows that `watchfrr_enable="YES"` is present. Possibly a problem upstream in `/usr/local/etc/rc.d/frr`. Manually starting FRR from services does not encounter this problem.

**Comment by fichtner** [comment]
watchfrr_enable is not visible to watchfrr service if it writes to /etc/rc.conf.d/frr as it should be in /etc/rc.conf.d/watchfrr -- quagga plugin has the same problem apparently.

> FRR fails to start as a result.

It should not matter for FRR startup though, because frr_enable is mandatory here.

**Comment by rootwyrm** [comment]
That is also my thought @fichtner but alas, it does cause the entire startup to fail. Which makes no sense. It should only stop `watchfrr` not `frr` itself. I will have to look at the port script tomorrow.

**Comment by fichtner** [comment]
FWIW, this is a plugin bug, not core. Did not notice before.

**Comment by rootwyrm** [comment]
Whoops! It wasn't clear to me in 18.1r2 that this is still a plugin, TBH. My bad there. 

Found one problem, though. `%%LOCALSTATE_DIR%%` isn't being expanded in `/usr/local/etc/rc.d/watchfrr` which obviously is not good.

Root cause is use of `load_rc_config $name` - it's attempting to source `/etc/rc.conf.d/watchfrr` which does not exist. Obviously this presents two fix options; change `/usr/local/etc/rc.d/watchfrr` to use `load_rc_config frr` or place `watchfrr_enable="YES"` in `/etc/rc.conf.d/watchfrr`

However, there remains a significant bug. Both of those fixes will cause `/usr/local/etc/rc.d/watchfrr` to attempt to start; however it attempts to start as `limits -C daemon /usr/local/sbin/watchfrr` resulting in an error as no daemons to monitor are being passed to the script.

**Comment by fabianfrz** [comment]
@fichtner Cannot reproduce - it is running flawlessly on my end (freshly installed FRR plugin):

![screenshot_20180118_191744](https://user-images.githubusercontent.com/3713914/35114211-434cf416-fc84-11e7-9cef-5961bdc324fe.png)

**Comment by fichtner** [comment]
Yes, this is about watchfrr anyway, it's also wrong in quagga, but it doesn't matter.

**Comment by fabianfrz** [comment]
watchquagga was also optional. It should restart a deamon after a crash but I do not think it is really needed...

**Comment by rootwyrm** [comment]
No, this is actually needed, since certain bad-actions are supposed to trigger abort/quit. I'm not sure why it's not reproducing for you, but it reproduces reliably for me and I can tell you for fact that the `watchfrr` script as it stands is broken. That's just a fact.

@mimugmail said that he would prefer sticking to `/etc/rc.conf.d/frr` rather than adding an additional file, so I'll try and get a fix thrown together today.

**Comment by mimugmail** [comment]
@fabianfrz we should really use this, or better, allow the user to decide if it's enabled or now.

Some months ago there was this problem with Quagga and announcing too many prefixes. Also me was affected and my bgpd crashed (without beeing restarted). 

https://lists.quagga.net/pipermail/quagga-users/2017-October/014853.html

The problem is, if bgpd would be restarted, it would crash again and restart and after an hour you would run into problems because of route flapping :) 

@fichtner opinions?

**Comment by lorephoenix** [comment]
@fabianfrz @fichtner 
I encounter the same issue reported as @rootwyrm .
Started from a fresh OPNsense 18.1 installation I updated OPNsense first to version OPNsense 18.1.2_2-amd64. Afterwards I installed the plugin os-frr (1.0_2) and I configure my OSPF settings.
Initiate the service from OPNsense page works fine but it doesn't startup the service (frr) from boot.

I also notice the same  message:
Cannot 'start' watchfrr. Set watchfrr_enable to YES in /etc/rc.conf or use 'onestart' instead of 'start'

Any progress about solving this issue?

**Comment by fichtner** [comment]
@lorephoenix trying a workaround in https://github.com/opnsense/plugins/commit/f26a704f9

It's tricky to debug startup but we use a similar trick for c-icap

**Comment by fichtner** [comment]
Fixed, removed faulty watch* line from rc.conf.d file as well https://github.com/opnsense/plugins/commit/975b9558

**Comment by nanfengnan1** [comment]
so frrwatch denpends on quagga? why document did'n any explain?
