### ISSUE TITLE
Min, Average, Max, Last CPU usage

### ISSUE THREAD

**Issue by NOYB** [opnsense/core#2105]
How about it?
Min, Avg, Max, Last CPU usage, of the graph time period, in the system information widget.
Below the graph perhaps.

**Comment by fichtner** [comment]
Sure, sounds useful. Do you want to be the assignee of this ticket?

Two related forum entries for reference:

https://forum.opnsense.org/index.php?topic=6854.0
https://forum.opnsense.org/index.php?topic=6888.0

**Comment by NOYB** [comment]
No, don't want to be assignee of this ticket.

**Comment by weust1979** [comment]
As the creator of topic 6880.0, this is what I have been noticing for a long time now.

Environment: Windows 10 using various browsers (Edge, Waterfox, Vivaldi).

Situation: When I mouseover the CPU graph, it will always show the percentage in the top middle, reflecting the CPU percentage from the middle.
It doesn't matter where I place the mouse cursor on the graph, the middle is always shown.

Expected behavior: The percentage shown moves alongside the CPU graph where I move the mouse cursor, showing the percentage at that point on the CPU graph.
![cpu_graph](https://user-images.githubusercontent.com/11320409/35091811-f35962c8-fc3d-11e7-9725-fe7b04bf8dd8.png)

**Comment by beren12** [comment]
Yeah would be nice to have this fixed. I wondered what was going on...

**Comment by fichtner** [comment]
This was a feature ticket, @weust1979 please recreate a bug ticket
