### ISSUE TITLE
TrafficShaper not Working on 18.1_1

### ISSUE THREAD

**Issue by ckals** [opnsense/core#2192]
Hi there,

I have 2 TrafficShaper Rule's in use to Limit the Download & Upload Speed for our guest users (in Guest WiFi). Since on or two Updates back i need to "re-apply" (only hit apply without canging any settings) the rules/pipes to get the correct limitation. Otherwise (lets say one day without "re-apply") i only get very low speeds. 
The Limitations are 15 Mbit/s for Download and 2 Mbit/s for Upload.
When one Client is there and i "Re-apply" the rules the SpeedTest show the correct speed; Otherwise i get 1 Mbit/s Download and 0,1 Mbit/s Upload.

Any Ideas about that behaviour ?

**Comment by mimugmail** [comment]
To troubleshoot I would create the same rules and Pipes for other Ethernet Nic. If also occurs check status page while testing and check the logs.

Perhaps deleting all, reboot and recreate also helps?

**Comment by hutiucip** [comment]
It **might** be older than 18.1, I remember I noticed a similar drop in effective throughput after the winter holidays, OPNsense being left alone since 12.23.17 until 01.08.18 - 17.7.11 or 12, I can't really remember the sub-subversion. The effective speed was crawling, and a quick disable/ enable restored everything to normal.

But I don't use TS any more, so I didn't experienced anything like this since then.

**Comment by fichtner** [comment]
Docs updated https://github.com/opnsense/docs/commit/64663c9fb26a7fb27b502c8f3f8ee9c5f6c0ee01
