### ISSUE TITLE
Squid 3.5.27 now fails audit security check

### ISSUE THREAD

**Issue by seanbarr1988** [opnsense/core#2224]
***GOT REQUEST TO AUDIT SECURITY***
Fetching vuln.xml.bz2: .......... done
squid-3.5.27_2 is vulnerable:
squid -- Vulnerable to Denial of Service attack
CVE: CVE-2018-1000027
CVE: CVE-2018-1000024
WWW: https://vuxml.FreeBSD.org/freebsd/d5b6d151-1887-11e8-94f7-9c5c8e75236a.html

1 problem(s) in the installed packages found.
***DONE***

**Comment by fichtner** [comment]
Sure, we cannot control releases of third party fixes. The scanner is for your convenience. Will most likely be fixed in 18.1.3.

**Comment by seanbarr1988** [comment]
no worries, I just felt it was the right thing to do to make sure it was known. I wasnt expecting there to be a sudden rush to patch the vulnerability but perhaps a newer version can be added when its ready 👍

**Comment by fichtner** [comment]
FWIW, the links with additional info can help mitigate or see the affected scope, sometimes it’s not a problem. E.g. DoS when proxy is only reachable from a trusted network. But haven’t had time to look at the CVEs yet myself.

I think 18.1.3 hits around Wednesday. It’s been a bit slower the last two weeks on our end due to the vacation season, but picking up the usual pace again soon.

Thanks for the heads-up. :)
