### ISSUE TITLE
i can't install some rules of the ids

### ISSUE THREAD

**Issue by idlmcw** [opnsense/core#2253]
after installation of OPNsense i can't install some rules of the ids.

This rules are:

abuse.ch/Dyre SSL IPBL 	
abuse.ch/Feodo Tracker 	
abuse.ch/SSL Fingerprint Blacklist 	
abuse.ch/SSL IP Blacklist
ET open/emerging-trojan 	
ET open/emerging-user_agents 	
ET open/emerging-voip
ET open/emerging-web_client 	
ET open/emerging-web_server
ET open/emerging-web_specific_apps 	
ET open/emerging-worm
ET open/tor 	
OPNsense/test rules

Thank you

**Comment by fichtner** [comment]
Click the checkbox in from of the rulesets you want to enable. Click "Enable selected" on top. Lastly, click "download & update rules".

Let me know which step isn't working for you?


Cheers,
Franco

**Comment by petererdos** [comment]
Maybe it's because the GUI doesn't have some kind of progress for these actions? They are usually enabled and downloaded in the background, but there's no indication of this in the GUI (if i remember correctly) and if you don't wait long enough, you might think it's not working, while all you have to do is to refresh the page a few minutes later.

**Comment by Fr3ki** [comment]
'Click the checkbox in from of the rulesets you want to enable. Click "Enable selected" on top. Lastly, click "download & update rules".'

doesn't work for me. I can enable the rules, but not download it. 

kind regards
