### ISSUE TITLE
Realtek RTL8723AE Support?

### ISSUE THREAD

**Issue by sempervictus** [opnsense/core#2270]
A number of devices we're using include Realtek wireless cards which aren't detected by OPNSense as viable for use in wireless networking.
_pciinfo -lv_ says the devices are:
```
none1@pci0:1:0:0:	class=0x028000 card=0x21141a3b chip=0x872310ec rev=0x00 hdr=0x00
    vendor     = 'Realtek Semiconductor Co., Ltd.'
    device     = 'RTL8723AE PCIe Wireless Network Adapter'
    class      = network
```
Quick search online shows that BSD and wireless are still not playing well with each other all these years later, and Realtek is not well supported. Any chance this situation has changed and i'm simply doing something wrong in the system configuration, or that the kernel is not being compiled with these drivers? Or is it still along the lines of "get a well supported card, HW-specific support levels fluctuate in BSD, good luck?" :)
If wireless support could be expanded somewhat, it would definitely be of use for smaller locations where the separate wireless APs are redundant given that the FW's have the necessary physical devices to run the wireless network for the entire place, were they to be usable by the OS.

**Comment by AdSchellevis** [comment]
you probably better try Realtek or FreeBSD directly, we normally don't try to add drivers ourselves.

**Comment by fichtner** [comment]
For wired ethernet we use the official Realtek driver as opposed to FreeBSD's. It's proven less error-prone in general. For wireless, I think it's more complicated as there is no official Realtek driver and the actual chipsets are scattered around different drivers due to USB or other means of attachment. Sometimes the device is simply not known to the driver so it refuses to operate, e.g. https://github.com/opnsense/src/commit/c1e3838d9506b4ddb2b08894a4b90d6b306b7dd8 but I don't know if that's the case here.
