### ISSUE TITLE
Question: will netmap be updated regulary?

### ISSUE THREAD

**Issue by mimugmail** [opnsense/core#2288]
https://github.com/luigirizzo/netmap/commits/master

There are many fixes regarding ix drivers, still searching for my problem that ixl Interface stops working when Suricata in IPS mode ...

**Comment by fichtner** [comment]
we have no time to Q/A future versions for them, maintainers regularly introduce breakage and are mostly unresponsive, just look at this tiny example:

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=191320

... or when we had to fix 11.0 release driver emulation mode because they didn't want to. It was only fixed after it was sponsored by pfSense ;)

https://github.com/opnsense/src/commit/175886459 vs. https://github.com/freebsd/freebsd/commit/569945959b6

**Comment by mimugmail** [comment]
Just for my own understanding (no offense):

1) GitHub Code is also badly maintained regarding FreeBSD? There are also fixes for virtio which also struggles with IPS :)

2) FreeBSD team maintain their own Version? Or is the Dev state stale? This would mean new NIC and drivers in the Future would make more problems with netmap.

**Comment by fichtner** [comment]
Netmap regularly updates in FreeBSD, but mostly only in CURRENT, not releases. The authors of Netmap can commit to FreeBSD on their own, but rarely fix production issues or take care during their "new netmap version" dumps obscuring all the code history.

**Comment by fichtner** [comment]
Basically you get a "new netmap version" 1000+ lines of code and then start looking for the one line that breaks a use case. The netmap.git is helpful for bisect, but it shows that errors are not caught early because of the staged release approach...

**Comment by fichtner** [comment]
And when I say "regularly", that means 1-2 times a year at most.

**Comment by fichtner** [comment]
Netmap is as good as it tries to be on its very own. That's all there is to it.

**Comment by mimugmail** [comment]
Ok, I was just looking for an easy (self solvable) solution, thanks 👍

**Comment by fichtner** [comment]
Sure, no problem. The gist is that it's difficult either way. Trading fixes for regressions.
