### ISSUE TITLE
flowd.log size and rotation

### ISSUE THREAD

**Issue by alesnav** [opnsense/core#2296]
Hello there!

I have a problem with disk usage in my OPNsense installation. It is related basically to two problems.

One is squid cache (my fault, apparently), but the other one is related just with one huge file: /var/log/flowd.log

It seems that no process is taking care with this file because it is getting bigger and bigger... I had to delete this file to be able to use my firewall again.

Can you please check it?

Thanks!

**Comment by AdSchellevis** [comment]
flowd.log is collected and rotated by `flowd_aggregate`, which is used for network insight. Are you using the latest version of OPNsense?

**Comment by fake-name** [comment]
This issue is not resolved, or at least can reoccur easily.

Basically, the log file is not rotated by the daemon consuming it. As such, if `flowd_aggregate` gets in a bad state and/or crashes, the `flowd` feeder daemon will happily continue to log to the same log file until it runs out of disk space.

I just hit this issue when my PFSense instance started exhibiting a whole variety of weird issues due to being completely out of disk space.

The component of flowd that writes to the log file HAS to also be the component that does the log rotation, or at least it needs to monitor the file size and stop logging under low memory conditions.

**Comment by TomFaulkner** [comment]
This seems to still be an issue today. I have to manually delete the file every few days, as it will fill the disk and take down other services.

**Comment by Jas0n99** [comment]
Seems to still be an issue, I just noticed that I was almost out of disk space today and when I checked /var/log I was shocked to see all the flowd files and the current was over 4 gigs. Seems like it hasn't been rotating either.
