### ISSUE TITLE
dhcpv6 static mappings not working?

### ISSUE THREAD

**Issue by kingfisher77** [opnsense/core#2324]
Our parallel IPv6 network is set up, the "unmanaged" modus of Router Advertiment (RA) is basically working. 

Later we configured dhcpv6 with "managed" modus of RA. Clients receive their dynamic ip adresses, perfect.

But converting dynamic leases to static leases is not working. Under Leases we find two entries with the same DUID and the dynamic ip address is still delivered and "online". The static entry is "offline".

Any hint for us?

**Comment by philippwaller** [comment]
With Debian and Centos I face the same problem. The DUI is displayed twice in the lease list and only the dynamic ip is delivered. Strangely, this problem does not occur with Coreos. The same behavior I have also found in PFsense. 

Are there any client settings that we have to consider?

**Comment by philippwaller** [comment]
I finally found the cause. The problem is how the dhcp client get involved by the most network managers / tools. For example, the `dhclient` must be called with the "-D LL" option to ensure a static DHCP client id. Unfortunately, this option is not considered by most network manager tools. 

I solved the problem by creating a manual net interface and calling the DHCPv6 client manually:
```
#/etc/network/interfaces
auto ens18
iface ens18 inet dhcp
iface ens18 inet6 manual
  pre-up sleep 2
  up dhclient -6 -D LL -v $IFACE
  down dhclient -6 -r -v $IFACE
```

Finally, the static DHCPv6 assignment with opnsense works.

**Comment by iamperson347** [comment]
I'm not sure if this is related, but I am seeing a similar issue. The only difference is that the dynamically assigned address does not show "online." This is with an ubuntu 18 vm.

![image](https://user-images.githubusercontent.com/1909402/43868354-2f66ede8-9b3b-11e8-8618-f890523cbdf9.png)
