### ISSUE TITLE
Route-based IPSEC / if_ipsec

### ISSUE THREAD

**Issue by mimugmail** [opnsense/core#2332]
Hi,

I'm targeting route-based IPSec and need some modifications. 
Before I start digging into it I just want to ask if it's ok to:

- make a new button in phase2: install policy yes/no
- make auto = route to auto = start when button install routes in Advanced is NOT ticked

If yes I'd try this by mysef ..

**Comment by AdSchellevis** [comment]
Hi Michael,

What do you mean with a new button in phase2? 
Adding route-based would certainly be a good addition to have, I can help you review some code and suggest changes as long as the commits are in a manageable state (not too large).

Best,

Ad

**Comment by mimugmail** [comment]
Sorry, I mean a checkbox ..

**Comment by AdSchellevis** [comment]
clear, that makes sense :)

**Comment by mimugmail** [comment]
Ok, I have a running setup. Quite easy but I need some additional commands like setting up a GRE/GIF tunnel. ATM .. I'm a bit underskilled for this.

Steps to reproduce:
- Create a VPN with left und right subnet 0.0.0.0/0
- In Advanced set Don't install routes
- In P1 we need a checkbox "Install Policy", default checked which sets installpolicy = yes (which is already set to yes some where. Then uncheck it.
- We need a if/else that when in Advanced Dont install routes is ticked, don't set auto = route, instead auto = start. 
- In P1 we new a new integer field for a "reqid" which sets reqid = XXX in con

This is fairly easy, now the tricky part:
- For P1 we need a IF Install Policy = no && IF req != '' then

```
ifconfig ipsec0 create reqid <reqid>
ifconfig ipsec0 inet tunnel <left-ip> <right-ip> up
ifconfig ipsec0 inet <left-tunnel-ip>/32 <right-tunnel-ip>
```

Then you can create a new gateway with right-tunnel-ip and set as many routes as you wish.

Perhaps you could also create a new checkbox in P1 with "Enable Route-Based VPN" as a selector for IF bla

**Comment by mimugmail** [comment]
If you are motivated you could create a new branch for this for testing ..

**Comment by ccesario** [comment]
Aybe this reference canal help https://redmine.pfsense.org/issues/8544

**Comment by ccesario** [comment]
@mimugmail is the feature working into 18.7.2  version?

**Comment by ccesario** [comment]
Hi folks, is there any progress with this feature!?

**Comment by fichtner** [comment]
Nope. All hands welcome.

**Comment by AdSchellevis** [comment]
```
pkg install -f opnsense
opnsense-patch 9ccabe6 4c3d069 a045d3e d9dbcaf 8a55989 77743cf 139ef62
```

**Comment by AdSchellevis** [comment]
```
pkg install -f opnsense
opnsense-patch 9ccabe6 4c3d069 a045d3e d9dbcaf 8a55989 77743cf 139ef62 ee8fd03 83bdc4b  9d6bf15
```

**Comment by AdSchellevis** [comment]
Some random notes as long as we don't have docs available:

- in phase2 a mode is added "Route-based" which expects an address locally and one remote, which defines the tunnel.
- internally all phase1 connections have a number assigned to it (ikeid), which is used to calculate a `reqid` for both strongswan and the virtual tunnel interface
- the device name created (e.g. ipsec1000) corresponds to the reqid (e.g. 1000) 
- not mobile ikev1 or tunnel isolation creates a `conn` section per phase2, which in this case also creates ipsecXXXX tunnel interfaces per phase2
- for every VTI there will be an interface visible in OPNsense, using the phase1 or phase2 description depending of what defines the tunnel (see previous point).
- you need to allow traffic on the `IPSec` interface in order for the VTI to receive it, so the vti interface in the firewall section looks a bit duplicate to some regard.
- you don't get to setup a local and remote network, since these should be handled via routing and are defaulted to any
- the rest of the tunnel definition should be pretty standard

![image](https://user-images.githubusercontent.com/9783985/53886697-de0c7400-4020-11e9-94e2-2378b782d61f.png)

**Comment by fichtner** [comment]
close and ship in 19.1.4 ? :)

**Comment by mimugmail** [comment]
I'd wait, I only tested what works, not what would break when X

**Comment by AdSchellevis** [comment]
The risk of doing so would however be rather low, impact on the existing features is minimal, unless I'm overlooking something. If the new feature doesn't work in some scenario's we'll likely find out after release anyhow.  (unless there are specific scenario's we still should test that we know of)

**Comment by mimugmail** [comment]
OK, then let's go for 19.1.4. I'll try to add a Cisco example to the docs end of next week.

**Comment by AdSchellevis** [comment]
@mimugmail thanks!

**Comment by fichtner** [comment]
ideally we should wrap all commits into one stable commit so that easy revert is possible, I just need all the relevant commits... are they all in this ticket?

**Comment by AdSchellevis** [comment]
it should all be here, I don't think I missed anything, I tried to reference every step.

**Comment by fichtner** [comment]
I had to pull in 6a4fa40e724 as well, result is 8490bc70abc383

Please double-check :)

**Comment by AdSchellevis** [comment]
@fichtner checked in git, looks good to me. Thanks!

**Comment by alexanderharm** [comment]
I am testing this patch with Azure. However the config is not 100% clear to me. What goes into `Local Address` and `Remote Address`? Some arbitrary IPs of the remote network? Just any two IPs? I initially set `Local Address` to my LAN IP but killed the firewall completely, no access whatsoever anymore. Any pointers appreciated.

**Comment by mimugmail** [comment]
https://github.com/opnsense/docs/blob/master/source/manual/how-tos/ipsec-s2s-route.rst

**Comment by alexanderharm** [comment]
@mimugmail Thanks!

**Comment by alexanderharm** [comment]
Any idea on how to get this working with Azure S2S VPN? I followed the manual but there is no ping whatsoever to the remote ip address defined.  Also hosts in the routed networks are not reachable. In the status overview I can see that the connection is established and that there is some activity (in/out). Do I need to configure the new interface in any way, do the local/remote ip need to be part of a specific subnet? I checked on my UniFi Gateway and there does not seem to be any local/remote ip defined.

**Comment by alexanderharm** [comment]
Solved! One needs to add the `Local Address` as additional `Address space` (e. g. `10.111.1.1/32`) to the Azure `Local network gateway`.

**Comment by alexanderharm** [comment]
Fantastic job guys, we just migrated from Sophos and so far I have zero regrets! Keep up the good work.

**Comment by mimugmail** [comment]
Would you like to add some screenshots of Azure and OPNsense and put it as an example in the docs? Or put it just here and we'll try to write it down. Would be a nice addition for the community :)

**Comment by alexanderharm** [comment]
Of course. I will make a PR to the docs, OK?

**Comment by mimugmail** [comment]
This would be awesome! :)

**Comment by alexanderharm** [comment]
The documentation can be found here: 

https://wiki.opnsense.org/manual/how-tos/ipsec-s2s-route-azure.html

**Comment by jroehler23** [comment]
Hi,
VTI tunnel is not working with 19.1.6. Tunnel is not coming up. In the logs I can see some mismatch with reqid?

I've done the configuration as shown in the wiki.

`

Apr 25 10:52:55 | charon: 09[CFG] trap not found, unable to acquire reqid 0
-- | --
Apr 25 10:52:55 | charon: 09[KNL] creating acquire job for policy XXX.XXX.XXX.XXX/32 === YYY.YYY.YYY.YYY/32 with reqid {0}
Apr 25 10:52:55 | charon: 09[KNL] received an SADB_ACQUIRE with policy id 52 but no matching policy found
Apr 25 10:52:43 | charon: 13[CFG] trap not found, unable to acquire reqid 0
Apr 25 10:52:43 | charon: 13[KNL] creating acquire job for policy XXX.XXX.XXX.XXX/32 === YYY.YYY.YYY.YYY/32 with reqid {0}
Apr 25 10:52:43 | charon: 13[KNL] received an SADB_ACQUIRE with policy id 52 but no matching policy found

`

**Comment by mimugmail** [comment]
Was it working with 19.1.4 or 5? 
Install policy enabled/disabled in Phase1?

**Comment by jroehler23** [comment]
I switched directly from 18.7 to 19.1.6.

The policy is not enabled in Phase 1.

**Comment by alexanderharm** [comment]
We still run it on 19.1.4 with the suggested patches and it works fine so far. We didn't dare to upgrade yet, though.

**Comment by jroehler23** [comment]
So, then don't do it. After this, it won't work anymore ;)

I have seen in some post that the reqid option in the IPSec settings was removed after 19.1.4. I think this is the major problem. In my logs I can see on both sides that IPSec is watching/working with different ids.

**Comment by fichtner** [comment]
> So, then don't do it. After this, it won't work anymore ;)

@jroehler23 If you're trying to be funny this may come off as rude to some who work on this code and use it successfully. I just want to point that out very friendly.

**Comment by fichtner** [comment]
FWIW, it would be even better to open a support ticket with all the info of your case condensed, because a number of bugs were fixed in 19.1.4 - 19.1.6 and the feature is still relatively young and the issue here is already closed and there's not much sense reopening it as it refers to the initial implementation and things have changed since.

**Comment by jroehler23** [comment]
@fichtner I know this is a feature for milestone 19.7, so for me it seems to be beta. And normally in the course of development, comments like mine shouldn't be treated so seriously. But you are right, it was not in my mind to blame somebody for his "bad work" or something like this! I apologize if somebody took it the wrong way. It should just be a hint for others to be careful to update to 19.1.6, because it has taken me days to come to this point.

I will open a new ticket with my issue.

**Comment by fichtner** [comment]
Thanks. No worries. Can only get better. :)

For reference the ticket is https://github.com/opnsense/core/issues/3443
