### ISSUE TITLE
More specific error message when firmware update fails

### ISSUE THREAD

**Issue by binaryanomaly** [opnsense/core#2370]
I had the DNS server not exposed on localhost which caused opnsense to not be able to resolve the update URLs. The error message I got was only: "Connection error."

This is not very specific and was not particularly helpful in finding the cause. It would have been better to return something like "DNS resolution failed".

**Comment by fichtner** [comment]
I'm going to change it to "Failed to connect to the selected mirror." as it could fail for a number of reasons.

**Comment by binaryanomaly** [comment]
Would it be much effort to return the real error cause?

I'm not sure if just altering the generic error message would help people to more easily identify the underlying root cause? (In my case it was the DNS resolution that failed not a real connection problem.)

Or maybe the message could point/hint to the logs one could consult to find out the real problem (I still have no clue which ones those would be).

**Comment by fichtner** [comment]
Define "real error". DNS resolution can fail on typos, suboptimal DNS resolution, IPv6 problems (latent).

We possibly have two errors that are somehow returned by "pkg update -f": DNS resolution failure or connection timeout. Right now we don't see those errors, but that's partly due to the current design.

So the question is not how to show "real errors" but how to help people troubleshoot their setups in a more meaningful way. So the first step would be to ask if the firmware section is the best way to do this?

**Comment by binaryanomaly** [comment]
Agree it's mostly about giving hints where to look for the problem. What really happened behind the scenes gives clues where to look further...

Imho if a problem occurs in the context of a process/action (ie. an attempt of updating the firmware) it should be displayed in that particular context.

Maybe just changing the super generic error message into something
"check DNS resolution on the OPNsense host (https://opnsense.localdomain/diag_dns.php) / check connectivity..."
could help if it's not easily possible to return the real error messages from the executable that fails (wget, curl, ...?).

(I'm aware the provided example text is far from perfect but just as an idea)

**Comment by fichtner** [comment]
Want to limit the process to pkg-update, pkg-install and pkg-upgrade... pulling in other checks/tests will bloat the code, add spurious checks / slowdowns and other problems in parsing these tool's outputs down the road.

What I can easily do is add a "timeout" error that basically means DNS resolution went through but could not update the repository while trying to connect. If that was IPv4 or IPv6 in the end is not visible though..

**Comment by fichtner** [comment]
PS: forcing an unresolvable DNS entry kills most of pkg's defined behaviour making the firmware page more or less unusable. Oh joy. ;)

**Comment by binaryanomaly** [comment]
> What I can easily do is add a "timeout" error that basically means DNS resolution went through but could not update the repository while trying to connect. If that was IPv4 or IPv6 in the end is not visible though..

Being able to distinguish between DNS or connectivity issues even only on a high level could indeed already be valuable - that sounds like a good improvement to me.

**Comment by fichtner** [comment]
Thanks for your help and discussion! Now I have:
* No address record found for the selected mirror. (breaks check early now)
* Could not authenticate the selected mirror. (breaks check early now)
* The current package configuration is invalid. (breaks check early now)
* Timeout while connecting to the selected mirror. (more or less the previous error)
* An error occurred while connecting to the selected mirror. (this one is unspecific on purpose because we don't know what happened, maybe it can not even be triggered but better to catch it than not)


Cheers,
Franco

**Comment by binaryanomaly** [comment]
Awesome! That'll certainly help people to more easily identify potential root causes of problems.

I thank, good job! 👍🏻

**Comment by fichtner** [comment]
Thank you for the report. :)

I don't tknow when this will hit 18.1.x, certainly not the next 1-2 iterations but it will be available before we jump to 18.7.

**Comment by binaryanomaly** [comment]
Given that it's not critical but rather an annoyance this makes a lot of sense. Anyway, looking forward to it ;) thx again
