### ISSUE TITLE
Importing an exported pfsense configuration xml breaks the web-ui.

### ISSUE THREAD

**Issue by fake-name** [opnsense/core#2374]
This might be a dumb issue, but I recently migrated a pfsense box to opnsense, because somehow the pfsense 2.3 -> 2.4 upgrade causes pfsense to no longer see any of the box's network interfaces.

In any event, I had a exported pfsense configuration xml file thing, and I figured it might import into opensense.

I tried doing so, and it resulted in no errors, but also broke both the web-ui and the local console. After importing the config, the web-ui no longer starts, and logging in on the local console results in getting dumped straight into a terminal session, rather then the "choose your option" thing you get on a normally functioning system.

This was on a brand new install, so it wasn't a terrible issue (I just reinstalled), but it seems that even if importing pfsense configurations isn't supported, it shouldn't completely hose the box.

Anyways, I'm attaching the config in question, though I've sanitized it a bit.

There are some VPN keys in there, still, but I've regenerated them entirely, so the private keys there are now useless.

Config gist: https://gist.github.com/fake-name/4cd2a93c955d300a32c7e427e9bb2664

**Comment by fichtner** [comment]
Hi there,

The &lt;system/&gt; section is not compatible for a few reasons now, the last one being that passwords are stored in an incompatible fashion nowadays. We used to hold a bit of migration code for older versions, mainly 2.1, but since 2015 2.2, 2.3 and 2.4 have diverged ever more rapidly that any attempt to keep up with it is pointless from our POV.

You can still import several other sections with fair results. People have done and continue to do so and for us this would mean adding work for fixing specific cases instead of preventing an import which would not fix our model of openness. :)

Here's an older ticket for reference: https://github.com/opnsense/core/issues/28


Cheers,
Franco

**Comment by fake-name** [comment]
The problem isn't that it doesn't work, but the fact that importing it **hosed the install**.
