### ISSUE TITLE
[18.7.b_65] SSH login stopped working after upgrade

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#2403]
Took me a few hours to figure out why, looks like the shell for all users except root was set to /sbin/nologin.

**Comment by AdSchellevis** [comment]
hmm, the culprit seems to be here https://github.com/opnsense/core/blob/master/src/etc/inc/auth.inc#L458 which used a csh when priv was set previously https://github.com/opnsense/core/blob/18.1.7/src/etc/inc/auth.inc#L464

@fichtner intended? or a slip of the pen?

**Comment by sjorge** [comment]
If it is intended, a mention in the release notes would be nice.

So people who hit the same problem of SSH not working after upgrade know what to change.

**Comment by fichtner** [comment]
Alright, here is the rub-in:

* SSH access is now bound to the "wheel" group which is automatically added to "admins" group, which "root" is a member of. "root" is the only user that has a default shell, namely rc.initial which is the root console menu.
* SSH access can be set for an arbitrary group as well under System: Administration for non-members of "admins" group. However, in both cases only SCP works due to a request in the forum to be more proactive regarding yielding of shell access rights. If you want a user to gain real SSH access you need to change their shell from "nologin" to an installed shell in their respective settings.

That's it. It's a compound change from several requests: user-selectable shells, allowing bash and zsh and so on to persist, allowing SCP without a login shell.

**Comment by sjorge** [comment]
Just for clarification, I meant a mention in the release notes once released.

**Comment by fichtner** [comment]
Of course. Will be in both the release and migration notes for 18.7. I've put it in writing here so it can be reused / referenced already. Thanks for the reminder. It may indeed be useful for others.
