### ISSUE TITLE
problems while adding widget in core

### ISSUE THREAD

**Issue by teliz** [opnsense/core#2428]
Hello @fichtner 

How do I make my changes in the core be added to the packagesite and so when I try to update an old build it receives these updates?

I have now managed to make this work with pkg, I have updated it (1.10.3 to 1.10.5) but I am not able to make any changes in the core (add theme, add widget) reflect for old ones.
I think I may be forgetting to change version, but I did not understand how to do this.

Thanks :)

**Comment by fichtner** [comment]
Hi @teliz,

When you commit changes to your branches, the version number changes automatically for each commit using YOURVERSION_x where x is the number of commits. You can also add a new tag for a new version on the branch you are:

    # git tag -a MYNEWVERSION

But you needto make sure MYNEWVERSION is a version that pkg knows is newer than the old one, otherwise it will not update.


Cheers,
Franco

**Comment by teliz** [comment]
So I've seen `/usr/core/Scripts/version.sh` return `tag_commit` to **CORE_VERSION** in` /usr/core/Makefile`

But when generating the DVD, packages sets are generated with big names:
`base-6790a7db5e00012f5fd68bfe12d9510a9eaa50d0-amd64.txz
`
`kernel-6790a7db5e00012f5fd68bfe12d9510a9eaa50d0-amd64.txz
`
`packages-e4f347d96f477a8d1b3d3b668b45bf2b6db0546d-OpenSSL-amd64.tar
`

I think there's something wrong,
they should be something like this: `base-1.0-amd64.txz` because for `/usr/core` **my tag is 1.0**





> "But you needto make sure MYNEWVERSION is a version that pkg knows is newer than the old one, otherwise it will not update."

Is there a way to restart the version count? assuming I want to start from 1.0

**Comment by teliz** [comment]
Work fine !!!!!
Thanks @fichtner 
amazing 🤘
