### ISSUE TITLE
Authorization with login via LDAP is case-sensitive

### ISSUE THREAD

**Issue by vielhak** [opnsense/core#2436]
We use LDAP Auth with AD. Works perfectly except that the imported user names are case sensitive regarding the authorization (group membership). So I can login as torsten.vielhak (authenticated against LDAP) but than I get 
"No page assigned to this user! Click here to logout. "

If I use "Torsten.Vielhak" everything works as expected. I think the authentication via LDAP is not case-sensitive but the mapping to the group membership inside OPNsense is.

Keep up your great work! We love OPNsense!

**Comment by AdSchellevis** [comment]
a solution could be to optionally force case on importing users, our end is indeed case-sensitive

**Comment by fichtner** [comment]
@AdSchellevis close or add glue?

**Comment by AdSchellevis** [comment]
let's close it, it's not high enough on my todo list and this doesn't affect a lot of users.

**Comment by anilkapoorbind** [comment]
Hi,
I have a point to add, I am using LDAP (AD) Authentication Server for Logging-in PFsense.
I have two users in the Authentication Containers OU one is "kernel" and other is "abind".
I get to log-in with the kernel user, but not with abind user.
I guess this is because of the difference between distinguishedName "Anil Bind" and username "abind",
for the same user.
whereas, the kernel user has the same distinguishedName and username.
any suggestions.
Apologies if the explanation is not clear.

**Comment by Ekuran** [comment]
Hi,
I have the same problem but i dont understand how you resolve that, so someone can explaine me.
I apologies for my english!

**Comment by AdSchellevis** [comment]
option for case-insensitive matches has been in OPNsense since some time (21.1), see https://github.com/opnsense/core/issues/4451
