### ISSUE TITLE
Incorrect subnet in strongswan.conf

### ISSUE THREAD

**Issue by darinpp** [opnsense/core#2531]
It seems like OPNsense sets incorrectly the`subnet` in `strongswan.conf` to the value specified in VPN: IPsec: Mobile Clients : Virtual Address Pool. 
The correct value is the one set in VPN: IPsec: Tunnel Settings : Local Network for Phase 2. 
I checked pfSense and it seems to do the correct thing. In my case I have Phase 2 local network set to 0.0.0.0/0 and Virtual Address Pool set to 192.168.11.0/24. The bug prevents the MacOS VPN client from setting up correctly the default route in the routing table and as a result doesn't route any traffic via the VPN. 

Another issue with the MacOS VPN client is that value set for `leftauth` in `ipsec.conf` defaults to `eap-tls` which is not supported. There doesn't seem to be a way to change this from the UI. Can you add a way to set it up or perhaps make the default be `pubkey` (which is supported and is what pfSense does)?

**Comment by AdSchellevis** [comment]
@darinpp first part of your question should be fixed with https://github.com/opnsense/core/commit/5b9d4240c31db13562762702a57f838eeabdd651 install via:

```
opnsense-patch 5b9d424
```

For the left/right auth parameters, I need to know what you selected in pfSense and what the expected result is, `eap-tls` is only used when eap-tls is selected in authentication (https://github.com/opnsense/core/blob/master/src/etc/inc/plugins.inc.d/ipsec.inc#L1227-L1228)

![image](https://user-images.githubusercontent.com/9783985/42475411-d86851f8-83ca-11e8-9548-9314353e8960.png)

**Comment by darinpp** [comment]
Thanks for the first fix. 
Ah. I see. I assumed that the authentication method controls the `rightauth` only. It seems to set both. 
I'm using a certificate on the client for authentication. I have the Authentication method set to `EAP-TLS`.
I need to have `leftauth=pubkey` and `rightauth=eap-tls`. In case of `eap-mschapv2` for example the `leftauth` is set to `pubkey` so I the MacOS client works fine when using password.

**Comment by AdSchellevis** [comment]
It looks like pfSense swaps behaviour when "mobile" is selected, but given all the possible schemes I don't expect this is to be the right fix for the issue.

https://github.com/pfsense/pfsense/blob/fc00cb2082a8ee4b5cb733d151c76c7368f01ede/src/etc/inc/vpn.inc#L1077-L1095

In our case this would lead to changing the eap-tls setting for all scenario's since eap-tls is only visible for mobile connections (if I'm reading their code correctly, same seems to be the case there).

We probably better add a scheme to supply this configuration, although I think we should eventually try to improve the selection options to better describe what their doing.

**Comment by AdSchellevis** [comment]
@darinpp ok, here you go https://github.com/opnsense/core/commit/82c869df89e60d031280c756568dac3b5c007dc1 can you test and confirm?

**Comment by darinpp** [comment]
I confirm that it works.

The naming however is a bit misleading. For the rest of the schemes you use `rsa` to indicate use of `pubkey`. Also the `leftauth` is the authentication method used by the firewall (vs `rightauth` being the authentication method used by the client). Given that I'm doing the configuration at the firewall, I would expect the name to be `RSA(local) + EAP_TLS(remote)`

I'm also very much in favor in separating the `leftauth` and `rightauth` into a distinct drop boxes so the users can choose any combination and perhaps also refer to the excellent documentation that `stringswan` has. For these settings they have for example:
```
left|rightauth = <auth method>

Authentication method to use locally (left) or require from the remote (right) side. 
Acceptable values are pubkey for public key encryption (RSA/ECDSA), 
psk for pre-shared key authentication, 
eap to [require the] use of the Extensible Authentication Protocol, 
and xauth for IKEv1 eXtended Authentication.
```
and then it goes to give even more details.

Thanks also for the quick reaction fixing these. It is a dream come true to have actively maintained, real open source firewall.

**Comment by AdSchellevis** [comment]
@darinpp thanks for your feedback, I'll change the caption to `RSA(local) + EAP_TLS(remote)` like suggested.

Eventually we might still end-up splitting the left/right auth, but that will need a larger overhaul, preferably refactoring the code to our mvc framework.

I'll close the issue with the commit to rename the option.
