### ISSUE TITLE
Enhance schedule

### ISSUE THREAD

**Issue by kagou** [opnsense/core#2533]
The scheduleis far too simple. It can only be done on specific days. I want to be able to create rules like: "every weekend", or "every day of the week", or "every second Tuesday of the month".

**Comment by markusd112** [comment]
Yes, I support this feature request. The schedule options are very poor in the moment. I have tried to set some schedules for our children's firewall rules to block the computer access in the night, but I "capitulate" because of the very basic GUI settings in the schedule menu. 

It should be possible to enter repeating events, like every day, every day of week, etc. as you know from every calendar program GUI. As well as setting single or multiple weekdays. It should be possible to manually enter the date, because the current GUI element for selecting dates cannot really handle selecting several weeks or monthes: you have to manually select each day. In the moment the GUI (date entering control) doesn't work with a tablet: you aren't able to select the days when using a tablet / smartphone.

**Comment by fichtner** [comment]
A schedule rework will have to be carried by the community. The current implementation works ok and replacing it takes a lot of effort that is better spent elsewhere. Thank you for your understanding.

**Comment by warnerbryce** [comment]
@kagou It is possible now to schedules for Every Mondays, etc... 
You have to click on the name of the days in the schedules calendar, it will select all the days of the specific month, but when you appli it will say Mon - Fri for exemple if you selected all the days of a working week.

![schedules](https://user-images.githubusercontent.com/11445205/58164690-97750000-7c86-11e9-8021-68f80fadfa79.PNG)


This issue could be closed.

**Comment by AdSchellevis** [comment]
timeout
