### ISSUE TITLE
IPv6 DUID-EN and others

### ISSUE THREAD

**Issue by marjohn56** [opnsense/core#2573]
Reading a reddit conversation it appears IPv6 DUID-EN is needed. I'll take a look and get this done. I also want to add a function to quickly clear the existing DUID and force a new one.

**Comment by cminnoy** [comment]
Hi, for my internet provided I also need to provide a DUID to get DHCPV6 to work with a fixed IP.
This used to work in a previous version of opnsense, but since a recent upgrade doesn't anymore.

What's strange is that the DUID accepted by opnsense always needs to have two more bytes (0e:00) before the rest of the identifier. The internet provider doesn't accept the first two bytes.
Always wondered why the difference?

That said, it used to work in a previous release, but in OPNsense 18.1.13_1-amd64 doesn't work anymore for me.

**Comment by marjohn56** [comment]
Nothing was changed in 18.13 in the duid area. Set the dhcp6c debug flag and then look at the dhcp6c log entries. Post them here and I'll try and see what's wrong. The first two bytes are for use by dhcp6c itself only.

**Comment by fichtner** [comment]
This has been merged into master.
