### ISSUE TITLE
OpenVPN Connection Status - Unable to Contact Daemon

### ISSUE THREAD

**Issue by pricklydevil** [opnsense/core#2610]
Posted this on the forum but no acknowledgement [..](https://forum.opnsense.org/index.php?topic=9328.0) hopefully here will help

I've got several OVPN connections established and working (confirmed by connections to WAN via 4G and from LAN); however, the dashboard and menu option (VPN > OpenVPN > Connection Status) are all giving "Unable to contact daemon Service not running?" even though they're definitely working.

Reboots are not solving the issue, nor killing the processes.

I've attached logs from the OVPN service as well as graphical evidence.

PS AUX output
`root@router:~ # ps aux | grep openvpn
root    23048   0.0  0.1 1085760  6728  -  Ss   Thu13       0:02.57 /usr/local/sbin/openvpn --config /var/e
root    24452   0.0  0.1 1085760  6924  -  Ss   Thu13       2:31.13 /usr/local/sbin/openvpn --config /var/e
root    30568   0.0  0.1 1085760  6888  -  Ss   Thu13       2:30.40 /usr/local/sbin/openvpn --config /var/e
root    32392   0.0  0.1 1085760  6920  -  Ss   Thu13       2:56.28 /usr/local/sbin/openvpn --config /var/e
root    86435   0.0  0.0 1080528  2840  0  S+   18:50       0:00.00 grep openvpn
`

![connectionstatus](https://user-images.githubusercontent.com/13431730/43735404-6d6ffbc8-99b2-11e8-8e84-4c2f3317fa29.png)
![dashboard](https://user-images.githubusercontent.com/13431730/43735406-6d8d9674-99b2-11e8-9841-ef2edb0f3386.png)
[openvpn.log](https://github.com/opnsense/core/files/2263723/openvpn.log)

**Comment by csriebel08** [comment]
This is a problem for me as well only the openvpn client drops the tunnel and is not working at all.  If I start the service through the gui then it will start and establish a connection but then the daemon stops and the tunnel goes down.  If you can help me out I can provide logs.

**Comment by csriebel08** [comment]
@fichtner I wish my situation was like this but my WAN port and connection is fine.  This for me started a while ago in version 17 however I didn't think it was a big deal as I could start the service and my VPN client would stay running and the tunnel would stay up.  However after moving to 18.7 the current version I have found this behavior as described with the OP with the exception that as far as I can tell my vpn is not working (that is why I offered to gather logs to help but I don't where to start that would help out).  This behavior is to the point that my VPN client will not stay running at all and in the GUI I get what is described above.  I would note that my VPN Server has no issues and is working fine.  I also would mention that the only other behavior that I noticed with this is that the NTP service seems to shut down when starting the VPN client service.  So this is what happens:
1. Start the firewall everything comes up fine except for the OpenVPNclient service is stopped and the client instance statistics shows: "Uncalbe to contract daemon Service not running?" and the interface for this shows down. 
2. Start the OpenVPNClient service, this starts and does bring up the tunnel, interface ect. but when this happens the NTP service goes offline.
3. Start the NTP service and the OpenVPNClient service stops
4. NTP service remains running

I looked at #1931 and the OP in this talks about his WAN not being stable and that might be the reason for the issues, in my case this is not an issue.  The only thing that I found in that post is that visualstation mentions his NTP service however I don't know if it is similar to my situation as he posted one time then was dismissed because he did not align with the OP in behavior.

**Comment by pricklydevil** [comment]
I'd like to say my WAN is unstable, but it's not. Solid uptime with no maintenance work being carried out (confirmed by the ISP and confirmed that the cable modem has been solid for the past 20 days straight). Rules out [#1931](https://github.com/opnsense/core/issues/1931).

The dashboard is attempting to locate PIDs that are not valid, therefore throwing the error of unable to connect to daemon

**Comment by csriebel08** [comment]
I had to revert to version 17.7.5, I continuously was having my vpn client  shut down and could not keep it up.  I also had a problem where it would not let me add any hosts to my aliases or add new aliases for that matter.

**Comment by fichtner** [comment]
All past, present and future disappointment aside... the code tries to call stream_socket_client() on the unix socket that is supposed to be created by OpenVPN, but is refused by the file system. let's see what the actual error is with 0a8794f:

    # opnsense-patch 0a8794f

Please send a screenshot of the status page with the additional error reporting in place.

**Comment by fichtner** [comment]
I found this note, maybe it is relevant:

"You need to bind each OpenVPN client to enable its management daemon: use 'Local port' setting in the OpenVPN client screen"

**Comment by pricklydevil** [comment]
Updated screenshot after apply  patching 0a8794f

![ovpn_status](https://user-images.githubusercontent.com/13431730/43917163-66800c7a-9c07-11e8-8d59-9355b1b1b94f.png)
![dashboard](https://user-images.githubusercontent.com/13431730/43917165-669ad924-9c07-11e8-8f35-25ff6723f8b8.png)

I've also attempted to set the local port using 0, rather than blank, for a random port. Still the same error. I've also set a local port in the high 20000's, away from any other port that is currently open, same result.

**Comment by fichtner** [comment]
Ok, let's see if the socket is there or not...

    # ls -lah /var/etc/openvpn/*.sock

What kind of clients are these? tun/tap, p2p?

**Comment by pricklydevil** [comment]
Recreated all of these today, still exactly the same error on the dashboard and connection status

**Comment by fichtner** [comment]
@pricklydevil "connection refused" seems to point to two possibilities: either OpenVPN is refusing to accept a management connection which would show in the OpenVPN. Or it fails to reclaim the socket and this should also be in the log. To rule out the latter let's remove the socket before starting OpenVPN:

    # opnsense-patch 2916d62

**Comment by pricklydevil** [comment]
@fichtner Okay so patch applied, cleared VPN log, took down one of the VPN connections and brought it back online.

Dashboard still shows Connection Refused (61), with the logs showing below

> Aug 13 19:28:01 | openvpn[29779]: UDPv4 link remote: [AF_INET]31.3.153.248:12200
-- | --
Aug 13 19:28:01 | openvpn[29779]: UDPv4 link local (bound): [AF_INET]86.26.10.182:0
Aug 13 19:28:01 | openvpn[29779]: Socket Buffers: R=[42080->42080] S=[57344->57344]
Aug 13 19:28:01 | openvpn[29779]: TCP/UDP: Preserving recently used remote address: [AF_INET]31.3.153.248:12200
Aug 13 19:28:01 | openvpn[29779]: Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Aug 13 19:28:01 | openvpn[29779]: Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Aug 13 19:28:01 | openvpn[29779]: NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Aug 13 19:28:01 | openvpn[29779]: MANAGEMENT: unix domain socket listening on /var/etc/openvpn/client5.sock
Aug 13 19:28:01 | openvpn[29326]: library versions: LibreSSL 2.6.5, LZO 2.10
Aug 13 19:28:01 | openvpn[29326]: OpenVPN 2.4.6 amd64-portbld-freebsd11.1 [SSL (OpenSSL)] [LZO] [LZ4] [MH/RECVDA] [AEAD] built on Jul 28 2018
Aug 13 19:28:01 | openvpn[29326]: WARNING: file '/var/etc/openvpn/client5.up' is group or others accessible
Aug 13 19:27:54 | openvpn[18898]: SIGTERM[hard,] received, process exiting
Aug 13 19:27:54 | openvpn[18898]: event_wait : Interrupted system call (code=4)

**Comment by fichtner** [comment]
@pricklydevil not sure either, but happy this helped. what I saw was that normally OpenVPN removes the sockets on its own. It could have been related to a power failure leaving damaged socket files on the disk? I'll push that cleanup to 18.7.2 since we don't know more and it certainly doesn't cause any side effects. If you want you are satisfied please close the ticket. :)

**Comment by pricklydevil** [comment]
Definitely happy 👍 No power failures as I know of as everything is attached to a UPS but it's still definitely possible.

Thanks for all your help @fichtner I really do appreciate it
