### ISSUE TITLE
HSTS always on 

### ISSUE THREAD

**Issue by bobafrinet** [opnsense/core#2657]
It looks like unticking the "Enable HTTP Strict Transport Security" on the preferences does not work as expected. Browser always enforced the HSTS even after cache has been cleared. 

Version: 18.7.1
Browser: Firefox 61.0.1 (Mac)

**Comment by AdSchellevis** [comment]
@bobafrinet easy to check, if the following results in an empty result, it's not enabled:
`
grep 'Strict-Transport-Security' /var/etc/lighty-webConfigurator.conf
`

**Comment by fichtner** [comment]
One of the reasons for HSTS off by default is that once enabled your browser may keep enforcing it. That’s especially bad when you turn it off and can’t access the page anymore because of the HSTS violation. That could be the case here.

**Comment by sjorge** [comment]
A small note on that, I ran into this in the past while testing some tls stuff... Short from dropping my entire firefox profile I could not get firefox to not try and honer the previously present HGST setting.

That was in the 40 range of firefox release though, I think that behavior might be intended on the browser part.

**Comment by cu** [comment]
This is expected browser behavior. The whole point of HSTS is that once the flag is seen by a browser, the browser refuses to communicate with a host in any manner except HTTPS with a valid certificate from that point on until the HSTS policy expires. https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security

I don't see it as an opnsense issue since as @fichtner pointed out, HSTS is off by default.

opnsense _could_ issue a warning upon checking the box that unless HTTPS and a good certificate are configured correctly, one might lose access to the web UI. It could also offer to set a very low HSTS max-age (on the order of 15) for testing and a longer one (say, a year) for "production".

**Comment by fichtner** [comment]
I would like to take our chances with this. Very low max-age that doesn't annoy tentative administrators is practically no HSTS at all, which is already the default. ;)
