### ISSUE TITLE
Web UI does not use selected Let's Encrypts certificate 

### ISSUE THREAD

**Issue by MaartenJB** [opnsense/core#2666]
I've generated a Let's Encrypt certificate with the plugin, status of the certificate is "Ok". I can select this certificate "System: Settings: Administration", but the WebUI does not use this certificate.

Versions OPNsense 18.7.1_3-amd64
FreeBSD 11.1-RELEASE-p12
OpenSSL 1.0.2o 27 Mar 2018 
CPU Type AMD GX-415GA SOC with Radeon(tm) HD Graphics (4 cores) 
Plugin: os-acme-client 1.17 (Let's Encrypt client)

**Comment by AdSchellevis** [comment]
what certificate does it use according to your browser? and what does the settings page point to?

**Comment by MaartenJB** [comment]
Browser a certificate verified by: CN=Fake LE Intermediate X1

Settings page SSL Certificate: Let's Encrypt Certificate

**Comment by AdSchellevis** [comment]
@MaartenJB maybe a problem with Let's encrypt, doesn't look like something for core. maybe @fraenki has an idea.

**Comment by fraenki** [comment]
> but the WebUI does not use this certificate

@MaartenJB Why do you think that the WebUI does not use the Let's Encrypt certificate? You stated that browser shows a certificate that was issued by "Fake LE Intermediate X1", so you're clearly using a Let's Encrypt certificate already.

I guess your browser still shows a security warning regarding the SSL certificate and that _may_ be the reason for your question. That security error is shown because you're using the Let's Encrypt **Staging** servers. These are for testing and evalutation purposes only, they cannot issue a valid certificate.

You may want to change to the **Production** Let's Encrypt servers:
`Services -> Let's Encrypt -> Settings ->  Let's Encrypt Environment`
Note that you need to forcefully reissue the certificate to get a valid certificate. Make sure to refresh the WebUI certificate afterwards in `System: Settings: Administration` by clicking the `Save` button.

**Comment by MaartenJB** [comment]
Hi Fraenki,

You are right thanks! I had to delete the staging test certificate and generate a new one. Switching to production and force a renew did not work. 
When you delete a Let's encrypt certificate you must delete it from the opnsense thrust certificates manually, maybe this is a designed this way intentionally.

**Comment by fraenki** [comment]
>  When you delete a Let's encrypt certificate you must delete it from the opnsense thrust certificates manually, maybe this is a designed this way intentionally.

Yes, it's by design. You may think of it as a safety net.

@AdSchellevis, this issue can be closed. :)

**Comment by AdSchellevis** [comment]
@fraenki thank you for helping out!
