### ISSUE TITLE
Suggestion on pfsense old config import process in opnsense

### ISSUE THREAD

**Issue by miksib** [opnsense/core#2673]
Hi,
First of all compliment to the opnsense team for the great job done and I hope to write this post in the appropriate section.

According to Franco's answer in [Importing an exported pfsense configuration xml breaks the web-ui.](https://github.com/opnsense/core/issues/2374)) the system section is not anymore compatible between pfsense and opnsense.
Can you suggest me the correct way to try to import old pfsense configs?

a) I have to make a basic configuration of opnsense (to have the system section correctly filled) and then in the config.xml, I've to paste/merge the single sections taken from the original pfsense?
or

b) after the initial opnsense config I've to import only the single original sections stripping away all unneeded in the pfsense bck files?

I've several installations of pfsense so I'm trying to understand the overall effort and how much time could the migration take me...

Most of my original config to migrate are in pfsense version 15.8 according to the info in link [Versions of pfSense and FreeBSD.](https://www.netgate.com/docs/pfsense/releases/versions-of-pfsense-and-freebsd.html#versions-of-pfsense-and-freebsd),is there around a similar reference for opnsense ?
thank you.

**Comment by AdSchellevis** [comment]
I think you best try our forum (https://forum.opnsense.org/), there are area's you can just copy, but certainly not all. We don't offer free support on migrations ourselves.

**Comment by miksib** [comment]
thank you very much for your kind reply and your time. I'll follow your suggestion. have a nice day.
M

**Comment by fichtner** [comment]
Basically the system section is incompatible in both directions because our password hash is written in an older format as we try to skip migrations of the config format. And there was an issue with our theme setting in pfsense where the pfsense code would take the theme for granted and not render the gui anymore because there is no “opnsense” theme obviously.

As for other sections that may still work 90% of the time minus additions that were made on both software after the 2015 fork point. Special care should be taken with the firewall section, others should be straight forward to import and tweak and use.

So, yes, partial section by section restore is a feasible way to migrate if you don’t want to do it from scratch. 😊
