### ISSUE TITLE
Outbound NAT rules disappear when switching to manual

### ISSUE THREAD

**Issue by Adamizme** [opnsense/core#2691]
When I switch from automatic to manual outbound NAT rules, all existing rules disappear.

In prior versions, the automatic rules would be converted to editable manual rules.

**Comment by fichtner** [comment]
I think this is from the forum? Assigned as promised.

**Comment by Adamizme** [comment]
That's correct. Thank you.

**Comment by fichtner** [comment]
@Adamizme Alright, I double-checked this and it is the intended behaviour:

Manually created rules are always retained. Automatic rules do not create manual rules to be consistent with hybrid mode behaviour as well--what is manual is manual and what is automatic is automatic.

The reason this worked previously in manual mode also caused a bug where automatic rules could be creating duplicated manual rules if you switched back and forth more than once so this was adjusted to avoid the side-effect.


Cheers,
Franco

**Comment by AdSchellevis** [comment]
@monreal we're not going to add a clone button to the automatic rules, sorry about that. A new empty rule is quite similar to what the clone would do, except selecting your source network and target address.  I do hoever think that we should also look at the target selection, since it does seem to suffer from a similar issue as the source/destination selections.
