### ISSUE TITLE
Verify disk space 

### ISSUE THREAD

**Issue by sachaz** [opnsense/core#2712]
This enhancement is coming from a recent issue:
a root filesystem was full, nothing on interface was telling me that. I changed my configuration, config.xml wasn't wrote correctly, then my firewall was unable to load the config file with a Fatal error: Uncaught OPNsense\Core\ConfigException: invalid config xml in /usr/local/opnsense/mvc/app/library/OPNsense/Core/Config.php:336

1st feature could be an alert when fs is full ?
2nd feature always check if there is enough disk space before writing ?

**Comment by AdSchellevis** [comment]
Monit (Services->Monit) can probably already do this for you.

**Comment by Franck78** [comment]
@AdSchellevis , monitor is good for establishing trends, base lines. 

I was working on dhcpv6 config of my box and some days after I noticed (dashboard)
disk usage 96% instead of the 20%

A gigantic dhpcv6_core file was sitting there, at /

So yes, something could be usefull to locate thoses kind of files (and erase them).

-gnome disk usage chart ?
-during boot erase /*_core ? 
-disable coredumps  ?

Thank you
Franck

**Comment by AdSchellevis** [comment]
Monit

**Comment by Franck78** [comment]
"System: Firmware: Reporter"

You could happily add the result of 

```
# find / -type f -size +10M
/boot/kernel.old/kernel
/boot/kernel/kernel
/usr/bin/lldb
/usr/bin/ld.lld
/usr/bin/c++
/usr/bin/cpp
/usr/bin/clang++
/usr/bin/clang-cpp
/usr/bin/clang
/usr/bin/cc
/usr/lib/libzpool.a
/usr/local/lib/libhs.a

```
because anything (except kernel) bigger than 10M byte is abnormal (including a compiler).
10M is arbitrary, the less, the better.

The system tends to dump gigantic corefile anywhere on the file system. 
(echo "" > /var/log/routing.log   you will get vlog.core in the httpd directory for example)

**Comment by fabianfrz** [comment]
all of those files are fine - lldb is a debugger, ld is probably some code used to run applications, then there will be a bunch of files which also belong llvm, which is the standard compiler for C/C++ on FreeBSD and the rest are static libraries. Many of the files are probably symbolic- or hard-linked. (clang++, clang-cpp and cpp, clang and cc)
