### ISSUE TITLE
NTP Service: Only listening on LAN, but answeres on WAN

### ISSUE THREAD

**Issue by woftor** [opnsense/core#2763]
**Behaviour observed:**
1. Enable NTP
Services - Network Time - General - Interfaces
Set To: LAN **only**

2. Make a NAT Port Forward rule from WAN to 127.0.0.1 on UDP 123

3. Check: https://servertest.online/ntp set to your WAN IP

Port is open AND gives a valid reply.

**Expected:**

If 1. is set to listen to LAN only, it shouldn't answer if probed from the WAN.

Or maybe I am missing something?

**Comment by fichtner** [comment]
This is difficult to answer and may be in the NTPd manual: if we bind to LAN, why is loopback answering?

The second part of that question is that as soon as you use NAT you are manipulating incoming interfaces so assuming loopback is always listening in NTPd you're manipulating WAN to be Loopback due to NAT. With that, don't use NAT, just open a port to verify.

**Comment by woftor** [comment]
> This is difficult to answer and may be in the NTPd manual: if we bind to LAN, why is loopback answering?
> 
> The second part of that question is that as soon as you use NAT you are manipulating incoming interfaces so assuming loopback is always listening in NTPd you're manipulating WAN to be Loopback due to NAT. With that, don't use NAT, just open a port to verify.

That completely makes sense. I have tested it and this is how it works. Thanks.
