### ISSUE TITLE
unbound creates an AAAA record for the link-local address

### ISSUE THREAD

**Issue by cu** [opnsense/core#2805]
I'm running OPNSense 18.7.4 and have DHCPv4 and unbound enabled.

When doing a quad-A lookup against the router's hostname from another machine on the LAN network, it correctly returns the router's LAN IP, but also it returns the link-local IP, which I believe is incorrect:

```
# full hostname redacted
$ dig AAAA firewall.example.net +short
fe80::1:1
2601:410:0:4c37:20d:b9ff:fe4d:4fe4
```
I see the entries being set in `/var/unbound/host_entries.conf`:

```
local-data: "firewall.example.net AAAA fe80::1:1"
local-data: "firewall AAAA fe80::1:1"
```

I'm not an IPv6 expert but my understanding is that link-local addresses (fe80::/10) are effectively useless for anything except NDP and other lower-level stuff because the applications would need to properly handle a zone index and practically nothing except ping does.

So far I have not actually observed any problems arising from this so maybe the applications or libraries already know not to bother with a link local address by default.

**Comment by fichtner** [comment]
Hi @cu,

I think unchecking "DHCP IPv6 Link-local" does what you want, but looking at it the "DHCP" is misleading and was likely added incorrectly.

In general, link-local is actually used for routing, gateway access and DNS with Unbound being particularly clever about link-local because binding supports scopes so unbound can listen on fe80::1:1%em0 correctly unlike e.g. SSH we discussed earlier. That being said, the code for this is still in the development version and the behaviour of SSH in 18.7.4 is what Unbound will do eventually in 19.1, but that has no bad impact in deployments.

If the option does work I'll change the label accordingly.


Thanks,
Franco

**Comment by cu** [comment]
Ah yes, bitten by another configuration option I didn't bother to go looking for. :P Unchecking the "DHCP IPv6 Link Local" setting does remove that AAAA record. Although I'm not totally clear on how an AAAA record with a link-local address is useful, that's something I'll put on my todo list soon.

Feel free to close this bug if you want and thanks for taking the time to respond.

**Comment by fichtner** [comment]
Always happy to discuss! Removed the "DHCP" from the label, will land in 18.7.5. :)


Cheers,
Franco
