### ISSUE TITLE
2FA by SMS ?

### ISSUE THREAD

**Issue by opnsenseuser** [opnsense/core#2825]
What is possible in my work or on pretty much every bank page is missing for me in opnsense. 
2FA by SMS. 
of course, at least a usb tongle sim card or similar is necessary. but I still think it's a very clean and safe solution. 
have you ever considered such a feature? 

best regards, rene

**Comment by AdSchellevis** [comment]
Hi René,

Not really, since most people have smartphones or hardware tokens to their disposal, but if someone is interested in working on a clean implementation to send sms's for the second factor we would consider the patches.

Quite some services still use sms as a second factor, although from a security concern it's not the best option to use and has known security flaws. (a nice read about the subject https://www.theverge.com/2017/9/18/16328172/sms-two-factor-authentication-hack-password-bitcoin) 

It's better then nothing, but worse then the option already available.

Best regards,

Ad

**Comment by opnsenseuser** [comment]
@AdSchellevis 
thank you for the information. 

actually a shame for all banks and all companies that sell it then as safe. 

best regards rene

**Comment by opnsenseuser** [comment]
@AdSchellevis 

thank you for the information. actually a shame for all banks and all companies that sell it then as safe. best regards rene
