### ISSUE TITLE
Remove the unminified bootstrap-select.js

### ISSUE THREAD

**Issue by MichaelDeciso** [opnsense/core#2950]
It seems that we don't use `bootstrap-select.js` at all, only the minified `bootstrap-select.min.js`. Would it be an idea to just get rid of it?

**Comment by AdSchellevis** [comment]
I usually keep the un-minified code for the same version as well, so we always have a reference to the source we're using at that point and helps debugging issues (easy to switch to). 

In the past we had some minor changes to these files, since we try to avoid that now and the upstream is the same, we don't really need it, but it's practical for debugging purposes. I would suggest keeping those files in.

**Comment by MichaelDeciso** [comment]
Ah, ok.
