### ISSUE TITLE
Firewall - log files - overview -  "Log packets that are handled user rules" explicit in a graph?

### ISSUE THREAD

**Issue by opnsenseuser** [opnsense/core#2953]
I find the firewall log overview very interesting.
What I think is missing would be the possibility to show the rules that are explicitly set with "Log packets that are handled by this rule" in a graph. the graph should show values like "name of the rule and how often and when was this called and what interface and ip triggered the rule" etc. would this be possible and does that make sense?

regards
rené

**Comment by AdSchellevis** [comment]
Historical it probably won't make much sense, since the rule itself isn't associated with the log entry and therefor is often different after a firewall reload. In the livelog for the current records, that's not an issue, but looking back the uncertainty grows.

Personally I don't find the overview very useful as it's usually a very incomplete view of your network.

**Comment by opnsenseuser** [comment]
thank you for your opinion. it's just an idea, but maybe that will give us new ideas. 
best regards
Rene

**Comment by opnsenseuser** [comment]
should I close the issue?

**Comment by AdSchellevis** [comment]
I think it's better to close it indeed, maybe in time we have better ways to collect firewall logging including context, but for the moment I don't expect we can add a lot of value here.

**Comment by opnsenseuser** [comment]
Ok.
