### ISSUE TITLE
OpenVPN cosmetic cleanup

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#297]
http://imgur.com/N1mGH3Q

Text should be less verbose with a more verbose tooltip? Or perhaps some more padding between the checkbox and the text.

**Comment by sjorge** [comment]
Perhaps like on the IDS page with the little awesome orange ? icon

**Comment by AdSchellevis** [comment]
I've restructured the page completely to make the process-flow easier to understand and less prone to errors. While at it I've also added the help widgets like we use in our new UI. 
commit https://github.com/opnsense/core/commit/b5fc573016bc8a817bd3de8e7dc233472cd22378 contains the last bits and pieces. 

Do you have time to test?

**Comment by sjorge** [comment]
I finally got around to upgrading to opnsense-devel, change looks good!
Should I create a 2nd issue to also have the text displayed in a tooltip on hover? (this would mostly be for desktop/laptop users, it will prevent the interface from shifting but is obviously useless on touch devices)

**Comment by sjorge** [comment]
Looks like setting the ```title``` attribute on the link is sufficient!
http://i.imgur.com/kRyAZpT.png

**Comment by AdSchellevis** [comment]
Thanks, I'm going to close this issue then.
Copying the same help content into the title attribute is not something we do want to implement, because some of the help messages contain more (html) info and that would break the look and feel across the whole system. Removing the hover messages was done on purpose.
Sorry about that.
