### ISSUE TITLE
Auto-complete of aliases no more working after update to 18.7.9

### ISSUE THREAD

**Issue by myksto71** [opnsense/core#3065]
After a update the last few weeks we see that autocomplete of aliases are no more working.
I noticed that a similar issue was opened more than 2 years ago: https://github.com/opnsense/core/issues/372

What we have:
- alias foo
-- type hosts
-- content 1.2.3.4

Now we add a new alias:
- alias bar
-- type hosts
-- content: start typing foo, but no autocomplete happens (uppercase and lowercase).

Best Regards,
Michele.

**Comment by myksto71** [comment]
Thank you very much for your quick reply.
I really hope you can bring that function back and hope you will do it soon! ;)

Thanks you again and best regards.

Michele.

**Comment by AdSchellevis** [comment]
This https://github.com/opnsense/core/commit/ab4e900a5288a357879c4217cd2846d35d5c330c should fix the issue, although there is still a minor glitch in validation (ideally it shouldn't be possible to mix port and other types, but since it won't render defective configs I think it's good enough for now).

**Comment by AdSchellevis** [comment]
Hi Michele,

Thanks for confirming.
We'll try to add the patch to the next release, since the impact should be quite low.
Otherwise you should indeed patch again after upgrade, which you can easily do with our `opnsense-patch` utility.

Best regards,

Ad

**Comment by fichtner** [comment]
Will be in 18.7.10.
