### ISSUE TITLE
[Feature Request] Ability to turn off logging for 'default deny rule' WAN

### ISSUE THREAD

**Issue by lhorace** [opnsense/core#3075]
See forum post for additional context https://forum.opnsense.org/index.php?topic=10801.0

**Comment by fichtner** [comment]
Forgive me for misunderstanding... but you can disable default deny logging under System: Settings: Logging. Since it is not an interface-specific rule by design it cannot be changed to exclude interfaces from logging.

You can, however, simply add your own default deny on WAN without logging enabled and that should be it?!

**Comment by lhorace** [comment]
Understood, it's by design.

I've updated downstream post here https://forum.opnsense.org/index.php?topic=10801.msg49305#msg49305.
