### ISSUE TITLE
IPv6, dynamic prefixes and services not working properly

### ISSUE THREAD

**Issue by ihatemicrosoft-was-already-taken** [opnsense/core#3099]
I have a setup where I get a /56 and delegate the /64 prefixes on my LAN interfaces via "track interface". My provider changes both IPv4 and IPv6 prefix every 24h on a forced disconnect. Delegation of IPv6 prefixes to the LAN interfaces works well.

_However_, services listening on LAN IPv6 interfaces won't work after a prefix change unless reloaded/restarted (e.g. `ntpd`, `dnsmasq`). I have set up `dnsmasq` to bind to `::`, but after a prefix change it will still only work properly after a restart. `ntpd` will bind to the IF IPv6 regardless of the configuration, so a restart is mandatory anyway.

To fix this issue, services should reload _after_ a prefix change on WAN _and_ propagation of the new /64 to the LAN interfaces to make sure the services are available to IPv6 clients on LAN interfaces.

**Comment by chaispaquichui** [comment]
I have the same problem with sshd. Each time I reboot opnsense, it takes a little time to get the prefix delegation from my ISP and sshd is not reconfigured to listen on the GUA when I finally get it. My current workaround is to manually reboot sshd after I get an ipv6 address.

**Comment by fichtner** [comment]
You should be able to reload SSH and web GUI on IP changes if you use strict binding to interfaces.

**Comment by chaispaquichui** [comment]
By "strict binding", you mean this 

![image](https://user-images.githubusercontent.com/38246962/51799545-66c61200-2222-11e9-9d13-91bb37b9032c.png)

?

It's configured since the beginning :(

I rebooted opnsense just to be sure and this is my situation : 

My lan interface has an ipv6 address

em0_vlan10: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        ether 52:54:00:cd:65:ea
        inet 192.168.42.254 netmask 0xffffff00 broadcast 192.168.42.255
        inet6 2a02:a03f:44fb:7600:5054:ff:fecd:65ea prefixlen 64

but sshd don't listen on this ip

HostKey /conf/sshd/ssh_host_ed25519_key
ListenAddress 192.168.42.254
ListenAddress 127.0.0.1
ListenAddress ::1
root@OPNsense:~ #

If I reboot sshd from the gui, the ipv6 address is added to sshd

HostKey /conf/sshd/ssh_host_ed25519_key
ListenAddress 192.168.42.254
ListenAddress 2a02:a03f:4436:9400:5054:ff:fecd:65ea
ListenAddress 127.0.0.1
ListenAddress ::1
root@OPNsense:~ #

**Comment by chaispaquichui** [comment]
I just did another reboot and my WAN interface gets his IPv6 address almost instantaneously 

But it takes a very long time (1-2 minutes) before the GUA is configured on the LAN interface. I don't know if it's related

**Comment by fichtner** [comment]
It's your ISP's router advertisement being delivered in longer intervals I'd guess.

**Comment by chaispaquichui** [comment]
I don't think so since my wan interface gets its IPv6 very quickly.

Anyway, I've also the same problem as ihatemicrosoft-was-already-taken. When I get my new ipv6 prefix, the config files of unbound/sshd is not rewritten and they become unjoinable on ipv6. Dynamic prefix is such a PITA...

It should be easy to fix. We just need to restart sshd and unbound when we get a new prefix. I can try to submit a patch if you point me in the right direction :)

**Comment by fichtner** [comment]
Timeout.

**Comment by cpatulea** [comment]
Hitting this with a PPPoE WAN. sshd config still contains some stale list of IPv6 ListenAddress. Current 'ifconfig pppoe0' shows a new address which is missing in sshd_config.
