### ISSUE TITLE
Feature request: Alias Type - URL Table (Ports) 

### ISSUE THREAD

**Issue by TheSagest** [opnsense/core#3102]
I would like to see an Alias type URL Table (Ports), similar to the URL Table (IPs).

Use case.

Changing the port on clients Web app can easily done by changing the Ports file in the URL. Within the frequency time frame, ALL clients firewalls using this Alias URL (Ports) will be updated.

**Comment by mimugmail** [comment]
I'm also missing this one. Was planning some basic central rule management but without ports it doesn't work.

**Comment by fichtner** [comment]
This used to exist, but there was an implementational issue that eludes me. 015ae9f0587506

In general, there is no support for pf(4) table for ports. That seemed to be part of the issue...

Need to wait for @AdSchellevis to be back to fill in the details.

**Comment by fichtner** [comment]
related issue was https://github.com/opnsense/core/issues/2567

**Comment by AdSchellevis** [comment]
pf doesn’t support tables for ports, since we don’t want to clutter the firewall logic a lot, we dropped support for this. 

To be honest, with the api available you really don’t need some obscure fetch construction, for management purposes you can easily push ports and reconfigure. 
We shouldn’t try to bring this back, unless at some point in time pf supports tables for ports.

**Comment by TheSagest** [comment]
After reading through the BSD pd documentation i agree.
I will utilise the API.

Thanks forbyour time
The Sage !!

________________________________

**Comment by AdSchellevis** [comment]
seems safe to close then
