### ISSUE TITLE
Can't edit permissions / create new users

### ISSUE THREAD

**Issue by alexschomb** [opnsense/core#3132]
I just noticed that I can't perform **any** edit actions to users/groups of the local user database of OPNsense in ``18.7.10``. Every save action results in the following error message: ``You do not have the permission to perform this action.``

Is this a known issue? And how can I add such required permission / all permissions to an existing account? It doesn't even work for the ``root`` user. I strongly expect that this error was introduced with an update in the past as it happens for all users and we didn't edit the permissions at all.

**Comment by fichtner** [comment]
You have assigned the "System: Deny config write" privilege to the user which had to be enforced due to a CVE: https://github.com/opnsense/changelog/blob/61cbcc863ca66b978ed2c698d71f91a56b0c9e79/doc/18.7/18.7.7#L5-L11

If you have shell access you can fix this in multiple ways, e.g. editing /conf/config.xml and removing "<user-config-readonly/> from the privileges of the root user (or the group associated with said user).

**Comment by alexschomb** [comment]
Perfect. Thanks for the prompt and helpful reply. I fixed it by removing ``readonly`` permission from the system administrators group in ``/conf/config.xml``
