### ISSUE TITLE
ui: regression in single host or network subnet select (bootstrap select)

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#3148]
The subnet select will not give any options other than the default. See e.g. src/dst in firewall outbound NAT edit.

maybe due to https://github.com/opnsense/core/issues/2848

via: https://forum.opnsense.org/index.php?topic=11274.0

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/2af9202d64000f0c2dcc42b7f59fa481c438916b fixes the behaviour, the layout however is still flawed.

@MichaelDeciso since your commit broke this, would you be so kind to fix the layout issues in the legacy code (for example in firewall_nat_edit.php). 

In 18.7 this looks like this:
![image](https://user-images.githubusercontent.com/9783985/51637251-88da3e80-1f5b-11e9-9cee-a3432f43b9a7.png)


Now it looks like this:
![image](https://user-images.githubusercontent.com/9783985/51637268-968fc400-1f5b-11e9-9843-2c07df65bbdc.png)

It's likely a css issue in the supplied stylesheet https://github.com/opnsense/core/pull/2939

**Comment by MichaelDeciso** [comment]
I have checked the Bootstrap documentation and the selectpicker CSS, and the problem is that the `.input-group-btn` class is not set. This is compulsory according to the Bootstrap docs, and selectpicker specifically looks for it.

Will open a PR once I'm sure it works correctly and I haven't missed any other occurrences.

**Comment by MichaelDeciso** [comment]
https://github.com/opnsense/core/pull/3151

**Comment by AdSchellevis** [comment]
@MichaelDeciso ok, looks good, thanks!
