### ISSUE TITLE
interfaces: avoid long names with stacked _wlan, _vlan, _stf, ...

### ISSUE THREAD

**Issue by thomasjsn** [opnsense/core#3222]
I've tried to upgrade from 18.7.10, and to live-boot 19.1 and 19.1.1. When I do I loose all internet access; both IPv4 and 6 on all connected devices.

Using the ping diagnostics from OPNsense itself I can see that IPv4 connectivity works, but IPv6 fails. During boot the following message is listed twice "Configuring firewall...failed".

I get a few notifications regarding too long interface name;
![2019-02-11-221810_1428x208_scrot](https://user-images.githubusercontent.com/6061006/52594898-e66ff580-2e4c-11e9-8305-f7e1569af429.png)

Looking in the log I found this, it seems to indicate that the interface using VLAN for my WAN does not exist.
![2019-02-11-221957_1386x241_scrot](https://user-images.githubusercontent.com/6061006/52595306-ddcbef00-2e4d-11e9-91f3-576dcd99c9de.png)

I dont recognize the literal name `igb0_vlan102_stf`, but both the VLAN and interface does exist.
![2019-02-11-222114_1245x347_scrot](https://user-images.githubusercontent.com/6061006/52595349-fcca8100-2e4d-11e9-9bff-eb8e3eb5fd01.png)
![2019-02-11-222140_1328x461_scrot](https://user-images.githubusercontent.com/6061006/52595353-005e0800-2e4e-11e9-9cf8-df00c46bfd31.png)

Have some internal names changed from 18.7 to 19.1? It does look like the name of the interface is `igb0_vlan102`. Without the `_stf` suffix.
![2019-02-11-222344_784x647_scrot](https://user-images.githubusercontent.com/6061006/52595581-7f534080-2e4e-11e9-91fe-37e37d1ff99f.png)

What is happening? Any more information I can provide?

**Comment by AdSchellevis** [comment]
`_stf` suggests a `6rd` or `6to4` network, we changed something in the naming, to use the technical name instead of the logical one, which seems to be 1 character longer. 

I think you should be able to revert this change https://github.com/opnsense/core/commit/adf314a4ab172d69a76f8d9fd78ed3ad8c30c698, but we have to think of a better solution to prevent an overrun in this case.

**Comment by fichtner** [comment]
Commit might not be all of it, careful with the revert.

It’s a bit sad as this has been in testing for a very long time.

FWIW, the issue here is the excessive VLAN naming scheme, it would be better to change this, I think FreeBSD uses em0.123, but it may break a couple of “_vlan” Scans in the code.

What do you think?

**Comment by AdSchellevis** [comment]
@fichtner I'll take a look

**Comment by AdSchellevis** [comment]
Changing the vlan naming scheme is a bit too tricky in the short term, since these are stored and there's more logic tied to it (if we change it, already configured devices will still use the previous name).

Most of the times the length doesn't lead to issues, it's probably a better idea to fix the `_stf` part for now. 
How about if we suffix the stf interface with a capital `S`, which would create an interface like `igb0_vlan102S`.

It should be easy to test, low impact for as far as I can see.

**Comment by fichtner** [comment]
In this case let me rather add a compatibility layer with the old naming scheme?

**Comment by AdSchellevis** [comment]
and leave the `_stf`? we could do both, rename _stf now, keep the issue open for a larger overhaul.

**Comment by fichtner** [comment]
Hmm, I'm not sure diverting from _wlan _vlan _stf scheme is of any benefit if we have a "better" and also confirmed working versions which is the old one from pre-19.1. I agree with the larger cleanup.

We also need a 19.1.x target that reboots so that no intermittent upgrade issues exist so I'll do a clean revert into a working version. I just don't want to break things even if it looks easy.

**Comment by AdSchellevis** [comment]
I'll leave this up to you then, reverting back to the previous naming scheme is fine for the short term too.

**Comment by thomasjsn** [comment]
I do have 6rd set up on that interface, so that makes sense. I was also seeing IPv6 related error messages in the log.

@fichtner That does this mean for my set up? Is there anything I can do to get 19.1 working? Or do I have to wait for a fix?

**Comment by AdSchellevis** [comment]
@thomasjsn I'll prepare a temporary fix for you, @fichtner can look at the final solution later

**Comment by AdSchellevis** [comment]
here you are, should revert the behaviour back to 18.7 
```
 opnsense-patch 2eabec27
```

**Comment by thomasjsn** [comment]
@AdSchellevis Thanks, so; Install 19.1, upgrade to 19.1.1 and apply patch?

**Comment by AdSchellevis** [comment]
I expect you can apply on both versions, so if you need the connectivity, first patch 19.1, then upgrade and apply again.

**Comment by fichtner** [comment]
@AdSchellevis thank you, I'm going to add it to 19.1.2 as well.

@thomasjsn feedback about patch making things work again is appreciated so we can safely go ahead and fix the underlying issue(s) later.

**Comment by thomasjsn** [comment]
This is what I did:
* Booted of 19.1 USB stick into liveCD mode.
* Updated to 19.1.1.
* SSHed into OPNsense and ran the command `opnsense-patch 2eabec27`.
* Restarted service **pf** from dashboard, IPv4 connectivity came back on all network devices, still no IPv6.
* Went to Interfaces -> WAN, clicked "Save" and "Apply", IPv6 connectivity came back on all network devices.

I'd say it looks like the patch works :)

**Comment by AdSchellevis** [comment]
@thomasjsn thanks for confirming, I'll leave the rest up to @fichtner

**Comment by fichtner** [comment]
Already queued up for 19.1.2, thanks!

**Comment by fichtner** [comment]
Same as 
https://github.com/opnsense/core/issues/3120

**Comment by fichtner** [comment]
There is no point doing this other than causing breakage. Nothing bad happened in two years.
