### ISSUE TITLE
Using interface networks in alias editor

### ISSUE THREAD

**Issue by monreal** [opnsense/core#3239]
**Is your feature request related to a problem? Please describe.**
In IPv4 I can block connections from for example DMZ to all other "inside" networks by using an alias containing 127.0.0.0/8, 192.168.0.0/16 and 10.0.0.0/16. In IPv6 this won't work as all hosts have dynamic global IPs.

**Describe the solution you'd like**
It would be nice of the alias editor would allow to add the interface networks used in the firewall editor such as "LAN net". This way I could just build an alias containing all the networks I want to protect.

**Describe alternatives you've considered**
Right now I have to add multiple firewall rules to get what I want.

**Comment by AdSchellevis** [comment]
I'm not sure that's a good idea, given how it is implemented. People will expect the alias to follow the interface address instantly, but since the underlaying tables won't support such a feature there will always be a risk of lagging behind.

Our aliases uses pf tables, which are detached from the firewall rule configuration, which has the advantage of being more robust for alias configuration issues and synchronisation issues (firewall load never has to wait for the aliases to be populated).

E.g. this adds the current addresses of an interface, but after the fact, won't know that it did.
```
pfctl -t myalias -T add em0:network
```

For static assignments, it would already be quite easy to add the alias, there's no real gain of adding interfaces in that case.

I can think of an option how this might work (always generate alias tables for all interfaces in the filter and reserve those for alias usage), but given the effort needed to do this, I'm not to enthusiastic at the moment.

**Comment by AdSchellevis** [comment]
timeout (https://github.com/opnsense/core/blob/master/CONTRIBUTING.md)
