### ISSUE TITLE
No option to disable NTP server completely

### ISSUE THREAD

**Issue by doublej74** [opnsense/core#332]
Currently in the NTP server options page, opnsense listens by default on all interfaces to NTP requests (no interfaces selected in the list). When the user selects an interface only that interface will listen to requests.

So there is no option to completely disable the NTP server?

**Comment by fichtner** [comment]
Will make this happen for 16.1.1 or 16.1.2

**Comment by fichtner** [comment]
When all NTP servers are cleared, the service will automatically stop running. Enjoy!

**Comment by roblatour** [comment]
Of note, while this issue was closed the option is not yet in the GUI.  Currently, I found manually stopping the server seemed to work ok.

**Comment by fichtner** [comment]
Quoting for emphasis:

> When all NTP servers are cleared, the service will automatically stop running.

**Comment by roblatour** [comment]
yes, I know.  However, I don't want to clear the NTP Services just to temporarily stop the service, because when I want to start it up again I have to repopulate them.   

To keep consistent with other services, it would great to just have an enable / disable checkbox.

**Comment by roblatour** [comment]
OK - its not a big thing for me.

I was having some issues with a device that requests an NTP update, it was not getting the NTP time or data.  

As part of debugging that, I wanted to disable the Network Time Service to see if the device would still have a problem if it was  getting the NTP info without the use of that (OPNSENSE Network Time Service).  I read elsewhere that clearing the Network Pools on the OPNSense: Services: Network Time: General would disable the service - but I found that stopping it did the same.  

Just struck me odd as there was not enable/disable checkbox at the top of the General window as with other services.  If it is by design that is fine.

For additional context, here is some more info on what I was testing: https://forum.opnsense.org/index.php?topic=45198.0
