### ISSUE TITLE
Interfaces column alignment issue on Lobby:Dashboard

### ISSUE THREAD

**Issue by jonny3010** [opnsense/core#3329]
**Describe the bug**
When you have an Interface with a long name it breaks the name up and spreads it over multiple lines on the interfaces view in "Lobby: Dashboard". Even when you have lots of free space left on the row, which it could be using.

See photo: 
![image](https://user-images.githubusercontent.com/3495647/54429841-8acdac00-4719-11e9-8c2f-df0999c2c199.png)
https://i.imgur.com/uwYsoGY.png

**To Reproduce**
To reproduce, set your interface names long. 
Goto dashboard, and set columns to 3

OPNsense 19.1.4-amd64 (amd64, OpenSSL).  
Intel(R) Core(TM) i3-7100U CPU @ 2.40GHz (4 cores)
6 * Intel I211-AT

**Comment by fichtner** [comment]
After numerous back and forth over the last 4 years in this particular "design" area at least for me this concludes as "won't fix" due to CSS vs. dynamic data vs. static display complexity. Auto-resize may work, but line wrap doesn't work and text will overflow. Fixes welcome, but they will have to adhere to previous complexity requirements upon review. I don't want to necessarily go chasing tails with this again. For more see any of the following:

https://github.com/opnsense/core/issues/3126
https://github.com/opnsense/core/issues/2960
https://github.com/opnsense/core/issues/2745
https://github.com/opnsense/core/issues/1755
https://github.com/opnsense/core/issues/1003
https://github.com/opnsense/core/issues/554
https://github.com/opnsense/core/issues/311
