### ISSUE TITLE
IPFW: Add a hook to ipfw.rules to include conf folder for plugins

### ISSUE THREAD

**Issue by mimugmail** [opnsense/core#3344]
[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

**Is your feature request related to a problem? Please describe.**
Some people were asking for L2 FW rule support in the past. As only ipfw support mac addresses how about a L2-Filter plugin. Only Tier3 community support and in style like rule config for shaper. 

**Describe the solution you'd like**
To build this plugin, if accepted in general, I'd need an include hook in ipfw.rules and call reload api afterwards.

**Additional context**
There's no real need from my side, so when declined no worries, just thought some ppl might have a use case for it, e.g. TISAX or ISO27001 certifications gave a + when using MAC filter in addition.

**Comment by AdSchellevis** [comment]
I'm not 100% sure the L2 filters work with the hooks in place for dummynet, but it probably will.
There might be some use cases for L2 filtering (although often quite insecure), question is if ipfw is the most practical place to fix this.

I'm a bit concerned that in the end you might end up in building all filter features again for ipfw, but that doesn't necessarily mean we should allow hooks for our ipfw script.

Just thinking, what if we add an alias type for mac addresses and do the lookup from our new alias system? It might lag a bit more behind than L2 in ipfw (since kernel level), but would allow the use of all filter features (because in the end, all mac addresses are just plain arp+ndp lookups to normal addresses).
It will be different, but maybe good enough for the use cases you're trying to fix.

**Comment by mimugmail** [comment]
But wouldnt this confuse users when they can add Mac alias but cant use them in normal Firewall rules?

Tbh, I havent thought that much about at all, it was just a quick idea after some beers :)

**Comment by AdSchellevis** [comment]
:) I think it's easy to explain,  but it's probably better to define what the feature should do (it's scope) and decide which tool is best suitable next. agreed?

**Comment by mimugmail** [comment]
Agreed, my "problem" is that I can only offer what I'm capable to do ;) 

I'd keep the scope rather limited but make it plugable (which it should be already when API enabled).
block&accept for specific source and destination mac address should be enough.

**Comment by AdSchellevis** [comment]
That's no problem, I can help out in these matters.  I think we should think this through first, adding a plugin for a feature that would better fit in core might shoot us in the foot later.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository, 
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue, 
just let us know, so we can reopen the issue and assign an owner to it.
