### ISSUE TITLE
OpenVPN and IPSEC UI needs some more love (latest devel)

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#336]
![ipsec](http://i.imgur.com/fDrPdY7.png)

![openvpn](http://i.imgur.com/eTtDmvt.png)

**Comment by AdSchellevis** [comment]
(for reference) issue 1 is fixed in https://github.com/opnsense/core/commit/db5faebf0fbe43cd927c66a43f98f67557777312 I have to look the other later

**Comment by AdSchellevis** [comment]
Checked hardware crypto, on my side I do have another option available "bsd crypto" and the "No hardware ..." comes from the same unchanged function.
To check if the list displays the options correctly, you can run :
/usr/local/bin/openssl engine -t -c

On my end it shows:

(cryptodev) BSD cryptodev engine
 [RSA, DSA, DH, AES-128-CBC, AES-192-CBC, AES-256-CBC]
     [ available ]
(dynamic) Dynamic engine loading support
     [ unavailable ]

Note that the use of AESNI is handled by openssl and no crypto accelerator should be used to utilize it. 

Closing this one for now, because it doesn't seem to be related with the gui page.

**Comment by sjorge** [comment]
```
root@opnsense:~ # /usr/local/bin/openssl engine -t -c
root@opnsense:~ #
```

Nothing :/ Perhaps this option sould be disabled or hidden completely then instead of offering a blank dropdown?

**Comment by fichtner** [comment]
It should not add an empty option. The utility doesn't print a newline.
