### ISSUE TITLE
Feature request: PayPal Billing Solution in CaptivePortal

### ISSUE THREAD

**Issue by AndyX90** [opnsense/core#3393]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[+] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[+] I have searched the existing issues and I'm convinced that mine is new.

**Is your feature request related to a problem? Please describe.**
-

**Describe the solution you'd like**
I would like to ask for a PayPal billing solution on the portal-site.
So that you can enter a voucher on the portal-site or have the opportunity to buy one via PayPal.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by Ste84** [comment]
I agree with the request

**Comment by RomanJos** [comment]
Hi i did something similar with stripe and a raspberry running flask(python). you could do something like this easily with php by following a [tutorial on youtube](http://www.ilovephp.net/php/stripe-payment-gateway-integration-in-php-with-demo-examples/).
for exemple assuming you sell a voucher for $5, the user connect to your captive portal click on buy and he is redirected on the [checkout page](https://stripe.com/docs/checkout) of stripe [Be sure to add this to work with webview](https://stackoverflow.com/questions/34904149/using-stripe-mobile-checkout-in-a-webview-payments-in-kik) 
Now you can [charge his card](https://stripe.com/docs/charges) and give him his voucher.
and because its a captive portal you need to enter the checkout.stripe.com, api.stripe.com, js.stripe.com,
m.stripe.network and q.stripe.com ips in the bypass section of the captive portal and in the acl of squid (the proxy). to make the stripe ips static you can specify them in the override section of unbound or dnsmask :smiley: good luck lol

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository, 
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue, 
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by RomanJos** [comment]
Actually I made my own solution using Stripe and Flask on a VPS https://github.com/RomanJos/CaptivePortalStripe
