### ISSUE TITLE
Opnsense shouldn't recommend "all" for SSH server

### ISSUE THREAD

**Issue by sebastiannielsen** [opnsense/core#3435]
The administration settings page:
http://192.168.1.1/system_advanced_admin.php

says (recommended) to listen to "all" interfaces on SSH server.

Security wise, I see it as a insanely stupid idea to recommend running the SSH server (for a firewall) listening on public-facing interfaces, and I would instead suggest showing (not recommended) on all interfaces which do have a gateway, and (not recommended) for the "all" option.

(But don't in any way prevent the user from choosing it if they want, but it could be a good idea to atleast dissuade people from choosing public-facing interfaces to run the SSH server on)

Also I would suggest the default to be changed into LAN preselected, to even more encourage secure setups.

**Comment by fichtner** [comment]
The current way of doing it has been the default and only option for many many years. Users wanted strict binding and we gave it to them a few years ago under the condition that it can break itself and we cannot support all use cases.

The recommendation refers to the fact that you can lock yourself out if you choose to pick specific management interfaces. It can happen because strict interface binding requires reading IPs from the system and they can go out of sync.

As for the larger point what you describe also applies to the web GUI: in a default install you can only reach the services via WAN (if anti-lockout is on and there's only a WAN), from LAN (if it's there, protected by anti-lockout and the default access rule), or from OPT1 (if there is no LAN, protected by anti-lockout alone).

So whatever you have set up as interfaces, a way to access the web GUI / SSH at all is provided automatically to a a single trusted zone as much as you can infer trust from the user's intent without having him locked out by default and unable to administrate the newly set up system.

The only issue that you would consider security is the subsequent manipulation of firewall rules to allow SSH access from other interfaces -- either intentionally or unintentionally -- which is not a security issue but rather a misconfiguration.


Cheers,
Franco
