### ISSUE TITLE
openvpn: resync_if_needed and ".interface" file use

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#3449]
I don't think this is needed at all...

```
$ git grep "[^a-z_-]\.interface[^a-z_-]"
src/etc/inc/plugins.inc.d/openvpn.inc:    $fpath = "/var/etc/openvpn/{$mode_id}.interface";
src/etc/inc/plugins.inc.d/openvpn.inc:    @chmod("/var/etc/openvpn/{$mode_id}.interface", 0600);
src/etc/inc/plugins.inc.d/openvpn.inc:            $fpath = "/var/etc/openvpn/{$mode_id}.interface";
```

**Comment by fichtner** [comment]
@AdSchellevis it looks like openvpn_resync_if_needed() is another leftover from the gwgroup support. it actually tries to move to another interface, but that requires binding to WAN interfaces explicitly instead of just using "any". We could simply reload in these cases for the specific interface. What do you think?

**Comment by AdSchellevis** [comment]
@fichtner it kind of lives in the same area as the rest of this weirdness, `openvpn_resync_if_needed()`  should likely die with it indeed

**Comment by fichtner** [comment]
Having all the code removal ready it seems that there's real point in having rc.openvpn at all if we don't really do anything.

**Comment by AdSchellevis** [comment]
I'll have to double check if we're not overlooking something here.

**Comment by fichtner** [comment]
It's only caller is https://github.com/opnsense/core/blob/master/src/etc/rc.monitor#L40-L42 and you can see that dyndns and rfc2136 already lost support for it...

**Comment by AdSchellevis** [comment]
it feels like we miss some facility that restarts the client in these events, I'm not sure openvpn will recover for these automatically.

**Comment by fichtner** [comment]
How about a new rc.syshook.d/alarm facility to mimic carp and make it pluggable?

**Comment by AdSchellevis** [comment]
That sounds like a good idea, independently of the facility, we should check if we miss a caller somewhere now (which should then be added as a facility). 

Only question is what context we should send to the facility, the gateway alone might not be enough (or the right parameter) in this case.

**Comment by AdSchellevis** [comment]
@fichtner I've checked the openvpn code again for both carp and monitoring, I think we're almost there.

In `openvpn_restart()` I think we can safely ditch the "backup" check:

https://github.com/opnsense/core/blob/1bc478fbaa16239d31d484e0955ed5e761ce201a/src/etc/inc/plugins.inc.d/openvpn.inc#L987-L991

Since the vip can't communicate when its backup, it doesn't matter if its either running or not. The restart itself is necessary, openvpn would try to reconnect, but the time in between tries would normally grow when offline.

The behaviour itself should be backwards compatible for as far as I could find.

Then there's the `get_failover_interface()` and its usage, I've checked both dyndns and openvpn again.

In OpenVPN it looked like it was there, but a group didn't return an ipprotocol, which effectively disabled it.

https://github.com/opnsense/core/blob/08c5527824b936b69c0f46d59ce06cb7449b889a/src/www/vpn_openvpn_server.php#L773-L777

https://github.com/opnsense/core/blob/08c5527824b936b69c0f46d59ce06cb7449b889a/src/www/vpn_openvpn_client.php#L640-L644

For dyndns+rfc2136 we might consider reverting https://github.com/opnsense/plugins/commit/0454288b11fdee919546941ac3259d082b5d6782 and move the twisted logic inside both plugins. Both seem to be using the first active gateway interface they can find to determine which address to use, since we don't have a proper solution for it now, we probably better make sure our issue is isolated in the plugins. In the long run, I don't think we want to support both plugins.

what do you think?

**Comment by fichtner** [comment]
The openvpn_restart() CARP code is correct. We want the client to connect when it's not in backup mode. The logic is a little tricky, but it always stops on CARP events and starts if actually != BACKUP. In testing that seems to happen correctly so I am assuming that is the desired behaviour here.

I agree with the dyndns/rfc2136 plugin handling. Let's keep it the way it is and move the code out of core.

**Comment by fichtner** [comment]
I have to correct this a little: RFC 2136 does not support gateway groups so we ditch it there and move get_failover_interface to dyndns only.
