### ISSUE TITLE
WPAD doesn't work with CNAME record in unbound DNS

### ISSUE THREAD

**Issue by pksadiq** [opnsense/core#3457]
WPAD doesn't seem to work with CNAME record in unbound DNS. Based on the recommendation at https://serverfault.com/questions/54567 I replaced CNAME record with an A record and it seems to work fine.  May be it's better to set A record instead of CNAME by default.

OPNsense 19.1.6 (amd64, OpenSSL).

**Comment by fichtner** [comment]
@fabianfrz CNAME doesn't work well in Unbound so I'm not sure why we have WPAD setting them up?

**Comment by fabianfrz** [comment]
@fichtner because CNAME does not require me to check out which IP of OPNsense is open for the web interface.

* Why should unbound fail in deploying a CNAME record?
* Why should it not be working - this feature is unmodified quite old and from the forums a plenty of users seem to use this setup without problems (usually only problems with the web interface https redirect)
* CNAME **MUST** be supported: https://tools.ietf.org/html/draft-cooper-webi-wpad-00#section-5.4.3

**Comment by fichtner** [comment]
https://nlnetlabs.nl/pipermail/unbound-users/2015-March/009194.html
https://github.com/opnsense/core/issues/1614#issuecomment-419376740

**Comment by fabianfrz** [comment]
```
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 22804
;; flags: qr aa rd ra ; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0 
;; QUESTION SECTION:
;; wpad.hell.   IN      A

;; ANSWER SECTION:
wpad.test.      3600    IN      CNAME   opn.sense.

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 0 msec
;; SERVER: 127.0.0.1
;; WHEN: Fri May  3 19:53:47 2019
;; MSG SIZE  rcvd: 50
```
so unbound serves an empty 

converting to A/AAAA would mean, that we may get hundreds of entries as this means that the following code would have to be moved to the loop which runs over the interfaces:
```php
        $tmp_known_domains = array($domain);
        foreach ($config['dhcpd'] as $dhcp_interface) {
            if (isset($dhcp_interface['domain']) && !empty($dhcp_interface['domain']) && !in_array($dhcp_interface['domain'], $tmp_known_domains)) {
                $unbound_entries .= "local-data: \"wpad.{$dhcp_interface['domain']} IN CNAME {$system_host_fqdn}\"\n";
                $unbound_entries .= "local-data: '{$dhcp_interface['domain']} IN TXT \"service: wpad:{$webui_protocol}://{$system_host_fqdn}:{$webui_port}/wpad.dat\"'\n";
                $tmp_known_domains[] = $dhcp_interface['domain'];
            }
        }
        unset($tmp_known_domains); // remove temporary variable
```

so it means that we get

`count(interfaces) * count(configured DHCP domains)` entries. Only because an unknown SW cannot resolve DNS?

**Comment by fichtner** [comment]
I'm happy for a better fix ;)

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
