### ISSUE TITLE
generic link for Python 3

### ISSUE THREAD

**Issue by m-schaeffler** [opnsense/core#3461]
Is it possible to add a link named python3 which is pointing to the actual python interpreter linke this is done in Ubuntu:

```
ll /usr/bin/python3
lrwxrwxrwx 1 root root 9 Mär 26 11:25 /usr/bin/python3 -> python3.7
```

With this you do not need to reference the actual installed python version in python scripts.

**Comment by fichtner** [comment]
I'm not sure. The FreeBSD ports decision is to deliberately leave out conflicting symlinks to ensure packages can be installed in parallel. In theory we could provide one via core.git but implications are hard to assess. cc @AdSchellevis

**Comment by AdSchellevis** [comment]
as long as python 2 and 3 are cleanly separated (python vs python3), I don't mind, although its not very high on my priority list

**Comment by L1ghtn1ng** [comment]
@fichtner @AdSchellevis The other reason for this would allow you to use py3.7 instead of py3.6 for example as everything that is 3.6 compatable will work in 3.7. It also allows you to easly upgrade python versions and not worry about having to update scripts unless you are using things that get deprecated but I think you can see where I am going with this :)

**Comment by AdSchellevis** [comment]
We know how it works, while using 2.7 it wasn't very relevant (2.7 was the final 2.x version), python 3 is more likely to be upgraded in between indeed.
