### ISSUE TITLE
/usr/local/etc/suricata/opnsense.rules/ aren't loaded in the GUI rule explorer with the other /usr/local/etc/suricata/rules/

### ISSUE THREAD

**Issue by offsecn00b** [opnsense/core#3472]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[-] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[-] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
/usr/local/etc/suricata/opnsense.rules/ aren't loaded in the GUI rule explorer with the other /usr/local/etc/suricata/rules/ on the https://opnsense/ui/ids#rules page. The impact is you cannot tune these rules from the gui or view them at all. 

**To Reproduce**
1. Go to /usr/local/etc/suricata/opnsense.rules/ open an rule file of choice and pick a random rule sid
2. go back to  https://opnsense/ui/ids#rules and search for that rule sid (my example was sid 2210003 from /usr/local/etc/suricata/opnsense.rules/stream-events.rules) using the search bar. It isn't there. Alerts with that id will show up on the  https://opnsense/ui/ids#alerts page indicating they are loaded properly.

**Expected behavior**
All loaded rules should be searchable and listed on https://opnsense/ui/ids#rules 

**Screenshots**
N/A
**Relevant log files**
N/A

**Additional context**
This bug has been around since at least February 25

**Environment**

Versions | OPNsense 19.1.7-amd64FreeBSD 11.2-RELEASE-p9-HBSDOpenSSL 1.0.2r 26 Feb 2019
Updates | Click to check for updates.
CPU Type

**Comment by AdSchellevis** [comment]
looks like a missing cleanup, the example you mention is a rule in `stream-events.rules`, which likely isn't available in `/usr/local/etc/suricata/rules/` anymore (/usr/local/etc/suricata/rules/ is indexed).

We should remove extra files from `/usr/local/etc/suricata/opnsense.rules/` after installation to avoid confusion, since it will automatically overlay the files in `/usr/local/etc/suricata/rules/` anyway.


In this case stream-events.rules isn't used as well, since its not registered in `/usr/local/etc/suricata/installed_rules.yaml`

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/df4fe1c683cf1ba4a8be882ea9720597ae0f9bfb makes sure the staging directory is cleaned after install. If you install your custom rules in `/usr/local/etc/suricata/rules` you should be fine
