### ISSUE TITLE
Feature request: Auto import SSL-Certs

### ISSUE THREAD

**Issue by devNan0** [opnsense/core#3507]
**Is your feature request related to a problem? Please describe.**
I would like to push SSL Certs to OPNsense via ansible.

**Describe the solution you'd like**
A "drop-off" folder where i can drop my ssl certs with ansible. Ideally OPNsense would auto-import them and also reload the webui/webserver if needed.

**Describe alternatives you've considered**
I´ve tried to override the files with ansible and then reload the ui.
But on reload the config gets rebuild and the cert files newly written.
OPNsense stores the certs/ca in the config.xml file.
I see no "good" way to mange the config.xml with ansible.

**Comment by AdSchellevis** [comment]
You can use php and the standard config classes to create a script which does something like this, an example script which reads the certs (other way around) can be found here 

https://github.com/opnsense/core/blob/master/src/opnsense/scripts/OPNsense/CaptivePortal/generate_certs.php

An automatic import likely won't be included in our core product, since most of these use cases have other custom code installed on the same machine as well and the user interface won't use this functionality anywhere (which increases chances for future undetected issues).

**Comment by fichtner** [comment]
Closing as per https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
