### ISSUE TITLE
IPv4 addresse of new interface is added to the DNS A record of OPNsense FQDN

### ISSUE THREAD

**Issue by JasMan78** [opnsense/core#3526]
**Describe the bug**
When I create a new VLAN interface and select it in Unbound for listenig for DNS querys, the IPv4 address of the new interface is added to the DNS A record of the OPNsense FQDN.
Therefore the access to the OPNsense WebGUI over the FQDN timed out sometimes, because Unbound delivere the IP address of the new interface on which the WebGUI is not listening.

Already existing VLAN interfaces are not affected.

**To Reproduce**
1. Create a new VLAN interface
2. Select it in Unbound to listening for DNS querys
3. Do a nslookup for the FQDN of the OPNsense appliance

**Expected behavior**
The OPNsense FQDN should only point to one IP address. 

**Screenshots**
_NSLOOKUP for OPNsense FQDN_
````
C:\Users\xxx>nslookup jaswall.mgmt.home.arpa
Server:  JasWall.jasnet.home.arpa
Address:  10.0.10.1

Name:    jaswall.mgmt.home.arpa
Addresses:  10.0.20.1
          10.0.1.1
C:\Users\xxx>
````
10.0.1.1 (re1) is the correct address for my OPNsense.
10.0.20.1 (re1.20) is the new VLAN interface.

**Relevant log files**
Not sure which log files could help you.

**Additional context**
I had an similar issue with OpenVPN last year (see https://github.com/opnsense/core/issues/2828). Maybe this helps you.

**Environment**
OPNsense 19.1.9-amd64
Installed on self-configured hardware (Intel(R) Celeron(R) CPU J1900 @ 1.99GHz (4 cores))

**Comment by AdSchellevis** [comment]
Technically this is more a feature request than a bug, all interface addresses are recorded in the local dns, which is correct, but might not suite your use-case. A solution could be to provide the option to 
disable these automatic interface rules so you can add the one you need manually. 

Logically, it should need an option and an additional check around here https://github.com/opnsense/core/blob/31a81c51a6d76b44439acf4fdcb186075cab0e79/src/etc/inc/plugins.inc.d/unbound.inc#L527

**Comment by JasMan78** [comment]
That means I should use the IP address instead of the FQDN to access the WebGui? That's OK for me, but I'm interested if this is the recommend way.

Also why only new adapter register in DNS for the OPNsense FQDN? I've two other VLAN interfaces and one WAN interface which are not listed when I resolve the FQDN via nslookup.

Thank you for your support!

**Comment by AdSchellevis** [comment]
If I'm not mistaken, all non local (and non ovpn) interfaces are registered in /var/unbound/host_entries.conf. What I was suggesting is not switching to ip, but adding an option to stop automatic generation so you can add the entry you actually want to use (instead of registering all).

Thinking about this a bit more, you can also add another (static) host entry, which you then use to access the webgui. This would be the easiest option and doesn't require any changes to the system.

**Comment by JasMan78** [comment]
> Thinking about this a bit more, you can also add another (static) host entry, which you then use to access the webgui. This would be the easiest option and doesn't require any changes to the system.

Yep, that's a cool idea :)
But the option to choose which address will registered for the OPNsense FQDN would be also nice.

**Comment by AdSchellevis** [comment]
you should already be able add a manual entry (different hostname) in `Services -> Unbound DNS -> Overrides`

**Comment by vistalba** [comment]
I run to the same issue as well.

I hostname of opnsense is "fw1.internal.domain.com".
On management interface I activated snmp and added it to the monitoring server.
A few minutes later the devices was down and I realized that the problem is the same: `fw1.internal.domain.com` points to all interface ip's exept the WAN.

Problem is:
- I've created a override in unbound for `fw1.internal.domain.com` and there are still all IPs in DNS.
- I've also selected to only activate the "WebGUI" on management interface. So there should be no reason to add the other IPs to DNS I think.

Is there any workaround for this exept to use another DNS name for FW?

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
