### ISSUE TITLE
network assignment remembered by interface name, not by mac address

### ISSUE THREAD

**Issue by hboetes** [opnsense/core#3530]
From my opnsense 1.19.1 running on proxmox/kvm with about 8 vlan interfaces: I removed an obsolete interface, and then I discovered that the interface assignements were messed up, most likely because interface assignments are matched to interface names and not to the mac address.

So my suggestion is to use the mac addresses to assign network interfaces.

For anyone in the same situation, if the bug isn’t fixed, you have to fix the interfaces one by one and keep pressing save in between each step.

**Comment by hboetes** [comment]
@AdSchellevis I pressed the wrong button and then updated the description. Please relabel.

**Comment by AdSchellevis** [comment]
@hboetes we provide forms for feature requests (hence the incomplete tag). Hooking on mac addresses also has disadvantages, you can however prevent interfaces from being removed from the firewall itself (see lock on the interface) and reallocate manually. In BSD interfaces are usually created on bus order, which should prevent accidental shifting of interfaces.

**Comment by hboetes** [comment]
Hello Ad,
Thanks for your reply. What might be disadvantages of using mac addresses? How can I prevent interfaces being removed from the firewall if I removed obsolete interfaces in proxmox? Accidental shifting is not what happened here: I removed an obsolete interface and then all newer interfaces got relocated. I don’t see how your answer helps.
I hope you can come up with a more robust solution.

**Comment by AdSchellevis** [comment]
sorry, I'm not using proxmox myself. With physical interfaces and removing an interface in between, the order should stay the same which usually needs relocating the plugs for the interfaces (after the one removed).

When using physical order (which is how it works now), you can safely replace an adapter without issues. When relocating on mac address, the order might change (which for example happens a lot in linux) and renders the box unusable after service.

There likely is a logic order in which things have changed on your proxmox instance, which usually is easy to adept in maintenance plans. 

It would probably be possible to write a syshook script to rename all interface to match mac addresses on boot, which might solve your issue, but it's not very high on my priority list.

Robust it already is, just depending which area has primary focus (replacement v.s. virtual removal).

You could also consider using vlans instead of interfaces, which is virtually often easier to manage (and doesn't require reboots).

**Comment by hboetes** [comment]
> You could also consider using vlans instead of interfaces, which is virtually often easier to manage (and doesn’t require reboots).

That sounds like a solution indeed. Just forward a trunk to the VM.

**Comment by AdSchellevis** [comment]
ok, let's close the issue then.

**Comment by hboetes** [comment]
It's much easier than I thought. The untagged interface is a trunk already.
