### ISSUE TITLE
Check validity of interface selected with virtual ip.

### ISSUE THREAD

**Issue by hboetes** [opnsense/core#3549]
By a slip of the mouse I selected the wrong VLAN with a virtual IP, after which things go wrong in spectacular fashion with the routing table, and the cause of the problem was rather hard to find.
Wouldn’t it be nice if the interface checked if the selected IP was actually in the same range as the selected VLAN? Perhaps it’s even possible to propose the right VLAN based on the given IP?

Thanks for taking my request into consideration.

**Comment by AdSchellevis** [comment]
You mean the same network configured on one of the other interfaces or VIP's? we might add a check for that, although I'm a bit cautious here, since there are quite some scenario's which eventually turn out to be valid use-cases after all.

(once there was a validation to check if the vip's subnet matches the parent interface for carp, which isn't really needed for example and prevents certain scenario's from being implemented)

**Comment by fichtner** [comment]
I think quite some people use foreign networks on their WAN VIP (one private one while the normal one is public). This can be a requirement from the ISP so I don’t see a lot of potential for sane validation.

**Comment by mimugmail** [comment]
If your provider gives you a /30 for P2P you'd use some private IP ony the pyhsical IF and the official one in VIP.

**Comment by hboetes** [comment]
Thanks for the enlightening comments. In my case I accidentally put an external IP on an internal interface, that shouldn’t happen, should it? Perhaps a warning would suffice?

**Comment by AdSchellevis** [comment]
We can’t do that, external vs internal is not something you know for sure when looking at the interface (it’s network implementation, not firewall logic in this case)

**Comment by fichtner** [comment]
Closing as per https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
