### ISSUE TITLE
Captive Portal: performance issue with large number of users (>3000)

### ISSUE THREAD

**Issue by muratbalaban43** [opnsense/core#3559]
In trying to diagnose a performance issue today; we found out that the kernel taskq thread for an interface was hitting 100% cpu utilization, which in turn was causing packet losses. 

We found out that this was due to thousands of ipfw count rules. When we removed the count rules manually, cpu utilization dropped significantly. This deployment has roughly 3000 devices behind it. 

This deployment has Captive Portal enabled. 

It looks like kernel is running through a very long list of rules for every packet that it encounters and this is causing high cpu utilization. 

I'm happy to provide more help on the resolution. 

**Environment**
VMWARE Guest
OPNsense 19.1.1 (amd64, OpenSSL).
Intel® Xeon™ CPU X7550 @2.00GHz (64 cores)
Memory: 64GB
Network Intel® 82545EM

**Comment by AdSchellevis** [comment]
Hi Murat,

I've checked our options, but they seem to be limited here. 

Unfortunately ipfw doesn't support statistics on tables (as pf does), which made it necessary to create separate `count` rules to know the last accessed time (and used traffic).

I think there are three options to improve this situation, let me summarise them first:

1. Change `ipfw` to support table statistics, which is the approach pfSense seems to have chosen in the past (but none of the patches ever made it to FreeBSD).  Probably quite some work and then it needs to be accepted upstream.
2. Do accounting in `pf`, using a table there. This would unfortunately also require kernel changes, since FreeBSD's pf doesn't support the match keyword and would complicate the system a bit more (due to combining `pf` and `ipfw`).
3. Keep the existing rule parsing logic we have now, but use  `skipto tablearg` to jump into the correct section (split accounting rules). In theory this would reduce the amount of time needed to process the ruleset significantly, without the need for kernel changes. 
4. Optionally disable accounting, which would have the downside of having options that are hard to explain (disable accounting, would drop support for session timeouts for example)

I've created a preliminary change for option 3 (https://github.com/opnsense/core/commit/b54f3d2cc437efe4790c1587433dca985614e6ca), since our code has more changes for the upcoming python 3 requirement, I think the patch itself doesn't fit at 19.1.1, so you may need to pull the CP code from master (or switch to devel int the gui).

Could you test this patch on the same (or similar) setup and check if this is indeed faster? I only tested it in a small environment.

Best regards,

Ad

**Comment by muratbalaban43** [comment]
Ad,

Thanks for the detailed suggestions. We'll try option 3  in a few days. Will update on the progress.

**Comment by muratbalaban43** [comment]
Ad,

We applied the patch yesterday. It applies to 19.7/stable cleanly. 

System looks a lot better now.

IMHO, interface taskq thread cpu utilization is still high (around %80-85) for 155 Mbps, but the system is relieved for now. No packet losses. 

Monitoring the status. I'll update the thread in a few days.

**Comment by muratbalaban43** [comment]
An update to this issue:

More than a week in production, patch looks quite good. 

Deployment reached 800+ users at peak time.

**Comment by AdSchellevis** [comment]
ok, great, thanks for letting us know. I'll pull the patch into master for release in the 19.7.x branch

**Comment by AdSchellevis** [comment]
@muratbalaban43 can you test https://github.com/opnsense/core/commit/440f957e5ca525414f1d67553a4b6c6af0379d64 on 19.7.1 as well? I had to rebase to fit the changes in.

**Comment by muratbalaban43** [comment]
@AdSchellevis , sure thing.

**Comment by AdSchellevis** [comment]
@muratbalaban43 where you able to test https://github.com/opnsense/core/commit/440f957e5ca525414f1d67553a4b6c6af0379d64 ?

**Comment by muratbalaban43** [comment]
@AdSchellevis, not yet :( A lot on the table. Will try to do this week.

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/ffcd85f116efa
