### ISSUE TITLE
Unable to add IPv6 phase 2 on routed IPSec

### ISSUE THREAD

**Issue by nairial** [opnsense/core#3573]
on 19.7r1:

If I set up a route-based IPsec phase 2, and enter in IPv6 addresses in the tunnel network address boxes, I get the following error:

The following input errors were detected:

A valid local network IP address must be specified.
A valid remote network IP address must be specified.

**Comment by fichtner** [comment]
Try https://github.com/opnsense/core/commit/c3ccc63fd via

    # opnsense-patch c3ccc63fd

**Comment by nairial** [comment]
The patch does not solve the issue.

**Comment by AdSchellevis** [comment]
likely a typo in the address (not trimmed) or network provided instead of the expected address:

https://github.com/opnsense/core/blob/c3ccc63fd184168e22822fe49aabf7e7e8b40d1a/src/www/vpn_ipsec_phase2.php#L234-L235

https://github.com/opnsense/core/blob/c3ccc63fd184168e22822fe49aabf7e7e8b40d1a/src/www/vpn_ipsec_phase2.php#L264-L265

is_ipaddr() validates if the input is IPv4 or IPv6.

@nairial please note the incomplete tag on the issue, we offer templates for a very good reason....

**Comment by fichtner** [comment]
Not using a ticket template.
