### ISSUE TITLE
python3: remove subprocess.call in favour of subprocess.run

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#3574]
https://docs.python.org/3/library/subprocess.html#subprocess.run

**Comment by ErikJStaab** [comment]
Is this going to be merged in any time soon? I have been noticing with update_tables.py running every 1 minute it reads in all of the aliases and compares them which can take a while depending on how long your url tables/geo ip are. I am curious if this is faster will it make it a non issue? (Currently with 250k lines or of aliases so it takes about 50% of 1 core on my router for 5s every minute) It does seem to affect the threading somewhat since it is a good size load to be running off/on every minute.

As an alternative I am wondering if there is a reason it needs to read/compare loaded pf tables against for the file tables url/urltable/geoip types every time the script runs? Have there been consistency issues in the past?

**Comment by fichtner** [comment]
Is this done or is there still work for plugins to do? :)

**Comment by AdSchellevis** [comment]
I think there's one left in configd and some in the plugins, the plugins should be easy to replace, configd I rather leave for now. Let me look at the plugins and close the issue when done.
