### ISSUE TITLE
SQUID 3 to SQUID 4 migration

### ISSUE THREAD

**Issue by AndyX90** [opnsense/core#3584]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
After updating from 19.1.10 to 19.7, the Squid service would not automatically start.
The Cache-Clear Button was not enough. 
I noticed the following in Access log:

FATAL: certgen -s /var/squid/ssl_crtd -M 8MB helpers are crashing too rapidly, need help!

After that i had to manually do "/usr/local/libexec/squid/security_file_certgen -c -s /var/squid/ssl_crtd -M 8MB".

> Initialization SSL db...
> Done

Now it works.
**To Reproduce**
1. Upgrade from 19.1.10 to 19.7 with enabled Webproxy
2. press the Clear-Cache Button on the Webproxy Support Tab
3. Notice that Squid will not run.

**Expected behavior**
After pressing the Clear-Cache Button on the Webproxy Page, it should initialize the db by itself and start properly.

**Environment**
OPNsense 19.7 (amd64, OpenSSL).
Intel® Xeon™ E3-1225V5 3.3Ghz Quad Core
Network Intel® I210-AT
(DEC-4630)

**Comment by AdSchellevis** [comment]
What happens if you remove  `/var/squid/ssl_crtd` now and restart? 
The odd thing is, when it's not there the usual startup should create it 

https://github.com/opnsense/core/blob/75444ea6e8a578d113bf57b9be1340a4ac4251cb/src/opnsense/scripts/proxy/setup.sh#L28-L36

Our reset just flushes all, and expects the setup to re-create it, which in some cases  doesn't seem to work.
https://github.com/opnsense/core/blob/cdaa275fff06d0e1a9a9eb48c8fc654e8e6ea56a/src/opnsense/service/conf/actions.d/actions_proxy.conf#L29-L39

If the original setup.sh has an issue in your setup, that might explain something, otherwise it seems very difficult to reproduce this consistently.

**Comment by AndyX90** [comment]
Okay,iIf I remove the Directory and restart Squid:

> Jul 18 13:34:53 | (squid-1): FATAL: Received Segment Violation...dying.
> Jul 18 13:34:53 | (squid-1): FATAL: The /usr/local/libexec/squid/security_file_certgen  -s /var/squid/ssl_crtd -M 8MB helpers are crashing too rapidly, need  help!

**Comment by AdSchellevis** [comment]
it looks like we missed a rename here https://github.com/opnsense/core/commit/981a718da087b37e4a505b0323967a24bc1d40bc

`ssl_crtd` vs `security_file_certgen`

**Comment by AndyX90** [comment]
It works, thanks!

**Comment by AdSchellevis** [comment]
@AndyX90 thanks for testing and letting us know!
