### ISSUE TITLE
Unbound: add custom include like with strongswan

### ISSUE THREAD

**Issue by mimugmail** [opnsense/core#3621]
**Is your feature request related to a problem? Please describe.**
Quite often people ask for DNSBL and there are many guides around solving this via include files in custom options.

**Describe the solution you'd like**
Maybe we could add a static include: `/var/unbound/etc/opnsense/*.conf`
This would allow custom plugins to hook into Unbound without touching the custom options and adding the possibility to remove this field in (far) future.

I'm not really sure if include of a whole directory is allowed, I'm more familiar with bind syntax, but if you agree to the idea I'm willing to contribute a plugin

**Comment by mimugmail** [comment]
I was able to load custom.conf via this in custom box:

`include: etc/*.conf`

So maybe we could place it at same location where custom options sits, directory is already there and should be usable.

**Comment by AdSchellevis** [comment]
@mimugmail I'll take a look

**Comment by AdSchellevis** [comment]
Since unbound is running from it's own jail, there needs to be some mechanism to make sure the expected files are really there.

We could create a template directory for Unbound in https://github.com/opnsense/core/tree/master/src/opnsense/service/templates/OPNsense, to generate the required files into `/var/unbound`.

Move `root.hints` over to a template, because it's an easy starting point.
https://github.com/opnsense/core/blob/1da07949b5eef74f0d4e0e71712ba552f452ac62/src/etc/inc/plugins.inc.d/unbound.inc#L357

If I remember correctly, a `configctl template reload "OPNsense/Unbound/*"` would generate the top level and all subdirectories. In which case we can "plug" new features into their own directory.
unbound_generate_config() should execute the template reload in this case.

Just thinking out loud, not sure this is the best approach already, but would fit within our current code base.

**Comment by mimugmail** [comment]
`configctl` sounds good so external plugin can easily hook in.

When finished I would try to add a submenu as MVC to add DoT support. I think it might be stable enough for core support compared to DNSBL stuff.

**Comment by AdSchellevis** [comment]
we might even consider pulling it into core when done, plugin is a good starting point.

**Comment by AdSchellevis** [comment]
@mimugmail can you test https://github.com/opnsense/core/commit/3211eaed62461e98a33476df125a7a49ffd9be7d and close the issue if ok? thanks!

**Comment by mimugmail** [comment]
I try to test .. needs a plist-fix btw :)

**Comment by mimugmail** [comment]
It works, thank you @AdSchellevis 👍
