### ISSUE TITLE
VLAN allowed as parent of same VLAN

### ISSUE THREAD

**Issue by ruffy91** [opnsense/core#3648]
When editing a VLAN the VLAN I am editing can be selected as it's own parent.

**To Reproduce**
1. Got to: Interfaces: Other Types: VLAN
2. Click on edit for an existing VLAN
3. Select the VLAN you are editing in Parent interface
4. `opnsense: /interfaces_vlan_edit.php: The command `/sbin/ifconfig 'vlan0' name 'igb2_vlan100_vlan100'' failed to execute`
5. you now have an additional interface vlan0 with MAC 00:00:00:00:00:00

**Expected behavior**
If QinQ is supported: Do not show the VLAN interface you are editing as possible Parent interface
If QinQ is not supported: Do not show any VLAN interfaces as possible Parent interface

**Screenshots**

**Relevant log files**

**Additional context**

**Environment**
OPNsense 19.7.2 (amd64, OpenSSL)
APU4

**Comment by AdSchellevis** [comment]
QinQ is not supported, but this looks buggy indeed.

`get_interface_list()` seem to suggests it doesn't want to return these entries:

https://github.com/opnsense/core/blob/ab75fbb673e1298eade55367d3605ad4101ae829/src/etc/inc/util.inc#L813-L815

But since other consumers seem to expect these entries as a result from the same function (and only omit types like `pfsync`, `pflog` from the list) , we probably shouldn't try to repair this here.
