### ISSUE TITLE
VLAN names get truncated in Diagnostics/routes

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#366]
(From crashreport: 349c3af4-1f05-4ce1-a8e1-4b469e0fed69 ) 
I have multiple VLANs with multiple routes to these VLANs.   When I display routes (Diagnostics->Routes), the "Netif" column is not showing the complete interface name.  Instead, "vtnet1_vla" is displayed.  This limit troubleshooting since all displayed interfaces are the same.

**Comment by fichtner** [comment]
Unfortunately, that's how netstat works in the interface column, pfSense had a patch for this, but I don't feel we should put it back as this limits our interoperability. Not sure what to do other than scrap the interface name and statistics from somewhere else.

**Comment by fichtner** [comment]
Briefly disucssed with @fabianfrz -- my personal conclusion is we can't fix this as FreeBSD's netstat utility truncates the routes and there is no other utility that display them correctly in base.

A better fix would be to make the names shorter, which I won't dive into because "_vlan" is hardcoded in so many places that we will surely break something, leading to breakage instead of pure inconvenience. Sorry.
