### ISSUE TITLE
Adding new interface should restart services bound to "all interfaces" 

### ISSUE THREAD

**Issue by banym** [opnsense/core#3681]
[-] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[-] I have searched the existing issues and I'm convinced that mine is new.

**Is your feature request related to a problem? Please describe.**
When a new interface or vlan interface is added. The services bound to all interfaces like DNS need a manuall restart. Otherwise DNS resolution or NTP may not be possible on that new interface until reboot or manuall restart of the services.

**Describe the solution you'd like**
If a new interface is added the services with binding to all interfaces should be restarted gracefully, so they listen on all interfaces including the new from that time.

**Describe alternatives you've considered**
Maybe there could be concerns that this could add a security problem. I don't think so. As long as no rules are defined only the service is listening but can't be accessed. As long as no rule on the new interface allows the port for that service everything should be save.

**Additional context**
Adding new interfaces is a common task in daily firewall administration. Debugging why DNS is not working on that new interfaces brought up that issue to me. This could make life easier and safe time for otherse.

**Comment by AdSchellevis** [comment]
Usually if a service is listening to *, it should start listening to new interfaces automatically. Restarting services shouldn't be necessary and would add a lot of unwanted side affects. 

It's the responsibility of the service to cope with change, if there's a specific workflow that doesn't function, we could always check if there's an issue with it or if it should register to a specific event (https://docs.opnsense.org/development/backend/legacy.html#configure).
Separation of concerns is quite important for a stable environment.

From a system perspective you don't know which services expect to be bound to all interfaces, since components have their own way of coping with these things.

Some services do restart when adding an interface by the way, for example lighttpd, but to be honest, when bound to *, it does more harm than good (unneeded restart, kills your active connection):

https://github.com/opnsense/core/blob/601868162322c98f8086a072bef0523140acfea3/src/etc/inc/plugins.inc.d/webgui.inc#L36

In my opinion, it should only register the hook when not bound to [*].

**Comment by banym** [comment]
I understand that restarting some services can harm user interaction or lead to a not working configuration. 

Never the less the adding of interfaces is a common task. I see people rebooting the firewalls often because of such behaviour and see myself to do so, too. As it is not clear when you add the interface that some services require reboot, it is hard to relate not working DNS to the added interface the task was done a while ago. 

Will think about how I would like to be informed that maybe services need to be restarted after a specific action is done or how this could made visible that the running configuration is not in line with the defined configuration. Maybe an service overview page where a service that is not running on all interfaces while it is defined to do so could be marked as "waiting for restart" so it can be done in a planed way by an administrator. 

Regards,

Dominik

**Comment by AdSchellevis** [comment]
Hi Dominik,

If a service is bound to all, this shouldn't be necessary as mentioned before. only specific bounds might have issues. but as said, since there is no uniform way to know this, it won't be maintainable.
Issues around adding interfaces, often have other causes.

Best regards,

Ad

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
