### ISSUE TITLE
Use DNS servers just from one uplink or add priority

### ISSUE THREAD

**Issue by norg** [opnsense/core#3701]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

**Is your feature request related to a problem? Please describe.**

I have two uplinks, one via PPPoE (VDSL) and one via DHCP (Cable). The issue is that I just want to use the DNS servers provided by the VDSL uplink since those are the only ones which have the correct DNS entries for VoIP. The option Allow DNS server list to be overridden by DHCP/PPP on WAN is global and thus I end up with a mixed resolv.conf. This results in VoIP issues.

**Describe the solution you'd like**

I would like to have the DNS overriding setting interface/uplink specific instead of local. An alternative would be setting a priority so workaround it as well.

**Describe alternatives you've considered**
Setting the DNS servers manually, but as they could change I won't notice it right upfront as they're provided via PPPoE. And the provider even said that they can change quite often within a specific range.

**Additional context**
Forum post: https://forum.opnsense.org/index.php?topic=13659.0

**Comment by AdSchellevis** [comment]
Hi Andi,

It might be difficult to change the specific option for `dnsallowoverride` to a interface specific one, since dhcp client types of setups usually just seem to grep for the setting https://github.com/opnsense/core/blob/90c0c395a54967f28c797b46293d4fb975b27ded/src/opnsense/scripts/interfaces/dhclient-script#L260

An option might be to extend `get_nameservers()` to return the source of the entry and filter it out when a specific option in the interface is set here 

https://github.com/opnsense/core/blob/afe3c3a6cb52b0de7b439b17a126d4bd1ff7a7f6/src/etc/inc/system.inc#L171-L173

Next find a logic spot and description for the new option to ignore dns entries from a specific interface (maybe just a select picker underneath the original option with interfaces to ignore).

At the moment I don't have time to do the work needed for this, but it looked like a good idea to add some notes here.

Best regards,

Ad

**Comment by norg** [comment]
I think adding the option to ignore the dns entries from one interface is totally fine as well. Thanks for the hints at the code, maybe I will take a look at that myself at least from the internal perspective, UI part is not my best skill set :)

Thanks!

**Comment by AdSchellevis** [comment]
@norg can you try https://github.com/opnsense/core/commit/38b613614b392cfeea40edcd977cd3681a0421a0 ?

**Comment by norg** [comment]
I have it set and will keep an eye on it if it's working as expected, thanks a lot for that!

**Comment by AdSchellevis** [comment]
@norg ok, I'll close the ticket, just open a new one if there are issues with it.
