### ISSUE TITLE
NetFlow - Virtual WAN IPs

### ISSUE THREAD

**Issue by AndyX90** [opnsense/core#3703]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Is your feature request related to a problem? Please describe.**
In insight it counts nat'ed traffic twice which originates from or goes to virtual ips on WAN Interfaces (carp / aliases).
It is currently impossible to select virtual ips/aliases in the section 'WAN-Interfaces' in netflow-configuration.

**Describe the solution you'd like**
Make virtual ips and aliases selectable in the section 'WAN-Interfaces' in netflow-configuration.

**Describe alternatives you've considered**
Maybe exclude them by default...?

**Comment by AdSchellevis** [comment]
I don't expect that's possible, but if you want to investigate more, we use ng_netflow (https://www.freebsd.org/cgi/man.cgi?query=ng_netflow&sektion=4) to collect stats.

**Comment by ruffy91** [comment]
Add an option to select VIPs and filter the netflows after the capture in the Insight panel with nfdump.
I regularly use nfdump to filter netflows which account for billions of flows in a matter of seconds. nfdump can filter netflow using bpf expressions just like tcpdump does it for packet captures.

If you really can't do that add a ng_bpf node before ng_netfwlo, separate the traffic for the VIP there and collect it using a separate ng_netflow hook.


Bonus questions to the developers after reading about netgraph and ng_netflow:

- Is there a specific reason OPNSense collects the flows using multiple ng_netflow nodes?
One ng_netflow node can process up to NG_NETFLOW_MAXIFACES (default 65536) hooks

- Don't you have problems with ng_netflow mangling IPv6 and CARP packets?

According to Lutz Donnerhacke it's advisable adding an ng_ether and a ng_tee in front of an ng_netflow node because IPv6 and CARP do not fully survive ng_netflow (https://lutz.donnerhacke.de/Blog/Netflow-und-Netgraph)
The passage I refer to is:

> Unglücklicherweise gibt es erhebliche Probleme mit Frames, die von Netflow als "unverständlich" angesehen werden. Es ist zwar vorgesehen, daß nur bei echten Fehlern die Nachrichten verloren gehen können, aber IPv6 und CARP scheinen das Netflow-Accounting nicht komplett zu überleben.

My translation: 

> Unfortunately there are serious problems with frames that are considered incomprehensible by ng_netflow. It's meant that frames can only be dropped for real errors but IPv6 and CARP do not seem to survive netflow accounting completely.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by AdriDevelopsThings** [comment]
Hi, are there any updates regarding the problem with the traffic counted twice in the insights because of NAT? I'm currently struggling with the same issue and found this issue which is sadly closed.
