### ISSUE TITLE
Outbound NAT Rule Creation Using HA Creates Impossible Rule On Backup FW

### ISSUE THREAD

**Issue by TotalGriffLock** [opnsense/core#3712]
If you create a firewall rule on the primary firewall in an HA pair opnsense provides a list of placeholders in the interface selection dropdown. For example if my HA firewalls have an interface called WAN, an option in the dropdown is "WAN address". In the HA scenario, when this rule is pushed to the secondary/backup firewall, it inherits the equivalent "WAN address" IP for the secondary firewall.

If you do the same with an outbound NAT rule, this does not take place. If I create an outbound NAT rule on my primary firewall which does NAT on the WAN interface, the same list of placeholders is present in "Translation / target". However if I choose "WAN address" from this dropdown, when the rule is pushed to the secondary/backup firewall in the HA pair, the IP address of the primary firewall on which the rule was created is present. This then means that traffic exiting the secondary firewall is rewritten with the IP address of the primary firewall.

Running OPNsense 19.7.4_1-amd64

**Comment by AdSchellevis** [comment]
a bit of inherited legacy, "Interface address" selects the proper interface address.

https://github.com/opnsense/core/blob/0e17ecf584ce3be5dcf00eaa5f48370e950c8e26/src/opnsense/mvc/app/library/OPNsense/Firewall/SNatRule.php#L72-L84

but for consistency reasons, we better replace the stored address to a reference ([lan,wan,optXX]ip) as in the other firewall sections. please note that current items will show an address in that case, since the item stored was an address.
