### ISSUE TITLE
Port Forward: Rule applies to wrong interface too

### ISSUE THREAD

**Issue by ruffy91** [opnsense/core#3718]
[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
19.7.4_1
If I apply a NAT rule on Interface OPT1 and use LAN net as source address, traffic on LAN interface also gets affected.

**To Reproduce**
1. Go to Firewall: NAT: Port Forward
2. Create new Port Forward on Interface OPT1 with the following settings:
Interface: OPT1
TCP/IP Version: IPv4
Protocol: TCP
Source: LAN net
Source port range | from:to: any
Destination: any
Destination port: HTTPS
Redirect target IP: localhost
Redirect target port: 3129
Filter rule association:  Rule

**Expected behavior**
When traffic hits OPT1 with a source IP in the LAN range it gets redirected.
When traffic hits LAN it is not affected at all by NAT rules applied to OPT1

**Screenshots**
Firewall Log: you can see the traffic on LAN (igb2_vlan42) gets redirected.
![image](https://user-images.githubusercontent.com/344634/65392739-37977e80-dd78-11e9-87f4-2542d8a84991.png)
PFInfo: rule as it appears in the table
![image](https://user-images.githubusercontent.com/344634/65392752-50a02f80-dd78-11e9-9c2d-63f080fe3555.png)
Firewall: NAT: Port Forward: rule as I defined it in the GUI
![image](https://user-images.githubusercontent.com/344634/65392779-93fa9e00-dd78-11e9-8ae9-5b36322599dd.png)

**Additional context**
I made a mistake when setting up transparent proxy (as you can see in the last screenshot) which caused me to being unable to surf on HTTPS from the LAN.
This really is a red flag for me and does make me a little suspicious about the ability of my firewall to correctly filter traffic as defined by me. Is it possible that other rules I applied to different interfaces suddenly match for an interface they shouldn't?
Do I have to audit all the firewall rules with test traffic on all interfaces?

**Environment**
OPNsense 19.7.4_1 (amd64, OpenSSL).
APU3C4

**Comment by ruffy91** [comment]
What just crossed my mind:
Is it possible that a pf rule ignores/understands the vlan tag?
So that
`pass in log quick on igb2 inet proto tcp from xxx to xxx port = xx flags S/SA keep state`
also applies to all traffic of child interfaces because the vlan tag is understood but ignored because it is not used in the rule?

**Comment by fichtner** [comment]
TBH, looks like the firewall does what you tell it to, but not what you expect. There's a long history of problems with tagged/untagged on the same interface and that seems to be the case here.

We could add a warning on the interface assignment page for these kind of situations, but since pf.conf(5) doesn't support VLAN ID filtering the only sensible thing is to redesign the network layout to avoid it.


Cheers,
Franco

**Comment by ruffy91** [comment]
So just to confirm.
If I apply Firewall rules to a untagged interface it will also apply to tagged interfaces on the same NIC?
Is this reliable or will it sometimes work and sometimes not?
I can work around that if I know the limitations.

2nd question. I configure Trunk ports on the switches which sometimes contain VLANs which are not configured on the OPNSense. Will the OPNSense happily ignore the VLAN tag and forward tagged frames if it finds a matching route in the FIB even if the VLAN is not assigned to a interface or will these frames be dropped?

**Comment by fichtner** [comment]
> If I apply Firewall rules to a untagged interface it will also apply to tagged interfaces on the same NIC?

Yes, because the VLANs are "slurped" into the rule engine by skipping the headers so rules match for all VLANs on it and the untagged traffic. If the rule matching is loose enough it'll start to act on not just the supposed traffic but all that matches due to the complication of VLANS being contained in the interface itself.

> Is this reliable or will it sometimes work and sometimes not?

This should be reproducible 100% of the time.

> I configure Trunk ports on the switches which sometimes contain VLANs which are not configured on the OPNSense. Will the OPNSense happily ignore the VLAN tag and forward tagged frames if it finds a matching route in the FIB even if the VLAN is not assigned to a interface or will these frames be dropped?

It should never forward unknown VLAN traffic because unknown traffic is supposed to be discarded. That also goes for having an untagged assigned interface and "seeing" VLANs on it, because the network stack won't read it of not allowed.


Cheers,
Franco
