### ISSUE TITLE
NAT reflection doesn't appear to be working

### ISSUE THREAD

**Issue by loganx1121** [opnsense/core#3769]
Not sure if this is a bug or not.  I'm running 19.7.5_5.  So I have my XMPP server on an inside subnet, and I've got the port forward working...at least from the outside.

So outside my LAN, people can reach my chat server and authenticate using the DDNS I have setup. No issue there. However, from inside the LAN I can't use the DDNS address. I have to specify the internal IP of the server to use the chat when I'm at home. I can only assume this has something to do with the port forwarding, but I'm not sure what it would be.

I don't see anything in the live logs in terms of traffic being blocked or anything when I try to connect using the DDNS address.  I can see the traffic being allowed, or at least it seems to be.  
`Inside		Oct 16 18:07:36	192.168.50.71:62192	10.5.7.18:5222	tcp	let out anything from firewall host itself	
Inside		Oct 16 18:07:36	192.168.50.71:62192	10.5.7.18:5222	tcp	`

Not sure I know how to read the state table but I do see this

`192.168.50.27:49436 -> 10.5.7.18:5222	SYN_SENT:CLOSED`

![2019-10-16 15_20_31-Port Forward _ NAT _ Firewall _ Asgard-Wall localdomain](https://user-images.githubusercontent.com/56660155/66968352-be2b3d00-f052-11e9-8d91-2b617e455ee1.png)
![2019-10-16 15_21_00-INET _ Rules _ Firewall _ Asgard-Wall localdomain](https://user-images.githubusercontent.com/56660155/66968354-be2b3d00-f052-11e9-9c05-2cb583971bde.png)
![2019-10-16 16_50_52-Jump List for File Explorer](https://user-images.githubusercontent.com/56660155/66968355-be2b3d00-f052-11e9-80e3-ceb67ab02525.png)
![2019-10-16 16_51_10-Start](https://user-images.githubusercontent.com/56660155/66968356-be2b3d00-f052-11e9-9fcc-61d6abc97ffc.png)

I already have "Reflection for port forwards" and "Automatic outbound NAT for reflection" enabled.  I also reset the state tables but no change.

Any help is appreciated.  Thank you!

**Comment by loganx1121** [comment]
I was able to resolve this by adding an outbound NAT rule to my LAN interface.  Still means NAT reflection isn't working properly, but I was able to work around it...

**Comment by mimugmail** [comment]
Two days ago I had a installation of cameras and similar setup. Port forward was already there and I just enabled nat reflection (2 checkboxes) unser Firewall : Settings : Advanced

**Comment by loganx1121** [comment]
Yeah I have those same checkboxes enabled...doesn't work without the work around I did.  If I don't have the outbound NAT rule on my LAN interface, no dice.  I tore down the port forward and rebuilt it probably a dozen times.  Didn't change anything...and I tried having the NAT reflection enabled both before and enabling it after I did the port forward.  I'm on version 19.7.5_5...what version are you on?

**Comment by brandonmreeves** [comment]
Same issue here

/b

**Comment by muchahagrande** [comment]
Same issue here. @loganx1121 , can you send the Outbound NAT rule you set as workaround?

**Comment by brandonmreeves** [comment]
Still same issue. NAT not functional. Hope this gets fixed soon so my NAT rules start working again

OPNsense 19.7.7-amd64
FreeBSD 11.2-RELEASE-p16-HBSD
OpenSSL 1.0.2t 10 Sep 2019

**Comment by brandonmreeves** [comment]
Any update on this?

**Comment by brandonmreeves** [comment]
Is this an issue or are we doing something wrong? I am open to a workaround for this but right now our nat forwards are not working properly. @AdSchellevis is this an open item or do we need to downgrade or make config changes for this to work?

**Comment by AdSchellevis** [comment]
@brandonmreeves it's a community support ticket. There might be scenario's where automatic reflection rules don't function properly, in which case you can always create manual rules.

**Comment by brandonmreeves** [comment]
Thanks @AdSchellevis Can you give me an example of the manually created rule. We are having some issues getting them to work. 

In our scenario we have an ftp server behind opnsense that we allow the internet to access via 21 only. What would that rule look like?

So its:

(FTP Server:21)<---[OpnSense WAN]<-----Public Internet

Thanks for any help in advance

**Comment by mimugmail** [comment]
You start with the most complicated protocol. Why dont you Install a small http server inside for testing, create a fresh Nat rule with reflection and test.

FTP has different modes with different directions, and also flips the ports from 21 to highport range. Highly error prone in such a scenario

**Comment by brandonmreeves** [comment]
I am well aware of the complexities of ftp and other protocols. However, I am not doing this for testing purposes. We use opnsense and need to nat ftp and other ports/protocols which has been working properly up until this point. While we have been very supportive of opnsense since the split from pfsense this seems like something where we will need to reevaluate our choices. Functioning NAT is basic requirements for perimeter devices to allow access. Therefore, if there is no fix coming around unfortunately we will need to make some technology changes even though we like the opnsense platform.

Thx

**Comment by mimugmail** [comment]
No need for a fix, you need to post some screenshots and packet dumps from internal connection and coming back (or trying to)

**Comment by fichtner** [comment]
I feel like this is easily wrapped up through commercial support one way or another. Please be aware this is a community support ticket and providing substantial data on your case basically is the only way how anyone will be able to inspect it. Generally, „I have the same issue“ is the least productive way to start a question or discussion or bug hunt or feature request. Looking through the responses that was made clear earlier, but then again maybe it was skipped over so forgive me for reiterating.

**Comment by pjdouillard** [comment]
Why was this ticket closed?  
No solution was provided and this problem still exist as of today.  

I have encountered this quite often since last fall as I am teaching network and security classes and use OPNsense regularly with my students.  The problem occurs (and can be reproduced) under VirtualBox (Windows or Linux) with an OPNsense firewall having 3 interfaces: LAN, WAN (dhcp) and a DMZ.   The port forward are a simple redirection of some ports (1111, 2222, 3333) on the WAN interface to vms' port 22 (SSH) in either the LAN or DMZ.
The firewall logs show that the incoming connection are accepted on said ports, and the translation (NAT) has occured to the proper destination.  The problem is: nothing is ever received on the destination machines.  It's like the packets are not even going on of the destination interface (LAN or DMZ) and nothing ever reach the vms because I am monitoring coms there too.

Then, out of the blue, things starts to work for either me, or some students. And then again, things stops while no change were made.

If I switch to any other firewalls (running inside a vm) like Sophos, Checkpoint, pfSense, it works right away and never fails.

So there is something that is worth investigating imo that's doesn't require commercial support as Port Forwarding is a basic fonctionality on any modern firewall.

**Comment by mimugmail** [comment]
Affected by this?
https://github.com/opnsense/docs/pull/236

**Comment by fichtner** [comment]
> Why was this ticket closed?
> No solution was provided and this problem still exist as of today.

Why so rough? You can read about our ticket policy here: https://github.com/opnsense/core/blob/master/CONTRIBUTING.md#issue-reports

This includes not responding to closed tickets.

**Comment by VooPoc** [comment]
I think this is resolved, I've just been looking at this myself and just enabling NAT Reflection on a rule isn't enough. it needs additional Outbound Rules.

The quick solution is enabling "Automatic outbound NAT for Reflection" within Firewall > Settings > Advanced.  

When looking at what "Automatic outbound NAT for Reflection" does, for me it also creates outbound rules for ssh and HTTP and the enabled NAT reflection on all interfaces.  I didn't want this so I just created one Outbound Rule:

```
Interface: LAN
Protocol: TCP
Source: LAN net
Destination address: internal address of host
Destination Port: internal address port
Translation / target: Interface address
```

**Comment by beananimal** [comment]
@VooPoc 
What you posted will not work
It should be

Interface: LAN
Source: LAN net
Destination Address:  WAN net
Destination Port: Your server port
Translation/target: Internal Server Address and Port

The rule says "If traffic from inside bound for the public ip/port is found, redirect that traffic to the internal host and port"

**Comment by fengchen-github** [comment]
Firewall: Settings: Advanced
 Reflection for port forwards	Y
 Automatic outbound NAT for Reflection	Y

This setup works fine.

**Comment by fengchen-github** [comment]
Firewall: Settings: Advanced
 Reflection for port forwards	Y
 Automatic outbound NAT for Reflection	Y

This setup works fine.
