### ISSUE TITLE
unbound: ACL should generate for full WAN IPv6 prefix

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#3797]
Since there is a reload missing when LAN tracker gets a dedicated subnet it would be easier to extend to the real prefix so there doesn't need to be a reload.

**Comment by maurice-w** [comment]
This might be easier, but creates a security issue. It results in unbound responding to queries from clients on _all_ tracking LAN interfaces, even if only specific network interfaces are selected on `services_unbound.php`. Also, the calculated prefix length is applied to IP Aliases, too.

**Comment by fichtner** [comment]
backed out the main change, you're right

**Comment by chaosbiber** [comment]
Sorry if this is not sufficient related, but with 20.7.3 I still got the problem of being denied DNS requests via IPv6 because of ACL update problems after a reconnect with updated IPs (forced daily by my bad provider 1&1 or previously a cron job). LAN is tracking WAN for an IPv6 subnet. The list on /services_unbound_acls.php contains the correct, updated IPv6 networks, but `/var/unbound/access_lists.conf` keeps the old entries until I restart unbound manually.

**Comment by Peter0x48** [comment]
Hi @fichtner,

I sometimes run into this problem too. I receive a new prefix every night and on the next day queries are "Refused" (Reply code 5). But the ACL file (/var/unbound/access_lists.conf) contains the correct prefixe for each track interface.

However, If I restart, two lines are removed, e.g.:
```
access-control: 2001:12e1:d73b:9200:20d:b9ff:fe57:7758/64 allow
access-control: fd00::20d:b9ff:fe57:7758/64 allow
```
The first line is a address with the prefix from the day before.

Maybe the file is updated correctly (except the two lines) but not loaded by Unbound?

Thanks!
