### ISSUE TITLE
API: firewall rules

### ISSUE THREAD

**Issue by thomasfinstad** [opnsense/core#3826]
**Is your feature request related to a problem? Please describe.**
I would like to use opnsense in a IAC environment, but currently there is no API for creating/deleting firewall rules, only aliases

**Describe the solution you'd like**
The firewall module in the API to implement options for manipulating the firewall rules.

**Describe alternatives you've considered**
Shortly considered using the shell over SSH, but believe this fits the API, and would make opnsense much more attractive to anyone utilizing the API

**Additional context**
With better/full api support for the firewall setup I would be able to start work on a terraform provider for opnsense.

**Comment by bewue** [comment]
@thomasfinstad please modify the post to the guidelines accordingly 
then you get a thumbs up from me ;)

For example, this feature would be very helpful for applying a standard rule set to a newly created interface.

**Comment by thomasfinstad** [comment]
@bewue I believe I have filled it out well enough now, I did read the contrib and search other issues, but assume that would just waste space to keep it in with a checked box. If I still am failing to fill it out please let me know how to do it properly, thanks.

**Comment by fabianfrz** [comment]
@fichtner I may do that but then move to plugins like backup.

**Comment by AdSchellevis** [comment]
@fabianfrz you can always build a plugin with the facilities which are already in place,  although in my opinion it would only make sense when it could act as a drop in replacement for the full package (which is a considerable amount of work involving quite some frontend challenges). Most use-cases are served properly already using a setup configuration boilerplate and aliases by the way.

**Comment by fabianfrz** [comment]
then I will try to build it into the core but then it will be a bigger refactoring I think. Since this involves many components, it may require some JS build environment to get that done even using standard components of OPNsense like bootgrid but for example the standard dialogs will be far too small for this view. I may be able to recycle some nginx plugin components which are partly also non-standard UI components.

If you look at this screenshot, the following components needs to be checked, changed or added:
![Bildschirmfoto vom 2019-12-10 um 18 59 22](https://user-images.githubusercontent.com/3713914/70556048-61df2800-1b80-11ea-9ce7-4c2a0bf61a0d.png)

**Comment by AdSchellevis** [comment]
@fabianfrz please keep your proposals in plugins first, we can always consider moving over later depending overall quality and amount of work needed at our end to guide the process.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
