### ISSUE TITLE
System: Wizard: causes no internet connection in static IPv4 WAN environment

### ISSUE THREAD

**Issue by igpit** [opnsense/core#3873]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Bug decscription**
Walking through the Wizard, configuring a static IPv4 WAN, still 2 gateways get configured:
1. The IPv4 "WANGW" corresponding to your static WAN configuration. It will show as offline in System: Gateways: Single. 
2. The IPv6 "WAN_DHCP6" from the default DHCP setting for IPv6 of the interface.  It will be online in System: Gateways: Single, and cannot be removed there (of course, comes from interface configuration). Note: Getting state "online" happens even when no IPv6 configuration / DHCP is present.

**To Reproduce**
Reset to defaults.
Wizard: Configure static IPv4 WAN, have no DHCP on WAN side. 
Test ping to some WAN address, fails with "ping: sendto: No route to host"

**Expected behavior**
1. Disable IPv6 DHCP
2. Allow IPv6 setting (e.g. IPv6 Configuration Type: None) in Wizard

**Workaround**
1. After running through the wizard, go to Interfaces: WAN, and set "IPv6 Configuration Type: None".
2. Edit the IPv4 GW, changing nothing, save. The IPv4  GW will now change to state online.
3. ping works now. 

**Additional context**
related to #3874 

**Environment**
19.7.8

**Comment by fichtner** [comment]
Hi, it seems like the default behaviour. IPv6 is left configured because the wizard never supported it.

**Comment by fichtner** [comment]
Relevant feature ticket without a contributor https://github.com/opnsense/core/issues/79

**Comment by igpit** [comment]
added:

**Additional context**
related to #3874

**Comment by tk-wfischer** [comment]
Hi Franco,

I think I have found the root cause of this issue:

- The wizard configures the IPv4 Default Gateway (e.g. "10.1.102.1" in my case) with Protocol **IPv6** -> this is wrong, it should be IPv4. Details see screenshot here: http://www.wefi.net/opnsense/Wizard-IPv4-Static.png

As a short fix/workaround:

- Go to "System" -> "Gateways" -> "Single" and edit the entry "WANGW". For some (to me strange) reasons, the editing dialog shows the "IPv4". So you just need to click "Save" - then the WANGW is correctly configured as IPv4 gateway, not as IPv6 gateway.
