### ISSUE TITLE
System: Configuration: Defaults: results in config having DHCPv6 enabled on default WAN interface

### ISSUE THREAD

**Issue by igpit** [opnsense/core#3874]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
The default configuration results in having DHCPv6 enabled on default WAN interface

**To Reproduce**
System: Configuration: Defaults: Load defaults
Power on
Connect to UI at 192.168.1.1
check System: Gateways: Single showing a default GW

**Expected behavior**
no gateway configured 
DHCP on default WAN interface off

**Additional context**
related to #3873 

**Environment**
19.7.8

**Comment by fichtner** [comment]
I can tell you right now this is the intended behaviour and I do not see what could be done to change it to make it “better”.

**Comment by igpit** [comment]
wow. did not expect that. is there any rational behind that? isn't that inconsistent? 

well, my better solution would be to leave WAN completely unconfigured until you decide what to do wih it. be it running the wizard or do manual configuration. imho the default should end at a point where you can start configuring the box.

1. even when there is no DHCP server answering, a gateway is created
2. apparently DHCPv6 client is on, and not DHCPv4? (or is just no gateway created?)
3. i can understand that you define as default to have the first interface be 192.168.1.1 with DHCP server on, but putting WAN on DHCP is imho really unexpected.

**Comment by fichtner** [comment]
WAN when configured in the install media is DHCP in IPv4 and IPv6 to enable instant connectivity. I’m not aware of a side effect that is not wanted when considering you can easily reconfigure it on install console. This is the default since at least 10 years and I am not aware of other requests to change something. And even changing it has grace implications for everyone else.

If you want a different default behaviour simply replace /usr/local/etc/config.xml and the sky is the limit. 😊

Cheers,
Franco

**Comment by igpit** [comment]
ok. so close this one up i guess. ;)
