### ISSUE TITLE
feat: Enable PortField to use BaseListField (alow multiple)

### ISSUE THREAD

**Issue by Szeraax** [opnsense/core#3895]
Make PortField capable of using BaseListField, so you can just add <multiple>Y</multiple> to the port field on plugins. Is better solution for https://github.com/opnsense/plugins/pull/1675 and related.

**Comment by AdSchellevis** [comment]
both https://github.com/opnsense/core/commit/c1c32c9eed483bbd1293ef317686c642c8317c41 and https://github.com/opnsense/core/commit/928a75bb0bcb3e02741652e8ef26263b3769212b are needed to retain backward compatibility. Since our other option lists return list types to the frontend, this would break our current port usages. 

Maybe we should eventually add a return type in the `BaseListField` type, but if we do, we can easily make sure the current state remains functional.
