### ISSUE TITLE
Keep the lobby traffic graphs persistent

### ISSUE THREAD

**Issue by grizzy255** [opnsense/core#3915]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[-] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[-] I have searched the existing issues and I'm convinced that mine is new.

**Is your feature request related to a problem? Please describe.**
Feature Request.
The traffic graph in the lobby:dashboard is not persistent. If I change to another view and get back the graphs start from scratch.

**Describe the solution you'd like**
 Please consider adding a history for the last n minutes/hours so the graph does not start empty. 

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by kcaj-burr** [comment]
After investigating, unfortunately I dont think its feasible to use the `flowd_aggregate` data for the live graphs due to the `flowd.log` parsing time and the need to have data at 1 or 2 second intervals (Im sure you smart guys could have told be that before)

It would be ideal to have `flowd` generate a second smaller log file holding 5mins of live data - unfortunately it does not have this capability.

A few things I thought about doing:

1. Split the `flowd.log` into a smaller piece and parse that. Dont see this being a good idea (though I'm not smart enough to know)
2. Run a second `flowd` process just generating a 5min log (this could be interesting)
3. Create a script which continually collects 5mins from data from `netstat` or the likes.
4. Just serve up the most up-to-date data we have from `flowd_aggregate` and live with it not being quite correct.

Any other ideas or thoughts?

**Comment by AdSchellevis** [comment]
currently I don't expect the core team to spend time on this, netflow isn't really suitable for live statistics and not always enabled as well, collecting stats with `ifinfo` just for keeping the widget up to date doesn't sound very efficient as well. 
A specific widget for only netflow statistics would be better from an architectural point of view, but wouldn't show the current traffic (netflow always lags).

**Comment by kcaj-burr** [comment]
Hi AdSchellevis,

I agree not really an ideal solution. I do have a question though; you mention you dont expect core team to spend time on this, does this mean I shouldn't bother even looking at code in the core as its only for core developers to alter? These issues are marked 'help wanted' so I assumed thats what it ment, though if its more of a burden on you guys I dont want to waste your time.

**Comment by AdSchellevis** [comment]
hi @kcaj-burr, you can certainly work on it, we do except pull-requests, but we are selective in which changes may go into our product. If the code quality is good and has a clear separation of concerns, it could just go into core. 

We try to be constructive in feeding enhancements into core, I was just trying to be clear about the expected effort from the core team (not going to start working on it, but if you start with a PR, probably are going to provide feedback to help this further).

**Comment by kcaj-burr** [comment]
Understood AdSchellevis, thank you!

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
