### ISSUE TITLE
Can't create gateway for routed IPSEC on 20.1.x

### ISSUE THREAD

**Issue by alexandredulche** [opnsense/core#4029]
**Describe the bug**
On OPNsense 20.1.4 when creating a routed IPSEC following the official documentation I can not create the gateway with the remote tunnel IP. 
It says : "The following input errors were detected: Cannot add IPv4 Gateway Address because no IPv4 address could be found on the interface."

The issue doens't occur on OPNsense 20.1.3.

**To Reproduce**
1. Fresh 20.1 install (on VMware VM) 
2. Update to 20.1.4
3. Create the IPSEC tunnel following documentation
4. Get stuck when manually creating the gateway

**Expected behavior**
Manually creating the gateway is mandatory for adding the proper routes.

**Screenshots**
N/A

**Relevant log files**
N/A

**Additional context**
Setting up a new OPNsense VM (20.1 -> 20.1.4) connecting via IPSEC to an existing one (20.1.3)
I reverted my new box from 20.1.4 back to 20.1 (VM snapshot) and I could mount the tunnel without issue.

**Environment**
OPNsense 20.1.4 (amd64, OpenSSL).

**Comment by fichtner** [comment]
I can't see anything related to https://docs.opnsense.org/releases/20.1.html?highlight=release%20notes#april-08-2020 that would cause this. It likely wasn't 20.1.4.

You can always check by issuing:

    # opnsense-revert -r 20.1.3 opnsense


Cheers,
Franco

**Comment by alexandredulche** [comment]
Reverting to 20.1.3, 20.1.2, 20.1.1, 20.1 gives me the same error when editing the gateway.
I'm not sure if I was supposed to reboot each time (I did after reverting to 20.1)

What else could I check ?

**Comment by alexandredulche** [comment]
I think I found a clue having a quick look at the code.

I guess the tunnel has to be up from an IPSEC point of view, so that the IPSEC interface will get it's VTI IP, before one can add/edit a gateway on top of the tunnel.

Can you confirm it ?

If so then a slight improvement could be to add to the error message stated above something like "If you are editing an IPSEC VTI gateway, make sure the tunnel (SA) is up", and also mention it in the documentation.

Thank you.

**Comment by alexandredulche** [comment]
Tested again and confirmed it.
IPSEC tunnel has to be UP first (although you can't confirm that with a ping for example since routes and gateways are not set yet).

**Comment by cluck** [comment]
This is still hindering setup of routed IPsec VPNs as documented in https://docs.opnsense.org/manual/how-tos/ipsec-s2s-route.html.

I think it is an error/bug to hold up the configuration because of runtime status of the tunnel.
Moreover I don't see a workaround documented herein. IMO this bug should remain open,

**Comment by mimugmail** [comment]
But if you strictly follow the Docs it works? For me it was not reproduceable.

**Comment by GaardenZwerch** [comment]
Hi,
I have put some time into this as I probably see the same problem, and I can reproduce it.
The result is that the created ipsec interface doesn't have an IP address, and then you can't create a gw.
I have observed that it depends only on the IP addresses specified in phase2. 
The problem is related to the 'distance' between the two point-to-point addresses (tunnel_local, tunnel_remote); it looks like they can not be more than 31 apart.
examples:
```
remote       -  local
----------------------------------------------
10.10.11.1  - up to 10.10.11.32 works
10.10.11.1  - 10.10.11.33 doesn't work (ifconfig ipsec<n> has no 'inet' line)
10.10.11.33 - up to 10.10.11.64 works
10.10.11.33 - 10.10.11.65 doesn't work
10.10.11.34 - 10.10.11.65 works (not in the same /27)
10.10.11.20 - 10.10.11.55 doesn't work
10.10.11.30 - 10.10.11.40 works (not in the same /27)
```

reproduce by editing phase2, save. apply and test with ifconfig ipsec<n>
I have upgraded to 21.1.8.
Thanks

**Comment by psychofaktory** [comment]
I have encountered the same problem.

The behaviour was exactly as described by GaardenZwerch.

I have OPNsense 21.7.1-amd64 in use.

**Comment by mimugmail** [comment]
I dont get it, this is Point to Point, if you use 10.255.255.1 and .2 like in the docs it works, correct?

**Comment by bimbar** [comment]
> I dont get it, this is Point to Point, if you use 10.255.255.1 and .2 like in the docs it works, correct?

It's not point-to-point, it's a link network. If, luckily, you use the usual, a /30 link network, then it will work, because it calculates the mask by
> mask = 31 - (IPA - IPB)
however, if the difference is greater than 1, the result doesn't make any sense, and if it's greater than 31, it starts to be actively incorrect / not allowed.

In any case, the user should be able to select the mask manually, if only so that he realizes it's not actually P-t-P but a link network.

**Comment by ppbrown** [comment]
arrrg.
I am having this exact problem, seems like.
I suppose I should mention that both sides are behind NAT.

If I just set the "remote side" and "local side" to what I would normally set the remote id and local id to (ie: the public IPs used by the NAT) then the connection happens... but I cant then make a gateway.

If I instead use made-up names like the sample 10.111.1.1 .. it doesnt work.. because auth fails.

(I should mention that one side is not OPNsense but a meraki router)

**Comment by ppbrown** [comment]
What gets me is that the OTHER side seems to understand the situation just fine. It figures out that it can route packages through the link just fine with the "tunnel remote address" and local address being the remote and local ids of the two routers involved.
So pings make it all the way through to a machine behind the opnsense box. But opensense, doesnt have the sense to return the ICMP reply .

**Comment by ppbrown** [comment]
Wait.. why is this closed? Its still a bug? !!
Please reopen this issue.

**Comment by fichtner** [comment]
What exactly is the issue and where does it happen? Jumping into a closed ticket with no template data is unhelpful. The netmask issue referenced by @bimbar in September was fixed in a 21.7.x release. Next is your „me too“ so I’m having a hard time understanding.

**Comment by ppbrown** [comment]
Ah. 
well i was having *exactly* the same issue, so didnt think it neccessary to repeat the info.

The ticket seems to be closed with no justification. It's great to know it was fixed. 
In this kind of situation, on other github projects, I'm used to seeing some kind of "closed, fixed in X.Y,Z" marker.

**Comment by fichtner** [comment]
No version info, no steps to reproduce. I’m locking this thread in the hope you will open a ticket with the necessary data.
