### ISSUE TITLE
Unable to resolve internal DNS names when external network connection is broken

### ISSUE THREAD

**Issue by dlotton** [opnsense/core#4030]
**To Reproduce**
1. Disconnect external ISP connection (path to external DNS server)
2. Try to resolve names of machines on internal network 

**Expected behavior**
All machine names on internal network which are managed by the OPNSense router should resolve, regardless of the state of the connection to the external network.  They do not.  

These machine names include 'Host Overrides' defined in the 'Dnsmasque DNS=>settings=>Host Overrides' section, and also names that are registered by the DHCP service.

**Additional context**
No external connection to a DNS service should be required to resolve internal machine names managed by my internal OPNSense router.  **I fear this represents a information leak, and therefore a security risk.**  Is the router's DNS service first trying to resolve internal machine names externally?

I am uncertain with which version of OPNSense this broke, but I'm reasonably certain it has not always behaved in this manner.  My ISP connection failed yesterday a couple of hours after updating my router packages, which created a lot of confusion about what was happening.  I finally realized my external network connection was down.  When the connection returned, I was able to resolve internal machine names again.  

**Environment**

All latest OPNSense updates applied as of 04/11/2020
Versions
OPNsense 20.1.4-amd64
FreeBSD 11.2-RELEASE-p18-HBSD
OpenSSL 1.1.1f  31 Mar 2020

**Comment by fichtner** [comment]
If you use a forwarder, then be prepared for your queries to be forwarded. ;)

I'm not sure if this is actually a feature, but I do know that possibilities to configure this more elaborate do not exist (in Dsnmasq). No such report for this over the years, likely not relevant to security, but that's no conclusive analysis.

That being said, I'm not sure your connection is non-existant or simply hangs due to ISP hiccup, in wich case no service would have a chance to return directly and instead do some operation that has to time out first.

My best guess is try to use Unbound and see if that works better. Unbound is our default since a few years.


Cheers,
Franco

**Comment by dlotton** [comment]
After a bit more digging around in the Services=>Dnsmasq=>Settings and digging into 'Domain Overrides' I found some instructions that helped me figure it out.
 
I added a Domain Override for my domain and set the value of the IP Address to '!' as noted by the instructions.  
 
Here are the instructions given for the IP Address field on that page...
 
> IP address of the authoritative DNS server for this domain
> e.g. 192.168.100.100
> Or enter # for an exclusion to pass through this host/subdomain to standard nameservers instead of a previous override.
> **Or enter ! for lookups for this host/subdomain to NOT be forwarded anywhere.**
> 
 
I was thrown by OPNsense because this was default behavior for the router's system domain on other routers I have used.
 
Anyway, this appears to resolve the issue.  DNS look-ups for the router's domain are not forwarded to an external DNS, and DNS lookups for my domain on my internal network don't hang when my external network connection goes down.
