### ISSUE TITLE
wrong AJAX request in the export config gui

### ISSUE THREAD

**Issue by MosheL** [opnsense/core#4031]
**Describe the bug**

I am reciving this error message while I am playing GUI.

[12-Apr-2020 15:06:37 Asia/Jerusalem] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function OPNsense\OpenVPN\Api\ExportController::accountsAction(), 0 passed and exactly 1 expected in /usr/local/opnsense/mvc/app/controllers/OPNsense/OpenVPN/Api/ExportController.php:205
Stack trace:
#0 [internal function]: OPNsense\OpenVPN\Api\ExportController->accountsAction()
#1 [internal function]: Phalcon\Dispatcher->callActionMethod(Object(OPNsense\OpenVPN\Api\ExportController), 'accountsAction', Array)
#2 [internal function]: Phalcon\Dispatcher->dispatch()
#3 /usr/local/opnsense/www/api.php(26): Phalcon\Mvc\Application->handle()
#4 {main}
  thrown in /usr/local/opnsense/mvc/app/controllers/OPNsense/OpenVPN/Api/ExportController.php on line 205

**To Reproduce**

navigate the export menu, without  server configured

**Screenshots**

**Relevant log files**

**Additional context**

**Environment**

OPNsense 20.1.4-amd64
FreeBSD 11.2-RELEASE-p18-HBSD
OpenSSL 1.1.1f 31 Mar 2020

I also tested it on diffrent machine with OPNsense 20.1-amd64 , the same problem shows but the VPN itself is working.

**Comment by AdSchellevis** [comment]
The `http[s]://your.firewall.address/api/openvpn/export/accounts` is only called from the exporter, when a parameter is omitted it will crash (I could only trigger this manually on my end, which is expected behaviour)

https://github.com/opnsense/core/blob/fde54d978e82bdb1c4460715f9f1f4a5e1025a47/src/opnsense/mvc/app/views/OPNsense/OpenVPN/export.volt#L120

For a site2site example, you might want to visit our docs https://docs.opnsense.org/manual/how-tos/sslvpn_s2s.html

**Comment by MosheL** [comment]
I found the vpn problem, and I found also the wrong and irrelevant Ajax request as you described.

thanks.

**Comment by AdSchellevis** [comment]
you're welcome, I'll close the ticket.
