### ISSUE TITLE
Custom scripts

### ISSUE THREAD

**Issue by adrianschneider94** [opnsense/core#4051]
[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

Some plugins/components have the option to add custom configuration, for example the "Advanced" text area in the OpenVPN Server config.
One application of those fields would be, to include a callback script.
However, there is no possibility to add scripts, which are persisted in the config. That means, one would have to backup not only the config file, but also the custom scripts.

So I'd wish to have a option, to add custom scripts in the webinterface, which are stored in the configuration and loaded and chmodded on config load. One could use those scripts for Cron jobs or like in the example for callback scripts.

This would further increase the flexibility of OPNSense.

**Describe alternatives you've considered**
One could write a plugin instead of adding scripts. but this would be a bit overkill I guess.

**Comment by AdSchellevis** [comment]
not going to happen, it's an architectural choice to limit shell injection possibilities.

Just for reference, some similar requests
https://github.com/opnsense/plugins/issues/1110
https://github.com/opnsense/plugins/issues/877

and a commit making it explicit that these things will be removed in the future, for the last ones existing in core, due to the impossibility to validate input (which in the past has resulted in multiple security issues) 

https://github.com/opnsense/core/commit/d62015df1cdb0c0711b488bd66ced631b9a4f37b

Functionality shouldn't be part of the configuration.

**Comment by fichtner** [comment]
I concur. You can write custom plugins with embedded scripts and easily build, deploy and update them.
