### ISSUE TITLE
IDS alerts page navigation items not updated correctly

### ISSUE THREAD

**Issue by bewue** [opnsense/core#4053]
**Describe the bug**
The IDS alerts page (Services: Intrusion Detection: Administration: Alerts) navigation items at the bottom are not beeing updated correctly or behave correctly.

**To Reproduce**
1. Go to "Services: Intrusion Detection: Administration: Alerts"
2. Select "500" (same for other values) for max visible entries per page (i have 512 entries)
3. Click on the query button at the top right to update the results (see screenshot)

Bug 1: Navigation widget at the bottom left: The mouse cursor is missing the "clickable" icon indicator on hover (Firefox + Chrome)

Bug 2: Navigation widget at the bottom left: Click on ">>" button: It wont jump to the last page

Bug 3: While changing the max visible entries per page the navigation widget (available page numbers) and the info text ("Showing 1 to 7 of 512 entries") is not beeing update correctly

**Screenshots**
![opnsense-bug](https://user-images.githubusercontent.com/38508611/79863861-c2a52980-83d8-11ea-97c4-4ed4d9cc2f0c.PNG)

**Environment**
OPNsense 20.1.4 (amd64, OpenSSL).

**Comment by AdSchellevis** [comment]
duplicate https://github.com/opnsense/core/issues/756 ?

**Comment by bewue** [comment]
yes probably a duplicate, at least bug 2 and 3.

**Comment by AdSchellevis** [comment]
explanation why this can't be solved within the boundaries we have can be found in the other ticket.

**Comment by myradon** [comment]
@AdSchellevis It's probably a technical constraint right. From a user perspective it's odd the system shows a control which actually is incorrect. Can you save the pagination settings? I don't like I have set it EVERY time I visit this page. First time wrong, future probably right. Or render everything client-side..

**Comment by AdSchellevis** [comment]
@myradon yes, you have to read the whole file to know its size, which would lead to sloppy user response.  In most components we save the number of entries selected in the browser data, if that doesn't work here,  feel free to open a ticket (using our template) and file a feature request.

**Comment by myradon** [comment]
The feature request, which is UX related, best approach is to be based on feedback/input more users.

 Many logs with pagination are not correct. Look at the Unbound screendump below. The system "State" is showing the entries 1 to 20 of 21. At least that is what the text says. What happens when you select the next page the total just increases. It provides the user false information and doesn't make sense.

<img width="692" alt="Screenshot 2020-05-19 at 20 35 51" src="https://user-images.githubusercontent.com/856503/82365369-dad88a80-9a10-11ea-93b5-fc6760e7aa06.png">

Suricata the same;
<img width="1240" alt="Screenshot 2020-05-19 at 20 36 44" src="https://user-images.githubusercontent.com/856503/82365742-5cc8b380-9a11-11ea-8fc5-f31156074295.png">
<img width="1243" alt="Screenshot 2020-05-19 at 20 36 55" src="https://user-images.githubusercontent.com/856503/82365750-60f4d100-9a11-11ea-94de-041ef4704306.png">
<img width="723" alt="Screenshot 2020-05-19 at 20 36 22" src="https://user-images.githubusercontent.com/856503/82365759-63efc180-9a11-11ea-9309-0f445bacdd88.png">

No offense to al the hard work from you guys, but pagination really can have an improvement.  
If you want I can help you guys out with UX/ Interaction Design related stuff because it's my profession.

**Comment by AdSchellevis** [comment]
@myradon feel free to create a pull request, as far as I can think of this can't be solved without parsing the whole file to count line endings (which will kill performance) or remove/hide the buttons/pagination.  Most of the logs use a single template and backend handling, so if one can come up with a sensible solution, it would be easy to make sure all are handled equally. 

No offence taken, but the UX design part only makes sense if it can operate within the technical boundaries which exists. (we don't know the number of rows in a file and can't guess them when knowing its size).

**Comment by myradon** [comment]
All roads leads to Rome. How come you don't know the amount of entries _when_ user selects a link to show some log file? How about also storing a counter? I don't know if that fixes the root problem. How many entries can/do an OPNsense firewalls run in the wild?

**Comment by AdSchellevis** [comment]
we're circling back, log files usually don't come with row counters. When designing database applications, this question is usually pretty simple (add an index, request a row count), when dealing with flat files things are very different. 

A lot of these files can grow big, sometimes very big and change while being viewed. So a better solution which makes it more obvious what's going on would be highly appreciated, changing the technical constraints is a no go area when impacting performance too much.

**Comment by myradon** [comment]
We are looking at it from 2 different perspectives. I get it a sluuugggish system will piss people off and make your work miserable when you use OPN in a business setting. 

Are you saying GUI shows flat text logfiles? OPNsense reads "set amount by user/default" from a logfile and serve in the GUI? So GUI is more like a "shift register"? Otherwise you have to read the entire file and then cut into chunks. Is that what you are saying?

**Comment by AdSchellevis** [comment]
@myradon I'll gladly provide you the pointers so you can come to your own conclusions, unfortunately I don't have enough time to explain the architecture and design of OPNsense in this ticket (best check our docs https://docs.opnsense.org/development/architecture.html).

https://github.com/opnsense/core/blob/e690ff6fec3de90949cae42c7620ae6ec6b8beb0/src/opnsense/mvc/app/controllers/OPNsense/IDS/Api/ServiceController.php#L171-L209

configd configuration:
https://github.com/opnsense/core/blob/e690ff6fec3de90949cae42c7620ae6ec6b8beb0/src/opnsense/service/conf/actions.d/actions_ids.conf#L37-L41

script parsing the log:
https://github.com/opnsense/core/blob/master/src/opnsense/scripts/suricata/queryAlertLog.py

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
