### ISSUE TITLE
Please add sha-256 to dhcp key configuration

### ISSUE THREAD

**Issue by stasiakk** [opnsense/core#4136]
https://github.com/opnsense/core/blob/6c91d7f87a1c7f14ae29e1889fa2936557fd6527/src/www/services_dhcp.php#L924

please add: "hmac-sha256" to algotitm list (Its standard rndc-key algoritm in BIND plugin):

-- foreach (array("hmac-md5", "hmac-sha512") as $algorithm):
++ foreach (array("hmac-md5", "hmac-sha256", "hmac-sha512") as $algorithm) :

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by elforesto** [comment]
Bumping this as I cannot configure dynamic DNS updates from DHCPv4 without this change.

**Comment by GaiusJarin** [comment]
I did get this to work by adding the algorithm to the services_dhcp.php file, fixing capitalization errors and adding "allow-update rndc-key" in the named.conf template, and updating ownership of /usr/local/opnsense/etc/namedb/master and the files with in it.  I'm not saying necessarily this is the right way to do this, but I was able to make it work.  I would encourage the package be reviewed by someone more versed than myself.  Would it be possible to reopen this issue or does a new one need submitted?

**Comment by AdSchellevis** [comment]
@prgrmdrk better open a new issue if you have plans for improvements, this issue was marked "incomplete" for good reasons, which doesn't mean there isn't room to add the option. When there's a relation with the bind plugin, it will be imperative to figure out how the two systems should cooperate (example proposals either in a PR or step by step todo list will probably help).

**Comment by hairlesshobo** [comment]
Is it possible that there are two different pieces to this? I am here because I also need hmac-sha256, but it has nothing to do with the bind plugin. My network runs two instances of powerdns on separate systems and this is the algorithm that I need for pushing dns updates to my dns servers. I am looking to jump ship from pf to OPNsense and this is one piece that is missing. I would be happy to create a PR just for adding the option to the front end list without any changes necessary to the bind plugin.

Guidance here would be greatly appreciated. I will plan to open a new issue but first I want to make sure it's appropriate to consider this as two separate issues.
