### ISSUE TITLE
Typo in Copyright header

### ISSUE THREAD

**Issue by x-jokay** [opnsense/core#4139]
In multiple files, there is a typo in the copyright header for **AS IS**.

```sh
...
THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES
...
```

**Comment by marjohn56** [comment]
What's wrong with that?

**Comment by marjohn56** [comment]
https://en.wikipedia.org/wiki/MIT_License

**Comment by x-jokay** [comment]
@marjohn56 What about "AS IS" vs ``AS IS''.

**Comment by AdSchellevis** [comment]
I'm pretty sure we have better things todo than looking at the type of quoting used in the sentence... which is likely only intended to emphrase the wording and is used in a lot of BSD licences.

**Comment by x-jokay** [comment]
@AdSchellevis is this really your sense of quality? A quick find and replace seems too much to ask? I'm willing to do the `PR` to not affect `your better things todo` if you are ok with it?

**Comment by fichtner** [comment]
Please don't be silly. This is older typewriter style.

**Comment by AdSchellevis** [comment]
I'm just saying that it's highly likely intentional, please search other BSD licenses (for example in FreeBSD and OpenBSD) before concluding that there's anything worth fixing. 

Changing large portions of code mainly to replace a quote seems senseless and counter productive, since changes are that they lead to merge conflicts and lots of noise when handling releases. 

So, no, I'm currently not really interested in a PR for these changes.
