### ISSUE TITLE
Update 20.1.7 to 20.1.8 breaks Status Overview in IPsec

### ISSUE THREAD

**Issue by mimugmail** [opnsense/core#4189]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
I just did an upgrade to 20.1.8 on my test machine cause of this report:
https://forum.opnsense.org/index.php?topic=17912.msg81304#msg81304

Seems this is true, after update the Status Overview page is empty:

![image](https://user-images.githubusercontent.com/20438689/86377825-21183f00-bc89-11ea-81d9-f04e6a7c7799.png)

Reverting to 20.1.7 does not work, I got this in configd.log when refreshing the page:

`Jul  2 18:38:05 OPNsense configd.py: [2704c3dc-254b-4a86-b107-1cb6fd0d6fd2] Script action failed with Command '/usr/local/opnsense/scripts/ipsec/list_status.py' returned non-zero exit status 1. at Traceback (most recent call last):   File "/usr/local/opnsense/service/modules/processhandler.py", line 484, in execute     stdout=output_stream, stderr=error_stream)   File "/usr/local/lib/python3.7/subprocess.py", line 363, in check_call     raise CalledProcessError(retcode, cmd) subprocess.CalledProcessError: Command '/usr/local/opnsense/scripts/ipsec/list_status.py' returned non-zero exit status 1.
`

**Comment by AdSchellevis** [comment]
the output of `/usr/local/opnsense/scripts/ipsec/list_status.py` please :)

**Comment by mimugmail** [comment]
```
root@OPNsense:~ # /usr/local/opnsense/scripts/ipsec/list_status.py
Traceback (most recent call last):
  File "/usr/local/opnsense/scripts/ipsec/list_status.py", line 90, in <module>
    print (ujson.dumps(result))
TypeError: reject_bytes is on and 'pre-shared key' is bytes

```

**Comment by AdSchellevis** [comment]
yeay, new options.... https://github.com/ultrajson/ultrajson/pull/266
https://github.com/opnsense/core/commit/30a9195437c00085fed7b5c3989b4c3bfef9e34c should fix it.

**Comment by mimugmail** [comment]
Sorry, added my comment in commit and not here

**Comment by fichtner** [comment]
Hotfix is out :)

**Comment by Teemoe86** [comment]
Since some weeks,the status overview of ipsec is blanc. I have two opnsense installed. One without the bug, the second have the issue.

OPNsense 22.1.10-amd64
FreeBSD 13.0-STABLE
OpenSSL 1.1.1q 5 Jul 2022

Script action failed with Command '/usr/local/opnsense/scripts/ipsec/list_status.py ' returned non-zero exit status 1. at Traceback (most recent call last): File "/usr/local/opnsense/service/modules/processhandler.py", line 482, in execute subprocess.check_call(script_command, env=self.config_environment, shell=True, File "/usr/local/lib/python3.9/subprocess.py", line 373, in check_call raise CalledProcessError(retcode, cmd) subprocess.CalledProcessError: Command '/usr/local/opnsense/scripts/ipsec/list_status.py ' returned non-zero exit status 1.

# /usr/local/opnsense/scripts/ipsec/list_status.py
Traceback (most recent call last):
  File "/usr/local/opnsense/scripts/ipsec/list_status.py", line 35, in <module>
    import vici
ImportError: bad magic number in 'vici': b'\x03\xf3\r\n'

**Comment by fichtner** [comment]
I wouldn't say weeks, but: https://forum.opnsense.org/index.php?topic=29356.msg141812#msg141812
