### ISSUE TITLE
Recent chrome bypassing unbound/DNS overrides due to DNSSEC

### ISSUE THREAD

**Issue by sesquipedality** [opnsense/core#4206]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[-] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

Yes

[-] I have searched the existing issues and I'm convinced that mine is new.

Yes

**Describe the bug**
A clear and concise description of what the bug is, including last known working version (if any).

In mid May Chrome turned on a new security option to resolve DNS queries using DNSSEC by default.  This is, of course, a good thing.   However, as a result, Chrome seems to be bypassing local unbound DNS resolution and going direct to the internet, which of course breaks unbound overrides.

I would expect that this would be solvable by turning on DNSSEC support in unbound, but that does not appear to have resolved the issue for me. 

I've tried to confirm that DNSSEC is actually working on the OPNSense router.  Accessing https://1.1.1.1/help witht the unbound DNS DNSSEC option ticked and Firefox configured to use DNSSEC via the router address reports

```
Using DNS over HTTPS (DoH) | No
Using DNS over TLS (DoT) | No
Using DNS over WARP | No
AS Name | Google
AS Number | 15169
Cloudflare Data Center | MAN
```

(I get the same result in Chrome, but I did want to remove any chrome weirdness from the equation)

As a result I am not sure whether or not the problem is because DNSSEC in unbound is not working as intended.

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

Using a recent version of chrome (83.0.4103.116 (Official Build) (64-bit) (cohort: Stable) is what I used) on a machine using OpnSense as a DNS server

Create an override in unbound - for testing purposes, alias any well known website to a different one.

Attempt to access the original web page in chrome.  With Chrome DNSSEC support turned on (default) the web site will resolve to the original address,  With DNSSEC support off, it will resolve to the redirected address.

Turning DNSSEC support on or off in the Unbound DNS settings on the router does not appear to change this.

**Expected behavior**

Overrides should ideally work in modern versions of chrome without the need for any user intervention or configuration changes on the OpnSense router.

**Screenshots**

**Relevant log files**
If applicable, information from log files supporting your claim.

**Additional context**

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 20.1.8_1-amd64
FreeBSD 11.2-RELEASE-p20-HBSD
OpenSSL 1.1.1g 21 Apr 2020
Client is Chrome 83.0.4103.116 on Windows 10 19.10 running on a Threadripper 1920x.

Thank you.

**Comment by TheNec** [comment]
Hello,

I think you are mixing up some things here.

First of all there is a DNSSEC (DNS Security Extensions) validator addon for chrome and as I searched for it I found no evidence that this is used in the Chrome base (same seems for Firefox). What I found and already knew is that DoH (DNS over HTTPS) was put into Chrom[e/ium] last year and defaulted it in may this year.

> https://duo.com/decipher/google-makes-dns-over-https-default-in-chrome

These technologies don't have anything to do with each other. DNSSEC is pretty useful because it checks the signatures of signed DNS-Zones. Usually only the last DNS-Server that is queried in your network does this for querying upstream DNS-Servers if you don't have DNS-Zones transferred to your DNS-Servers or a business grade Intranet-DNS which you would know and even for the intranet DNSSEC would be a questianable choice, DoH is a technique that encrypts DNS-Traffic which is imho pretty useless because the endpoint is visible anyways. 

Solution for you: Just deactivate DoH in your browsers =)

Additional Information:

If you activate DNSSEC on Unbound (via OPNsense) this just means that unbound checks the signatures of Upstream-DNS-Servers as I wrote above and  DNSSEC would never alter the DNS-Chain alone!

Your config:
> Browser -\> Cloudflare DoH =\> Nothing you do with your DNS-Servers will change anything

'Normal' DNS config:
> Browser -\> Operating System's DNS-Client -\> Internal DNS Server (1 -\> Internal DNS Server 2...) -\> External DNS Servers (...)

So imho the ticket could be closed because it has nothing to do with OPNsense.

Best regards!
