### ISSUE TITLE
Unbound: "Domain override" leads to an invalid configuration when a "Custom Options" is specified

### ISSUE THREAD

**Issue by xgcssch** [opnsense/core#4208]
[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Description**
When there is a value specified in the "Custom Options" field of the unbound "General" settings page (e. g. `private-domain: xip.io`) unbound will not start in case there is also a domain override specified. The configuration file in this situation is not valid.

**Steps to reproduce**
1. Fresh installation with minimal configuration (any installation should do)
2. Goto "Services"->"Unbound DNS"->"General"
3. Click on "Show advanced options" on the "Advanced" Setting Entry
4. Enter `private-domain: xip.io` in the "Custom options" field
5. Click on "Save" an afterwards on "Apply changes" -> Note that the "Run icon" on the upper right corner is still green
6. Goto "Services"->"Unbound DNS"->"Overrides"
7. Click on the plus sign near "Domain overrides", and add a sample entry. (e. g. Domain=my.test.it, ip address=1.2.3.4)
8. Click on "Save" an afterwards on "Apply changes" -> Note that the "Run icon" on the upper right corner is now red, as the configuration is now invalid
9. Either removing the override or the additional makes the configuration usable again

**Additional information**
- In the logfile is no hint that the configuration is invalid
- In a shell `unbound-checkconf /var/unbound/unbound.conf` will report a syntax error

**Expected behavior**
The configuration should be usable even when a domain override and an additional option is given

**Environment**
OPNsense 20.1-amd64
FreeBSD 11.2-RELEASE-p16-HBSD
OpenSSL 1.1.1d 10 Sep 2019

**Comment by mimugmail** [comment]
That's the reason the custom field should be removed, as it leads to user generated errors. 
Best way would be to no use custom field and add a feature request for the things you are missing.

**Comment by xgcssch** [comment]
Theoratical i totally agree!
This is the still the best option.

But ....
adding a UI option for every (useful) option of an upstream service implementation is much work to do. 
And if you restrict a service like unbound to only the UI supported options it's a pitty to remove special usecases from OPNSense.
There should be an extension point for such use-case. Maybe only accessible by editing an specific file?

**Comment by AdSchellevis** [comment]
The extension point should be in the component, in most cases by including a configuration directory which the service in question includes (which isn't validated, can not be edited from the ui and is the responsibility of the administrator who added the file)
Eventually, all custom edits will vanish, which is why we added a note to the ones still there.

**Comment by xgcssch** [comment]
With 
> Eventually, all custom edits will vanish, which is why we added a note to the ones still there.

you mean the UI hint `This option will be removed in the future due...` and not the administrator supplied configuration file?

As i said: i agree that the removal of the "Custom options" UI field is a good idea.
But existing administrator supplied configuration files should not vanish!

And it would be a good idea, to document this extension point.

**Comment by AdSchellevis** [comment]
It's definitely a good idea to document things, contributions to https://github.com/opnsense/docs are more than welcome. 

In case of unbound, the extension point is used in the unbound-plus plugin (https://github.com/opnsense/plugins/blob/7e61220fbe8acd58f6282e57881e590a331ec93f/dns/unbound-plus/src/opnsense/scripts/OPNsense/Unboundplus/dnsbl.sh), which will be merged to core in 20.7.

https://github.com/opnsense/core/blob/144272ffbb78a5ede438ee9fc5651c6f32f9443b/src/etc/inc/plugins.inc.d/unbound.inc#L353-L354


Unfortunately extension points may vary per service, since it really depends on what it supports (some have clear "conf" directories, some can only be merged from the template system).

**Comment by xgcssch** [comment]
While writing the documentation i realized that if the `Custom options` is
```
server:
private-domain: xip.io
```
everything is fine,
The problem is, that the clause in which this options are included in the configuration cannot be predicted and differs if an domain override is specified or not.
Adding a domain override leaves the configuration in the `forward-zone` clause.

So the solution should be, that the final line in the generated domainoverrides.conf is always
`server:
`
