### ISSUE TITLE
OpenVPN: False gateway address set when topology "subnet" is used

### ISSUE THREAD

**Issue by vlcty** [opnsense/core#4268]
**Describe the bug**
One VPN provider uses net30 as addressing method. In the logs the tunnel address is properly set:

```
openvpn[64918]: /usr/local/etc/inc/plugins.inc.d/openvpn/ovpn-linkup ovpnc5 1500 1557 10.92.0.42 10.92.0.41 init
openvpn[64918]: /sbin/ifconfig ovpnc5 10.92.0.42 10.92.0.41 mtu 1500 netmask 255.255.255.255 up
```

After starting the tunnel the local tunnel address is set to `10.92.0.42` and the automatically generated gateway is set to `10.92.0.41`. 

Another VPN provider I use uses subnet as addressing method with a /24 mask. Here are the logs:

```
openvpn[92855]: /usr/local/etc/inc/plugins.inc.d/openvpn/ovpn-linkup ovpnc3 1500 1557 10.5.81.242 255.255.255.0 init
openvpn[92855]: /sbin/ifconfig ovpnc3 10.5.81.242 10.5.81.1 mtu 1500 netmask 255.255.255.0 up
```

In this case 255.255.255.0 is sent to the ovpn-linkup script. The result: The tunnel local address (`10.5.81.242`) is written to `/tmp/ovpnc3_router` and set as gateway address. The rigth IP would be `10.5.81.1`.

While debugging I found this in the OpenVPN reference manual:

```
Note: Using –topology subnet changes the interpretation of the arguments of –ifconfig to mean “address netmask”, no longer “local remote”.
```

**Environment**

OPNsense 20.7-amd64   
FreeBSD 12.1-RELEASE-p7-HBSD   
OpenSSL 1.1.1g 21 Apr 2020

**Comment by AdSchellevis** [comment]
I expect it would just work if it didn't create a /tmp/xxx_router file, since it probably doesn't need the address to send the traffic to the correct place (should be easy to test). 

https://github.com/opnsense/core/blob/11017fa4ab31d33bcbf6678fd7395762e712d22c/src/opnsense/mvc/app/library/OPNsense/Routing/Gateways.php#L247-L255

Currently I don't have time to test the different options, there already is a ticket about the same topic if I'm not mistaken (https://github.com/opnsense/core/pull/4134). 
But at a first glance I think we're overcomplicating things by trying to find the endpoint (the new "Dynamic gateway policy" knob on the interface without the gateway file likely do the same). 

To help bring this further we would need someone configuring the different options and document them in a ticket what happens if` /usr/local/etc/inc/plugins.inc.d/openvpn/ovpn-linkup`  would `exit 0` before doing anything and there  would be no router file on disk.

**Comment by vlcty** [comment]
I checked the Dynamic gateway policy checkbox and saved it. Does not change anything. Additionally I added an exit 0 at the top of `ovpn-linkup` and it did not do anything either.

My proposed solution:
If the gw parameter to `ovpn-linkup` starts with 255 then we can be sure it's a netmask, so taking the first address from that range is the gateway. Otherwise use the passed gateway. Same applies for IPv6. I'd patch it into OPNsense and open a pull request if wanted.

**Comment by AdSchellevis** [comment]
@vlcty can you show your routing table (for the related ovpnc routes) after ovpn-linkup has the `exit 0` and there's no router file on disk?

**Comment by vlcty** [comment]
I think I've collected the required screenshots.

![Bildschirmfoto 2020-08-25 um 18 59 46](https://user-images.githubusercontent.com/5420564/91205203-7743b480-e705-11ea-8f59-3da563d6c495.png)

![Bildschirmfoto 2020-08-25 um 19 00 03](https://user-images.githubusercontent.com/5420564/91205211-7874e180-e705-11ea-99b5-b3f796f63705.png)

![Bildschirmfoto 2020-08-25 um 19 00 37](https://user-images.githubusercontent.com/5420564/91205213-790d7800-e705-11ea-840e-ae50b5c43241.png)

![Bildschirmfoto 2020-08-25 um 19 01 10](https://user-images.githubusercontent.com/5420564/91205214-79a60e80-e705-11ea-8be2-074acd065753.png)

Note: There is no ovpnc* file. Only the file from the running server.
![Bildschirmfoto 2020-08-25 um 19 01 29](https://user-images.githubusercontent.com/5420564/91205216-7a3ea500-e705-11ea-877c-0e8d49b3cd61.png)

![Bildschirmfoto 2020-08-25 um 19 01 44](https://user-images.githubusercontent.com/5420564/91205217-7a3ea500-e705-11ea-8d78-e540e12b3644.png)

![Bildschirmfoto 2020-08-25 um 19 02 47](https://user-images.githubusercontent.com/5420564/91205300-9c382780-e705-11ea-84a4-e5b3b8a14768.png)

**Comment by vlcty** [comment]
After the `exit 0` and no router file the VPN provider with the net30 addressing is broken now.

**Comment by AdSchellevis** [comment]
@vlcty ok, if I read your feedback correctly, the /24 uses the correct gateway automatically now, but the /30 which worked doesn't work at all now (service failed to start)?  If that's the case, it would be interesting to know why the /30 died, since the gateway shouldn't be a requirement for the tunnel itself.

**Comment by vlcty** [comment]
The /30 network method works out of the box (without any mods to files)  
The /24 network does not pick the right gateway

The tunnels always go up, but the gateway addresses are not set correctly. I need the gateways for source based routing rules.

I've had a look at the passed variables from the VPN provider which uses the /24 addressing.

![Bildschirmfoto 2020-08-25 um 19 54 05](https://user-images.githubusercontent.com/5420564/91210135-099b8680-e70d-11ea-94d0-88745187cc47.png)
![Bildschirmfoto 2020-08-25 um 19 54 11](https://user-images.githubusercontent.com/5420564/91210146-0e603a80-e70d-11ea-9305-11e4cb96a771.png)

Looks like the gateway is not passed in a variable. But I know why it use the local address also as gateway: Because it's the last statement in the if.

Printenv in the prints the following:

```
xormask_1=
daemon_start_time=1598378310
local_1=10.20.0.2
daemon_pid=1901
trusted_ip=192.145.127.210
untrusted_port=150
X509_0_ST=Zug
tun_mtu=1500
X509_0_CN=Server_milan.perfect-privacy.com
X509_0_emailAddress=admin@perfect-privacy.com
remote_1=192.145.127.210
proto_1=udp
X509_1_emailAddress=admin@perfect-privacy.com
tls_id_0=C=CH, ST=Zug, O=Perfect Privacy, CN=Server_milan.perfect-privacy.com, emailAddress=admin@perfect-privacy.com
tls_id_1=C=CH, ST=Zug, L=Zug, O=Perfect Privacy, CN=Perfect Privacy, emailAddress=admin@perfect-privacy.com
untrusted_ip=192.145.127.210
ifconfig_ipv6_local=fdbf:1d37:bbe0:0:85:9:0:f2
daemon=1
tls_serial_hex_0=ea:e7:b8:76:5c:a1:9c:97
trusted_port=150
tls_serial_hex_1=fa:11:b5:c4:aa:69:af:69
dev_type=tun
X509_1_ST=Zug
X509_1_CN=Perfect Privacy
script_context=init
tls_digest_sha256_0=1f:c3:58:33:e9:01:ba:a6:db:5a:b5:86:01:b2:c5:41:8f:9a:09:57:0c:d5:5f:78:10:59:34:9c:b5:7d:77:6f
tls_serial_0=16926700542995045527
PWD=/
xormasklen_1=0
daemon_log_redirect=0
tls_digest_sha256_1=ff:b0:f0:e3:1c:fe:ef:b6:e7:6d:28:3e:25:3e:ad:81:cb:3a:ee:25:f0:ef:0b:55:a9:c9:a0:28:bd:d2:bc:f0
tls_serial_1=18019383440363335529
ifconfig_local=10.5.81.242
local_port_1=0
dev=ovpnc3
link_mtu=1557
remote_port_1=150
X509_0_C=CH
tls_digest_0=e5:db:d0:15:5d:74:dc:e2:c5:68:7f:70:44:62:af:46:90:49:9f:f7
tls_digest_1=31:4c:e8:a6:8c:30:18:bf:23:35:cf:75:1e:3c:52:5e:fd:4b:e8:f3
script_type=up
X509_1_C=CH
ifconfig_broadcast=10.5.81.255
ifconfig_netmask=255.255.255.0
ifconfig_ipv6_netbits=112
ifconfig_ipv6_remote=fdbf:1d37:bbe0:0:85:9:0:1
xormethod_1=0
config=/var/etc/openvpn/client3.conf
X509_0_O=Perfect Privacy
X509_1_L=Zug
verb=1
common_name=Server_milan.perfect-privacy.com
X509_1_O=Perfect Privacy
```

The corrent gateway is not passed.

**Comment by vlcty** [comment]
My suggestion would be: If ifconfig_remote is not passed -> calculate the first address based on the subnet mask passed.

**Comment by AdSchellevis** [comment]
I don't think you need to calculate anything, since the proper gateway (105.87.1) seems to be set when not writing the _router file on the /24 entry.

**Comment by vlcty** [comment]
If you don't write any router file both addressing methods break.

**Comment by vlcty** [comment]
With "break" I mean the tunnel go up, but the dynamic gateway addresses are not set. This breaks source based routing. It may work with destination based routing. Did not try that.

**Comment by AdSchellevis** [comment]
Ok, I was already writing a response that this doesn't make sense, the source based routing is indeed the culprit in this case, you can't send the packet to the next hop without knowing it. Can you validate normal destination based routing first? 

Trying to calculate the address is likely prone to errors, if the address is predictable, a combination might work in this case, don't create a _router file if we don't really know it (the subnet response) and add one statically in the gateway configuration.

**Comment by vlcty** [comment]
OpenVPN server always assigns the first address. So the error factor should be quite low. I'll try destination based routing tomorrow.

**Comment by AdSchellevis** [comment]
If it's documented behaviour, I won't mind calculating the address, but only if we can point to the intended behaviour in OpenVPN. Issues in these areas are usually difficult to trap if we use our own assumptions, so I'm a bit cautious in that area. 

There already was a similar issue (https://github.com/opnsense/core/issues/4133)  about this behaviour with a PR (https://github.com/opnsense/core/pull/4134) attached, the problem is the amount of extra complexity added and difficultly to track issues if something goes wrong underway. I'm also not sure why you would like to keep the other parameters such as $ifconfig_local as an additional fail safe if you can always extract the endpoint from the tunnel. 

The current construction probably doesn't really win a beauty contest, but in order to known which value to choose we should probably know the valid options for the different usage scenarios.

**Comment by vlcty** [comment]
Okay so I was wrong with the first address. This is just the default OpenVPN server behaviour of OPNsense. Now I don't know how to go on with this.

**Comment by vlcty** [comment]
I've played with it a bit again. OpenVPN won't pass `ifconfig_remote` if topology subnet is used. However it's more or less default that the first available address is used. Thankfully for IPv6 it's always passed. My "solution" is the following:

I've added a new case to the if in `/usr/local/etc/inc/plugins.inc.d/openvpn/ovpn-linkup`

```
#!/usr/local/bin/bash

# let the configuration system know that the ip has changed.
# /usr/local/opnsense/service/configd_ctl.py interface newip $interface

if [ -n "${route_vpn_gateway}" ]; then
	/bin/echo ${route_vpn_gateway} > /tmp/$1_router
elif [ -n "${ifconfig_remote}" ]; then
	/bin/echo ${ifconfig_remote} > /tmp/$1_router
elif [ -z "${ifconfig_remote}" ]; then
	IFS=. read ip1 ip2 ip3 ip4 <<< "${ifconfig_local}"
	/bin/echo "${ip1}.${ip2}.${ip3}.1" > /tmp/$1_router
elif [ -n "${ifconfig_local}" ]; then
```

That's a dirty hack but it works for me. I think I'll close this issue and hope that IPv4 dies soon.
