### ISSUE TITLE
OpenVPN Split-DNS feature request

### ISSUE THREAD

**Issue by derek-shnosh** [opnsense/core#4313]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

- [x] I have searched the existing issues and I'm convinced that mine is new.

**Is your feature request related to a problem? Please describe.**

Using OpenVPN in OPNsense 20.1.9-1 (updating over weekend), while connected via VPN all DNS queries go through VPN.

**Describe the solution you'd like**

I would like to be able to specify the *default domain*, and maybe a *domain list*, so any queries that match these will go to the VPN provided DNS server; all other queries will use the client's local resolver (statically assigned or obtained via DHCP).

**Describe alternatives you've considered**

I've looked into unbound (very briefly), but would like to see a split-dns feature to accommodate this request versus adding configuration complexity for different scenarios/use-cases.

**Additional context**

I did see @ssbarnea's issue (#3506) and share his sentiment, but see that his issue was closed due to formatting of the issue submission; so I'm hoping I ticked all the marks necessary.

Currently I'm only runing OPNsense at home, but have *potential* other use cases for SMB clients.

My familiarity with Split-DNS is with our enterprise clients [using Cisco AnyConnect with SSL client](https://www.cisco.com/c/en/us/support/docs/security/anyconnect-secure-mobility-client/116016-technote-AnyConnect-00.html#anc1); understandably a different product, but I'm hoping that this is something that OPNsense can tackle as well.

**Comment by muchahagrande** [comment]
Hi Darek, I actually do this using domain override on unbound.

**Comment by derek-shnosh** [comment]
@muchahagrande doesn't that require your request to go through the tunnel to the OPNsense firewall? How is the client's *local* resolver used when Unbound thinks it should send the request back?

True split-DNS should **only** send DNS requests for the domains in the **specified domain list**.

I don't want DNS requests to have to traverse the tunnel twice to accomplish this; please clarify your solution if I'm misunderstanding.

**Comment by AdSchellevis** [comment]
I don't think split-dns works similar in the OpenVPN world as it does in the IPsec world, where split dns is part of the formal specification (https://tools.ietf.org/html/rfc8598) and is configured on the clients end automatically. 

Some clients such as Viscosity might offer support to control the local client (https://www.sparklabs.com/support/kb/article/configuring-dns-and-wins-settings/#split-dns), but I don't think there are other configuration items we need/can set on our end. 

In order to progress this using something other than unbound/bind/... or specific settings in a client, we do need to know what to configure where and for which reasons.

This question has been asked before (https://github.com/opnsense/core/issues/3506), but back then we didn't look into it ourselves as far as I know.

The solution combining unbound is what's most commonly used as far as I could find, but is indeed a different kind of setup.

**Comment by muchahagrande** [comment]
You are right @derek-shnosh, I misunderstood your case. Sorry

**Comment by derek-shnosh** [comment]
@muchahagrande - no worries here. 👍

@AdSchellevis - reading through your response triggered some clarity for me that should have otherwise been obvious.

Cisco is able to accomplish this with AnyConnect because they provide the client and server/concentrator framework, allowing them to pass these configuration variables to the client; which then runs on the system managing the DNS queries locally, only sending them for defined domains through the VPN as needed.

I don't see how this is an issue that can be addressed since OPNsense is offering a baked in OpenVPN server solution (to which I'm thankful for) without any *linked* client. That being said, this issue can likely be closed out... but unsure if proper etiquette, so I'll let you guys decide when to do so.

**Comment by AdSchellevis** [comment]
I'm afraid that's just the consequence of not being able to influence the client, in a managed environment one can probably come up with a solution (outside the scope of OPNsense in my opinion). 

I'll close the issue, if other insights in the future provide workable alternatives we can always reopen.
