### ISSUE TITLE
unbound: remove custom options setting et al

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#4327]
Unbound can already live without the custom options, but the chroot makes it a little difficult to inject persistent files. We need another inclusion dir where we stage templates (and other things) to be copied over into the chroot on config changes.

Somewhat related to what @mimugmail is struggling with for unbound-plus.

Also of note are missing features around DOT:

```
qname-minimisation: yes
qname-minimisation-strict: yes

forward-zone:
name: "."
forward-tls-upstream: yes
forward-addr: 5.1.66.255@853#dot.ffmuc.net
forward-addr: 185.95.218.42@853#dns.digitale-gesellschaft.ch
forward-addr: 5.9.164.112@853#dns3.digitalcourage.de
```

Get rid of the apply now that we have a cache retain option:

    # git grep subsystem_dirty..unbound

**Comment by AdSchellevis** [comment]
@fichtner wouldn't the template engine already take care of that https://github.com/opnsense/core/blob/master/src/etc/inc/plugins.inc.d/unbound.inc#L443 (https://docs.opnsense.org/manual/unbound.html#advanced-configurations), although reading the docs again, If one would add a submodule in the Unbound template dir it would be added automatically, which is what "plus" also did if I'm not mistaken.

**Comment by fichtner** [comment]
Yes and no, part of the issue is https://github.com/opnsense/core/blob/master/src/etc/inc/plugins.inc.d/unbound.inc#L413 returning too early (easy fix in general) and also not having a sufficiently persistent directory to avoid the clearing of /var/unbound on boot where unbound-plus requires refetching which can fail). so the templating needs a staging area in this case, preferably outside of /var -- not entirely sure yet but a good goal for 21.1 and the advanced options removal

**Comment by fichtner** [comment]
So @AdSchellevis also mentioned that we need a non /var MFS staging area for blacklist itself with the best course of action making a whole persistent staging dir for unbound configurations so that reboots do not have bootstrap issues.

**Comment by shonjir** [comment]
Not sure if this is the right place to comment on this, if not, my apologies in advance.

It seems to me that removing the advanced configuration capability doesn't really solve any issues but definitely makes OPNsense less flexible than it is.

I currently use advanced configuration to deploy support for DNS over TCP with server name validation as current DoT support doesn't validate TLS server name allowing MiTM attacks, disabling DNS round-robin responses as this interferes with reverse resolving primary vs alternate hostnames, adding custom SOA records for the local domain as this enables certain client functionality, adding custom SRV records for kerberos realm support, and adding custom PTR, SRV and TXT records for DNS Service Discovery support for my local domain.

Without advanced configuration I have no way of configuring OPNsense to handle my DNS needs and would be forced to use another DNS server (pihole or BIND) instead of unbound which is more than capable today.

**Comment by AdSchellevis** [comment]
@shonjir as mentioned in earlier posts, these types of options will disappear for security reasons, in most cases there are alternatives as described here https://docs.opnsense.org/manual/unbound.html#advanced-configurations in the case of unbound.

**Comment by fichtner** [comment]
Relevant docs changes https://github.com/opnsense/docs/commit/775d737c3da

**Comment by fichtner** [comment]
harden-below-nxdomain: yes is the default

**Comment by ciroiriarte** [comment]
> @shonjir as mentioned in earlier posts, these types of options will disappear for security reasons, in most cases there are alternatives as described here https://docs.opnsense.org/manual/unbound.html#advanced-configurations in the case of unbound.

Will any of those alternatives will be preserved/restored by the backup module/function?

**Comment by fichtner** [comment]
Features worth being backed up should have full GUI integration. That’s our only rule.
