### ISSUE TITLE
DNS Resolver - Unbound - Not able to resolve DHCP leases until it is saved

### ISSUE THREAD

**Issue by StopTrain** [opnsense/core#435]
So, this odd issue popped up where I was not able to resolve DHCP leases within the DNS Resolver.

What I found was an article speaking about how Unbound is not able to resolve new leases as it doesn't know about them until you 'save' the configuration again.

As a test, I logged into OPNsense, went to the DNS Resolver page, and submitted a save, even though no changes on my side had happened.

Bingo.. once it applied, active DHCP clients were now resolvable on my network.

**Comment by fichtner** [comment]
@StopTrain reported that not setting up IPv6 unbreaks unbound

**Comment by fichtner** [comment]
@StopTrain hey Matt, close this or investigate further?

**Comment by 8191** [comment]
Investigating a different issue with this feature I can now tell what's the reason for this one, I'd say:

The DHCP leases are mapped as static host overrides within unbound. The "magic" is done within [`etc/inc/unbound.inc:560-575`](https://github.com/opnsense/core/blob/master/src/etc/inc/unbound.inc#L560-L575), which (afaik) only get's called when applying changes in the DNS Resolver.
@fichtner Is there a mechanism which calls the config scripts regularly?

**Comment by fichtner** [comment]
There is quite a bot of complication going on. There is a daemon called dhcpleases, which knows the PID of the DNS daemon so the config can be reloaded using SIGHUP, but I don't know how the host file is regenerated other than probably doing it in the daemon itself, not sure if some code is missing since the GUI code was forked 9 months after the dhcpleases code disappeared...

https://github.com/opnsense/core/blob/master/src/etc/inc/system.inc#L465
https://github.com/opnsense/ports/blob/master/opnsense/dhcpleases/files/dhcpleases.c#L491

I've ran a test with Matt using the newer daemon's code but it was unsuccessful.

**Comment by fichtner** [comment]
Matt, @AdSchellevis has revorked this for the development version of 16.1.5. I've tested this, looked pretty good now. Can you retest when it's out?

**Comment by StopTrain** [comment]
I most certainly can.

**Comment by fichtner** [comment]
This is in since a while, I'd like to vote for close and worst case opening a new bug. The behaviour of the resolver seems to be better now and original behaviour may not apply. :)

**Comment by fichtner** [comment]
timeout
