### ISSUE TITLE
Unbound Whitelist doesnt work

### ISSUE THREAD

**Issue by timota** [opnsense/core#4362]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
Unbound DNS Whitelist functionality doesnt work. 
When adding domain to Whitelist in Unbound configuration - domain still not accessible and unbound returns 0.0.0.0. 
Also, whitelisted  domain should be removed from `dnsbl.conf` but it not removed.

**Expected behavior**
Whitelisted domains should return valid ips.

**Environment**

OPNsense 20.7.2-amd64FreeBSD 
12.1-RELEASE-p8-HBSD
OpenSSL 1.1.1g 21 Apr 2020
--

**Comment by the-wright-engineer** [comment]
I am also experiencing this issue as described.

```
OPNsense 20.7.3-amd64
FreeBSD 12.1-RELEASE-p10-HBSD
OpenSSL 1.1.1g 21 Apr 2020
```

**Comment by AdSchellevis** [comment]
I've rewritten the blacklist retrieval code (https://github.com/opnsense/core/commit/84ce802b16a03becab1fd955abb22b4ebb33405f, https://github.com/opnsense/core/commit/f16b67232c6000137f210eba8567a8abe46d9b1d, https://github.com/opnsense/core/commit/e5e9e92290cc432b8cb7a8cd42a5da5675830342) and wrote some documentation on how to use this feature (https://github.com/opnsense/docs/commit/3af24c7cecb4958ebae12d03dab7d51dacf2b5de). It's probably best to wait until this makes a release, since I've seen quite some issues with the feature as well, which made me decide to rewrite it. Maybe we pulled it a bit too soon into core.

**Comment by the-wright-engineer** [comment]
Thank you for your work on this. I'll be looking forward to the future release.

**Comment by dburkland** [comment]
Is this one any closer to getting included in a future release? Running into the same issue.

**Comment by gwjo** [comment]
> Is this one any closer to getting included in a future release? Running into the same issue.

@dburkland these changes are in 20.7.4 onwards

**Comment by dburkland** [comment]
I eventually got the config working with some persistence in the meantime. With that said looking forward to the 20.7.4.

Thanks!

Dan

**Comment by dburkland** [comment]
Thanks, I got it working eventually :)

Dan
