### ISSUE TITLE
unbound: add checkbox for creation of PTR-records to "Host Overrides"

### ISSUE THREAD

**Issue by Starkstromkonsument** [opnsense/core#4420]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Is your feature request related to a problem? Please describe.**
I'm using the haproxy on my opnsense for several services in my network. To accomplish this I need to add several additional subdomains as overrides. I don't want these to be created as PTR-records for my opnsense-machine though.

**Describe the solution you'd like**
 * Add a checkbox "create PTR record" to the "Edit entry" form for the Type A or AAAA
 * Add the same checkbox for each Aliases-row of this Type
 * Add a corresponding column to the "Host Overrides" table

**Describe alternatives you've considered**
Add a new type CNAME. This dos not allow to control which A or AAAA-record it should point to, in case there are multiple entries for that host though.

**Additional context**
PR  #3938 is related to this, but it is closed / not being worked on anymore. I do not opt for creating a new type (A or AAAA without PTR), because I want to be able to switch the creation of the PTR-records on/off on a per alias way.

**Comment by maciekb** [comment]
I strongly support that it should be possible to manually indicate whether a PTR record should be generated for a given override record. The problem is quite trivial, but annoying. Many web services rely on reverse name recognition. The first example that comes to mind is Zenarmor (Sensei), which presents inconsistent data in its reports in the current situation. Multiple PTR records for the same IP address cause the name to be retrieved randomly, causing the reports to show several hosts as the source despite the data coming from a single IP address.
In addition, I noticed that Unbound in OPNsense generates just as many IN A records as both PTR records for the local network gateway IP address. This is a problem if we have vlans, for example, and are trying to access the router by name. If the resolver gets an IP address in response from a vlan address that we don't have access to from the source network, then access is obviously not possible.
