### ISSUE TITLE
LDAP Server configuration - memberOf not returned

### ISSUE THREAD

**Issue by GeoCookie** [opnsense/core#4454]
Hi there,

I'm trying to get the memberOf attribute from my OpenLDAP server but I can't get it to work. I know this is something that has been asked many times, but I have not found any answer.

On the LDAP Server configuration, I have checked "Read Properties" and "Synchronize groups"
![image](https://user-images.githubusercontent.com/43962716/98804439-7c67f400-2416-11eb-9dd8-915e5ccb7aa6.png)

When I test a user, OPNSense retrieves all the attributes except memberOf
![image](https://user-images.githubusercontent.com/43962716/98804478-8ab61000-2416-11eb-9fbd-5d6e5ed7b2f5.png)

If I do a ldapsearch with this user, I can get the memberOf attribute but I have to specifically ask for it
![image](https://user-images.githubusercontent.com/43962716/98804685-bc2edb80-2416-11eb-9e66-c07687f1b846.png)

If I don't add "memberOf" to the query, LDAP will not return it. From what I understand, this is a normal behavior since it is an operational attribute.

Do you know how I can tell OPNSense to request this attribute? Or maybe I'm missing something else?

Edit :
I use the memberOf attribute to filter which accounts OPNSense can retrieve
![image](https://user-images.githubusercontent.com/43962716/98807188-93a8e080-241a-11eb-846c-3c2c8fd973bf.png)

It is working. OPNSense only see members of the group, not all users
![image](https://user-images.githubusercontent.com/43962716/98807283-b5a26300-241a-11eb-87b6-da0a32f86f81.png)

**Comment by djesionek** [comment]
Hi,

I do not see where and how this was resolved. 
Can any of you help me to understand since I have the exact same issue and adding extended query does not change what the tester shows below "This user is a member of these groups: " for me?

memberOf is still not requested by the query looking at my OpenLDAP logs and without sync of groups its not possible to use this feature properly as far as I can see.
