### ISSUE TITLE
Having ruleset description for IDS rulesets

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#453]
It would be handy to have descriptions for IDS rulesets on hover or similar.

**Comment by AdSchellevis** [comment]
Not sure what its going to be exactly, but very likely a link to the original provider of the content. 
ET for example delivers extensive documentation about their package: http://doc.emergingthreats.net/bin/view/Main/EmergingFAQ

Because we're not the provider of the content, I rather not copy a lot of content in that's hosted somewhere else (and might use a restricted license).

**Comment by sjorge** [comment]
A link would probably work fine.
