### ISSUE TITLE
Activate github discussions

### ISSUE THREAD

**Issue by ssbarnea** [opnsense/core#4547]
It would really be great to activate github discussions as this would make it much easier to use than current forum, also allowing you to convert issues to discussions when they prove not to be real bugs.

**Comment by AdSchellevis** [comment]
currently I don't expect we'll add another communication channel, the world is already complicated enough as it is. It's practical if all is integrated into a single toolkit, but that also raises the question if we're willing to increase the dependency on GitHub, in the past GitHub hasn't been very flexible when it comes to issue registration for example. (one would really like to enforce the use of templates for example)

**Comment by fichtner** [comment]
I don't think adding more noise on GitHub will help with getting things done on GitHub in particular. If anything, it would be nice to streamline GitHub work and get all the community support tickets off this platform into the forum as well.


Cheers,
Franco

**Comment by marjohn56** [comment]
In that case there needs to be a more boards on the forum. i.e.  Plugin issues, GUI issues, Firewall issues, IPv4 issues, IPv6 issues... etc etc.. Pain in the bum with everything under basically two groups, current release and general, hard to find related issues.

**Comment by fichtner** [comment]
Lack of search function use is more obvious with all the repeating questions already. Adding more forums just makes it harder to place questions and ask for version numbers etc and thread hijacking.

**Comment by marjohn56** [comment]
Good luck with that then, it will be interesting to see how you make the users do that.  My thoughts were that each release would have a number of sections or sub categories, so release version would not be the issue.

**Comment by bristea** [comment]
IMHO, SMF and similar standalone forums are some kind of dead-end. The only good argument in favor of them is that they are open-source.  Probably most people using opnsense are already passioned about opensource.

Making a decision is tough here because on one side one would want to go as **purist** as possible and use only open-source software, on the other hand you do not want to endup not being able to focus on core-project goals because your time is drained by infrastructure maintenance (yep, SCM, issue-tracker, forum, website, chat platforms, all count as "infra").

I seen projects picking various positions on that scale and so far I can say that I found purists ended up building entry barriers by doing everything DIY. Instead of growing community, this limited access and endup with a far smaller community. On the other side, there is also the danger of being too accessible, where you end-up being flooded by too many newbie users.

We can also look at that proposal from another point of view: what is the cost of trying it unofficially? What will happen if discussions feature is enabled and @fichtner post a first topic there saying that that is only experimental and not officially endorsed as a support platform.

**Comment by AdSchellevis** [comment]
@bristea At this point we just don't want to add another channel, our current forum might not be perfect, nor is GitHub in that regard. Eventually we may need to abandon our own forum (using smf), just not now. Adding another channel in "experimental mode" would raise expectations about a choice we're currently not willing to make, closing it off again at a later point in time, since we just don't want multiple similar channels, would just create more noise.  

It's not that we don't want to consider alternatives in the future, when choosing something else it has to bring something to the table for all of us (including the core team, to avoid being flooded by communication all the time). We currently not overly 
enthusiastic about GitHub's issue management (at least I'm not), more than 80%  is in reality community support, only a fraction of the people creating issues are kind enough to explain the actual issue and document it properly as asked in the templates..... It is convenient to organise the whole workflow around a single toolkit, to offer traceability around changes, but some level of validation and control would help the people doing the work all day....

**Comment by Stifler6996** [comment]
You are already hosting forum.opnsense.org, so why not move to hosting your own Gitlab?

1. open source. No more wondering what Microsoft might do with your code, or the T&C surrounding it.
2. You now have complete control, and dont rely on github (you could make the github a readonly, that you push releases to, while getting people to gitlab.
3. You can use gitlab discussions.
4. You can finally drop the outdated BBS format.

Or you could use gitlab's hosted service.

**Comment by fichtner** [comment]
Er, we do not see any particular issue with GitHub so changing everything to GitLab is over the top.

The forum is provided for historical reasons and familiarity with other projects. Yeah, maybe it can be removed, but more likely with a modern support platform, not a coding platform.

If people will, however, like this migration is another question entirely.


Cheers,
Franco
