### ISSUE TITLE
Allow dnsmasq port=0

### ISSUE THREAD

**Issue by kevemueller** [opnsense/core#4559]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
dnsmasq DNS server can be disabled by setting its port to 0. This makes sense if you want to use opnsense with dnsmasq as a tftp server (network boot). dnsmasq tftp service is in certain scenarios superior to BSD tftpd.
Currently the UI treats a zero in the port as the undefined value and hence reverts to the default (53).

**To Reproduce**
1. Go to 'Services/Dnsmasq DNS/Settings'
2. Click on 'Enable Dnsmasq'
3. Enter 0 as listen port
4. Save
5. The number will have been replaced with a greyed 53 and dnsmasq started listening on port 53

**Expected behavior**
The UI should allow specifying 0 for the port and hence allow disabling the DNS features of dnsmasq by passing port=0 on the command line.

**Environment**
OPNsense 20.7.7_1 (amd64/OpenSSL)
AMD GX-412TC SOC

**Comment by AdSchellevis** [comment]
we have had this discussion before, but until now I haven't heard much arguments in why it would be better. since custom options won't be available in 21.1 (https://opnsense.org/about/road-map/), it wouldn't be enough either to allow tftp usage from dnsmasq (since it's disabled by default as far as I know).

**Comment by fichtner** [comment]
Custom options still work from the file system in the 21.1 approach. It makes little sense, however, to make a core dns service do something else. It is asking for trouble later. tftp currently discussed here https://github.com/opnsense/tools/issues/196

**Comment by AdSchellevis** [comment]
Almost forgot about the new file imports in https://github.com/opnsense/core/tree/master/src/etc/dnsmasq.conf.d , we should probably explain that in the docs before release (https://github.com/opnsense/docs/blob/master/source/manual/dnsmasq.rst)

**Comment by razamatan** [comment]
is there going to be a similar [some service].conf.d structure for other services?  i'd like to put some netboot/pxe related settings in isc dhcpd configs without hacking up the config templates:

https://ipxe.org/howto/dhcpd#pxe_chainloading

**Comment by AdSchellevis** [comment]
If the service supports it, we tend to expose it (IPsec, Unbound and Suricata currently support includes), but that's not always the case. When trying to expand sections of a service most parsers aren't that flexible.

**Comment by Nemric** [comment]
I use dnsmasq for my pxe boot, I came here because of road map that will deprecate custom options.
Dnsmasq need very few configuration to work as pxe server that can be implemented with some check box and text box to replace pxe typical custom options.
As someone will deprecate custom options and will work on UI and service background it would be nice to use some more time to enable dnsmasq as "pxe server only" with few parameters isn't it ?

**Comment by fichtner** [comment]
> deprecate custom options

With 21.1 the custom options are not in the config.xml anymore as they moved to a config include directory which allows to actually build a plugin with dynamic configuration options for Dnsmasq.

**Comment by razamatan** [comment]
+1.  with the new approach, it'll be pretty easy to get pxe only dnsmasq going.  primarily though, if you don't want dnsmasq to avoid binding/serving dns and dhcp, opnsense needs to allow setting dnsmasq's port to 0.
________________________________

**Comment by fichtner** [comment]
I don't really understand. You could use unbound from OPN for DNS and use rc.conf to set up dnsmasq and the GUI will not interfere...

**Comment by razamatan** [comment]
i agree.  but ideally, you can use unbound for dns and isc dhcpd as stock opnsense AND be able to easily setup dnsmasq for pxe-only via ui (enable checkbox and set port to 0) and add an extra custom config include to handle the tftp settings.  i would see trying to manage two "types" of services and seeing their state through different channels (gui, cli) as a less-optimal steady state.  just my opinion, so certainly ignorable.
________________________________

**Comment by fichtner** [comment]
Yes, I already acknowledged the fact that a plugin can do the job... It's just not something for the core to handle here.

**Comment by razamatan** [comment]
doesn't core here still need to allow port=0 though?
________________________________

**Comment by fichtner** [comment]
Why, you want to disable core dnsmasq to be able to run it using a plugin?

**Comment by razamatan** [comment]
i want to run just the tftp server w/in dnsmasq.  the ask in this issue is to just to be able to set the port argument to 0 iiuc.
________________________________

**Comment by Nemric** [comment]
> 
> 
> Yes, I already acknowledged the fact that a plugin can do the job... It's just not something for the core to handle here.

Hi, I think that it should be in core because dnsmasq is a core component
As dnsmasq has a built-in read-only TFTP server and is able to act only as tftp server it should be implemented by core as it only need few paramaters.
I'd like to suggest you some modifications :
Replace menu entry "DNS Dnsmasq" by "Dnsmasq" (as it can be other than only dns)
Add a check box like "dns server" that enable "listening port for dns" text box
Add a check box like "tftp server" that enable a text box for tftp root path in order to set config like :
```
# Disable DNS or enable with dns port to listen
port=0 (or 53 or ???)
# Enable the TFTP server
enable-tftp
tftp-root=/path/to/tftproot
```
Am I right ?

**Comment by AdSchellevis** [comment]
it wouldn't be an issue if it was in core and configuration options would be clear to the user (which is why we're not going to support port=0), adding the feature just isn't one of our priorities and there are alternatives without the need for core involvement (as mentioned by my colleague earlier).
