### ISSUE TITLE
IPv6 address is missing from "Interfaces: Overview" screen in 21.1

### ISSUE THREAD

**Issue by mattwalkenhorst** [opnsense/core#4651]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**

I updated from 20.7 to 21.1 this morning and discovered that the Interfaces: Overview screen at the path `/status_interfaces.php` no longer displays the IPv6 address for any interface. I believe this is a UI issue, as ifconfig shows each interface as having an inet6 address, and IPv6 is working correctly. I thought it possibly a theme issue, so have tested with the default opnsense theme as well - same result. This was working in 20.7.

**To Reproduce**

1. Ensure that IPv6 is configured correctly and IPv6 traffic is flowing
2. Click on "Interfaces" and then "Overview" in the side navigation
3. Expand an interface known to have an IPv6 address
4. Observe that no address is displayed

**Expected behavior**

The overview for each interface shows the correct IPv6 address.

**Screenshots**
The screenshot below shows that the overview tab for an interface shows the Link Local address, but not the address assigned to the interface statically or by DHCP6.

![image](https://user-images.githubusercontent.com/1747590/106346631-8d851a80-630c-11eb-8864-28522feb46d5.png)

Software version used and hardware type:
OPNsense 21.1-amd64
FreeBSD 12.1-RELEASE-p12-HBSD
OpenSSL 1.1.1i  8 Dec 2020
Intel(R) Celeron(R) CPU J1800 @ 2.41GHz (2 cores)
Network - Intel(R) PRO/1000

**Comment by fichtner** [comment]
Hi, WAN or LAN, if WAN which IPv6 type?


Cheers,
Franco

**Comment by fichtner** [comment]
Ok, I think this is it, please confirm:

    # opnsense-patch 3354485


Cheers,
Franco

**Comment by mattwalkenhorst** [comment]
@fichtner thank you, that fixed the issue.

**Comment by Greelan** [comment]
@fichtner Sorry to necro this, but I've just noticed some IPv6 behaviour that I think may be related, and that suggests this is not just a presentation/UI issue.

Before the change that led to this issue, my Overview menu showed both the IPv6 GUA and ULA (Virtual IP) on my LAN/VLAN interfaces. The GUA was always listed first, and the ULA second (preceded by a small + symbol).

When this issue emerged, the GUA disappeared from the Overview menu (I believe, but can't recall exactly, that the ULA still showed).

After the patch, the GUA reappeared, but now the GUA is always listed _after_ the ULA.

For other reasons today I was testing ping6 to an external address (google.com) from the LAN/VLAN interfaces, rather than the WAN. The ping failed, because the ping was sent from the _ULA_ to google.com's public IP, rather than the GUA on the interface. If I removed the ULA from the interface, the ping worked correctly from the GUA. However, once reinstated, the ULA was again used.

I wonder if the change that led to this issue actually created a more fundamental issue? I seem vaguely to recall that maybe 18-24 months ago there was an issue in OPNsense with ULAs taking priority over GUAs on interfaces. Has there been perhaps been an inadvertent reversion?

**Comment by Greelan** [comment]
This is one of the previous issues I was thinking about: https://github.com/opnsense/core/issues/3310. Not quite the same as here (now the GUA does not get lost after a reload/reboot), but a similar flavour of the ULA taking priority.

**Comment by maurice-w** [comment]
The diag tools issue is not new, we discussed it starting at https://github.com/opnsense/core/issues/3310#issuecomment-584420007.
It seems I mentioned opening a separate issue for this but never actually did. Would you mind?

**Comment by Greelan** [comment]
Tbh, I see this as different because the GUA doesn't disappear now. It just doesn't seem to be used properly. Up until the 21.1 changes I didn't notice this issue.

Happy to create a new issue but it seemed to me related to the changes that led to the issue originally raised in this thread.

Maybe I am missing your point?

**Comment by fichtner** [comment]
@Greelan Screenshot and ifconfig might help

**Comment by maurice-w** [comment]
@fichtner, we noticed that the diag tools use the alias instead of the primary address while testing the patches for #3310. But there were no attempts to fix that back then and I just forgot about it. So I don't think this ever worked correctly, or did it?
@Greelan, are you absolutely sure that the diag tools used the primary address in 20.7?

**Comment by fichtner** [comment]
Yes we should fix these calls, maybe ditch the old function for good:

```
 % git grep find_interface_ipv6
src/etc/inc/interfaces.inc:        $ip6 = find_interface_ipv6($realifv6);
src/etc/inc/interfaces.inc:    $oip = find_interface_ipv6($lanif);
src/etc/inc/interfaces.inc:    $oip = find_interface_ipv6($lanif);
src/etc/inc/interfaces.inc:function find_interface_ipv6($realif, $ifconfig_details = null)
src/etc/inc/interfaces.inc:function find_interface_ipv6_ll($realif, $ifconfig_details = null)
src/etc/inc/plugins.inc.d/dpinger.inc:                $gwifip = find_interface_ipv6_ll($gateway['if'], $ifconfig_details);
src/etc/inc/plugins.inc.d/dpinger.inc:                $gwifip = find_interface_ipv6($gateway['if'], $ifconfig_details);
src/etc/inc/plugins.inc.d/unbound.inc:        $laddr6 = find_interface_ipv6($realifv6, $ifconfig_details);
src/etc/inc/plugins.inc.d/unbound.inc:            $lladdr6 = find_interface_ipv6_ll($realifv6, $ifconfig_details);
src/www/diag_ping.php:                $ifaddr = find_interface_ipv6(get_real_interface($pconfig['interface'], 'inet6'));
src/www/diag_ping.php:                $ifaddr = find_interface_ipv6_ll($realif) . "%{$realif}";
src/www/diag_testport.php:                $ifaddr = find_interface_ipv6(get_real_interface($pconfig['interface'], 'inet6'));
src/www/diag_testport.php:                $ifaddr = find_interface_ipv6_ll($realif) . "%{$realif}";
src/www/diag_traceroute.php:            $ifaddr = find_interface_ipv6(get_real_interface($pconfig['interface'], 'inet6'));
```

**Comment by Greelan** [comment]
@maurice-w, no I am not absolutely sure that this worked OK before 21.1. So it could be as you say a continuation of the previous issue.

@fichtner, happy to post further details such as CLI output and screenshots. Given that this issue, while seemingly related to the Overview presentation issue that prompted this thread, may be a broader concern that pre-dates the presentation issue, I will open a new GH issue and include the relevant information there (and reference this thread and the earlier one). I should be able to do that in the next day.

As a preliminary point, though, I query whether the solution is properly just to favour the GUA in all cases. I would have thought, for example, that using the `-S` flag for ping6 is so that the user can test routing issues, etc. So in some cases they may want to use the ULA, such as if testing local routes. Perhaps the better solution is that the GUI allows the user to select exactly what source IP to use on an interface when selecting a Source other than default?

(As an aside, the default behaviour of course of ping6 is to use the GUA when pinging GUAs, and to use the ULA on the appropriate internal interface when pinging ULAs. The appropriate internal interface will naturally differ depending (as I understand it) on what network the ULA being pinged is in, and the routing table.)

The same comment I would imagine applies to other tools, such as traceroute.

**Comment by fichtner** [comment]
I created https://github.com/opnsense/core/issues/4749 for this purpose and further discussion. Closing this closed ticket again :)
