### ISSUE TITLE
ui: Tokenize 1.3.3 and string.replaceAll may causes JS errors

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#4654]
Error: TypeError: string.replaceAll is not a function
Source File: https://cencored/ui/js/tokenize2.js?v=(somehexnumber that perhaps should be secret)[
Line: 1033

https://forum.opnsense.org/index.php?topic=21199.0

**Comment by AdSchellevis** [comment]
Can't reproduce, although we don't use their new `escape()` in may places (since it has other issues), it's valid JS as well https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll (note the compatibility matrix on the bottom)

This is highly likely a browser issue (I've tested Firefox, Chrome and Safari on osx, without issues), https://stackoverflow.com/questions/62825358/javascript-replaceall-is-not-a-function-type-error suggests the same by the way. 

We can patch it out, but maybe it's better to just require updated browsers in this case. It's highly likely other JS libraries will follow in which case we end up trying to support something nobody else apparently seems to be caring about...

**Comment by fichtner** [comment]
Looking at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll#browser_compatibility it makes sense either to let it go or bother Tokenize to address it.
