### ISSUE TITLE
IDS: filter rules by status and action

### ISSUE THREAD

**Issue by kulikov-a** [opnsense/core#4665]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Is your feature request related to a problem? Please describe.**

Hi!
Now filtering rules by status or action in the Services: Intrusion Detection: Administration:Rules tab does not work.

**Describe the solution you like**
It seems to me that after https://github.com/opnsense/core/commit/a2a21829fae11a1ad6d738cbd2c1639687ee6f53 the command "configctl ids query rules" already returns actual rule parameters?
might it be possible to return filtering by status and action in
https://github.com/opnsense/core/blob/efd880b9dbd36ff2127fca92b800303db2c22897/src/opnsense/mvc/app/controllers/OPNsense/IDS/Api/SettingsController.php#L110
?(tested. seems to work fine)
maybe even lines 127-130 are no longer needed? (not tested)

these filters helps a lot!
Thanks!

**Describe alternatives you considered**
no

**Additional context**

Add any other context or screenshots about the feature request here or links to relevant forum thread or similar

**Comment by AdSchellevis** [comment]
@kulikov-a you're right about the direction, ` 'action' ,'status'` shouldn't be excluded from the filters. Although there will always be a small risk that results are different then configured (since we query current settings, not planned ones), the intend was to just query the ones that are there indeed. thanks for the ticket, will close with a patch shortly.

**Comment by kulikov-a** [comment]
thanks!
