### ISSUE TITLE
OpenVPN Server Client Settings cannot be deactivated and saved

### ISSUE THREAD

**Issue by MikeyMikeDO** [opnsense/core#4678]
After activating of VPN -> OpenVPN -> Servers  [Client Settings]

Option: DNS Default Domain
Option: DNS Servers

and after enter somesettings it´s not possible to

a) clear the fields
b) deactivate the settings

After saving these changes the old values / checked options are retained.
A change of the field content is saved normally.

Version: OPNsense 21.1-amd64

**Comment by cbrueffer** [comment]
I see the same problem in 21.1.3. Which additional information can I provide to help debug this?

**Comment by cbrueffer** [comment]
The problem is that the text fields for `DNS Default Domain`, `DNS Servers`, `NTP Servers` and perhaps others are not cleared when the option box is unticked. This causes the `!empty` checks for the options in `src/www/vpn_openvpn_server.php` and `src/www/vpn_openvpn_csc.php` to return `true` and the entries are written into the server config.

Workaround:
Clear the domain name / DNS server / NTP server text fields before unchecking the box, then the config gets written correctly.
