### ISSUE TITLE
DHCPv6 server intermittently unresponsive, not responding to solicits

### ISSUE THREAD

**Issue by maurice-w** [opnsense/core#4691]
- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new (kind of).

**Describe the bug**

OPNsense 20.7 / FreeBSD 12.1 introduced a bug which causes intermittent unresponsiveness of services that listen to multicasts. For Router Advertisements, this was eventually solved by updating radvd (#4338). But the same issue still exists for the DHCPv6 server. The intention behind opening this bug report is keeping it on the agenda after #4338 has been closed.

**To Reproduce**

dhcpd6 intermittently doesn't respond to DHCPv6 solicits. A restart of the dhcpd6 service temporarily restores functionality.

1. Do a packet capture on the LAN interface, filter for DHCPv6 packets.
2. See error: DHCPv6 solicits from clients to multicast address ff02::1:2 with no response from OPNsense.
3. Restart dhcpd6.
4. The next DHCPv6 solicit results in the usual DHCPv6 handshake (solicit - advertise - request - reply).

**Additional context**

Not sure how to approach this. Port the radvd patch to dhcpd6? Fix the underlying FreeBSD issue?

**Environment**

OPNsense 21.7.a_6 (amd64, OpenSSL)

**Comment by fichtner** [comment]
Hi @maurice-w,

This isn't very good news, but could be expected given the radvd adventure we have had. Basically I looked through FreeBSD code to find a fix but if it isn't on 21.1 yet there is not much else there to find for the moment.

For some reason subsequent LEAVE/JOIN sequences  are broken for a single interface and worse yet I haven't been able to write a simple POC binary that triggers this. In isolated code that works without issues?!

If it can be avoided for isc-dhcp binary by patch that would work, but patching upstream software gets messy fast. In the radvd case it was ok-ish because the pieces that broke radvd only ever lived in FreeBSD ports.

No suggestion yet, just trying to offer to get the conversation going hereby.


Cheers,
Franco

**Comment by marjohn56** [comment]
Just to add my few cents, I'm seeing the same thing.

**Comment by andryyy** [comment]
I saw the same thing happening and came to comment on the other thread when I stumble over this issue. :)

I installed a local dhcpy6d in my network. which is pretty straight-forward. It works!

Pinging @martinvogt-tinc 🤜🏼

**Comment by fichtner** [comment]
I checked the ISC code and there is no multicast leave in it so the bug in the kernel may be worse than we previously hoped for. I still don’t see a path to a reliable POC and the radvd sidestep approach we did definitely doesn’t work here. It also means radvd is not really fixed.

**Comment by joni1993** [comment]
For me restarting either radvd or dhcp6 does not temporarily solve the problem but only restarting the whole box brings ipv6 assignments back to my clients.

**Comment by andryyy** [comment]
Try restarting the service in OPNsense and restart the network stack on your client.

Give https://dhcpy6d.ifw-dresden.de/ a try.

**Comment by megmug** [comment]
I can confirm the issue is reproducible in 21.1.5 on my machines. Is there a suggested workaround besides rolling your own dhcp server? Would SLAAC be expected to work, or could this bug interfere with that, too?

**Comment by maurice-w** [comment]
SLAAC is expected to work and does so for me (radvd was fixed a while ago, see #4338).
For dhcpd6, I'm not aware of a workaround other than running a separate DHCPv6 server.

**Comment by Wireheadbe** [comment]
I have the same thing. At a certain point - the DHCP6 service just stops handing out IP's - and nothing is logged anymore (I have a remote graylog instance where I send everything towards). It then reloads after some time (I suppose due to LAN IPv6 tracking the WAN IPv6 interface), but it's still not handing out IP's. Only a manual restart of dhcp6 recovers it.

**Comment by fichtner** [comment]
It's likely related to FreeBSD 12 so we are hoping the upgrade to 13 will improve this situation.


Cheers,
Franco

**Comment by Wireheadbe** [comment]
Thanks Franco, appreciated. I'll give 22.1 a spin from the moment a beta/RC is avail. For now, I'll implement a workaround via cron. It's a tricky one, not a single error condition is logged.

**Comment by fichtner** [comment]
@Wireheadbe yeah, the only clue is an ENOMEM coming from the kernel eventually as far as I remember (also the case for radvd).

**Comment by Wireheadbe** [comment]
Thanks anyway Franco! For others running into this - I added the following to /usr/local/opnsense/service/conf/actions.d/actions_dhcpd.conf:
```
[restart]
command:/usr/local/sbin/pluginctl -s dhcpd6 restart
parameters:
type:script
description:Restart dhcp6 service
message:restarting dhcp6
```
Then afterwards
```
service configd restart
```

And then you can add an hourly action to restart dhcp6 in cron via the GUI.

**Comment by Wireheadbe** [comment]
@fichtner - hope I did this pull request correctly, but it would help massively if such an action was available. (now it's lost with each update ;) )

**Comment by MaZe3D** [comment]
I love to see the engagement regarding this issue. But one question i couldn't answer directly while researching this.
First do i get this right:
- since FreeBSD 12 DHCPv6 is unreliable (witch apperently with freebsd 13 not changed.
- this issue is primarily with freebsd and not opnsense

Now my actual question.
What are the next steps or how will this be addressed in the future? I mean the workaround is looking promising but it is still a workaround and no fix of the actual problem. I dont want to hurry anyone working on this, i am just curious.
I recently switched from pfsense to opnsense because of the great community 👍 and development compared to netgate. I was a little bit disappointed to see that DHCPv6 is not reliable (as I like to deploy ipv6 networks 😄).

**Comment by StrangePeanut** [comment]
Initially Wireheadbe’s workaround seemed to work wonders, but unfortunately devices kept losing their IPv6 connection at random. We made the DHCPd6 daemon restart every 5 minutes and eventually every 1 minute to minimise the number of incidents.

Is there any other workaround (besides SLAAC) that we can deploy to our OPN instance to make IPv6 stick?

**Comment by splooge** [comment]
I'm also having this issue.  I've been working with v6 in a large environment of servers for many years, but all of our v6 addresses are statically assigned during server provisioning.  When I wanted to learn the ins-and-outs of dhcpv6 I figured I'd start with an opnsense environment in my home lab.  I thought I was going crazy when I couldn't figure out why things weren't working.  Turns out the dhcpv6 server was - sporadically - not to responding to requests.

When I run a split-screen tmux session on the opnsense machine with the left side running tcpdump on ports 546 and 547 and the right side tailing dhcpd/latest.log, I see the dhcp requests coming in on tcpdump, but I don't see a corresponding entry in the dhcp server logs.

Restarting the dhcpv6 server sometimes fixes this.  At other times it takes a working dhcpv6 server and makes it unresponsive again.

I appreciate that there's now a way to restart the dhcpv6 server via cron but it seems to break it more often than fixes it.  I'm currently restarting it every hour but I think lowering that time frame to 1 minute might work better for me, as the previous poster mentioned.

**Comment by StrangePeanut** [comment]
We made the sane decision of switching to a commercial offering as a result of this issue and our lives could not be better. The 1-minute cron was neither sufficient nor should it have been a thing in the first place. Unfortunately we are quite dependent on managed IPv6 or we would have overlooked it by not going dual stack. Hope none of you are stuck having to deal with this in a larger environment as you will go absolutely mental.

**Comment by MaZe3D** [comment]
I have to say we **need** a fix for this issue. As I am new to opnsense and I came from pfsense (with its old Kernel), I am not familiar when this issue occurred and what is causing it. But I have to say that it is a critical issue because IPv4 is getting increasingly unusable because of the IPv4-address-exhaustion and therefore I need a working IPv6 environment. Services have to be publicly available and should be working reliable which is currently not possible even if I repeatedly restart the Service. 

I am willing to help to resolve this issue, but I don't know how and where. I am mostly interesting what is actually not working or what do we know about this so far. This workaround does not make my network reliable again and therefore we need to fix it. 
I have enough barriers (soon no Public IPv4 address anymore, changing IPv6 prefix) and overall, my setup will work but it depends on a reliable working DHCPv6 Server.
I love this community so far and I don't want to go back to netgate (pfsense) because of this.

**Comment by fichtner** [comment]
> I have to say we need a fix for this issue.

Sure. I'll fix it, but thus far I'm unable to produce this in a lab environment at all. From the FreeBSD side we don't seem to have progress either.

And pfSense will have the same problem eventually. There's no doubt about that.


Cheers,
Franco

**Comment by MaZe3D** [comment]
I am glad to hear that this issue is not just ignored (what was my actually fear). I know that errors are not solved by complaining, so I would like to offer my offer my help. So, if i can help with troubleshooting do not hesitate to contact me.

**Comment by fichtner** [comment]
I simply need a clear guide on how to reproduce. I work on IPv6 in OPNsense most of the time. I have functional setups, but I haven't seen this yet. Basically it means there are some factors here like number of clients or certain configurations being affected (more than others). All hints are appreciated.


Cheers,
Franco

**Comment by joni1993** [comment]
Hi,
I am also experiencing this issue from time to time and I operate a non mission-critical IPv6 network.
We could look into the issue together when it occurs - if there is any special debug flags that would need to be enabled beforehand just let me know.

**Comment by Wireheadbe** [comment]
Any of you guys running this in combination with Realtek HW / Unifi Switches / J4115 CPU / ... ?

**Comment by MaZe3D** [comment]
I have built my Router a few years ago. It is equipped with an AMD Ryzen 1200 on a Gigabyte A320 Mainboard of which I use the Realtek adapter for my WAN connection. For LAN I have an Intel Quad NIC. 
Originally build for pfsense I switched since about 6 weeks now to opnsense because of stability issues and random crashes with pfsense and was blown away of the software, software maintenance and community.

**Comment by ghemberg** [comment]
I am also experiencing this issue in my setup.
It took me a while to pinpoint the exact cause. When I finally found this issue and saw it was "Closed", I assumed the problem should have been resolved in the latest version: it isn't.
I applied work-around (scheduled restart of DHCPv6 daemon every minute) and that seems to work so far... But this hardly seems ideal.

I understand the cause is with the upstream FreeBSD project and they need to fix it, hence why this issue is closed here. It appears to me as if very little progress is being made. In the end, an OPNSense feature is broken because of this upstream issue. IMHO this should, at least, be clearly documented in the IPv6 documentation for OPNSense.

**Comment by ArnCo** [comment]
I know that it may not be very productive regarding the issue, but I encounter the same behavior on my home network. I have a very small number of clients (< 10) and the server becomes unresponsive after a while, so my leases are never renewed.

The packets are received on the OPNsense side but never taken into account by the DHCP server daemon, unless it is restarted, which fixed the problem instantly.
I cannot seem to diagnose the issue. If this is indeed kernel-related, it does go way beyond my debugging skills.

**Comment by mjhill1** [comment]
My ISP just lit up IPv6 a few weeks ago, and I finally got around to setting up DHCPv6 over the weekend.  It worked for a while, but then I started hitting exactly the same problem described above in this thread.

I'm going to try upgrading from 21.10 to 22.7 (I probably should have by now anyway); hoping maybe that will fix it.

**Comment by zemsten** [comment]
Is this still a thing? I'm trying to setup DHCPv6 for the first time on a fully updated box and just getting absolutely stonewalled on the client side.

**Comment by greggitter** [comment]
PSA: I was looking at this recently because there was a delay for some apple devices receiving ipv6 addresses when joining the network.  They would eventually get one (router advertisement every 5 minutes), but it appeared the router solicitation was being ignored by radvd or not getting there.  A week or so later, it was discovered by someone else that some newer TP-Link access points were erroneously dropping the RS packets.  TPL advises a fix is in the works.

**Comment by nickles95** [comment]
> Is this still a thing? I'm trying to setup DHCPv6 for the first time on a fully updated box and just getting absolutely stonewalled on the client side.

Yes, this is absolutely still a thing, and very annoying.

**Comment by MaZe3D** [comment]
Hi, maybe this is not directly related to this issue, but i recently figured out why my router was acting up. https://forum.opnsense.org/index.php?topic=30522.0

I can assume, if my opnsense looses wan connection, because of reasons 😉, the dhcpv6 has problems restating. And instead of restarting it is just spawning thousands of new instances. Which i cannot kill via the web ui, rather than killing all of them via the shell.

**Comment by danny91** [comment]
Unfortnately also having this issue still on 22.7.8
Hope it gets fixed soon.
