### ISSUE TITLE
No IPv6 address assigned on WAN interface / Router Advertisement ignored

### ISSUE THREAD

**Issue by marjohn56** [opnsense/core#4733]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x ] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**

IPv6 ICMPv6 RS does not get sent over a PPPoE link.

**To Reproduce**

You'll need to set up a PPPoE server! Reason being the interface needs to come up on PPPoE v4 before you can see anything. Once you have done this then using Wireshark monitor the ICMPv6 traffic being sent to the PPPoE  server, there is no RS being sent.

**Expected behavior**
ICMPv6 RS packets should be sent over the PPPoE link

OPNsense 21.1.r_96-amd64FreeBSD 12.1-RELEASE-p12-
HBSDOpenSSL 1.1.1i 8 Dec 2020
Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 cores)

Solution is to not use the -a flag on RTSOLD as that prohibits RS being sent on point to point interfaces ( according to the man ), but to supply the actual interfaces on the command instead.

**Comment by fichtner** [comment]
https://github.com/opnsense/src/commit/2485dc0351

**Comment by fichtner** [comment]
For the record, the PPP limitation came from KAME in 2000 to FreeBSD via https://github.com/freebsd/freebsd-src/commit/804c83d4bd3 with the "-a" option. Since we force PPPoE interfaces one way or another and the auto-probe just adds devices to the argument list like we would pass it we are good here. Thanks for the pointers to the problem.
