### ISSUE TITLE
Bug in DHCP server Available range

### ISSUE THREAD

**Issue by x1alfa** [opnsense/core#4762]
Hi, I noticed this in 20.1.1, not sure if the same behavior exist in older version, same is exist in 20.1.2, I was able to reproduce in two different installation.

Interfaces (LAN, OPTx) \ IPv4 Configuration Type (Static IPv4) \ IPv4 address (x.x.x.x/32)
Services \ DHCPv4 \  Available range (x.x.x.2 - x.x.x.0)

With /32 sub-net no IPv4 range should be available for DHCP, plus the range is backward.

I hope reporting this bug help improving OPNSense.

**Comment by x1alfa** [comment]
I'm not a PHP programmer, but looking at the code I think the quickest fix is to add a validation line if subnet is 32 then set start IP and end IP to the same IP of the interface

services_dhcp.php (line 709)

<?php
          if ($config['interfaces'][$if]['subnet']) = 32  {
$range_from = $config['interfaces'][$if]['ipaddr'];
$range_to = $config['interfaces'][$if]['ipaddr'];
} ?>
<?=$range_from;?> - <?=$range_to;?>

<?php
else {
$range_from = ip2long(long2ip32(ip2long($config['interfaces'][$if]['ipaddr']) & gen_subnet_mask_long($config['interfaces'][$if]['subnet']))) + 1;
$range_to = ip2long(long2ip32(ip2long($config['interfaces'][$if]['ipaddr']) | (~gen_subnet_mask_long($config['interfaces'][$if]['subnet'])))) - 1;}?>
<?=long2ip32($range_from);?> - <?=long2ip32($range_to);?>

**Comment by IShouldHaveBeenAQATester** [comment]
This is also an issue with /128 on ipv6.  Also wondering if a /31 or /127 is handled properly.

**Comment by fichtner** [comment]
I'm assuming nobody uses /31 since the validation fails and there are no bugs for it. So /30 is required and will only then show an available range although it won't try to poke a hole into it for the IP address used by the interface.

In IPv6 /128 suffers the same fate, but /127 works since we don't have a network or broadcast address to reserve.

For more details see c7c6299.


Cheers,
Franco
