### ISSUE TITLE
hard-coded <style> definitions in vpn_ipsec.php

### ISSUE THREAD

**Issue by mihakralj** [opnsense/core#4772]
- [ x ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ x ] I have searched the existing issues and I am convinced that mine is new.

vpn_ipsec.php has embedded two <style> statements that override any applied themes. Particularly annoying with dark themes, see the screenshot

**To reproduce (visually):** apply any of the dark themes (Cicada, Vicuna), go to VPN-IPSec and create a tunnel entry
**To verify (code inspection):** check the /www/vpn_ipsec.php lines 324-335 for embedded stylesheet

**Expected behavior**
The dark theme should render vpn_ipsec.php with its own stylesheet; the embedded <style> statement should be removed from vpn_ipsec.php and replaced with style elements from main.css

**Screenshots**
![image](https://user-images.githubusercontent.com/31756078/109820222-a887ca80-7be9-11eb-9e83-f6ac5653ce16.png)

**Comment by AdSchellevis** [comment]
We have some pages with embedded stylesheets, often it's best to ask the theme developer for a fix, since most of these can't easily be slipped into a minor release (and usually be overwritten anyway). Ideally all should be embedded in the theme, but that would also require a more stable style guide and associated classes.

**Comment by mihakralj** [comment]
As an (aspiring) theme developer I do not want to push the change of vpn_ipsec.php file into the theme. Embedded color statements inside PHP are overriding any customization that theme can do through main.css.

Don't usk theme developer to fix this. We will botch it. :-)

**Comment by AdSchellevis** [comment]
Just managing expectations here, waiting for core to fix this might take a long time, fixing it in the theme likely is easy.... if you're having difficulties fixing it there, we can always try to help out. Since I'm quite sure this isn't the only spot where overrides exists it likely won't help fixing this and pushing it in 21.7 or 22.1.

**Comment by mihakralj** [comment]
let me re-iterate: theming (core.css) cannot override hard-coded <style> statements within .PHP file.

**Comment by AdSchellevis** [comment]
yes you can..... (I wouldn't point you to there if it wasn't possible, I'm pretty sure this isn't the first time I answered a similar question), testing it out locally first before claiming it doesn't work really helps moving things forward.

added the following to my main.css
```
tr.phase2_tr {
  background-color: yellow !important;
}
```

after which it looks like:

![image](https://user-images.githubusercontent.com/9783985/109837332-5b394680-7c45-11eb-8036-3a8f7a26989d.png)

If elements are hard to replace, we can see if we can help out, but the general rule remains the same.... 

So, again, if it's not possible for some elements, we can see if we can help out with minimal changes without breaking other existing theme's.

**Comment by mihakralj** [comment]
Sigh, I stand corrected.
