### ISSUE TITLE
Firewall Alias Port range needs input sanitization

### ISSUE THREAD

**Issue by Alives** [opnsense/core#4889]
- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

Apparently - is not valid for port ranges, only :.  Example: mosh UDP ports 60000 to 60100, the gui allows entering 60000-60100, however this will not work (and possibly throws nat php errors, though not confirmed).  What does work is 60000:60100.

**Comment by AdSchellevis** [comment]
Can you use full templates please? versions and steps performed matter...

When adding a port range alias, on my end it signals invalid input properly (21.1.4)
![image](https://user-images.githubusercontent.com/9783985/113391862-7b6b3b00-9394-11eb-931a-a92991117e04.png)

**Comment by bsd-source** [comment]
Unfortunately, I can't test this right now. But I recall having an issue with the firewall -> shaper -> pipes with PHP error showing when that the IP was not valid. I suspect the port issue might be a similar issue. To possibly reproduce port issue 60000-60100:

1. in Content box type in 60000-60100 press enter key on keyboard
2. select the save alias button
3. should produce the invalid port number error

To avoid the error you can select the empty space to the right of the port range. Then select save and it will probably work. I think the issue here is that if you press the enter button is creates a carriage return or something that isn't visible on the webgui page. Again I'm unable to test this but I had a similiar issue with adding IP address to a shaper pipe.

**Comment by Alives** [comment]
I tested and was unable to reproduce as well, but I think your pressing enter idea might be it.  At the same time I kept getting notices that a php page was erroring around line 125 IIRC... page was nat.*\.php, I don't remember exactly.  I did file an issue about it though from the GUI.

**Comment by Alives** [comment]
I was unable to reproduce with the current ISO on a fresh install.  I suppose this can be closed.  I don't know how I was able to save a port range with a '-' in it.

**Comment by AdSchellevis** [comment]
ok, let's close then
