### ISSUE TITLE
Captive portal isn't working, several problems

### ISSUE THREAD

**Issue by havarh** [opnsense/core#49]
Captive portal problems:
PS! I've tested the same config file on pfSense, and everything is working under pfSense.
For this test I have used the IP 192.168.2.105 for the WAN and the IP 10.13.37.1 for the LAN

I have activated the captive portal on the LAN interface, with local user and voucher authentication.
- Captive portal doesn't work at all. All clients gets connected to the internet, without the captive portal showing up. If I manually try to enter http://10.13.37.1:8002/?redirurl=http://example.com the portal page is shown as usual, and redirects correctly after a successful login.
- Unable to upload custom "Portal page contents". If I select a file with "Browse" and click "Save", the changes aren't saved.
- I tried chaning the "Portal page contents" by editing the config file, with the <page><htmltext>...</page></htmltext> generated by a pfSense install, so now I see a custom page. But still unable to reupload a new file.
- The link for the "View current page" in the "Portal pages contents" area is wrong, the port number is 2 instead of 8002, like this:
http://192.168.2.105:2/ instead of this http://192.168.2.105:8002/
A copy of the test config file is located here:
https://dl.dropboxusercontent.com/u/4412405/config-OPNsense.localdomain-20150219230819.xml

PS! I've tested this on OPNsense 15.1.5 and pfSense 2.2.

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/91bf66effec3ec04040593e54bae4ad2540b59d6 
Stopping and starting the zone didn't result in reloading the ipfw rules, added a reload of the rules to the start action to prevent this from happening. The current version only reloads after a reboot.

Eventually we should rewrite more code from CP, because the legacy system uses all kind of kernel hooks which will probably never make it to the standard FreeBSD kernel and we will try to avoid this. 

We had to rewrite the rule handling and generation before our mvc framework was finished. Let's try to polish some of this to a working state and schedule a rewrite into our mvc framework at a later moment.

**Comment by DivakarRajagopalan14** [comment]
Hi.I am new to opnsense or Pfsense what ever. The Captive Portal part is not working at all..
Any easy way to implement it. and is there anyway to track the users browser history as per ip address in opnsense
