### ISSUE TITLE
Unbound DNS blacklists don't survive a reboot when /var RAM disk is enabled

### ISSUE THREAD

**Issue by pR0Ps** [opnsense/core#4938]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**

The Unbound Blacklist functionality doesn't work after reboot when /var RAM disk enabled because `/var/unbound/etc/dnsbl.conf` is missing.

It's the same bug as https://github.com/opnsense/plugins/issues/1798. I opened a new issue because that one is against the unbound-plus plugin which has had the blacklist functionality integrated into the core. The problem is also mentioned in #4327 .

**To Reproduce**

1. Go to 'System -> Settings -> Miscellaneous'
2. Enable '/var RAM disk'
3. Go to 'Services -> Unbound DNS -> Blacklist'
4. Choose list(s) and enable
5. Reboot

**Expected behavior**

`/var/unbound/etc/dnsbl.conf` exists or is created on boot and used by Unbound.

**Describe alternatives you considered**

I have currently worked around this by adding the following in `/usr/local/etc/rc.syshook.d/start/51-dnsbl`:
```bash
#!/bin/sh

if [ ! -f /var/unbound/etc/dnsbl.conf ]; then
    configctl unbound dnsbl
fi
```

**Environment**

OPNsense 21.1.4-amd64
FreeBSD 12.1-RELEASE-p15-HBSD
OpenSSL 1.1.1k 25 Mar 2021

**Comment by AdSchellevis** [comment]
It's a known omission indeed, but I think there isn't an issue for it currently. https://github.com/opnsense/core/pull/4528#issuecomment-746000277 has some more context, we should fix some issues around loading and storing blacklists, but I can't promise when it will land into the product.

**Comment by pR0Ps** [comment]
While the general Unbound plugin config structure is being redesigned, does it make sense to add something temporarily so that any missing blacklists are regenerated on OPNsense/unbound startup?

In the linked issue you mentioned not wanting to slow booting down with generating the blacklists on initial startup. This is definitely a concern, but if a user has enabled blacklists then they probably want them to still work after a reboot, regardless of if it takes a bit longer.

I'd be willing to submit a PR that implements this on-demand regeneration. Is this something that would be merged?

**Comment by AdSchellevis** [comment]
@pR0Ps probably not, there aren't a lot of shortcuts to take there. If the files are stored on a memory disk, you do need to download them again, during boot this might be tricky (everlasting boots due to the networking not being ready for example). memory disks just aren't great for this type of content I guess.

The proper fix likely isn't a huge amount of effort either to be  honest, testing and keeping the documentation up to date might be the hardest part here. At a first glance we should fix the following main concerns in the current approach:

1. Making sure there's a static configuration directory to feed additional config data (somewhere in `/usr/local/etc/`) to simplify https://docs.opnsense.org/manual/unbound.html#advanced-configurations
2. support some sort of lazy loading for larger lists (which is what https://github.com/opnsense/core/pull/4528 aims for)
3. If possible keep it backwards compatible with the current approach, so we can slip it into a minor version more easily
