### ISSUE TITLE
DPD setting not reflected in /usr/local/etc/ipsec.conf for IKEv2, breaks (double) NAT-T

### ISSUE THREAD

**Issue by cluck** [opnsense/core#4969]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [*] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [*] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**

Keepalives / DPD is not operational for IKEv2. Reason is that IKEv2 keepalives are to be configured with different config statements than IKEv1, which is not implemented.

Credits for spotting the problem and mentioning a solution go to the user posting here: https://forum.opnsense.org/index.php?topic=21380.msg100267#msg100267

**To Reproduce**

1. 'Setup IPsec site to site tunnel' with IKEv2
2. Activate DPD
3. Reboot both firewalls, see tunnel coming up
4. Move both firewalls behind additional NAT (e.g. CGNAT).
5. Reboot both firewalls
6. See error: tunnel does not come up (or comes up after a long delay).

**Expected behavior**

IKEv2 based tunnels automatically recovering after reboot.

Configuration according to https://wiki.strongswan.org/projects/strongswan/wiki/Retransmission.

**Describe alternatives you considered**

Switch back to IKEv1.

**Screenshots**

**Relevant log files**

Looking for repeating "parsed INFORMATIONAL response" in /var/log/ipsec.log.

**Additional context**

This might affect #3414 under some circumstances.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 21.1.5-amd64
FreeBSD 12.1-RELEASE-p16-HBSD
OpenSSL 1.1.1k 25 Mar 2021

**Comment by cluck** [comment]
The problem and a workaround was also described in https://github.com/opnsense/core/issues/3291#issuecomment-479827420 back in 2019.

**Comment by AdSchellevis** [comment]
Given that this can only be configured globally, the most logical option seems to be to expose these settings in the IPsec advanced settings on our end. 

For reference, `strongswan.conf` is generated around here https://github.com/opnsense/core/blob/64e88b3360691d56f60ff58b3a28a83fcce1170a/src/etc/inc/plugins.inc.d/ipsec.inc#L1124-L1143

The legacy settings page is available at https://github.com/opnsense/core/blob/master/src/www/vpn_ipsec_settings.php

Bonus points for hiding the non relevant settings in the ipsec phase1 page

Since this is probably not a very complex ticket, marking this help wanted in case someone likes to work on this one.
