### ISSUE TITLE
Connection blocked from lo0 to lo0

### ISSUE THREAD

**Issue by gianogli** [opnsense/core#5115]
On the live logs tab I've just seen some connections blocked on lo0 interface as you can see here:

![WhatsApp Image 2021-07-23 at 12 02 42](https://user-images.githubusercontent.com/14093378/126776343-cdf7992b-0bd7-4aae-b7de-13bf3ed02389.jpeg)

This behavior is very strange and I think it's appeared some time ago after one of the last upgrade of the software.

Due to these drops, some plugins stopped working: in the attached image you can see in instance the connections to the redis server (port 6379) we did with `redis-cli` command .

We have check the file `/tmp/rules.debug` and we discovered 2 things:

1. Is it correct to have the "#debug:Interface lo0 not found" message?
```
# [prio: 1]
#debug:Interface lo0 not found
# pass in log quick on ##lo0## inet6 from {any} to {any} label "70fcd47cc0b8782476fce1731eb7eb4c" # Pass all loopback IPv6
```

2. We haven't any rule to accept all loopback IPv4 connections!

We checked into the opnsense configuration but we haven't find any setting related to drop/accept connections on lo0 so I'm quite sure that these drops are related to a bug...

What do you think?

Is there a way to solve this issue or to configure opnsense to accept connections from lo0 to lo0 interface?

**Environment**

OPNsense 21.1.7_1-amd64
FreeBSD 12.1-RELEASE-p18-HBSD
OpenSSL 1.1.1k 25 Mar 2021

Thanks... ;-)

**Comment by AdSchellevis** [comment]
Well, there should be a loopback rule, created here
https://github.com/opnsense/core/blob/5e5e2ada3a680ae3f20ab14f2e3e2d17ea69ec62/src/etc/inc/filter.lib.inc#L538

depending on a loopback interface being saved to the config, originating from:
https://github.com/opnsense/core/blob/5e5e2ada3a680ae3f20ab14f2e3e2d17ea69ec62/src/etc/inc/plugins.inc.d/core.inc#L265-L280

Can you try to edit a firewall rule and save+apply? If the problem is the interface hasn't been written, the plugin framework should likely recover automatically

**Comment by gianogli** [comment]
The issue is disappeared... I modified and saved a rule as suggested and after I applied the change the lo0 interface started to work again as expected. 
Thanks!!!

**Comment by b2ag** [comment]
I also encountered the loopback traffic blocked problem on three opnsense installments. I had updated all of those from some 2019 version to latest 2021 and I think the problem started around the first of the 2021 versions.

**Comment by fichtner** [comment]
@b2ag What's the use case and what's the block causing to fail? This is a bit difficult to extrapolate.

**Comment by b2ag** [comment]
I have one Opnsense installation on bare metal which I updated recently and had trouble to access the web interface only to find out my method of "ssh -L10443:127.0.0.1 opnsense-box" failed because all the loopback traffic was dropped after one of the upgrade. I continued updating via ssh console and hoped for the error to go away. But it didn't. 

To "fix" the problem it's enough to add any random rule to loopback which can be deleted afterwarts. This seems to bring back the previously lost/defunc generated "pass loopback" rule.

**Comment by mas1701** [comment]
One out of four of my OPNsense installations (2 private, 2 at employer, all on OPNsense 24.1) has started to show a similar strange behavior of loosing internal loopback connectivity.

It recovered from this all by itself after approx. 90 minutes (this value is a bit rough due to the delay until the external monitoring sends an alarm) while I was digging through the logs.

I found this:

![opnsense-loopback-deny](https://github.com/user-attachments/assets/c9464169-d51c-47e3-b2da-c0e48a3e5028)

I wonder, what exactly "sshlockout" is doing there? There is very little information about this hardcoded internal rule. Should this even be active on loopback? And if that is considered normal, why does it affect connections that are not SSH-related?

All these connections are from relayd and HAproxy. 55443 is the OPNsense WebGUI port and 127.4.4.3 is a Virtual IP for HAproxy.

relayd is used to enable external SSH, since all other ways seem to be blocked. I successfully tested this before installing the system to the server rack. This is the only difference to the other OPNsense installations regarding loopback use.

This is also the only OPNsense running on physical hardware, all others are virtual machines on XCP-ng hosts (XenServer OSS fork).

I'm posting to this old issue since it seems related (lo to lo), but I may be wrong.
