### ISSUE TITLE
[Router Advertisements] Deselecting 'Advertise Default Gateway' has no effect when selecting "(static)" variant of Interface.

### ISSUE THREAD

**Issue by cluck** [opnsense/core#5120]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[-] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[-] I have searched the existing issues and I'm convinced that mine is new.

[-] The title contains the plugin to which this issue belongs

**Describe the bug**
Selecting the '(static)' interface variant seems to push a 'RemoveRoute off' setting to all potential routes in the context of that interface, making the default route to re-surface in error. This results in a default route being advertised nevertheless of the setting to disable it.

**To Reproduce**
1. Select the "(static)" variant from 'RA Interface' in Router Advertisment configuration.
2. Deselect Advertise Default Gateway
3. Find a 'route ::0/' in /var/etc/radvd.conf is generated nevertheless.

**Expected behavior**
Deselecting 'Advertise Default Gateway' should prevent a 'route ::/0' to be added to radvd.conf in the context of that interface. 

**Screenshots**
![Screenshot 2021-07-27 at 23 59 29](https://user-images.githubusercontent.com/870386/127233308-4ef081b1-4e21-45a0-b696-07a8891a093f.png)

**Relevant log files**
If applicable, information from log files supporting your claim.

**Additional context**

**Environment**
OPNsense 21.1.3_3-amd64
FreeBSD 12.1-RELEASE-p14-HBSD
OpenSSL 1.1.1j 16 Feb 2021

**Comment by fichtner** [comment]
@cluck hi I was doubting myself about this for a bit but I found what you are saying https://github.com/opnsense/core/pull/4692 and it's already fixed in 21.7 which comes out today. We have to be a bit careful during minor iterations with these kind of changes so it wasn't added to 21.1.x along with another fix to always deprecate routes, see

https://github.com/opnsense/changelog/blob/33f9d578089bac96b9829dadd2358b1e9b2d3f6d/community/21.7/21.7.r1#L53-L54


Cheers,
Franco
