### ISSUE TITLE
radvd and DHCPv6 cannot run on local-link IPv6

### ISSUE THREAD

**Issue by 8191** [opnsense/core#514]
Is it intentionally, that radvd and DHCPv6 cannot run on interfaces with only a local-link address?

If yes, the user should be notified so in the DHCPv6/radvd configuration window.

**Comment by danrl** [comment]
If you mean link-local addresses (fe80::/10) then it is no use running radvd or dhcpv6 on these addresses. They are not meant to be used for that. Link-local address assignment is done by the kernel itself, so need for a boot protocol or router advertisements there.

Voting for "wontfix".

**Comment by 8191** [comment]
But anyway the local link prefix should be deployable. Not every subnet needs to use fe80::/16.

**Comment by danrl** [comment]
What do you mean by deployable? Do you want to send a Prefix Information Option that "advertises" the link-local prefix? If so, please don't. link-local prefixes are not meant to be advertised. They don't need to.

Could you specify what the expected behaviour is in your opinion of the feature you are requesting?
