### ISSUE TITLE
Improve LAGG configurability

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#5157]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

There are some additional options available for lagg interfaces, like how distribution is calculated (use_flowid) and the hashing used. It would be practical to be able to configure these and make sure the current selections are visible in the interfaces overview as well.

**Describe the solution you like**

Add missing toggles to the lagg configuration and show them in the overview page, while there make sure un-configured interfaces are visible as well, so when using a lagg with vlan's on top of it still shows the parent properties in the overview.

**Describe alternatives you considered**

none

**Additional context**

none

**Comment by alex-h7h** [comment]
Can this be expanded to include the LACP hashing algorithm option?

The current value is displayed in the ifconfig output on the "laggproto" line (e.g. "laggproto lacp lagghash l2,l3,l4"), and is configurable via ifconfig (e.g. "ifconfig lagg0 lagghash l3,l4"). Valid values are a comma-separated list string of any combination of {"l2", "l3", "l4"}.

Please let me know if a separate issue would be best to track this feature request. Thank you!

**Comment by AdSchellevis** [comment]
@alex-h7h in theory yes, although you would need to add a ticket, I'm just not sure this actually works for a lot of interfaces, a quick scan on "MBUF_HASHFLAG_L3" in the source only lights up two Mellanox drivers (which we don't use ourselves) https://github.com/freebsd/freebsd-src/search?q=MBUF_HASHFLAG_L3. If I'm mistaken, I'll gladly add it sometime, but I would like to have someone test the different options first.

**Comment by alex-h7h** [comment]
@AdSchellevis thanks for the quick reply. I believe lagghash does indeed work. Anecdotally when I use the default "l2,l3,l4" or just "l2", packets from a single connection leave opnsense spread across both of my lagg members. Whereas when I change to "l3,l4", the packets only leave on a single lagg member; the member chosen does change as the layer3 ports change, but it's always only one member per connection. Actually I'm not sure why hashing on layer2 for a single connection will not result in only a single lagg member being used, because as far as I can tell the hashed layer2 attributes are the same on all the packets. But the result does seem to be reliable.

In the freebsd code, it's used at least in m_ether_tcpip_hash for layer 2, and m_tcpip_hash for layer 3/4 (https://github.com/freebsd/freebsd-src/blob/373ffc62c158e52cde86a5b934ab4a51307f9f2e/sys/kern/uipc_mbufhash.c#L157).

It looks like technically lagghash can have a value and is settable for any lagg proto, however based on the ifconfig documentation, it's only actually used for lacp and loadbalance. From the freebsd source (https://github.com/freebsd/freebsd-src/blob/373ffc62c158e52cde86a5b934ab4a51307f9f2e/share/examples/libifconfig/status.c#L289), it looks like the output of the "lagghash" section is outputted only when set, but anecdotally it seems to be set even for other lagg protos.

On that note, based on the ifconfig docs, I believe use_flowid is also applicable to the loadbalance proto (though in this recent patch it was limited to lacp).

If this seems reasonable to proceed with, I can create a new issue and optionally submit a pull request.

**Comment by AdSchellevis** [comment]
@alex-h7h I looked at it before, but didn’t test it, so if it works for you on a non mxX driver, I don’t object adding it as a feature. I probably misread, sometimes these toggles are hard to track
