### ISSUE TITLE
Creating new OpenVPN server captures log warning into autogenerated TLS authentication key

### ISSUE THREAD

**Issue by cluck** [opnsense/core#5172]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Creating new OpenVPN server captures log warning into autogenerated TLS authentication key. VPN still operational.

`WARNING: Using --genkey --secret filename is DEPRECATED.  Use --genkey secret filename instead.`

![Screenshot 2021-08-22 at 12 45 39](https://user-images.githubusercontent.com/870386/130352381-6e612da9-dc9c-4389-bbed-0a3ce589ede2.png)

**To Reproduce**

1. Go to VPN > OpenVPN > Servers
2. Click on '+'
3. Unter 'TLS Authentication' leave 'Automatically generate a shared TLS authentication key' selected.
4. Hit 'Save'
5. Select newly created VPN for editing
4. See error under 'Cryptographic Settings'

**Expected behavior**

Warning not be captured into configuration.

**Describe alternatives you considered**

None

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 21.7-amd64
FreeBSD 12.1-RELEASE-p19-HBSD
OpenSSL 1.1.1k 25 Mar 2021

**Comment by fichtner** [comment]
I'm sorry but I have to assert that this is rude not testing on 21.7.1 and ignoring release notes:

https://github.com/opnsense/changelog/blob/613960454b7da72e18f282211f7cbd5f1bf844b7/community/21.7/21.7.1#L28
https://github.com/opnsense/core/commit/5e2319e4e4

Yes, you haven't checked the verification checkboxes for this ticket but I assume you thought you did hence my complaint.

**Comment by cluck** [comment]
I have checked both open and closed issues for a trace of this issue, and found none. Maybe you want to change the stated rules in the important notices section or stick to your own rules. I accept your apology for being rude in advance; no need to discuss this in a ticket system any further.

**Comment by fichtner** [comment]
I will accept your rudeness and not touch your issues again. Good luck!

**Comment by Anuril** [comment]
> "With vast knowledge comes great chaos" @fichtner

This issue was created while @cluck was evaluating if OPNsense will continue to be part of our company's strategy or not.
You may be right that @cluck should have tested on the newest release.

That doesn't change the fact that time and effort was spent to document this issue, which was not easy to find. otherwise it would have been found, by following your Contribution Guidelines. 

Let me illustrate: 

Search the issues with "openvpn genkey": No Results.
![image](https://user-images.githubusercontent.com/1939311/132054453-72d0f699-8f8e-4356-ac44-775b4c28d01f.png)

Search for openvpn key
![image](https://user-images.githubusercontent.com/1939311/132052706-039deafd-4899-4175-8373-d1a690327733.png)

Search for openvpn tls key
![image](https://user-images.githubusercontent.com/1939311/132052775-873fbb13-7799-41cb-a293-534811deadc2.png)

Search for openvpn warning
![image](https://user-images.githubusercontent.com/1939311/132052877-8a0fed64-34fd-4bd4-aa0e-d71a70f34e31.png)

Only when you just search for "genkey" through the whole Organization, you can find the commit. (but not the release notes...)
Even if somebody finds the commit: 
![image](https://user-images.githubusercontent.com/1939311/132059372-ce8ceb76-b775-4d77-9c7e-06501ae31857.png)

There is no indication for the fix in the commit, as there is no further comment beyond "leading to warnings". Warnings where? 

Even less clear are the four words in the release notes: "openvpn: fix genkey format on 2.5" 

Let me be perfectly clear: I understand your frustration of having somebody open an issue that already got resolved. 

[This response](https://github.com/opnsense/core/issues/5172#issuecomment-903255275) is still unacceptable, even if you're frustrated.

OPNsense has undeniably been an important part of our company's growth. I was hoping that it will continue to be, now that we are finally in a position to start giving back. That is why @cluck was spending a considerable amount of time evaluating the software and reporting issues he found.

After reading this exchange, it is hard for me to imagine a working relationship with Deciso B.V. - after one of it's employees behaved this way, especially since the intention was clearly not to be rude. 

>“We put high value in the community around OPNsense”, says an enthusiast Jos Schellevis, Deciso’s CTO. “The OPNsense project wants to give users, developers and businesses a friendly, stable and transparent environment.”

Maybe @AdSchellevis can also intervene and we can try to solve this conflict and perhaps profit from each others expertise and resources, instead of wasting time, energy and happiness being angry. 

> "You either die a Hero, or live long enough to become the villain"

I'd be happy to set up a call to clear the air. You can find my info in the Bio.

**Comment by AdSchellevis** [comment]
Hi @Anuril,
 
I'm not sure there's much to intervene here to be honest, if you're seeking a business relation, you can contact our office 
at any time, but if this is about community request and response we might have a different issue at hand.

Usually we're quite open in pointing people towards fixes already being provided in either the master branch or 
a version released, that's likely not the point here. People misread, forget to update software to the latest 
version or simply suffer from an issue that might be in the software. That's probably all part of life.

When creating tickets in community projects (any not just ours), always try to think what change you're seeking, how could somebody help you and, if someone would put a similar request on your desk, how would you feel.

There is a longer history with your colleague and his reports, let's take for example this one https://github.com/opnsense/docs/issues/331 later followed by https://github.com/opnsense/docs/issues/334 (there's more in between).

What if we changed the context of these tickets into something in the real life, a bit inspired by a great book, working in public by Nadia Eghbal (if you can spare the time, certainly a must read). Let's say your colleague decorates his house every year for Christmas, he really enjoys doing so and spend a lot of his free time creating a really nice looking nordic themed garden. 
Lot's of people in the neighbourhood like his efforts and when going home, slowdown with their cars to watch the show. 
Then one day someone from a close by village rings his doorbell telling him, "I don't like the theme you chose, I don't understand it and expect you to change it".
How would he feel? Would he start changing the decoration the next day? and to what end?

Don't get me wrong, your colleague is free to open issues at any time, but consider there are people on the other end spending a  lot of their free time reading them and maintaining the software you're using. 
When the same people open unrealistic tickets over and over again, just don't be annoyed if at some point people doing the work don't seem to be interested in reading and interacting to them. 

If you consider @fichtner's reaction rude, I really would like to encourage you to read the tickets opened by your co-worker 
and assess them along the same yardstick. When his intend was very different then what eventually ended up in tickets, 
there's certainly something to work on.

Best regards,

Ad
