### ISSUE TITLE
Egress gateway default is incorrect under NAT port forward auto-associated firewall rules on wireguard interfaces

### ISSUE THREAD

**Issue by hazarjast** [opnsense/core#5307]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue
(older report of issue was only closed automatically, not because this was determined not to be a bug or otherwise resolved)

**Describe the bug**

Port forward NAT firewall rules auto-generated for wireguard interfaces do not route return traffic out of the wireguard interface as they should by default. Instead, they egress using the default gateway which will always result in a broken connection attempt for clients. Interfaces for other vpn protocols such as openvpn have their auto-generated port forward firewall rules egress through the same interface as ingress which is the proper and expected behavior. 

**To Reproduce**

1. Configure wireguard in line with OPNSense official documentation and assign an interface to it along with an associated gateway.
2. Create a NAT port forward on the newly assigned wireguard interface to any target IP and choose the "Add associated filter rule" option for the "Filter rule association".
3. Attempt a client connection to the associated wireguard endpoint on the forwarded port. It will time out.

**Expected behavior**

When "Add associated filter rule" is chosen in the port forward creation, default 'reply-to' behavior should be to egress via the same interface gateway which ingress already traversed, i.e. the wireguard interface. This would align wireguard in feature parity with other vpn protocols such as openvpn.

**Describe alternatives you considered**

The only alternative at present is to choose "None" for "Filter rule association" during port forward creations on wireguard interfaces and then manually create a firewall rule for the same with 'reply-to' explicitly set to the wireguard interface gateway.

**Screenshots**

See previously auto-closed issue report: https://github.com/opnsense/core/issues/4389 .

**Relevant log files**

Can provide packet captures on request which clearly show this behavior but the auto-closed issue 4389 referenced above already had a wealth of information provided so I doubt such additional information would be necessary.

**Additional context**

N/A

**Environment**

OPNsense 21.7.3_3 (amd64, OpenSSL).
os-wireguard 1.7
AMD RX-427BB (HP T730)
Intel® I350 (Quad port, copper)

**Comment by agh1467** [comment]
Maybe wireguard isn't the only thing affected by this. I didn't see any specific code for setting the gateway in the source at all, so I would assume that any filter rule created from this would use the default gateway. I could easily be mistaken though. There is even a bit of help text which mentions something similar:

> NOTE: The "pass" selection does not work properly with Multi-WAN. It will only work on an interface containing the default gateway.

Regardless, I put this together:

https://github.com/agh1467/core/commit/0ccbcf2d3a46d7865e12064f8370aeb6a161926a

It sets the gateway value for the rule to a (first one found) gateway which is configured on the same interface using the same ipprotocol, otherwise no gateway is set. It has limited scope, and it may be more of a guess, than deterministic. I don't have much experience with the gateways, but I imagine that there are scenarios that are possible which would prevent this from working as expected.

Just an idea for now unless someone wants me to PR.

**Comment by dubwoc** [comment]
So this and the other bug referenced here fixed my issue but it is stale? Is this a bug or is this a problem with how we tried to set this up?
