### ISSUE TITLE
IPv6 over IPv4 Tunneling

### ISSUE THREAD

**Issue by depeo** [opnsense/core#5352]
Hi,

In pfsense there is an option to forward protocol 41/RFC 2893/tunnel traffic to another ipv4 address.
https://docs.netgate.com/pfsense/en/latest/config/advanced-networking.html

Is it possible to add this option to Opnsense?
I want to be able to forward protocol 41 traffic to another host.

**Comment by fichtner** [comment]
Hi @depeo,

It was removed a long time ago: https://github.com/opnsense/core/issues/964

Cannot recall a single request since then so this would be the first.


Cheers,
Franco

**Comment by fichtner** [comment]
If I recall correctly you can just add a port forward that does this... https://github.com/opnsense/core/commit/a356f26b639ca5

**Comment by depeo** [comment]
OK thanks, I'll try that!

**Comment by RT-Tap** [comment]
I'm interested in this because I don't have a static IP from my ISP (and can't get one) but I need a static IPv6 address for a server I am running and so I got a /48 block from hurricane electric.  Now I don't want to have my entire network routed through that tunnel, just a single host (or 2) ... I have been banging my head against a wall for some time now.  It seems my interface is setup correctly, it has an IP and it says its online but I can't ping anything , any words or wisdom?
