### ISSUE TITLE
API unbound dns override

### ISSUE THREAD

**Issue by Thibaut833** [opnsense/core#5392]
Hi,

i come here to know if there is a solution about the opnsense's api on unbound dns services, particularly to post override host to the firewall.

Is there a functionnality to post an override host in unbound dns service via api rest ?

Is there an alternative ? Via config xml with a reboot to push the modifications ? 

Best regards,
Thibaut.

**Comment by tabnul** [comment]
I am also very interested in this. In fact i think it is a very common use case (automatic provisioning machines, and creating 'dns records' for them.

I tried to debug the GUI, adding the record should be doable (post with some data, do a second APPLY post. Biggest challenge will be avoiding the CSRF.
Removing it is almost impossible since it uses an ID that can only be found in a table in the HTML.

**Comment by swhite2** [comment]
@Thibaut833 @tabnul This is now merged in master: https://github.com/opnsense/core/pull/5488.
