### ISSUE TITLE
Collapsed Sidebar for Firewall Rules

### ISSUE THREAD

**Issue by kabaga** [opnsense/core#5427]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

I have 27 interfaces/groups and Floating rules under the **Firewall --> Rules**; therefore, it may requires to scroll up/down depending the location of the interface from the list. 
If the Sidebar is expanded, this is not an issue since I can scroll up and down. However, when the Sidebar is collapsed and going to Firewall --> Rules --> {some-interface}, some of the interfaces including the Foating option cannot be selected. I can only view the last 16 interfaces/groups. 

My screen resolution is 1080p, and have not tried this issue on a much higher resolution TV or monitor since I do not have one.

**To Reproduce**

1. Collapse the sidebar
2. Go to 'Firewall --> Rules
3. The first half of the Rules list will not be visible and cannot be selected

**Expected behavior**

The admin should be able to see all the items under the Firewall/Rules even when the Sidebar is collapsed.

**Describe alternatives you considered**

N/A

**Screenshots**

[Sreenshots.](https://imgur.com/a/F0cOIhA)

N/A

If applicable, information from log files supporting your claim.

N/A

N/A

Software version used and hardware type if relevant, e.g.:

OPNsense 21.7.7 (amd64, OpenSSL)
Commit: 3f5165238

**Comment by AdSchellevis** [comment]
The sidebar is a bit limited in visible items, due to the lack of scrolling. Increasing the max number of items based on the size of the screen might be an option, but with a lot of interfaces there likely will always be a scenario where it just doesn't fit.

Marking this "help wanted" for now in case anyone would like to suggest some changes.

**Comment by agh1467** [comment]
At first glance, I'm seeing a compounding of issues:
1. Menu rises up into the header and goes behind it (happens with dropdown/dropups as well).
2. Sub menu attaches to the top of the previous menu entry and initially goes down until it reaches the bottom of the screen, and if the bottom of the screen is reached, the menu changes and attaches to the bottom of the menu entry and goes up.
3. Menu doesn't stack horizontally when it doesn't fit vertically.

It doesn't appear to be a number limitation, but it's how the menu handles reaching the bottom of the screen. It's forcing it up and out of reach, which is why you only see the last end of the entries of the menu. I'd bet that the menu entries are there for all of the interfaces, and how the menu is rendered makes them inaccessible. The screen would have to be tall enough to exit the Rules menu button and extend down without hitting the bottom of the screen.

@AdSchellevis I think this is a little bit out of my depth, but I did take a look through the source and found some stuff in `src/opnsense/www/js/opnsense_theme.js` which was related to the side bar, but nothing there stood out to me as logic about what to do when the bottom of the screen is reached. 

Also I was able to replicate this without having so many interfaces by adding a bunch of entries to a plugin Menu.xml, and then adjusting the bottom of the window using the Dev Tools panel. Around 21 entries is probably enough to get the menu to appear correctly without touching the bottom of the screen, and then adjusting the bottom higher, and viewing the menu again and it will push up off of the screen.

**Comment by kulikov-a** [comment]
may be we can just limit level3 max-height and allow scroll? (like https://github.com/kulikov-a/core/commit/158999b1113c8f54d9100275b9547b55f28436a3 not tested)

**Comment by agh1467** [comment]
@kulikov-a That's a good idea. I tried these changes, not with the opnsense theme, but with cicada theme. They didn't seem to have the desired affect. Something is still forcing the menu to drop up, and then go out of view. I did confirm that all of the menu items are there in the HTML, they just aren't in view.

I also noticed that scrolling moves the whole page, and isn't isolated to the menu itself. If the menu size can be limited to a portion of the screen height, and scrolling working on it (and not scrolling the page) that would be a good compromise.

**Comment by agh1467** [comment]
Ok, so I kept poking at this, and I found where I think the dropup is occuring:

https://github.com/opnsense/core/blob/de3a021dd948c89c14cea2a49b07a9b4f0a2e227/src/opnsense/www/js/opnsense_theme.js#L65

Commenting that out prevents the dropup from occurring. It also prevents the dropup from occurring on **all** menus, so any that are near the bottom of the screen will continue to go down out of view, which is not ideal.

I also discovered that I was mistaken in that the changes didn't have the desired effect. I tried again in ui_devtools and it worked. I found that I just happened to try it under circumstances that make it appear not working. The issue is that sometimes the menu doesn't appear at all and that's what I saw. It has something to do with the number of items, and how tall the box should be (aka how tall the items are) with respect to the bottom of the screen. I'd venture a guess that with the height of the box limited to 40vh, the calculation for adjusting the menu to drop up then puts the entire menu out of view because (I'm guessing) that the calculation takes into account the height of the items in the box. I'm seeing `margin-top` adjusting to around `-800` when the menu drops up, so it ends up being a menu limited to 40vh dropped up nearly the full height of the screen which would put it completely above the view.

It does work though, there would have to be some other adjustments and more testing to make sure it's reliable though.

Here's what it looks like:
![image](https://user-images.githubusercontent.com/7823088/147521412-3efdb51a-3cd6-45a8-b394-120e3b5cd1c2.png)

**Comment by opnsenseuser** [comment]
@agh1467 i will take a look at the problem. I just can't say when I'll get to it. I have a lot to do at my job at the moment. but thanks for the input.

**Comment by opnsenseuser** [comment]
The first submenu is only folded down if there is enough space. If this is not the case, it folds up and if there is not enough space at the top, it moves the submenu down according to the number of entries that are above the visible area. This works great for the first submenu. But with the second submenu, pushing down doesn't work. I'll take a look.

**Comment by opnsenseuser** [comment]
@agh1467 @fichtner I think i fixed it. Ready for testing!
![image](https://user-images.githubusercontent.com/34602360/153348924-f46415e2-ad8a-459d-9a5e-66f187a033e2.png)

fix >> https://github.com/opnsense/core/pull/5556

**Comment by opnsenseuser** [comment]
i tested it and it works perfect for all submenues! no problem found!

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/pull/5556 + https://github.com/opnsense/core/pull/5570 +https://github.com/opnsense/core/pull/5571
