### ISSUE TITLE
Hardware Checksum Offloading & KVM virtio

### ISSUE THREAD

**Issue by danrl** [opnsense/core#544]
If using virtio network devices on KVM on Linux and not having "Hardware Checksum Offloading" disabled, TCP packets will be dropped by next router.

Scenario:
* next hop = openbsd
* KVM on Intel XEON 64bit, virtio NIC for guest
* guest config: 2 vcores, 1gb ram, 16gb HDD

Solution: Since we can detect virtio-devices, we should disable "Hardware Checksum Offloading" on such platforms. Default is enabled. I would not change the default for compatible platforms, just when virtio NICs are detected.

**Comment by fichtner** [comment]
Out of scope, sorry. Adding the workaround is convenient, removing it will likely be forgotten long after the original guest/host issue will be fixed.

**Comment by FlorianHeigl** [comment]
None of those issues ever get fixed. Same issue in FreeBSD/xen has never fully been fixed from 2005 till 2016 which is 11 years.
It makes sense to add a workaround instead of installing something that doesn't work.
It is not relevant if the bugfix stays in place by mistake since it will only mean a small performance degradation which is a different story than a very bad performance issue along with no functionality.

I know it's industry practice to let people suffer on those hw + vm offloading issues but I personally don't insist on suffering. Unless noone puts up testcases to validate working drivers, there's only one right thing to do.

**Comment by fichtner** [comment]
@danrl @FlorianHeigl alright, auto-detect will always be tricky so we are opting for a portable solution: we're going to change the default to disable in the sample configuration going forward, which means factory reset or new installs will have this addressed within the scope of our project at least. This will also help the IPS folks who run into the same issues...

Thanks,
Franco
