### ISSUE TITLE
unbound-anchor: prioritize system-wide DNS servers over public roots

### ISSUE THREAD

**Issue by marinbernard-pep06** [opnsense/core#5577]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

We use the unbound resolver in forwarding mode on several OPNsense boxes hosted in internal networks. These unbound instances are used as caching DNS servers, and have no connectivity to the root DNS servers living on the Internet.

At unbound startup, `unbound-anchor` is run to update DNS roots. By default, unbound-anchor tries to contact DNS root servers. Since the box has no connectivity to foreign DNS servers, unbound startup is delayed until unbound-anchor gives up (timeout).

In such a context, running `unbound-anchor` with the `-Rf /etc/resolv.conf` argument is appropriate, as it would prioritize system-wide DNS servers from `resolv.conf` (which typically are upstream servers) over public roots to update the keys, while still allowing falling back to public roots on failure.

This is the only way to perform successful anchor updates at startup in offline network environments such as ours, and avoid a 60-second delay each time the unbound process is restarted.

**Describe the solution you like**

Modify unbound startup script at `/usr/local/opnsense/scripts/unbound/start.sh` to make unbound-anchor use the servers set in `resolv.conf`, still allowing a fallback to public roots on resolution failure:

```
--- /usr/local/opnsense/scripts/unbound/start.sh        2022-01-27 11:25:21.000000000 +0100
+++ start.sh    2022-02-14 13:45:50.232509000 +0100
@@ -30,7 +30,7 @@
 
 # prepare and startup unbound, so we can easily background it
 
-chroot -u unbound -g unbound / /usr/local/sbin/unbound-anchor -a /var/unbound/root.key
+chroot -u unbound -g unbound / /usr/local/sbin/unbound-anchor -a /var/unbound/root.key -Rf /etc/resolv.conf
 
 if [ ! -f /var/unbound/unbound_control.key ]; then
     chroot -u unbound -g unbound / /usr/local/sbin/unbound-control-setup -d /var/unbound
```

**Describe alternatives you considered**

Replace the startup script with our own amended version. But it'd be more future-proof to commit it upstream.

**Additional context**

- Already reported in issue #4427 (now closed)
- Same issue as #5441 (but different cause)

**Comment by swhite2** [comment]
This is a good solution for an offline environment, and I agree that it makes sense to use `/etc/resolv.conf` in this case. Especially since you're assuming a pure forwarding environment you wouldn't expect Unbound to make any recursive queries itself to bootstrap. However, I'm worried as to how generic this solution is.

When specifiying `-Rf /etc/resolv.conf`, regardless of whether query forwarding is enabled, Unbound will forward to any nameserver listed in `resolv.conf` in order - including localhost (which of course hasn't been bootstrapped yet). Besides it maybe being unwanted behaviour for security reasons, any nameserver listed here not responding in time will create a delay in the completion of `unbound-anchor`. This is even worse if you factor in *purely validated* environments in which all UDP port 53 traffic might be blocked and instead DNS-over-TLS is used. If it's blocked upstream, it will take even longer and make it very hard to debug.

I'm honestly wondering about the usefulness of `unbound-anchor` as before this program was shipped, by default, a `root.key` file was shipped with it instead. Also, the failover implemented in it writes out a hardcoded `root.key` file which gets updated as soon as Unbound has started - via the correct channels (be it forwarding, or DoT setups). 

Ideally this addition would be dependent on the fact that query forwarding is enabled. Also, as a general optimization, I'd make `unbound-anchor` run only if no `root.key` file is present, or is empty.
