### ISSUE TITLE
Pagination bugs - fix the number of displayed entries

### ISSUE THREAD

**Issue by arodier** [opnsense/core#5620]
**Important notices**

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

The pagination applet on any page, when selecting for instance 50 entries, will display "Showing 1 to 7 of 51 entries". It should display "Showing 1 to 50 of xxx entries", or if too complicated, "Showing 1 to 50 entries".

**To Reproduce**

Select, for instance, the firewall logs, and try to use the pagination.

This bug has been ongoing for years, I believe this is the kind of bug everyone knows exists but nobody dares to fix...

**Expected behaviour**

At least, display the number of entries displayed.
If possible, also display the total number of entries.

**Comment by AdSchellevis** [comment]
About the "Showing 1 to 7 of 51 entries" your referring to  https://forum.opnsense.org/index.php?topic=23847.msg132089#msg132089 , which is specific to that single grid and fixed in https://github.com/opnsense/core/commit/8100e506bf582a384ad52572d88c0db870b38b15.

Other discussions about total number of entries on unspecified length datasets are a known limitation, explained many times, so let me point you to one of them  
https://github.com/opnsense/core/issues/756#issuecomment-180848249

**Comment by fichtner** [comment]
Omitting final entry count via 6e6a0a280cac78
