### ISSUE TITLE
No IPv6 route or address to client (radvd/DHCPv6) issue

### ISSUE THREAD

**Issue by Joel-Muller** [opnsense/core#5626]
Hi since a few update all my clients doesn't get anymore a IPv6.

So my setup is:

OPNsense 22.1.2_1-amd64
FreeBSD 13.0-STABLE
OpenSSL 1.1.1m  14 Dec 2021

https://abload.de/img/14uj60.png
https://abload.de/img/29qjyy.png

No route and IPv6 to the all clients (1x iPhone, 1x Android TV,1xBrother Printer, 3x ArchLinux Computer)
My ISP said they changed nothing. It was working at previous releases
How I can fix it or are you pushing a patch?

**Comment by fichtner** [comment]
I've looked at a couple of such reports directly and I can assure you none of those could not be fixed. The problem always was a suboptimal setup of IPv6 to begin with and this certainly doesn't fall under community support.

Besides, the template wasn't used here so I don't think we can be of much assistance. See later comments by ticket automation...


Cheers,
Franco

**Comment by Joel-Muller** [comment]
I did https://www.tuxone.ch/2021/02/fiber7-access-mit-pfsense.html This tutorial.

It'was working flawless but since the latest update there are NO IPv6 addresses for my clients. So I didn't change anything!

**Comment by muh2000** [comment]
> 

same issue on my side, but for some reason i need to use a template for a bug that does not provide any error output.

i guess i have to go back to pfsense. i recomend you do the same.

**Comment by fichtner** [comment]
There's three things here:

1. A general lack of technical input needed for triage alone.
2. A particular lack of technical input needed to provide community support since we can't schedule a meeting and look at it in a video session.
3. A demotivating lack of community drive as presented by @muh2000 (go use what works for you but don't act petty).

I will happily close this issue if any of these points are being consolidated after this service message. No exceptions.


Cheers,
Franco

**Comment by muh2000** [comment]
1.  sorry, the appliance doesnt offer more than the red stop sign. it is all i can provide to you; besides the claim that it was working before 22.x
2. it became a bit harder to look at the logs since clog isnt installed anymore. or whatever was required for 'cat'-ing /var/log/system.log
3. i may sound petty, but when there isnt more to report on, i cannot present you the technical information or come accross 'non-petty' i am only reporting what i have and what i can be troubled with with, with my diabilities.  especially with no further output of the failed service, i dont have the energy anymore to look for a needle in the haystash that will not be found anyway.
4. i am not asking for service that a paying customer is getting.
5. ipv6 is very important in my network, of course i will be using/switching-to what is working after a short time of downtime.

thanks for your gratis appliance.

**Comment by fichtner** [comment]
1. it's not enough... it could be anything... we need IPv6 WAN LAN configuration settings, your ISP, your current WAN  and LAN addresses for it to make any sense.
2. The utility is called "opnsense-log" and there is a manual page for it.
3. See point 1. so "isnt more to report on" is wrong.
4. Fair enough :)
5. I agree. We have been working and fixing IPv6 ever since... this isn't a general issue... things happen all the time with ISPs, OS updates and also our patches.

Cheers,
Franco

**Comment by muh2000** [comment]
1. it is a static network from tunnelbroker.net/hurricane electric, thus no dynamic-v6 from a half assed provider
2. i am running a syslogserver and there is nothing to be found.
3. ok.  static config working on a prior version sounds very boring as a potential needle in a haystash. imho the new version sounds like a perfect needle. maybe a newer version chokes on an old config setting idk. possible of course.

i am fixing my sanity by removing opn/pfsense. 

have a nice weekend.

**Comment by fichtner** [comment]
It sounds like the same issue reported here... https://forum.opnsense.org/index.php?topic=26700.msg134109#msg134109

I'm happy to fix it now or later, with your help or without. Which will it be?

**Comment by muh2000** [comment]
sounds related, difference is: no opnsense is doing the GIF interface part. the tunnel-part is done by my router/dslmodem in front of opnsense. and opnsense was managing the whole /48 i had.

you can have no ipv6 connectivity upstream and radvd should announce the configured stuff anyway. which it is not doing. 

probably wthout me. i had wasted so much time the past 20 years for something hopefully working again and limiting my abilities to advance... i simply dont have energy left for a 'maybe successful' result.

sorry

**Comment by fichtner** [comment]
Well, maybe you can run an ifconfig and send your WAN configuration. How do you acquire the /48 prefix? Or are you just "using" it statically? If so that is not a good start... FreeBSD 13 is more prone to refusing you IPv6 routing if your WAN doesn't have at least a link-local IPv6.

**Comment by muh2000** [comment]
> 

i was able to ping the world FROM my wan interface.

tunnelbroker gives you the posibillity to acquire a dedicated static subnet for your own usage.

as i sai earlier: it was working before 22.x

**Comment by fichtner** [comment]
> as i sai earlier: it was working before 22.x

Maybe I should have said use 21.7 then? What's the reason not to use it? Maybe we can get some sanity in this discussion.

**Comment by muh2000** [comment]
i didnt found a way to revert.

**Comment by fichtner** [comment]
Because there is none. Happy to be of further service.

https://github.com/opnsense/changelog/blob/33adbc10d98db0f9c4412696bc58c3614ea6d6fa/community/22.1/22.1#L16-L21

**Comment by fichtner** [comment]
And of course https://github.com/opnsense/changelog/blob/33adbc10d98db0f9c4412696bc58c3614ea6d6fa/community/22.1/22.1#L190

**Comment by muh2000** [comment]
luckily i only had the radvd not working anymore -issue....

i try my best doing my network fully dynamic. probably will have issues getting my v6 address configured to be reachable on certain ports...

**Comment by KagurazakaNyaa** [comment]
> 1. it's not enough... it could be anything... we need IPv6 WAN LAN configuration settings, your ISP, your current WAN  and LAN addresses for it to make any sense.
> 2. The utility is called "opnsense-log" and there is a manual page for it.
> 3. See point 1. so "isnt more to report on" is wrong.
> 4. Fair enough :)
> 5. I agree. We have been working and fixing IPv6 ever since... this isn't a general issue... things happen all the time with ISPs, OS updates and also our patches.
> 
> Cheers, Franco

I had basically the same problem after upgrading from 21.7.7 to 22.1.4, but this issue doesn't seem to follow the bug report template, should I just continue with this issue or file a new bug report?
If I want to help you fix this problem, what should I do? Provide the information you mentioned directly here? Or include them in a new issue?

**Comment by fichtner** [comment]
@KagurazakaNyaa if you could open your own report we can work on it there no problem
