### ISSUE TITLE
Meaningless VLAN deviceId

### ISSUE THREAD

**Issue by Zepmann** [opnsense/core#5649]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

This was introduced with 22.1.4, and did not occur with 22.1.3.

URL:
https://opnsense/ui/interfaces/vlan

When adding a new VLAN to an existing interface, the deviceId of the VLAN will be 'vlanNN', where NN is the first free number starting at 01. The result is an ugly deviceId such as 'vlan01'. This deviceId has no value to the user.

An example of an older deviceId is 'igb1_vlan22', which tells the user which network device it concerns, and which VLAN it concerns.

The older deviceIds make it clear on the interface assignments page which interface concerns which network device and which VLAN. These details are lost with the new deviceIds. This requires the user to access the VLAN configuration page to see which ambiguous deviceId is mapped to which combination of network card and VLAN.

**To Reproduce**

1. Go to the noted URL
2. Create a new VLAN. Note that the deviceId value is empty, and that it is impossible to explicitly define a deviceId.
3. Save the new VLAN.
4. Edit the new VLAN. Notice its ambiguous deviceId, which will probably be 'vlan01'.

**Expected behavior**
When creating a VLAN, a deviceId should be proposed that has meaning to the user (i.e.: it contains the network device and the VLAN number). Lacking such a proposal for whatever reason, the user should be able to provide their own deviceId.

**Describe alternatives you considered**

A workaround is to backup the configuration, edit the configuration manually to change the device IDs, restore the configuration. This is quite cumbersome.

Another workaround is simply to accept the new situation, but this would be quite a regression.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 22.1.4_1-amd64 (upgraded from 22.1.3 directly to 22.1.4_1)
FreeBSD 13.0-STABLE
OpenSSL 1.1.1n 15 Mar 2022

**Comment by fichtner** [comment]
No, this is intended and I’m willing to let your ignorance slide on the matter. If you are interested I’m willing to give context in the form of tickets to educate yourself.


Cheers,
Franco

**Comment by Zepmann** [comment]
I read the [changelog](https://forum.opnsense.org/index.php?PHPSESSID=klcq4u681239cq62g58pna185s&topic=27631.0), the [blog](https://opnsense.org/blog/), and looked through [previous issues](https://github.com/opnsense/core/issues?q=is%3Aissue). I know that VLAN support was given an overhaul in 22.1.4, but nowhere do I read if or why this would change deviceIds.

Calling my unfamiliarity over this regression ignorance is less about my unwillingness to learn and more about your unfriendly attitude.

**Comment by AdSchellevis** [comment]
It isn't a regression as mentioned by @fichtner, the maximum device name length and ease of coping with changes (https://github.com/opnsense/core/commit/99aacf73266bee3bc215e1c6fab883c8fd34717d) are the reasons. From the gui's perspective device names don't matter, if you are searching for internals, it helps to read some commits  from time to time.

**Comment by Zepmann** [comment]
Thanks for clarifying, @AdSchellevis . That makes sense.

I do not think it is reasonable to assume that everyone will read commits in the hope of finding issues, especially since not every OPNsense user can read or understand code. Furthermore, the commit log is not part of the list of resources to consider before filing a bug. If you expect this, it might be a good idea to update the template to include this as something to acknowledge before opening an issue.

**Comment by beaukey** [comment]
@Franco: maybe next time give an answer like: "This is by design. Link: {HTML link here}". Then it would be perfectly clear.

@AdSchellevis: as Zeppman correctly stated (after his thorough research) you cannot expect each user to find and understand all of the underlying motivation of changes in the product. User uses product, product breaks after upgrade, tries to find solution and is treated this way?

**Comment by AdSchellevis** [comment]
@beaukey 
> @AdSchellevis: as Zeppman correctly stated (after his thorough research) you cannot expect each user to find and understand all of the underlying motivation of changes in the product. User uses product, product breaks after upgrade, tries to find solution and is treated this way?

Nor does anyone expect, but when pointing to internal changes (name changed, functionality didn't, nothing broke either), it's a bit strange to assume it's a regression without looking into the underlying details.  A simple question (either on the forum or on GitHub) would have resulted in a simple and clear answer, assumptions (it's different and thus wrong) usually don't. Again from the gui's perspective nothing changed, from the products perspective it's more reliable now.

**Comment by Zepmann** [comment]
@AdSchellevis 

> Nor does anyone expect, but when pointing to internal changes (name changed, functionality didn't, nothing broke either), it's a bit strange to assume it's a regression without looking into the underlying details.

From the perspective I wrote my reaction, it is a regression. It still is from that perspective:

```
When adding a new VLAN to an existing interface, the deviceId of the VLAN will be 'vlanNN', where NN is the first free number starting at 01. The result is an ugly deviceId such as 'vlan01'. This deviceId has no value to the user.
```

This has not changed, and therefore it was and is a regression **in my opinion**. Something can be both a regression and 'not a bug, but a feature'. Bugs are unexpected, features are not.

**Comment by AdSchellevis** [comment]
let's agree to disagree and get on with our lives.

**Comment by fichtner** [comment]
Ok, where to start... this is a fun one.

https://en.wikipedia.org/wiki/Ignorance "Ignorance is a lack of [knowledge](https://en.wikipedia.org/wiki/Knowledge) and [information](https://en.wikipedia.org/wiki/Information)."

There's really no point in being offended by the word as witnessed by the subject alone: Meaningless VLAN deviceId

First of all the device ID isn't meaningless. Internally "vlanif" always existed in the configuration structure and other device types have a similar registration of their device ID. The word device ID here helps generalise the term of "xxxif" key to be presented by the GUI.

Yes, classically a VLAN is named e.g. `igb1_vlan1200` but that's already 13 characters out of 16 device name characters allowed in FreeBSD. You can see how that might be an issue without in-depth technical knowledge. If we add the QinQ support on top would we name it `igb1_vlan1200_vlan1201`? No, because this is already 22 characters. It's also clear that embedding either the parent or the tag name into the device name would mean to adjust the device ID anytime an information changes... not just there but also in interfaces which assign these. It adds more unnecessary complexity that e.g. LAGG or GIF or GRE do not possess.

Furthermore the name "vlanX" is what FreeBSD/ifconfig uses and all other device types with a device ID embedded.

We add the "vlan0X" zero trick is to distinguish between our devices and manually created devices on the system... which I don't personally like but serves an important purpose of not causing assignment clashes.

If you want a meaningful description you should see that we did already add it some time ago to ifconfig output and everywhere else in the GUI you should get context about the devices you can select... I'm 100% sure interface assignment gives you a hint and even a comment of what was inserted in the VLAN.

You can also observe the overlong device ID within this ticket where "_stf" suffix assigned to a VLAN device can cause the overlong device name: #3222. The code itself therefore uses the ugly "wan_stf" trick which, you guessed it, is very unintuitive either since nothing else names devices according to assigned interfaces.

So now the real question is what does this renaming break technically? If one relies on "vlanif" key value for device naming nothing broke previously in the code and nothing will in the future.

Last but not least, "regression" is the wrong word here for moving internals and would also suggest something doesn't work because of it. If you can pinpoint the line that indeed breaks because of this name change (note that old devices remain the same for the time being) we will gladly fix it. This is what this issue tracker is for.


Cheers,
Franco

**Comment by Zepmann** [comment]
> https://en.wikipedia.org/wiki/Ignorance "Ignorance is a lack of knowledge and information."
> There's really no point in being offended by the word as witnessed by the subject alone: Meaningless VLAN deviceId

First of all, I am not offended. Rude people are everywhere, including on the internet. I deal with them daily, and you have done nothing to phase me whatsoever.

What makes your reaction rude is:

> No, this is intended and **I’m willing to let your ignorance slide on the matter**. If you are interested I’m willing to give context in the form of tickets **to educate yourself**.

You do not explain anything. You just state that I do not know something which you know with terms that are considered negative in common use of the English language. Instead of 'educating', you are ridiculing.

I did not know the reason for the change in deviceId naming, as the information was not available in any user-centric communication channel. I do not think it is reasonable that an OPNsense user needs to read every commit comment for each released version. Even if you think it is reasonable, add it to the bug report instructions.

> First of all the device ID isn't meaningless.

Consider this part, which was part of the first post:

> This deviceId has no value **to the user**.

It has no value to the user who observes it, compared to the old value. Seeing just 'vlan01' in an overview does not say anything compared to something that both mentions the relevant network device and VLAN. So for the user, it is meaningless.

> If you want a meaningful description you should see that we did already add it some time ago to ifconfig output and everywhere else in the GUI you should get context about the devices you can select... I'm 100% sure interface assignment gives you a hint and even a comment of what was inserted in the VLAN.

You are confidently incorrect:

![vlan](https://user-images.githubusercontent.com/4273943/160344461-92dc3025-6d17-4878-b672-d765fbe7a2e4.png)

> So now the real question is what does this renaming break technically? If one relies on "vlanif" key value for device naming nothing broke previously in the code and nothing will in the future.

Nowhere did I state it breaks things technically. I do not understand why you keep focusing on the technical part, while from the bug report itself it is clear that I am viewing this from a user perspective. As shown by the screenshot, from a user perspective who looks at the VLAN assignment page, it is a regression. I understand there is a technical explanation, and it would have been helpful if this was given first and foremost instead of just a snide comment.

A suggestion to improve the situation about the interface assignment page is to show the relevant network device and the VLAN in the description of the VLAN interface in the dropdown menu, similarly to PPPoE interfaces.

**Comment by fichtner** [comment]
Ok, fair enough. This is the end of the line for my technical assistance.
