### ISSUE TITLE
Incorrect DHCPv6-PD prefix calculation

### ISSUE THREAD

**Issue by cnbatch** [opnsense/core#5847]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Original post from a Chinese forum: https://www.v2ex.com/t/863738

Translated as below:

- Home Internet Service, fiber optic modem switched to bridge mode
- PPPoE configured on Gateway Router (OPNsense)
- The WAN port successfully obtained an IPv6 address by DHCPv6 from ISP, and also obtained an IPv6 address with prefix 60, 2001:aaaa:bbbb:**7890**::/60
- An IPv6 address 2001:aaaa:bbbb:**7890**:cccc:dddd:eeee:1/64 is also assigned to the LAN port successfully
- This LAN port is connected to another internal subnet router
- DHCPv6 service is enabled on the LAN Port, the prefix delegation range is from ::8 to ::c , prefix 62; A subnet of the IPv6 address with prefix 62, 2001:aaaa:aaaa:**7894**::/62 is assigned to the internal subnet router.
- DHCPv6 service is also enabled on this internal subnet router to obtain IPv6 address from the Gateway Router.
- This internal subnet router successfully obtained an IPv6 address with prefix 62, 2001:aaaa:bbbb:**780c**::/62

Question from the original post: Why the IPv6 address / prefix assigned to the internal subnet router is not 2001:aaaa:bbbb:**789c**::/62 ?

The correct address should be **7898** or **789C**, instead of **780c** .

In the discussions, another user has said this bug exists for a very long time (2 - 3 years)

**Expected behavior**

Calculate the IPv6 address prefix correctly.

**Describe alternatives you considered**

How about rewrite IPv6 calculation codes  like this:
https://stackoverflow.com/questions/10085266/calculate-an-ipv6-range-from-a-cidr-prefix

Instead of substr function

**Environment**

The OP said the gateway router is updated to the latest version.
I believe the version should be OPNsense 22.1.9 (amd64, OpenSSL).

**Comment by fichtner** [comment]
Is this automatic or manual tracking?

**Comment by fichtner** [comment]
https://github.com/opnsense/core/blob/98fe7a38813a78ab818d215bde530711d5676818/src/etc/inc/plugins.inc.d/dhcpd.inc#L1306-L1404

**Comment by fichtner** [comment]
Note to self: not sure why /61 is missing in switch statement.

**Comment by cnbatch** [comment]
It should be automatic

**Comment by vfreex** [comment]
This is a problem with the the algorithm to calculate a prefix for downstream devices: https://github.com/opnsense/core/blob/98fe7a38813a78ab818d215bde530711d5676818/src/etc/inc/plugins.inc.d/dhcpd.inc#L1371
https://github.com/opnsense/core/blob/98fe7a38813a78ab818d215bde530711d5676818/src/etc/inc/plugins.inc.d/dhcpd.inc#L1373

With a prefix `2001:aaaa:bbbb:7890::/60` got from ISP from an upstream wan interface and a range `::8 - ::C` configured to a downstream lan interface, OPNsense does the following calculation:

1. $pd_prefix_from_array_out[3] = sprintf("%04s", $ifcfgipv6arr[3]); // make it 4 bytes
2. $pd_prefix_from_array_out[3] = substr($pd_prefix_from_array_out[3], 0, 2) . $pd_prefix_from_array[2];
`pd_prefix_from_array_out ` was something like `["2001", "aaaa", "bbbb", "7890", "0", "0", "0", "0"]`.
`$pd_prefix_from_array` is something like `["0", "08"]` .
This line concatenate the first-2 letter of the 4nd group of four hexadecimal digits of the upstream prefix `78` with the 2 prefix_from digits `08`. So the downstream prefix becomes `["2001", "aaaa", "bbbb", "7808", "0", "0", "0", "0"]`.

4. $pd_prefix_to_array_out[3] = sprintf("%04s", $ifcfgipv6arr[3]); // make it 4 bytes
5. $pd_prefix_to_array_out[3] = substr($pd_prefix_to_array_out[3], 0, 2) . $pd_prefix_to_array[2];
Similarly, `pd_prefix_to_array_out ` was also something like `["2001", "aaaa", "bbbb", "7890", "0", "0", "0", "0"]`.
`$pd_prefix_to_array` is something like `["0", "0c"]` .
This line concatenate the first-2 letter of the 4nd group of four hexadecimal digits of the upstream prefix `78` with the 2 prefix_from digits `0c`. So the downstream prefix becomes `["2001", "aaaa", "bbbb", "780c", "0", "0", "0", "0"]`.

The problem here is function `dhcpd_dhcp6_configure` does prefix calculation with string truncation and concatenation instead of bitwise operations. It can't correctly handle prefix boundaries in the middle of a hexadecimal digit (like `/62`). Also, the switch block in the function assumes the certain upstream prefix lengths for given downstream prefix lengths, which happens to assume a prefix length of `/56` for a downstream prefix length of `/62`.

In my opinion, this  string truncation and concatenation based calculation should be completely rewritten in order to handle arbitrary prefix lengths.

**Comment by fichtner** [comment]
Thanks, I will take a closer look tomorrow.

**Comment by fichtner** [comment]
@cnbatch @vfreex what do you think about 4f082e9ad6d2 ?

**Comment by fichtner** [comment]
@cnbatch thanks, if we can get @vfreex feedback as well I'm happy to include it in a release

**Comment by vfreex** [comment]
@fichtner Hi, thanks for improving this. The new function `merge_ipv6_address` looks nice.
I found a few issues in your commit, but I am not quite familiar with the code base so I could be wrong:

**Comment by fichtner** [comment]
Thanks for your input. I’m happy to improve it further if I know the issue.

here for automatic we probably have something like “::” start to “ffff:….” as end. The function should handle this correctly.

If we want to have manual settings users use suffix annotation like “::aaaa:0:0:0:0” to “::dddd:ffff:ffff:ffff:ffff” to be precise. It’ll be the user to adapt this to correct prefix to be used.

Cheers,
Franco

**Comment by vfreex** [comment]
Hi, Just make sure we are talking about the same thing: To hand over IPv6 prefixes instead of individual addresses within the specific range to a downstream router that is connected to the configured interface. Following is an example ISC DHCP server config:

```
shared-network NETWORK1 {
    subnet6 2001:db8:1234:5678::/64 {
        range6 2001:db8:1234:5678::100 2001:db8:1234:5678::1ff;
        option dhcp6.name-servers 2001:db8::53:1, 2001:db8::53:2;
        prefix6 2001:db8:1234:1000:: 2001:db8:1234:3f00:: /56;
    }
}
```
In this config file, option `prefix6 2001:db8:1234:1000:: 2001:db8:1234:3f00:: /56;` tells `dhcpd` to lease a prefix from `2001:db8:1234:1000::/56, 2001:db8:1234:1100::/56, 2001:db8:1234:1200::/56, ..., 2001:db8:1234:3e00::/56, 2001:db8:1234:3f00::/56`. So there is no address ending with something like `::ffff:ffff:ffff:ffff`.

Prior to your commit, users are expected to specify prefix range `::10` to `::7f` and length `56` on the web UI, then OPNSense prepends the prefix `2001:db8:1234::` obtained from upstream DHCPv6 server and composite the resulting range `prefix6 2001:db8:1234:1000:: 2001:db8:1234:3f00:: /56;`.

**Comment by fichtner** [comment]
@vfreex thanks I think I understand now but this is highly problematic: `::10 to ::3f` is verified as IPv6 individually, but actually treated as something like `::10:0:0:0:0 to ::3f:ffff:ffff:ffff:ffff` and there isn't really a distinction between using a suffix annotation and using full scope like you would on no-tracked interfaces. We need to break something here to repair it properly. Let me think about it....

**Comment by fichtner** [comment]
@vfreex here's 8d4b63d3063e7a and 5fa042b687a to make this progress -- I added a backwards fix but it's not very elegant and also corrected the help text to what really should be done.

**Comment by vfreex** [comment]
@fichtner Thank you. This generally LGTM. I added a comment about backward fix to https://github.com/opnsense/core/commit/5fa042b687ad59f27df6f3b5d7afd08fc04f0396#diff-8254561e8f58e0691841e5f1e905da1cf6a7db695a2ade4c8ec6e15ac62cdfd0R1353

**Comment by fichtner** [comment]
@vfreex thanks a lot for your help, will get this into 22.7.
