### ISSUE TITLE
changing IP addresses from the console doesn't work

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#6]
Code in question has probably been broken for quite a while... via @timelessp (twitter)

**Comment by phil-davis** [comment]
Plenty of bugs in rc.initial.setlanip fixed in pfSense during Dec 2014. I had a quick look at the diff between the OPNsense and pfSense versions and, apart from some re-engineering of the y/n answer processing I did recently in pfSense, there are other just dumb bugs fixed - like line 323 and 546.
I guess you guys had to take a fork at some point in time, but there really are bucket loads of "just plain bugs" fixed in the master of pfSense in the last few months. Unfortunately it will take a bit of work now for you to look at all the diffs and work out all the obvious bug fixes to take...
I guess this is the life of forks - similar "bonus effort" has to be put in porting pf features and fixes between OpenBSD and FreeBSD and a load of other similar "parallel" projects that are all trying to find and fix a similar list of bugs.

**Comment by fichtner** [comment]
Thanks for the hint. :) Licensing is unclear so we ought to takle these issues as they appear in our code base. Except these are your patches and you give us permission under them BSD 2-clause license?

**Comment by phil-davis** [comment]
Most of the changes/fixes were done by me and I am very happy for you, your project and anybody to make use of whatever of it you like, under the license you are using.
For enhancements and re-engineering I understand that there is an issue about what is under what license and using it direct or taking it and re-engineering it into another product.
But for bug fixes, copying someone elses fix and researching it yourself and finding the fix end up being one and the same thing. If I see code like:
if (x = y) { }
and realize it is just wrong and should be:
if (x == y) { }
and submit that fix to some project, but then do not give "permission" for my fix to be used by others, then what are others supposed to do - they are stuck and somehow cannot fix their version of the code, because somehow I have managed to "copyright" the correct use of "==". That is a ridiculous position to be in!
So I do not see how things that are simply fixing dumb bugs can be subject to license, because in the end "everyone" will have to fix them in the same (or extremely similar) way.

**Comment by fichtner** [comment]
That's very kind, thank you!

**Comment by fichtner** [comment]
fixed for 15.1.1
