### ISSUE TITLE
Slow boot / DNS timeout @ VTI with hostname

### ISSUE THREAD

**Issue by Lokutos** [opnsense/core#6052]
**Describe the bug**

if you are using VTI Routed based tunnel with dns remote gateway your boot hangs at rename the ipsec interface. 

**To Reproduce**

i use a Ipsec IPv4 tunnel with:

Phase 1 Remote Gateway a FQDN that can public and private resolve tho an IP. 
Phase 2 Mode Routed Base

i have enabled Unbound 
i have set System -> Settings -> General -> DNS Servers to 8.8.8.8 and 8.8.4.4 (use Gateway none)

**Expected behavior**

normal boot time / maeby unbound hase to be start early

**Describe alternatives you considered**

change from fqdn gateway to IP

**Screenshots**
![Screenshot 2022-07-03 151638](https://user-images.githubusercontent.com/10000982/192731146-e754d39d-6296-4b1c-bf4f-acce4aa68d3b.png)

**Relevant log files**
`2022-09-28T10:13:26   Error   php   /usr/local/etc/rc.bootup: The command '/sbin/ifconfig 'ipsec5' 'inet' tunnel '136.243.195.58' 'fqdn.off.otherfirewall' up' returned exit code '1', the output was 'ifconfig: error in parsing address string: Name does not resolve'   
2022-09-28T10:11:56   Error   php   /usr/local/etc/rc.bootup: Device ipsec5 required for ipsec5, configuring now`

**Additional context**

Reference https://forum.opnsense.org/index.php?topic=29207.0

**Environment**
Also in 22.1. Installed as KVM 

Versions	OPNsense 22.7.4-amd64
FreeBSD 13.1-RELEASE-p2
OpenSSL 1.1.1q 5 Jul 2022

**Comment by marinbernard-pep06** [comment]
Same issue on our side. Possibly a chicken and egg problem, since:

- Local services such as Unbound expect functional network interfaces
- VTI interfaces with FQDN as endpoints require DNS resolution, but cannot rely on Unbound which is not yet available
- `/etc/resolv.conf` itself seems to be generated _after_ VTI interface configuration

I suppose the configuration of VTI interfaces should happen later in the boot process, after `/etc/resolv.conf` has been generated and Unbound started. I do not know if multi-stage interface configuration is possible with the startup scripts.

**Comment by fichtner** [comment]
I'd expect /etc/resolv.conf to stick around from the last boot so that if you require unbound/dnsmasq to give out the IP of the host that's likely not going to work since DNS services are started after devices are configured because they need devices to be configured in order to work.

I'll change the boot sequence slightly in a commit in a second, but it very likely won't fix the issue.


Cheers,
Franco

**Comment by Lokutos** [comment]
thats right resolv.conf is there but because it looks like 

nameserver 127.0.0.1
nameserver 8.8.8.8
nameserver 8.8.4.4

it try to resolv over unbound -> wait for timeout -> i think 1 minute or more 

Maybe it's just a too long timeout? because a alternate DNS (2/3) is available

**Comment by fichtner** [comment]
If you try to reorder 127.0.0.1 to the back would that help?

Set "Do not use the local DNS service as a nameserver for this system" under System: Settings: General, but add 127.0.0.1 to manual DNS servers above...

**Comment by Lokutos** [comment]
hi, in general yes, but for me not because i need the local dns for internal static results. 

But thanks, i think the commit can resolve it #untested

**Comment by fichtner** [comment]
Commit won’t fix it. Unbound/Dnsmasq are still started later on.

As far as complexity requirements go for your DNS layout I think that a more cohesive approach is required.

**Comment by marinbernard-pep06** [comment]
An ugly workaround would be to cache the IP address of the remote endpoint at shutdown, and use it at startup to configure the VTI interface. The remote IP address could be updated later in the startup process, once DNS resolution has become available.

Another option would be to postpone the whole VTI setup _after_ local services are started, but this may cause more harm than good, since some services may depend on those interfaces.

**Comment by AdSchellevis** [comment]
Using the hooks available (https://docs.opnsense.org/development/backend/autorun.html) there are enough options to work around network design issues, it's unlikely work arounds will be added to the product as it always leads to races in other areas.
