### ISSUE TITLE
2FA - separate dialog box for OTP when connecting to vpn

### ISSUE THREAD

**Issue by Gromigno** [opnsense/core#6228]
All VPN connection that I use with 2FA never ask to combine the OTP password with the local password in order to be authenticated. 
It's not very convenient, since the passwords are time based and we still have to type the local password after having typed the OTP one.
I suggest opnsense uses a 2-step authentication.
Enter the local login+password
Type in the OTP code

On top of that, this make impossible to authenticate with 2FA through an external RADIUS system.
If for some  reasons, it is not possible or too difficult to support this mechanism while using internal local database, it would be very usefull to support 2 steps 2FA when using RADIUS;
This is clearly limiting possibilities of use in integrated environnements where user have Single 2FA credential for all access; 

For example: 
In some scenari, the second factor is not requested (if the source IP/mac is already known). The RADIUS or MFA solution knows the logic and may request only password authentication without second factor is risk is low.
Because of the actual limitation, the only way to authenticate via a RADIUS/MFA solution is to use OPT password only without user password, which is a drow back in term of security.

This issue, could drive me away from opnsense, as this is more and more critical to users / companies.

Thanks,

**Comment by fichtner** [comment]
@Gromigno Would you mind qualifying "VPN"? For example, OpenVPN static challenge is an optional client-side setting and well supported for many years in OPNsense.

**Comment by Gromigno** [comment]
Thank you but it doesn't help. it needs to be in a separate dialog box. The request of the TOPT will be decided by the radius server who has the intelligence to decide if it is requested or not, case by case.

> @Gromigno As a workaround you could activate "Reverse Token Order" under System --> Access --> Servers --> Your login server so you can type in the password and then the TOTP.

**Comment by AdSchellevis** [comment]
It’s a client “thing” as @fichtner already noted, OpenVPN supports it, others might, I don’t know. The magic is usually the order in which the password and token are send to the server, I don’t expect our otp is much different than any other over radius.

**Comment by AdSchellevis** [comment]
For gui login it might not be very difficult, but implementing it properly still takes quite some time…. The ticket is about VPN’s, for which I already explained the impact above.

**Comment by meyergru** [comment]
Should I open another issue for GUI login?

**Comment by AdSchellevis** [comment]
That would be more polite than hijacking this one indeed. Searching if such a ticket already exists (either open or closed) would even be better….

**Comment by mimizone** [comment]
I'll be following this ticket as I have interest in using 2FA with our VPN too.
Today I haven't enabled it cause the user experience is not create from the client point of view because of the juggling required for the copy/past/concatenate, and the fact that it is not obvious to the user what has to be done.
We are using OpenVPN Connect on Mac and Windows.

Ultimately I'd like to use Google as our LDAP provider for VPN accounts, which I believe is done via the Radius integration in OPNSense/OpenVPN.
Having the capability to have a separate field in the VPN client is the best, much easier to understand for the users.
I assume it's not only an OPNSense issue and would require some testing of the entire chain with different clients/backends.

Btw, I have created a separate ticket regarding having the same separate field for the web UI login.
Completely unrelated to this issue.

**Comment by mimizone** [comment]
or maybe I need to dig a bit into older tickets. and hopefully an existing doc somewhere of how it has been done with Google Auth. Sorry for the noise if it is something that has been solved. My own user error in the search of existing issues if that's the case.... https://github.com/opnsense/core/issues/3290

**Comment by mimugmail** [comment]
Just for the archive:
https://github.com/google/google-authenticator-libpam/issues/112#issuecomment-484054832
