### ISSUE TITLE
Feature request: Alias and Category support for traffic shaper

### ISSUE THREAD

**Issue by janwiesemann** [opnsense/core#6615]
**Is your feature request related to a problem? Please describe.**

I've just looked into the traffic shaper to change a few settings and noticed, that it can get quite messy even with just a few rules. It would be great to include aliases in the source/destination field. Support for categories would also be a welcome addition.

<img width="1053" alt="image" src="https://github.com/opnsense/core/assets/1347201/d40e625b-cdd0-41d3-ad0b-867a94672b5a">
What the f is `5.71.95.266` referring to? (... Yes, I know ... It's referring to nothing. It's not a valid ip...)
<br/><br/>

**Describe the solution you like**

- Alias (from `/ui/firewall/alias`) support for Shaper in `ui/trafficshaper#rules`.
- Category (from `/ui/firewall/category `) support/field for Shaper `ui/trafficshaper`.

**Describe alternatives you considered**

Using painfully long naming prefixes and descriptions

**Additional context**

Tanks for your time and efforts on OPNsense <3

...and I like potatoes. Just saying...

**Comment by fichtner** [comment]
I'm sorry, what is this? You didn't even hit "save" and ask why you put in garbage?

<img width="877" alt="Screenshot 2023-06-13 at 10 56 02" src="https://github.com/opnsense/core/assets/1915288/bd66d813-e0a5-4158-9c5e-b4fc2fe4552f">

Not sure what categories are here what that means. Aliases don't work without much work because ipfw(8) unlike pf(8) is very restrictive towards source/destination content.


Cheers,
Franco

**Comment by janwiesemann** [comment]
> I'm sorry, what is this? You didn't even hit "save" and ask why you put in garbage?
> 
> <img alt="Screenshot 2023-06-13 at 10 56 02" width="877" src="https://user-images.githubusercontent.com/1915288/245416279-bd66d813-e0a5-4158-9c5e-b4fc2fe4552f.png">

@fichtner I know, it's just an example.
>> What the f is `5.71.95.266` referring to? (... Yes, I know ... It's referring to nothing. It's not a valid ip...) 

> Not sure what categories are here what that means. Aliases don't work without much work because ipfw(8) unlike pf(8) is very restrictive towards source/destination content.

I'm referring to the coloured dots, which are also present in the firewall aliases, rules and so on.
<img width="275" alt="image" src="https://github.com/opnsense/core/assets/1347201/badc90c5-df55-433b-954c-9d8b24060dc8">
<img width="265" alt="image" src="https://github.com/opnsense/core/assets/1347201/3acdefdd-f98f-476c-bf33-aedcc03d21ce">

**Comment by adamb53** [comment]
Being able to specify aliases in the destination and source fields would be awesome! It would align this area with other ones that do allow this, making it much easier to create rules where you might have multiple destinations for a single source.

It would also make it easier to manage and keep tidy as well as identify quickly within the rule what the destinations (or sources) are without needing to write an essay in the description.

Sounds like Franco is saying it might be a bit of effort due to the way the shaper works? @fichtner is it an unachievable amount of effort?
