### ISSUE TITLE
otp seed working on multiple devices

### ISSUE THREAD

**Issue by RayllanSouza** [opnsense/core#6627]
**Important notices**

Our forum is located at https://forum.opnsense.org , please consider joining discussions there in stead of using GitHub for these matters.

Before you ask a new question, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

Hey guys, I'm implementing this opnsense MFA, but I realized that the seed is not invalid when activating my device, is there any way I can make the seed invalid after activation?

**Comment by g-a-c** [comment]
Could you elaborate more? Which sets of instructions are you following? What steps have you taken?

TOTP seeds work on multiple devices by design, the seeds are not "activated" and "deactivated", it's just a shared key that both sides of the transaction need to know about, and if both have the same seed and time, then they generate the same "random" code.
