### ISSUE TITLE
system_log ssl3_get_record:wrong version number / tls_early_post_process_client_hello:unsupported protocol 

### ISSUE THREAD

**Issue by benvanthom** [opnsense/core#6689]
Im System-Log werden mehrfach pro Sekunden Log-Einträge geschrieben, welche die Fehler enthalten:

`lighttpd 43676 - - (/usr/obj/usr/ports/www/lighttpd/work/lighttpd-1.4.71/src/mod_openssl.c.3350) SSL: 1 error:14201076:SSL routines:tls_choose_sigalg:no suitable signature algorithm

lighttpd 43676 - - (/usr/obj/usr/ports/www/lighttpd/work/lighttpd-1.4.71/src/mod_openssl.c.3350) SSL: 1 error:14094419:SSL routines:ssl3_read_bytes:tlsv1 alert access denied

lighttpd 43676 - - (/usr/obj/usr/ports/www/lighttpd/work/lighttpd-1.4.71/src/mod_openssl.c.3350) SSL: 1 error:1408F10B:SSL routines:ssl3_get_record:wrong version number

lighttpd 43676 - - (/usr/obj/usr/ports/www/lighttpd/work/lighttpd-1.4.71/src/mod_openssl.c.3350) SSL: 1 error:142320EB:SSL routines:tls_handle_alpn:no application protocol

lighttpd 43676 - - (/usr/obj/usr/ports/www/lighttpd/work/lighttpd-1.4.71/src/mod_openssl.c.3350) SSL: 1 error:14209102:SSL routines:tls_early_post_process_client_hello:unsupported protocol

lighttpd 43676 - - (/usr/obj/usr/ports/www/lighttpd/work/lighttpd-1.4.71/src/server.c.1240) [note] sockets enabled again

lighttpd 43676 - - (/usr/obj/usr/ports/www/lighttpd/work/lighttpd-1.4.71/src/server.c.1248) [note] sockets disabled, connection limit reached

Aktuell gehen wir davon aus, dass die Fehler durch die Captive-Portal Webseite ausgelöst werden. Jedoch gibt es keine Einstellungen für den dazugehörigen Webserver. Die Captive-Portal Webseite hat auch keine Fehler angezeigt und der Dienst funktioniert einwandfrei!

Die Frage ist, gibt es eine Lösung dafür oder zumindest, dass es nicht mehr ins Logfile geschrieben wird? 

Software version and hardware:

AMD EPYC 7402P 24-Core Processor (24 cores, 48 threads)
OPNsense 23.1.11-amd64
FreeBSD 13.1-RELEASE-p8
OpenSSL 1.1.1u 30 May 2023
Captive-Portal 
Let's Encrypt Zertifikat

**Comment by gstrauss** [comment]
Some of these errors might possibly be caused by clients using older TLS stacks.  Modern lighttpd TLS configuration defaults to stronger ciphers to try to avoid some types of downgrade attacks.  However, if you have legitimate clients that you must support and those clients are not using modern TLS, then you may consider configuring your lighttpd.conf to permit earlier versions of TLS, and weakers ciphers.  See [lighttpd TLS docs](https://redmine.lighttpd.net/projects/lighttpd/wiki/Docs_SSL)

---

> [note] sockets disabled, connection limit reached

Separately, if your site is busy and your server has the resources to support more connections, then you might want to modify lighttpd.conf to increase number of fds and number of connections permitted.

[server.max-fds](https://redmine.lighttpd.net/projects/lighttpd/wiki/Server_max-fdsDetails)
[server.max-connections](https://redmine.lighttpd.net/projects/lighttpd/wiki/Server_max-connectionsDetails)

e.g.
`server.max-fds = 8192`
`server.max-connections = 3072`

**Comment by gstrauss** [comment]
> But we have to handle the log entries somehow.

lighttpd logs those legitimate client errors.

In lighttpd.conf, you can control to where lighttpd logs and can configure a custom log filter, if desired.

One option is a piped-logger.
[server.errorlog](https://redmine.lighttpd.net/projects/lighttpd/wiki/Server_errorlogDetails)
e.g. `server.errorlog = "| /path/to/custom_log_filter.py"`
The custom log filter could be written to filter out or to report aggregate counts for specific log messages.

Another option is sending the logs to syslog.
[server.errorlog-use-syslog](https://redmine.lighttpd.net/projects/lighttpd/wiki/Server_errorlog-use-syslogDetails)
e.g. `server.errorlog-use-syslog = "enabled"`
`server.syslog-facility` can be set to the syslog facility to use when sending logs to syslog.

> you suggest the lighttpd.conf change, but where to set it persistently in OPNsense?

I am a lighttpd developer and not as familiar with OPNsense specifics, so I defer to OPNsense documentation for how you might do that.  It appears that OPNsense provides `/usr/local/etc/lighttpd_webgui/conf.d/*.conf` for lighttpd customizations.
https://github.com/opnsense/core/commit/e5c80439f714942501511a4f7abe7b98aa5579eb
https://github.com/opnsense/core/pull/4837

If overwriting settings in lighttpd, use `:=`, e.g. `server.errorlog := "| /path/to/custom_log_filter.py"`

**Comment by gstrauss** [comment]
FYI the upcoming release of lighttpd 1.4.74 changes some of the syslog priorities of *some* error messages.
```
lighttpd 43676 - - (/usr/obj/usr/ports/www/lighttpd/work/lighttpd-1.4.71/src/server.c.1240) [note] sockets enabled again
lighttpd 43676 - - (/usr/obj/usr/ports/www/lighttpd/work/lighttpd-1.4.71/src/server.c.1248) [note] sockets disabled, connection limit reached
```
The above "[note]" error messages are now logged with LOG_NOTICE priority, if syslogging of error log is enabled.  If writing to a local log file, the difference in log priority has no effect since all error messages are written to the locally configured log file.

However, as posted further above, a better solution to that is to properly configure
`server.max-fds`
`server.max-connections`
for your system size and expected number of connections.

---

If you would like to contribute patches to lighttpd to change openssl logging priorities for **specific** error messages, such patches will be thoughtfully considered.
