### ISSUE TITLE
ssh as root should not display menu

### ISSUE THREAD

**Issue by sjorge** [opnsense/core#67]
If I SSH in as root I get greeted with the same menu as on console, ideally only display that on pty's and serial.
Talking about this menu:
```
 0) Logout                             7) Ping host
 1) Assign Interfaces                  8) Shell
 2) Set interface(s) IP address        9) pfTop
 3) Reset the root password           10) Filter Logs
 4) Reset to factory defaults         11) Restart web interface
 5) Reboot system                     12) Upgrade from console
 6) Halt system                       13) Restore a configuration
```

**Comment by fichtner** [comment]
Well this is something that should be discussed in detail, because it is not as easy as one might think. Maybe I'm overly concerned, but the state of the installation's security could be severely improved here.

(1) the menu is a shell, so whenever you are root you get your shell. I fixed this behaviour. The previous "run a shell script if X otherwise run the menu" is not a good practise although it may seem convenient.

(2) root access should be very very limited. I am inclined to kick "permit root login", which would solve the issue because you can then add a wheel user and use a proper sudo instead. create an additional user and you are without said menu.

(3) add a different user that is invoked in the console or for the shell. essentially you can pick your shell in the user manager or at least you should be able to. I don't know where that leaves root...

(4) I have come to appreciate the menu even on ssh for development and testing and I know that a lot of novice users like it too, because it's convenient. It is also more "secure" in the sense that you cannot do potentially disastrous things by default, meaning getting to the actual shell.

(5) we have zapped the spurious admin user which was essentially root and want to go further with privilege separation. That is somewhat related to (3), but plays another important role in not visibly gaining root access. Maybe we must scramble the root user and install su/sudo to work with wheel in the appropriate manner--I actually like sudo better, because then we don't run into the "change the root shell" for different applications argument.

What do you think? All feedback will help... :)

**Comment by sjorge** [comment]
I like the 2/3/5 combo,

- Force don't permit root login over ssh
- default admin should not be root
- make users in the admin group have sudo
- none of the 'admin' users should be special (you can delete all but one - the current logged in one)
- allow root on physical or serial console only, with a 'menu' and an option to add a new admin use (in case of a lock out) all
- allow non-root users to choice a shell (including menu)

That should cover most bases and be a lot more secure?

**Comment by weichert** [comment]
I'm using Ansible to manage my lab and for that use case any kind of interactive menu after a login is stupid.
Also sudo isn't as useful because I'd have to implement password-less sudo anyways.
Ansible is using SSH keys for authentication.

**Comment by fichtner** [comment]
With the next release the following works:

1. In the user manager, add a different users for your shell access, add "admins" group, save. Then, in the user's config, add privileges for "User - System - Shell account access". su(1) will work then, but still launch the root menu. It's not going away that easily.
2. sudo(8) will be part of the next release by default, if you change its config to support `wheel' users to run commands you'll have effectively circumvented the root shell.
