### ISSUE TITLE
Backup/Restore aliases separately

### ISSUE THREAD

**Issue by andreas-p** [opnsense/core#670]
With pfs, it's possible to backup and restore aliases separately which is quite convenient to maintain several firewalls in the same organization; in fact, it's the only separate backup item I ever used.
I'd like to see this in opns as well.

**Comment by 8191** [comment]
I'm currently working on that feature. ;)
I'm planning to implement it as "Export as CSV" via the Aliases page. Then you can import it again via the already existing Import feature of the Aliases.

**Comment by andreas-p** [comment]
That actually sounds superior to using the backup/restore path.

**Comment by fichtner** [comment]
@andreas-p aliases import and export is there, isn't it? please check System: Settings: Backups

**Comment by andreas-p** [comment]
Yes, done!

**Comment by fichtner** [comment]
that was easy, thanks :)

fwiw, the feature will be improved soon, there are some things that could be done in the backup and restore flow :)

**Comment by 8191** [comment]
The disadvantage of that feature is that it overrides all aliases when importing. Also i find it quite bulky to download the backup, then upload it again...

The feature I have in my queue (which hopefully will be pushed if i find the time to) is a "bulk edit" of aliases, so that you have a list of all alias entries and you can copy/edit all entries at the same time. So you could e.g. share single aliases between different firewalls without the requirement that all aliases need to be equal.

**Comment by fichtner** [comment]
hey @8191 .. it's better to track this in a new ticket. looking forward to it :)
