### ISSUE TITLE
Invalid characters detected in Firewall: NAT config

### ISSUE THREAD

**Issue by oparoz** [opnsense/core#671]
### Env

15.7.99

### Steps to reproduce

1. Go to manual mode
1. Clone the rule with the description "Auto created rule for ISAKMP - localhost -> WAN"
1. Change WAN to VPN1
1. Hi save

### Expected result

A saved rule

### Actual result

> The following input errors were detected:
Invalid characters detected Auto created rule for ISAKMP - localhost `-&gt;` VPN1. Please remove invalid characters and save again.

Note the HTML encoded characters

**Comment by 8191** [comment]
Thanks for the report. That error nagged me already several times too...

The question is, is it even required to limit the allowed characters? When encoding them correctly (`htmlspecialchars(str, ENT_XML1)`) there should not be a problem to use fancy characters like `>`, `<`, `&`, etc...

Otherwise of cause the `>` in the automatically created rule should be changed to something that's also allowed in manual rule comments.

**Comment by fichtner** [comment]
I agree, removing the invalid character is a good move.

**Comment by AdSchellevis** [comment]
For most refactored pages this can probably be very easy arranged by lifting the "legacy_escape" function in the get/post block. (Then both in and out will be escaped) Although I wouldn't suggest doing this for all pages at once, if I'm not mistaken the values will eventually be stored escaped by the xml/config parser. Maybe killing the check will lead to the same result.

**Comment by AdSchellevis** [comment]
Just checked, the validation seems to be totally pointless... when saving ">" it will automatically be converted to &gt; (like the original ones).
I will remove this validation in the affected pages.
