### ISSUE TITLE
VPN: OpenVPN: Instances missing a few options

### ISSUE THREAD

**Issue by tomatotoast** [opnsense/core#6758]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

While migrating to the openvpn instances i noticed that the advanced section is missing. This means that some options in the gui are missing.

**The options are missing:**
_port-share
tcp-queue-limit
bcast-buffers_

to configure.

For other users the options are:
_tun-mtu
mssfix_

may also be interesting.

**Describe the solution you like**

Please add the options mentioned above to the new instances menu.

**Describe alternatives you considered**
alternative: add the advances section again

**Additional context**

OPNsense 23.7.1_3-amd64
FreeBSD 13.2-RELEASE-p2
OpenSSL 1.1.1v 1 Aug 2023

**Comment by AdSchellevis** [comment]
We aim to keep the gui clean and as simple as possible, adding options needs stronger arguments to avoid ending up with a toggles nobody uses or should use (quite some toggles in OpenVPN are not very useful and people only set them because historically they had a use, but nowadays they don't). The legacy option will be around for quite some time.

Maybe we will offer a custom config file hook at some point to allow all options being used, a bit like we offer for other services as well, but no final decisions have been made on that topic.

**Comment by tomatotoast** [comment]
Im not the only one needing openvpn port-share. i found this forum post:
https://forum.opnsense.org/index.php?topic=35438.msg172002#msg172002

I have a few setups running on a single IP with openvpn running on tcp 443 (so that users are always able to connect even when in an restriced like hotel network).
unfortunately since nginx or haproxy is also running i need to share the port.

My advanced config looks like this:

port-share 127.0.0.1 8443
tcp-queue-limit 4096
bcast-buffers 4096

The other options are used for performance tuning.

**Comment by AdSchellevis** [comment]
out of curiosity, what does the rest of your config look like? I don't mind keeping a ticket open for discussion, but I would advise changing it to only include the port-share feature as that's what you seem to be looking for.

**Comment by tomatotoast** [comment]
Apart from the three advanced options, my configuration is actually normal client vpn.

A disadvantage with port-share obviously is that you do not see the real IP in the log of Nginx and the blocklist does not work in this case, but the vpn performance for the clients is better. I would not like to use os-sslh. In the openvpn log you would not see from which ip a client comes. TLS multiplexing can also be done with haproxy.

Please add more config options to the openvpn instances. I think there are a lot of setups out there that use this. In the forum there were some problems with the changes of the client specific overrides so that the advanced options are not available anymore.

**Comment by muchachagrande** [comment]
Hi @AdSchellevis , in my case I have various routers that handles and intercommunicates various remote devices with OpenVPN. As the remote devices accesses Internet through 3G and 4G, I made tests some time ago and found that using "fragment 1250", "mssfix 1250" and "tun-mtu 1500" the connections sped up significantly.
For now I'm still using the old configuration, but if I have to migrate to the new instances I will lose the optimization.
It is not necessary to have those option in the web page, with a config file hook should be enough.

**Comment by fichtner** [comment]
@muchachagrande https://github.com/opnsense/core/commit/0a4eacfb6abe1 ???

**Comment by muchachagrande** [comment]
@fichtner ,  a could not apply this patch.

> 1 out of 3 hunks failed while patching opnsense/mvc/app/models/OPNsense/OpenVPN/OpenVPN.php

**Comment by muchachagrande** [comment]
@fichtner , I found these new patches 605042ada8 and 0a4eacfb6ab that you pointed me out on the forum. I applied them, but I still can't find the intended options at the bottom under advance options.

**Comment by fichtner** [comment]
Did you look at CSOs?

**Comment by muchachagrande** [comment]
This is what I see:

![Captura de pantalla de 2023-08-21 16-17-59](https://github.com/opnsense/core/assets/20299175/f7e27ca2-2417-424a-8d33-388e0ad937da)

**Comment by muchachagrande** [comment]
This is what I see:
![Captura de pantalla de 2023-08-21 16-17-59](https://github.com/opnsense/core/assets/20299175/4c43c5c4-3ab0-47c7-baab-848d413ddc02)

**Comment by fichtner** [comment]
Yeah, you made a comment in CSO thread. It was added to CSO, not instances.

**Comment by muchachagrande** [comment]
You are right, my mistake. Sorry.
In the legacy configuration pages I used these options at the instance level, not as a client override.
I think that this changes can be applied at client level as well.

**Comment by tomatotoast** [comment]
what about the options i requested?
Will

port-share
tcp-queue-limit
bcast-buffers

be added to the instances?

**Comment by AdSchellevis** [comment]
not at the moment, no.

**Comment by muchachagrande** [comment]
@fichtner , I've tested tun-mtu, fragment and mssfix at a client override and unfortunately it doesn't work. The options have to be declared at the instance.

I know how busy you are, so again, sorry for my mistake.

**Comment by fichtner** [comment]
@muchachagrande thanks for testing. I'll try to pick it up next week.

**Comment by fichtner** [comment]
@muchachagrande it's on the development release for 23.7.3 now.

**Comment by Michael-Hennemann** [comment]
Hi, 

I think the **port-share** option is REALLY useful for people with an home or small business internet connection (like me) that only provides one single public IPv4 address. 

I run OpenVPN TCP on 443 because sometimes I connect from networks with restricted internet access or from behind a proxy server and I also run HAProxy on TCP 443 for my web services. 

I would really love to see this option back in OPNSense. 

Or should I use os-sslh instead anyways ? 

Cheers
Michael

**Comment by andrewpwade** [comment]
I think it's perfectly valid to request custom config options, without having to justify each config option one individually. The OPNsense team already know it's a valid use-case, as it's used heavily in non-OPNsense openvpn, and also in the legacy openvpn configuration in opnsense. Particularly also because often you are client whose config _has_ to match the config of a server that you do not control.

I would strongly suggest that the new 'instance' version in OPNsense support all custom configuration, as before.

VPN config isn't just one of those things that you can create a simplified UI for, remove config options, and hope all will work well in all situations.

**Comment by netrunnereve** [comment]
> not at the moment, no.

Sorry for reopening this old thread, but @AdSchellevis are you not interested in having port-share in Opnsense or is it just that no one plans on adding it? I've been hesitant to switch to the new OpenVPN instances system since I have port-share and block-ipv6 set as advanced options, and I'm willing to work on this (it doesn't seem that hard) and submit it as a PR.

Once the old servers page gets removed in version 26 I think the only way to get these custom options is to have a script which appends them to the config file in `/var/etc/openvpn`.

**Comment by plinss** [comment]
Personally I'd love to see port-share added back, I just haven't had the time to submit a PR myself. If you submit one I'd be happy to test.

I'm currently using SSLH as a replacement, but I've found it to be fragile. While it's more flexible if you're running other services, it tends to crash, leaving both VPN and other HTTPS services unreachable. Adding Monit to restart SSLH when it crashes has proven OK, but simply having port-share would be more reliable and depend on less moving pieces.

**Comment by AdSchellevis** [comment]
@netrunnereve I'm not against adding `port-share` to the list, just nobody has worked on it yet.  To gain more traction, it might be better to open a new ticket only requesting that specific feature and explaining some of the use-cases.
