### ISSUE TITLE
OpenVPN Instances: Add more DNS options (which exist in "Servers")

### ISSUE THREAD

**Issue by rac-HH** [opnsense/core#6770]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

Windows networking behaviour is strange - therefore openVPN offers some options for workarounds (existing Option field in "Servers"):

block-outside-dns  (Prevent DNS leaks)

**Describe the solution you like**

Add this option also to Instances - e.g. to Miscellaneous / Options

**Comment by AdSchellevis** [comment]
It's probably better to add these kind of options to client specific overwrites, given their not applicable for all (see also notes in https://openvpn.net/community-resources/reference-manual-for-openvpn-2-6/).

**Comment by rac-HH** [comment]
There are many "windows client only" networks. Here is a global configuration the right solution. As I understand the documentation non-windows clients will ignore it. So exceptional clients (non-windows) will not be harmed.

**Comment by marinbernard-pep06** [comment]
I support this request. Preventing DNS leaks is a required feature for us to switch to the new OpenVPN instance model. Feature parity is probably expected by many people too.

The current (`23.7.10-1`) implementation of OpenVPN instances already includes Windows-only options, such as `bypass-dhcp` or `bypass-dns`. So adding `block-outside-dns` to the list seems logical.

Client specific overrides do not fit our use case either, since all of our clients are Windows. IMO, the option should be made global.

Thanks!
