### ISSUE TITLE
Unbound or Dnsmasq to Override DNS Hostnames on the Interface level

### ISSUE THREAD

**Issue by tuaris** [opnsense/core#6789]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**
No, just a request for improving existing functionality

**Describe the solution you like**

I need a way to override DNS hostnames on a per interface basis rather than globally.

**Describe alternatives you considered**

I looked at both Unbound and Dnsmasq.  Although I can enable them per interface, I can not configure them per interface.

**Additional context**

Unbound service appears to be the most capable to support this feature (at least according to the UI options).  I'm sure Dnsmasq can do the same. Doesn't matter to me which one it goes to.

This may require launching multiple Unbound or Dnsmasq daemons that each use separate config files and setup to listen on their respective interfaces.  Uses more RAM, makes things more complicated for sure.

**Comment by fichtner** [comment]
Both are not suitable for the job, at least not in any form that is going to be implemented in OPNsense. The best bet is to use one service per interface or rewrite a custom unbound plugin that uses a custom configuration that achieves your goals.

To my knowledge, however, Unbound is a big server software for a single purpose so attempting to coerce it to play nice for multiple interfaces might be futile.


Cheers,
Franco


Cheers,
Franco

**Comment by doktornotor** [comment]
Pretty sure this is doable with Unbound. See [Unbound DNS
 - Advanced Configurations
](https://docs.opnsense.org/manual/unbound.html#advanced-configurations)

```
server:
    	access-control-view: 10.11.12.0/24 somevlan
view:  
  name: "somevlan" 
  view-first: yes
  local-data: "host.example.com 60 IN A 10.11.12.13"

```

**Comment by AdSchellevis** [comment]
Both might have issues in conjunction with `python-script` (https://unbound.docs.nlnetlabs.nl/en/latest/manpages/unbound.conf.html#python-module-options), which is the feature we use to hook large lists. In our experience `local-data` has issues coping with larger sets of data, which is why we choose the script hook for blocklists for example, which unfortunately has some other disadvantages (such as serving from a single cache independent of the client subnet).

For blocklists we did add subnets in our business edition (https://docs.opnsense.org/vendor/deciso/extended_dnsbl.html), but it has some disadvantages, which also made it less attractive to rewrite the overrides to use the same kind of logic (a single facility to modify answers would be more practical in terms of maintenance).

**Comment by doktornotor** [comment]
Probably could play with `module-config` ordering. It was just a quick hint on what to look at, personally do not have a pressing use case for this. And yes, large lists are definitely better handled with python scripts.
