### ISSUE TITLE
Poor throughput of OPNsense installed in a VMware VM using vmxnet3

### ISSUE THREAD

**Issue by Lay3r3ight** [opnsense/core#6859]
Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Traffic throughput is poor when installing OPNsense in VMware with vmxnet3 vNIC.

**To Reproduce**

- 10G Network and fast esxi host and client pc is needed
- Create a new VMware VM and Install a fresh plain 23.7 with some vCPUs and some RAM (i.e. 4-8 vCPUs and 4-8GB)
- Add at least one vmxnet3 vNIC and add it to a DPG / VLAN which is connected to a fast network with a fast phsysical host
- Install OPNsense
- Give you vmxnet3 a ipv4 address
- update the sense to 23.7.4
- install iperf3 plugin
- add allow all rule to floating interface
- start iperf3 plugin on the same interface where you fast phys. host is connected to
- start iperf3 on you fast phys host with following switches: iperf3 -c *opnsenseip* -p *portofiperfinstanceonopnsense* -t 30
- test will run 30seconds, note the average bandwith
- restart iperf3 daemon on opnsense in dashboard, then start iperf3 on same interface on opnsense again
- start iperf3 on you fast phys host with following switches: iperf3 -c *opnsenseip* -p *portofiperfinstanceonopnsense* -t 30 -R
- test will run 30seconds, note the average bandwith
- done

**Expected behavior**

Observed bandwith in iperf3 is far away from 10G. In my case, something around 3Gbit/s.

**Describe alternatives you considered**

Dont know workarounds, but running Ubuntu, Windows or plain FreeBSD13.2 is much much faster.

**Screenshots**

NA

**Relevant log files**

If applicable, information from log files supporting your claim.

**Additional context**

See this Topic for detailed benchmark results and detailed comparison with FreeBSD 13.2: 

https://forum.opnsense.org/index.php?topic=36023.0

**Environment**
Hypervisor: 
ESXi 8 U1
Ryzen 4000 series CPU with 128GB and x550-T2 phys NIC

Switch:
CISCO CBS350 series

Client:
Windows 11
Ryzen 3000 series CPU with 64GB and AQC107 NIC

OPNsense 23.7.4 in VMware VM with 8 vCPUs and 8GB RAM

No other workloads running on this ESXi during benchmarks shown in linked community topic.

**Comment by vladimirtravalja** [comment]
I have the same problem with my OPNSense 23.7 running on VMWare ESXi 7.0U3 using vmxnet3. Hardware is Dell XR12, X710 intel Fiber and integrated broadcom Fiber card. 

I have tested from 8 vCPU to literally 32 vCPU it has absolutely no difference in terms of performance, I have also tested from 16/32/48GB RAM as I were using Suricata, but the difference between using it or disabling it is literally cca 200 Mbps.

I have disabled hardware offload as the performance drops below 1Gbps, while enabling this they can reach max 2 Gbps on 10Gbps intel SR 850um certified transceivers.
In comparison on RL8 and Debian 12 I can get over 9,8Gbps

There is definitely something choking this version of the OPNSense.
P.S. Just for the reference I used pfSense 2.7, and I can reach additional 1,5Gbps more than OPNSense.

Seems to me that there is something throttling down the throughput.
P.S I don't want to be a grim reaper, but there are lot of claims that same problem is persistent since 20.7 version:

Please check this thread. There are some tweaks which might improve performance but this is definitely far from being perfect.
[https://forum.opnsense.org/index.php?topic=18754.0](url)

**Comment by AdSchellevis** [comment]
Feels like a trip down memory lane, I think I already explained differences in measurements in the same forum post (https://forum.opnsense.org/index.php?topic=18754.msg90576#msg90576). When a stock FreeBSD system offers higher throughput (which I don’t expect) I would recommend to check the tunables (sysctl) for differences.

**Comment by Lay3r3ight** [comment]
Thanks @vladimirtravalja vladimirtravalja for reply and confirming this issue. I know this topic in the forums, but I did not read all 11 pages in total. All tips I have tested did not work.

Did you read the linked topic in my first post? I was able to iperf at near line speed two days ago. And at the moment, my sense is still running at this speed - and I still dont know why.

I am using a lot of OPNsense installations in a bigger VMware environment at work. Yesterday, we spent some time and we noticed that we have also slow speeds at work. We benched and tried to optimize two OPNsense installations which we are using for testing reasons and I can confirm that we see the poor performance in this environment too. 

@AdSchellevis : Please read the linked post at the forum. A fresh plain FreeBSD installation has higher throughput then a free plain OPNsense installation (on my server at home). The reason is that OPNsense disables NIC-HW-acceleration in a default installation, while FreeBSD enables this in a default setup. 

I also noticed your post in the forum from 2017. I tried the blacklist tunable at home some days ago, but this did not work.

At work, we tried every available tunables which are listed in the vmx driver man from the FreeBSD documentation without making it better: https://man.freebsd.org/cgi/man.cgi?query=vmx&sektion=4 

We also enabled hardware acceleration at work, but this did not help. 

Our ESXi hosts are based on two years old Intel based servers. The NICs are dual 25G Broadcoms. And we also see only 2-3Gbits/s.

**Comment by vladimirtravalja** [comment]
> Thanks @vladimirtravalja vladimirtravalja for reply and confirming this issue. I know this topic in the forums, but I did not read all 11 pages in total. All tips I have tested did not work.
> 
> Did you read the linked topic in my first post? I was able to iperf at near line speed two days ago. And at the moment, my sense is still running at this speed - and I still dont know why.
> 
> I am using a lot of OPNsense installations in a bigger VMware environment at work. Yesterday, we spent some time and we noticed that we see also poor throughput there. We benched and tried to optimize two OPNsense installations which we are using for testing reasons and I can confirm that we see the poor performance in this environment too.
> 
> @AdSchellevis : Please read the link in the first post which I opened at the forum this week. A fresh plain FreeBSD installation has higher throughput then a free plain OPNsense installation (on my server at home). The reason is that OPNsense disables NIC-HW-acceleration in a default installation, while FreeBSD enables this in a default setup.
> 
> I also noticed your post in the forum from 2017. I tried the blacklist tunable at home some days ago, but this did not work.
> 
> At work, we tried every available tunables which are listed in the vmx driver man from the FreeBSD documentation without making it better: https://man.freebsd.org/cgi/man.cgi?query=vmx&sektion=4
> 
> We also enabled hardware acceleration at work, but this did not help.
> 
> Our ESXi hosts are based on two years old Intel based servers. The NICs are dual 25G Broadcoms. And we typically also see only 2-3Gbits/s.

Yes, I saw your post and I read all 11 pages of mine where they have some potential solution with tuning parameters in sysctl, and I also read yours..., It is different than mine. You are using direct NIC interaction from OPNSense which in my case I cannot, at least VMWare is not allowing me. Second Any attempt in enabling hardware offload results with far lower speed, so I have to check box on "disable hardware offload". Again thank you for your good intentions of giving a possibly solution, but it does not work for me unfortunately.

Brgds

**Comment by vladimirtravalja** [comment]
OK, after doing research for 3 days (before I posted info here) straight, I am getting 8,5Gbps with Suricata enabled on OPNsense (just for comparison, pfSense is performing bit better with 9,4Gbps but unfortunately I can't find why exactly as configs are similar).

there are couple of things which I had to do:
as it is OPNSense over VMWare ESXi 7.0U2 (typo in the previous messages), using vmxnet3 not "pass-through" I definitely need to check, the checkboxs for 

- Disable hardware checksum
- Disable hardware TCP segmentation
- Disable hardware LRO (this if it is not checked it drops the throughput by 50%)
- Disable VLAN hardware filtering

This step alone has increased bandwidth for 50% in my case

now, in tunable there are options which I used:
- disable spectre and meltdown, this mitigation takes a huge hit on Intel Xeon Silver 16 Core 2,4GHz CPU (hw.ibrs_disable="1",vm.pmap.pti="0")
- uncap the receive/transmit buff. (net.inet.tcp.sendbuf_max="16777216", net.inet.tcp.recvbuf_ma="16777216")
- make tweaks with threads (net.isr.bindthreads="1", net.isr.maxthreads="8") in my case it was 8 vCPUs single thread, but "-1" value can also be used to remove the limit and don't need to worry about how many box have
- Set net.isr.dispatch="deferred" - increase performance but on certain hardware, so not sure if this will work for everyone.
- vm.kmem_size="1G" I increased memory as default is way to low IMO, especially if you have possibility to utilize more...
- kern.maxfilesperproc = "32768" and kern.maxfiles="262144"

when running iperf3 make sure to use parallel requests to get as accurate reading  iperf -c xxx.xxx.xxx.xxx -t <whatever time you want> -P <in my case 16>  and check the summary. 

I also found out that with 8vCPU under OPNSense 23.7 running on top of VMWare vSphere 7.0U2 (vmxnet3) I can get 8,5Gbps with suricata IDPS. The problem is that my CPU is topping at 100% continuously. When scaled to 16 vCPUs, the same throughput is 9,4-9,5Gbps with max CPU of 65% (sadly VMWare supports only 8vCPU for FT).

Thank you all for reply, but seems that I solved my problem :-)

**Comment by AdSchellevis** [comment]
> @AdSchellevis : Please read the link in the first post which I opened at the forum this week. A fresh plain FreeBSD installation has higher throughput then a free plain OPNsense installation (on my server at home). The reason is that OPNsense disables NIC-HW-acceleration in a default installation, while FreeBSD enables this in a default setup.

Yes, that's a logical setup when the machine isn't being used as a router (see also https://wiki.freebsd.org/Networking/10GbE/Router as mentioned in my post). Other modifications on our end involve security (https://docs.opnsense.org/troubleshooting/hardening.html), in which case relevance of settings depend on the platform in use. In some cases it does make a difference to use RSS (https://docs.opnsense.org/troubleshooting/performance.html) to optimize the load. And, never, ever, test with iperf[3] running on the firewall as this will influence the relevant results a lot.

**Comment by vladimirtravalja** [comment]
Hi again.

I never do test from firewall even though there is iperf app installed on OPNSense. I always do that from external machines connected from LAN to WAN, meaning Debian 12 to RL8, so passing through OPNSense. But in short this config which I am running now got me the best throughput.

Brgds

**Comment by Lay3r3ight** [comment]
@vladimirtravalja Thank you for the summary. I will test your tunings in the next day and let you know what happened.


@AdSchellevis 

 > Yes, that's a logical setup when the machine isn't being used as a router (see also https://wiki.freebsd.org/Networking/10GbE/Router as mentioned in my post). 

Sorry, did not read this till now becaus it showed me "This page does not exist yet. You can create a new empty page, or use one of the page templates." until this afternoon. But I found it in archive.org now and now its working again.

> Other modifications on our end involve security (https://docs.opnsense.org/troubleshooting/hardening.html), in which case relevance of settings depend on the platform in use. In some cases it does make a difference to use RSS (https://docs.opnsense.org/troubleshooting/performance.html) to optimize the load. 

I will read this and see what happens.

> And, never, ever, test with iperf[3] running on the firewall as this will influence the relevant results a lot.

Whats the technical reason for this statement?

I compared iperf3 benchmarks running on the sense with routed iperf3 traffic to/from a far Ubuntu VM like you did it in your post from 2017. Both with same speeds.

**Comment by vladimirtravalja** [comment]
> @vladimirtravalja
> 
> Thank you for the summary. I will test your tunings in the next days.
> 
> @AdSchellevis
> 
> > Yes, that's a logical setup when the machine isn't being used as a router (see also https://wiki.freebsd.org/Networking/10GbE/Router as mentioned in my post).
> 
> Sorry, did not read this till now becaus it showed me "This page does not exist yet. You can create a new empty page, or use one of the page templates." until this afternoon. But I found it in archive.org now and now its working again.
> 
> > Other modifications on our end involve security (https://docs.opnsense.org/troubleshooting/hardening.html), in which case relevance of settings depend on the platform in use. In some cases it does make a difference to use RSS (https://docs.opnsense.org/troubleshooting/performance.html) to optimize the load.
> 
> I will read this and see what happens.
> 
> > And, never, ever, test with iperf[3] running on the firewall as this will influence the relevant results a lot.
> 
> Whats the technical reason for this statement?
> 
> I compared iperf3 benchmarks running on the sense with routed iperf3 traffic to/from a far Ubuntu VM like you did it in your post from 2017. Both with same speeds.

I hope this will work for you as well.
Please keep in mind that if you use iperf3 -c <IP> without specifying parallel, it somehow uses only 1 "core/thread". At least I red it somewhere (I can't find source as in 3 days I have read lot of documentation and forums, githubs, etc, so it is fairly difficult for me to find within numerous pages). Also in the same thread they said that 1 core/thread is capped up to max 3-5Gbps which actually corresponds to the 3,5Gbps which I got. But this tweak with threads might be the key which basically instructs to use more threads to process the traffic. "maxthreads=-1"

> make tweaks with threads (net.isr.bindthreads="1", net.isr.maxthreads="8") in my case it was 8 vCPUs single thread, but "-1" value can also be used to remove the limit and don't need to worry about how many box have

Again, check and test and see how it goes and if it helps you.
Have a lovely weekend

**Comment by Lay3r3ight** [comment]
Thanks, I know that iperf3 activates only one flow without using the -P(arallel) switch. But, its already not a problem to reach nearly 10G line rate with 8 or more streams since I have activated hardware offloading with virtual vmxnet3 adapter. Please note that I do NOT mean with a hardware NIC in passthrough mode.

The goal is to reach ~line rate with only one stream, because thats what typically happens if you open files on a NAS (if it dont suppoert multiple flows). Currently, its allready possible but I dont know why.

I think my Ryzen 4750G Pro is equal or maybe a little bit faster in single threads than your xeon, so I dont know why I had only 2,7G in total with one or multiple flows.

We will see...

Have a nice weekend too.
