### ISSUE TITLE
LDAP backend makes wrong assumptions about user groups

### ISSUE THREAD

**Issue by 0xC0ncord** [opnsense/core#6871]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

I am trying to integrate OPNsense's LDAP authentication with [Kanidm](https://github.com/kanidm/kanidm). By itself Kanidm is not a complete LDAP server, but it optionally exposes its internal identity information as a read-only LDAP database, e.g. to support LDAP authentication for clients and applications that don't support OAuth.

When querying Kanidm users over LDAP, the `memberOf` attribute does not contain `cn=`. Because of this, OPNsense does not understand that queried users are a member of any groups since the LDAP auth backend is hardcoded to look for `cn=` when searching for group memberships ([master/src/opnsense/mvc/app/library/OPNsense/Auth/Base.php#L167](https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/library/OPNsense/Auth/Base.php?rgh-link-date=2023-07-15T22%3A23%3A20Z#L167)):

```
User: concord authenticated successfully.
This user is a member of these groups:


Attributes received from server:
dn => spn=concord@idm.fuwafuwatime.moe,dc=idm,dc=fuwafuwatime,dc=moe
class => account
memberof
object
person
posixaccount
displayname => concord
gidnumber => 1688334410
loginshell => /bin/bash
memberof => spn=idm_all_persons@idm.fuwafuwatime.moe,dc=idm,dc=fuwafuwatime,dc=moe
spn=idm_all_accounts@idm.fuwafuwatime.moe,dc=idm,dc=fuwafuwatime,dc=moe
spn=sysadmins@idm.fuwafuwatime.moe,dc=idm,dc=fuwafuwatime,dc=moe
name => concord
spn => concord@idm.fuwafuwatime.moe
uuid => 14f4a2c1-4541-4018-9e7d-9b81010ece6c
```

OPNsense is making an incomplete assumption that the `memberOf` attribute for a user will contain `cn` for identifying the group name which may not be the same across all LDAP servers.

**Expected behavior**

OPNsense should perform additional LDAP queries to identify the name for a group which a user belongs to, instead of assuming that the `cn=` field will be returned in the `memberOf` attribute for a user.

**Describe alternatives you considered**

Alternatively instead of querying for users we query for groups, like so:
```
ldapsearch -H ldaps://idm.example.com -b 'dc=idm,dc=example,dc=com' -x '(&(name=admins)(member=concord))'
```

It may also be beneficial if it were possible to allow users to insert freeform LDAP queries using variables or templates for more complex setups.

**Additional context**

Originally I reported this in https://github.com/opnsense/core/issues/6670 but after mirroring the issue to Kanidm (https://github.com/kanidm/kanidm/issues/2132) for discussion, I've closed the former as it was not entirely accurate about the problem.

cc @Firstyear

**Comment by Firstyear** [comment]
> I am trying to integrate OPNsense's LDAP authentication with [Kanidm](https://github.com/kanidm/kanidm). By itself Kanidm is not a complete LDAP server, but it optionally exposes its internal identity information as a read-only LDAP database, e.g. to support LDAP authentication for clients and applications that don't support OAuth.

To clarify, Kanidm is complete with regard to it's search and simple bind functionality, it just refuses modify and write operations which are not relevant in this cas. 

> 
> When querying Kanidm users over LDAP, the `memberOf` attribute does not contain `cn=`. Because of this, OPNsense does not understand that queried users are a member of any groups since the LDAP auth backend is hardcoded to look for `cn=` when searching for group memberships ([master/src/opnsense/mvc/app/library/OPNsense/Auth/Base.php#L167](https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/library/OPNsense/Auth/Base.php?rgh-link-date=2023-07-15T22%3A23%3A20Z#L167)):
> 
> ```
> Attributes received from server:
> dn => spn=concord@idm.fuwafuwatime.moe,dc=idm,dc=fuwafuwatime,dc=moe
> memberof => spn=idm_all_persons@idm.fuwafuwatime.moe,dc=idm,dc=fuwafuwatime,dc=moe
> ```
> 
> OPNsense is making an incomplete assumption that the `memberOf` attribute for a user will contain `cn` for identifying the group name which may not be the same across all LDAP servers.
> 
> **Expected behavior**
> 
> OPNsense should perform additional LDAP queries to identify the name for a group which a user belongs to, instead of assuming that the `cn=` field will be returned in the `memberOf` attribute for a user.

To help explain further, what it seems to be is that OPNsense is assuming the structure of the DN in the MemberOf response. There is no requirement in rfc2307bis that MemberOf dn's must have an leading rdn component with a `cn=`.  Because OPNsense is assuming the MemberOf dn starts with this, it's trying to "explode" the dn into it's rdn components to construct and retrieve the group name. Of course, this trips Kanidm up since cn is *not* unique in Kanidm so we can't provide it as the rdn here. We have to use the security principle name (spn) here instead. 

The correct behaviour should be that when you get back a list of MemberOf dn's that you query each DN and request the list of attributes you want back from them. 

Also worth pointing out this would potentially fail in opensource ldap's where cn isn't guaranteed to be unique (in AD it is, regardless of tree location of an entry). It is valid in openldap/389-ds to have:

```
cn=a,ou=a,dc=foo
cn=a,ou=b,dc=foo
```

Notice the cn is the same, but the ou is different. This would also break your current implementation. 

Hope that helps,

**Comment by AdSchellevis** [comment]
Our implementation is only able to point to a single (unix) group, so overlapping groups in different domains would indeed lead to the same local match. There's not a lot we can do about that as these are actual local unix groups underneath (sure, you can add exact dn matches somewhere, but it would lead to quite some additional logic for a very small use-case).

So far, all implementations we've seen (Active directory, OpenLDAP,..) use common names to identify the groups, we could make the split configurable, assuming everything before the `@` is the actual group to match, although we do not know of other platforms that would need this. 

Querying more data depending on the received `memberOf` attribute is likely not going to happen as this will put a burden on all other users of this authenticator and it's rather easy to build your own authenticator based on ours (https://docs.opnsense.org/development/components/authentication.html).

**Comment by Firstyear** [comment]
> Our implementation is only able to point to a single (unix) group, so overlapping groups in different domains would indeed lead to the same local match. There's not a lot we can do about that as these are actual local unix groups underneath (sure, you can add exact dn matches somewhere, but it would lead to quite some additional logic for a very small use-case).

> actual local unix groups underneath

This is making some huge assumptions. MemberOf is showing *all memberships* not just memberships of posixGroups that are exposed via nss. Which means you are seeing and potentially using groups that are not unix groups. This also means that if you had:

```
cn=grp,ou=posix
cn=grp,ou=dir

dn: bad_user,<basedn>
memberOf: cn=grp,ou=dir
```

Then you will mistakenly allow bad_user as part of grp, which may depending on your config be a privilege escalation vulnerability. This can occur depending on the users rights in the directory to modify entries or create new entries. You may be surprised to find out how *common* this is both intentionally and accidentally that these writes are allowed in directories. 

This assumption also is problematic because the resolver may have a specific set of filters that you need to also perfectly emulate to ensure that your group resolving process is identical to the nss resolving process. If it is not identical, it can lead to other subtle issues.

If you are tying users to unix groups on the machine then you *should not* be accessing LDAP IMO. You need to ensure that your tool has the same view of the users and groups as the system does, and the nss resolver is already doing this for you. As a result, you likely should look at https://linux.die.net/man/3/getgrouplist or your languages equivalent instead of resorting to LDAP here.

I will say again - you should consider this a potential security risk. You either need to properly chase the dn's and resolve them with an identical filter that nss is, or you need to use getgrouplist instead. 

> So far, all implementations we've seen (Active directory, OpenLDAP,..) use common names to identify the groups, we could make the split configurable, assuming everything before the `@` is the actual group to match, although we do not know of other platforms that would need this.

While a group may have a cn as an attribute in the object there is no requirement for that cn to be the rdn component used in the dn of the group. I have seen plenty of setups that use different values. This is also to say nothing of the fact that rdns can have multiple values but that's very niche (and cursed) ... 

Regardless even splitting on the "@" here wouldn't resolve the problem that @0xC0ncord has, because kanidm is `spn=group@domain,<basedn>`. Since you assume cn, even with the '@' split you would still error since it's not cn in the rdn. Within kani this would also potentially lead to the security issues above it you try to explode the rdn and then split on '@' since in a trust config there may be two groups with the same resulting component in the end.

**Comment by AdSchellevis** [comment]
ok, let's assume we can't fix this to save everyones time. 

When needed, we can always add filters to explicitly require a certain base for groups, but when (in Active Directory) you are able to change the results of the memberOf attribute, all bets are more or less off. So there are security constraints, as  with every feature. I don't think `getgrouplist`  will be of much help as this will tell what we already know, the current membership of the user and not the ones the connected identity provider knows about.

**Comment by kulikov-a** [comment]
@Firstyear 
out of curiosity, could Kanidm return an memberOf in the multivalued RDN format like:
spn=idm_all_persons@idm.fuwafuwatime.moe+cn=posix_group_name,dc=idm,dc=fuwafuwatime,dc=moe
?
(I agree that a DN is not required to start with the CN, but not every RDN can be mapped to a POSIX-comaptibe local group name, and using a CN for this is a reasonable choice imo (excluding a possible matches in the case of cn non-uniqueness is the responsibility of the administrator))

**Comment by Firstyear** [comment]
> ok, let's assume we can't fix this to save everyones time.

This is not the right attitude for a possible security issue that will affect your users. 

It's also not the right attitude when an rfc4511 and rfc2307bis compliant server are breaking because of your assumptions and shortcuts to integrate with ldap. 

> @Firstyear
> out of curiosity, could Kanidm return a memberOf in the multivalued RDN format like:
> spn=[idm_all_persons@idm.fuwafuwatime.moe](mailto:idm_all_persons@idm.fuwafuwatime.moe)+cn=posix_group_name_,dc=idm,dc=fuwafuwatime,dc=moe
> ?
> (I agree that a DN is not required to start with the CN, but not every RDN can be mapped to a POSIX-compatibe local group name, and using a CN for this is a reasonable choice imo (excluding a possible matches in the case of cn non-uniqueness is the responsibility of the administrator))

We could, but we won't. You are suggesting we add it so that opnsense's dn-explode method can work, when the issue isn't our dns, it's the fact that opnsense assumes the content of dns and that they explode in a certain way. opnsense should not be exploding dn's, but following them and reading the content of their entries directly - the same way that every other application that follows memberof should behave.

We also take the view that Kanidm will always do the correct and simple thing in our designs - and if that happens to break other projects by highlighting faults and shortcomings in those projects, then we are *not* going to add hacks, workarounds or similar to support them. We will educate what has gone wrong to those upstreams (as we have done here) but it's not up to us to fix opnsense's incorrect ldap integration.

So as a result, I see no resolution to this. opnsense does not want to fix their ldap integration to be secure and correct. And we won't add workarounds for opnsense's incorrect dn handling.

As a result, I think we may have to sadly accept that opnsense won't work with Kanidm. I will again point out this isn't a Kanidm specific issue either - this could just as easily have happened to openldap or 389-ds.

**Comment by kulikov-a** [comment]
Wow. I'm sorry I asked. incompatibility is a comprehensive definition

**Comment by fichtner** [comment]
> This is not the right attitude for a possible security issue that will affect your users.

You can reasonably ask for security fixes given a POC at any time, but trying to change the whole integration to better meet external security goals is not that process. Don't mix up these two things.

And if you are worried about the constraints of the current implementation a paragraph in the documentation will certainly help users to keep their integration as secure as possible.


Cheers,
Franco

**Comment by Gorian** [comment]
Just checking to see if OPNSense has fixed this yet. They Paywall OpenID auth, and refuse to fix their LDAP implementation, not sure how to actually use OPNSense with any modern IDM.

**Comment by fichtner** [comment]
These threads and responses are unhelpful and irrelevant to the project as they add a lot of claims but produce no code changes. You can see this when people write walls of texts instead of pointing to a line of code to fix. I’m closing this since closed tickets should not be responded to anyway.
