### ISSUE TITLE
config.xml broke while making changes

### ISSUE THREAD

**Issue by fraenki** [opnsense/core#701]
While creating a new firewall rule my `config.xml` was destroyed. It was cut at the end of the `<hasync>` section, so the file is missing only the closing tags:

```
-  </hasync>
-</opnsense>
```

@fichtner made an assumption and suggestion on IRC:

```
19:09 <@fitch> maybe there was a webserver reload because of hasync changes, dunno
19:10 <@fitch> we could tighten the write by writing the temporary file and moving it into place afterwards
19:10 <fraenki> this is maybe a good idea, but add a syntax check before moving the file :)
19:10 <@fitch> more or less atomic(tm)
19:11 <@fitch> I suspect the writer gets killed so it'll never be moved
```

**Comment by AdSchellevis** [comment]
Strange, never seen this before. 
We might use another copy of the file to sync to and copy as proposed, but then the second (new) file always needs to be there for locking reasons.

Maybe it's better to rollback to the previous file if the current one isn't valid, for the legacy code there is a mechanism in place (need to verify what happens if the ending tag is missing) https://github.com/opnsense/core/blob/master/src/etc/inc/config.lib.inc#L67-L80 , maybe this strategy needs some work.

**Comment by fichtner** [comment]
@AdSchellevis fine with either approach, reassign if you want :)
