### ISSUE TITLE
BGP and "URL table" aliases do not load IPs after restoring system configuration from backup

### ISSUE THREAD

**Issue by ruslanbay** [opnsense/core#7075]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Steps To Reproduce**

1. Go to 'Firewall: Aliases'
2. Create a BGP ASN alias
![image](https://github.com/opnsense/core/assets/67730802/a1fcc8d6-a722-49f5-83f0-69a5c9be01c9)

3. Create a "URL Table (IPs)" alias
`Refresh Frequency = 30 days`
`Content = https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/firewall/spy.txt`
![image](https://github.com/opnsense/core/assets/67730802/5f120cdd-5863-44ef-885b-58d5af845c9d)

4. Save and apply changes
5. Go to `System: Configuration: Backups`
6. Download the encrypted configuration file
7. Deploy a new opnsense instance
8. Go to `System: Configuration: Backups`
9. Restore the system configuration using the file from step 6
10. Go to `Firewall: Aliases`

**Expected behavior**
Applying the configuration file and restarting the firewall triggers an automatic alias update.

**Actual behavior**
Aliases are empty. There are no relevant entries in the logs. For this reason, alias-related rules do not block traffic.

**Workaround**
Set `Refresh Frequency = 0.01 Hours`, save and apply changes, then return the previouse value. It works for `URL Table (IPs)`, but I don't know how to trigger update for the BGP aliases.

**Environment**
OPNsense 23.7.10 (amd64)

**Comment by ruslanbay** [comment]
> 2. Create a BGP ASN alias

Sorry, that was a bad example since [AS198097](https://ipinfo.io/AS198097) doesn't contain any IP addresses.
You can use any other ASN to reproduce the issue.

**Comment by AdSchellevis** [comment]
bgp content is fetched on time interval (when `/usr/local/share/bgp/asn.csv` is too old or doesn't exist)


https://github.com/opnsense/core/blob/481859b41290300512b23c6fe98d619c6562134f/src/opnsense/scripts/filter/lib/alias/bgpasn.py#L38-L50

similar to geoip's

**Comment by NateroniPizza** [comment]
There needs to be a way to manually trigger this refresh, rather than waiting 24 hours before your services are back up (in my case, I lose control of my home automation system). Before it is suggested, no, the "Update and reload firewall aliases" cron job does not refresh the BGP ASNs, at least while in this error state.

Last time this happened, a few weeks ago, I was able to restore from a backup a second time after everything was up and running to re-trigger an update, but that doesn't seem to be working this time around.

Error in the log at the time indicates a name resolution error when it tried downloading the BGP lists, which is not unexpected given the WAN interface wasn't fully configured at the time.

**Comment by AdSchellevis** [comment]
```
rm /usr/local/share/bgp/asn.csv
``` 
 
?

**Comment by ruslanbay** [comment]
Hi @AdSchellevis 
Thank you for your help, but I'm a little confused. So, there is no easier way to trigger an alias update via WebUI? Or maybe it is possible to include/exclude the asn.csv file from backup?

**Comment by AdSchellevis** [comment]
@ruslanbay the file isn't in a backup and when not there, it should fetch it on first use. The one thing I can imagine is that it couldn't fetch it the first time (no internet) left an empty file and assumed it did collect it. If that's the case, we should probably be able to fix that. easy way to try if that's the issue is to replicate that scenario and take a peek at the file (when empty and refusing to fetch later, there's something to fix).

**Comment by NateroniPizza** [comment]
> @ruslanbay the file isn't in a backup and when not there, it should fetch it on first use. The one thing I can imagine is that it couldn't fetch it the first time (no internet) left an empty file and assumed it did collect it. If that's the case, we should probably be able to fix that. easy way to try if that's the issue is to replicate that scenario and take a peek at the file (when empty and refusing to fetch later, there's something to fix).

That has been the case both times this has happened to me - an error is displayed in the system logs stating that a DNS resolution error has occured (due to no internet), and when I went to check the asn.csv file it was empty.

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/4c097be8ea1226728885b392e202939ec8723302 should fix the zero length file issue.

**Comment by NateroniPizza** [comment]
> [4c097be](https://github.com/opnsense/core/commit/4c097be8ea1226728885b392e202939ec8723302) should fix the zero length file issue.

Sweet! Thank you.

@ruslanbay was having a similar issue with URL Table (IPs) as well, though there was a way to decrease the refresh interval that was able to get it refreshed (though this still required manual intervention). I don't use those, so haven't looked into what files store those, and wouldn't know what their state is after the restore.
