### ISSUE TITLE
Multipath TCP Support - There's a new porting attempt in progress by a University

### ISSUE THREAD

**Issue by ilikenwf** [opnsense/core#7178]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

For multi wan connection aggregation through a VPS, a multipath TCP feature would be nice.

**Describe the solution you like**

I realize this may be beating a dead horse, but in the past there have been efforts to add MPTCP support to FreeBSD. Every time this happens it usually is a fork of a prior project. Recently I located another in progress work on MPTCP for FreeBSD 13, based on the prior patches, however it is in active development by a university in Australia, and is funded by a Comcast Grant. I think it may be worth revisiting, but it is a bit beyond my skills as I'm more software oriented and not the best network engineer.

https://github.com/MPTCP-FreeBSD

In addition, another useful resource on this topic is Steve Jacobson's FreeBSD MPTCP information page:

https://xenon.stanford.edu/~sjac/freebsd_mptcp_info.html

**Describe alternatives you considered**

Right now the only option I have is to setup OpenMPTCP router and use it in between opensense and my wans.

**Comment by AdSchellevis** [comment]
There's `ROUTE_MPATH` in FreeBSD since freebsd 13 (https://www.freebsd.org/releases/13.0R/relnotes/), which is disabled by default on our end (`net.route.multipath=0`). I do expect quite some regressions, but if it does help for your user-case, you could always take a look (https://man.freebsd.org/cgi/man.cgi?route). 

Documentation is quite limited as far as I could find, which also makes it less likely we will spend time on it as it might break current routing assumptions in core.

Our experience with a lot of these type of additions is similar to yours I'm afraid, one time efforts without long term commitment leading to bugs nobody cares to look at.

**Comment by ilikenwf** [comment]
Thank you for the information - I'll look into ROUTE_MPATH. 

I suspect this may later become more of a topic of conversation as more and more people migrate to full or partial remote work as time goes on.
