### ISSUE TITLE
Add selection of primary interface on Failover LAGG

### ISSUE THREAD

**Issue by BertVano** [opnsense/core#7306]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

When trying to setup a LAGG interface of type 'Failover', I am missing the possibility to select the primary interface. Currently it takes whatever is first in the list of selected interfaces. This is needed when one wants to select interfaces of different speeds (i.e. 10Gbe & 1Gbe)

**Describe the solution you like**

Add a dropdown box to select the primary interface.

**Additional context**

I am using OPNsense 3.7.12_5.

**Comment by AdSchellevis** [comment]
failover mode is not very popular for lagg interfaces, although not very specifically stated in the documentation, order should prioritize in this case. Since we remove all interfaces before configure, it shouldn't be a huge issue to change something in the ordering. 

https://github.com/opnsense/core/blob/4b1bc0c0f37ba58535b0ac2261dc6c741a0f90b8/src/etc/inc/interfaces.inc#L420-L424

I'll put it on the list, no promises.
