### ISSUE TITLE
[FR] Quickly show drop rules in Suricata

### ISSUE THREAD

**Issue by oparoz** [opnsense/core#751]
If users want to see which rules are dropping packets, they can't, even sorting using the action column doesn't work and only shows *Alert* actions.

**Comment by AdSchellevis** [comment]
Have you searched for "drop" using the searchbar (don't forget to press apply)?

Quick sorting and filtering isn't very likely to happen because of the potential size of the log file, if you like to sort you always have to read the full dataset. 
The search tries to find the max requested number of items + 1, so its in most case more lightweight.

Solutions like logstash/kibana (https://www.elastic.co/products/kibana) hosted on a separate box are probably an easier way there.

**Comment by oparoz** [comment]
>Have you searched for "drop" using the searchbar (don't forget to press apply)?

I did use the search bar, but since everything is dynamically re-ordered, I did not press on "apply". I've just tried. It didn't change anything and even worse, it restarted Suricata, which takes ages to bring the LAN back.

>Quick sorting and filtering isn't very likely to happen because of the potential size of the log file, if you like to sort you always have to read the full dataset. 

I think there is some confusion. I'm talking about the rules, not the logs. While there are over 13k entries, they come up quickly, so I don't think searching would be that slow.

Without some sort of switch to see the which rules are active, it's impossible to find them without browsing all the rules.

**Comment by AdSchellevis** [comment]
You right, confusion... the rules should be sortable and searchable without further interactions (they are on all machines running on my end), the logs not. 
A filter on active rules / action seems to be missing, we should add that. (sorting on action however also functions on my end)

**Comment by oparoz** [comment]
You're right, sorting on action does work. I must have left "drop" in the search field and was only filtering rules containing that word.
