### ISSUE TITLE
Graphics on "Traffic Graphs" widget are out of sync

### ISSUE THREAD

**Issue by oparoz** [opnsense/core#753]
### Steps to reproduce

1. Load the dashboard
1. Add the *Traffic Graphs* widget
1. Save
1. Wait 5 minutes
1. Click on the + sign for the LAN

### Expected result

New data points should be added at the same x value

### Actual results

New data points are added at x=0, while the older graphs will already be at 30 (300s/10)
This means that's it's impossible to correlate data from 2-3 different graphs

**Comment by AdSchellevis** [comment]
The traffic graphs are using very ancient code, we are planning to provide more network insights in 15.7 which might solve this eventually.
Maybe darkstat is something useful for you in the meantime, the package is in our repository (although we're not going to supply the configuration part because we're looking for something more integrated).

**Comment by fichtner** [comment]
15.7 -> 16.7 :)

**Comment by oparoz** [comment]
OK and thanks for letting me know about darkstat. I'll check if it's easy to set up.

**Comment by fichtner** [comment]
Closing, the only thing that will happen here is the removal of the old traffic graphs anyway.
