### ISSUE TITLE
abuse.ch rules not listed (not rulesets)

### ISSUE THREAD

**Issue by oparoz** [opnsense/core#758]
### Steps to reproduce

1. Open the *Intrusion Detection*
1. Got to the *Rules* tab
1. Switch the view to show a 1000 rules at a time
1. Type "SSL" in the search filed

### Expected result

I should see the SSL rules of abuse.ch

### Actual result

I see SSL rules by ET only.
I've tried looking for abuse.ch and only got the rules included in ET

**Comment by oparoz** [comment]
Ah, that's because those rules had never been downloaded.
I think it would be great if all rules could be included in the package, otherwise the *last updated* and *Enabled* headers are a bit misleading. It gives the impression that all rules are there, just waiting to be enabled.

**Comment by AdSchellevis** [comment]
We're not going to include the rules in the package, because they will always be outdated by the time they are installed (abuse.ch gets updated every 15minutes for example). 
I agree that "uninstalled" might be a bit clearer, I've fixed that in this commit : https://github.com/opnsense/core/commit/26879eb2a21d91b5c31fd1eed714f1d940e5049c
