### ISSUE TITLE
Kea: Support DHCP lease times per subnet

### ISSUE THREAD

**Issue by bagobones** [opnsense/core#7592]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

Kea currently only has a global lease time set however it is common to want different lease times by subnet / vlan.

- Servers: long lease times
-  workstations medium lease times
- WiFi / WiFi guest networks VERY short lease times to avoid pool starvation. 

**Describe the solution you like**

Kea should already support per subnet lease times that override the global lease time, add an option for lease time to the subnets.

**Describe alternatives you considered**

Set a middle of the road lease time as a workaround. Don't deploy Kea in serious business environments, stick with the old DHCP client.

**Additional context**

In larger networks having different lease times is important.. WiFi guest networks is the most common case where you will set a drastically shorter lease time as the pool will run out over the course of a day otherwise.

**Comment by CA-DigitalAnvil** [comment]
I would like to add my upvote for the original poster's request.  Per-pool lease times in a scenario such as described would be incredibly valuable, particularly since that feature was available (and very much used) in the old ISC dhcpd server.  Additionally, setting default lease times to something ridiculously small (as needed by the afore mentioned WiFi) and then using 'option-data' to crank the lease time around to something useful for those leases that are not of that flavour does not appear to be supported.   An example of an elegant use of classing would be really helpful, if such a critter indeed exists.

**Comment by GaardenZwerch** [comment]
I would need to have this too before dropping ISC. The main reason, as stated above is hugely different lease times for WiFi clients than for access-point.
Preferably a set of default values and the possibility to override them per network or pool.

**Comment by bagobones** [comment]
This is a fairly expected enterprise feature. Not sure it can be ignored

**Comment by AdSchellevis** [comment]
@drinn when someone volunteers working on it, we can always open a ticket.

**Comment by bagobones** [comment]
I switched to DNSMASQ which has this functionality and custom scope options fully realized in the opnsense UI. 

Switching over is fairly easy copying the reservations from the web UI from one to the other. Only quirk is the DNS forwarding configuration

**Comment by HidingCherry** [comment]
DNSMASQ instead always sends dhcp option 3 (router/gateway), which cannot be disabled or overridden via gui.
This is possible with kea DHCP, but via GUI you cannot set dhcp options 51, 58 and 59 - neither of them seem to work for me.

dhcp option 51 = lease-time/address-time
This option is the one mentioned in this issue.

For a complete picture:
<img width="837" height="249" alt="Image" src="https://github.com/user-attachments/assets/1f27e774-ca41-4dac-bbff-df4cfc7320bc" />
Those are then assigned either to the subnets and/or to reservations.

**Comment by bgilesmca** [comment]
I have successfully updated my appliance to use a value at the scope level which overrides the general valid-lifetime.

I will try to create a diff file with the changes.  I am currently on 25.1.12 but I also tested with the latest release which I have not upgraded to yet since I have been waiting to see if anyone has been able to fix this.

**Comment by bgilesmca** [comment]
If someone can give me a quick boost on how to contribute properly I would be happy to submit my code.

**Comment by bgilesmca** [comment]
I have offered to submit an update, but in the meantime, if you want to make the changes on your own, see my diff file to update the files in the following locations:

/usr/local/opnsense/mvc/app/controllers/OPNsense/Kea/forms/dialogSubnet4.xml
/usr/local/opnsense/mvc/app/models/OPNSense/Kea/KeaDhcpv4.php
/usr/local/opnsense/mvc/app/models/OPNSense/Kea/KeaDhcpv4.xml

in dialogSubnet4.xml, after pools field add :

```
    <field>
        <id>subnet4.valid_lifetime</id>
        <label>Scope Valid Lifetime</label>
        <type>text</type>
        <help>Valid Lifetime for this scope</help>
        <grid_view>
            <visible>false</visible>
        </grid_view>
    </field>
```

in KeaDhcpv4.php file, before /* add description and other custom keys */ comment add:

```
            /* add valid-lifetime at the scope level */
            $subnet_lifetime = (int)$subnet->valid_lifetime->__toString();
            if (!empty($subnet_lifetime)) {
                $record['valid-lifetime'] = $subnet_lifetime
            }
```

in KeaDhcpv4.xml file after </subnet> add:

```
                <valid_lifetime type="IntegerField">
                    <Required>N</Required>
                </valid_lifetime>
```

[valid-lifetime.diff.txt](https://github.com/user-attachments/files/27456164/valid-lifetime.diff.txt)

**Comment by Monviech** [comment]
@bgilesmca can you offer a PR with your changes?

**Comment by bgilesmca** [comment]
@Monviech I do not have access to do so yet.

**Comment by DonPablo1010** [comment]
Thank you for your work, per-subnet valid lifetime is a great step forward!

Would it be possible to extend this to host reservations as well? A single `Valid Lifetime` field in the Reservations dialog would allow fine-grained control for individual devices – for example, assigning very short lease times to IoT or mobile clients without affecting the rest of the subnet.

Under the hood, the GUI would need to set both `valid-lifetime` and `dhcp-lease-time` (option 51) together to keep server and client in sync:

```json
"reservations": [
  {
    "hw-address": "aa:bb:cc:dd:ee:ff",
    "ip-address": "192.168.1.100",
    "valid-lifetime": 600,
    "option-data": [
      {
        "name": "dhcp-lease-time",
        "data": "600"
      }
    ]
  }
]
```

One thing to keep in mind: `min-valid-lifetime` at global or subnet level must be set lower than the reservation value, otherwise Kea clamps it upward. Exposing `min-valid-lifetime` in the subnet dialog (alongside the new vltime field from #10266) would naturally complement this.

Happy to test if a patch becomes available. Thanks again!

**Comment by Monviech** [comment]
I would rather suggest you create some more vlans that group these devices instead.

The deeper down the rabbithole we go the harder maintainance gets in the long run. xD

**Comment by DonPablo1010** [comment]
Yes, vlan is a option. 

I tested per-host lease times and wanted to share some findings for anyone else trying this:

What does NOT work:

Setting valid-lifetime directly in a host reservation is not supported in Kea and results in a config error.

Setting only option-data with dhcp-lease-time (option 51) per reservation also does not work reliably and the server ignores it internally and assigns the global valid-lifetime.

What DOES work is, using client classes with valid-lifetime, assigned via the reservation:

```json
"client-classes": [
  {
    "name": "short-lease",
    "valid-lifetime": 600
  }
],
...
"reservations": [
  {
    "hw-address": "fa:cf:1a:3a:72:8c",
    "ip-address": "192.168.1.101",
    "hostname": "nilsphone",
    "client-classes": [ "short-lease" ]
  }
]
```


This correctly assigns 600s to specific hosts while all other devices get the global 86400s. Tested and confirmed working on Kea 3.0.3.

Would be great if this could eventually be exposed in the GUI as well – either via client class management or directly in the reservations dialog. Happy to test further if needed!

**Comment by Monviech** [comment]
For me this looks like micro management. Grouping devices that belong together into vlans is the better choice and keeps the DHCP server clean as well.

Offering in depth client-classes management is not on the list, neither is turning reservations into a per host policy engine.
