### ISSUE TITLE
OpenVPN crashes when <auth-gen-token/> is not empty

### ISSUE THREAD

**Issue by stuart-edge** [opnsense/core#7690]
|| || |Version|24.7_9|

If I configure anything in VPN --> OpenVPN --> Instances --> Instance --> Auth Token Lifetime
The OpenVPN service will not start or restart.
If I remove the value (blank) the OpenVPN service will start.
Also fails with the value set to 0
The value looks OK in the backup file.
<auth-gen-token>36000</auth-gen-token>

OpenVPN will not start with this config
          <maxclients/>
          <keepalive_interval/>
          <keepalive_timeout/>
          <reneg-sec>0</reneg-sec>
          <auth-gen-token>60</auth-gen-token>
          <redirect_gateway/>
          <route_metric/>

OpenVPN will run with this config
          <maxclients/>
          <keepalive_interval/>
          <keepalive_timeout/>
          <reneg-sec>0</reneg-sec>
          <auth-gen-token/>
          <redirect_gateway/>
          <route_metric/>

opnsense
Version | 24.7_9 |  
Architecture | amd64 |  
Commit | 0d38c7804 |  
Mirror | https://pkg.opnsense.org/FreeBSD:14:amd64/24.7 |  
Repositories | OPNsense |  
Updated on | Tue Jul 30 13:51:49 AEST 2024

**Comment by fichtner** [comment]
Same thing I posted here and got no response https://www.reddit.com/r/opnsense/comments/1efq0cg/openvpn_crashes_when_authgentoken_is_not_empty/

> This might clash with another setting that the OpenVPN daemon complains about and refuses to start. Can you check your log?

**Comment by stuart-edge** [comment]
I thinks this is the error. I gave up on OpenVPN and started using WireGuard.
/usr/local/opnsense/scripts/openvpn/ovpn_service_control.php: The command '/usr/local/sbin/openvpn --config '/var/etc/openvpn/instance-226a3474-1caa-4f0a-9cf1-e0cb671bb1d3.conf'' returned exit code '1', the output was ''

**Comment by fichtner** [comment]
I think we know the service didn't start. The question is what OpenVPN service itself logged when it decided not to start ;)

**Comment by hsiewert** [comment]
I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
 I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

I guess, the problem is probably the same as described before:

### Environment
OPNsense 24.7.4_1-amd64
FreeBSD 14.1-RELEASE-p4
OpenSSL 3.0.15

### Describe the bug
If you set renegotiaion time to 0 the openvpn intance will crash silently.

### To Reproduce
VPN -> OpenVPN -> Instances -> Add / Edit

![image](https://github.com/user-attachments/assets/e3f78dfc-2aae-4c84-a82f-3cc2b2b7fd56)
![image](https://github.com/user-attachments/assets/0dceff64-1986-4bbe-a9e0-d306323fafff)
![image](https://github.com/user-attachments/assets/a0570274-dddd-45d0-9450-a51a8442c0e8)

Save and Apply

### Shell
I tried to get more information on the shell: 
instance stopped

The gui produces this config:
![image](https://github.com/user-attachments/assets/75d346ef-32b4-4f51-991a-80d9905b3833)

execute this
![image](https://github.com/user-attachments/assets/acf5e91a-e958-4363-88a5-92f99b75e8f9)

will produce
![image](https://github.com/user-attachments/assets/deb3a5d9-b4d5-4890-962f-c1540d967f02)







### Logs
2024-09-20T11:11:29	Error	openvpn	/usr/local/opnsense/scripts/openvpn/ovpn_service_control.php: The command '/usr/local/sbin/openvpn --config '/var/etc/openvpn/instance-d785bb53-fb3c-4204-886a-14c086a5a6af.conf'' returned exit code '1', the output was ''	
2024-09-20T11:11:29	Warning	openvpn_server2	Use --help for more information.	
2024-09-20T11:11:29	Error	openvpn_server2	Options error: --auth-gen-token needs a non-infinite --renegotiate_seconds setting

### Screenshots
![2024-09-20 15_37_39-Instances_OpenVPN_VPN ](https://github.com/user-attachments/assets/6dcfbbc4-2614-49b8-b291-419bec5ef430)
perhaps you can remove those hints until this is fixed

**Comment by fichtner** [comment]
Thanks for the details. Looks like we miss a validation. Im passing this to @AdSchellevis to fix.


Cheers,
Franco
