### ISSUE TITLE
Captive Portal as independent module / plugin

### ISSUE THREAD

**Issue by Mad-Onion** [opnsense/core#770]
Hey everyone,

I'm using and heavily customizing opnsense's captive portal but with every release i have to re-implement the changes.
Is there a plan to make an independent module / plugin out of it, so that I can fork and customize it in a more satisfying manner?

Best regards
Tobias

**Comment by AdSchellevis** [comment]
Hi Tobias,

There's no plan to put the CP into a separate module at the moment,  but your probably referring to the changes between 15.7 and 16.1.
In the current version you shouldn't need to customize the pages, we solved that with the new template system which is fully detached and can be used as a package on other machines.
If you want to extend authentication, just create a new auth plugin and it should be ready to use as long as you follow our standards.

Because CP and the traffic shaper both use ipfw, it's just not very practical to put it into a separate plugin at the moment.

The 15.7 Captive portal had a lot of issues and was based on very old code which wasn't very maintainable, the new version offers better extendibility.

Regards,

Ad
