### ISSUE TITLE
Dashboard->Lobby->Firewall rules: Popup window content

### ISSUE THREAD

**Issue by bringha1** [opnsense/core#783]
When clicking reverse lookup on any address  in Dashboard->Lobby->Firewall Rules, a popup window appears showing

`<!doctype html>

<html lang="de-DE" class="no-js">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="robots" content="index, follow, noodp, noydir" />
    <meta name="keywords" content="" />
    <meta name="description" content="" /`

Browser is Safari ...

**Comment by azdps** [comment]
I think bringha1 was referring to the Dashboard->Lobby->Firewall Logs widget since there isn't a firewall rules widget. I can confirm the same error using **Chrome** when selecting "Reverse Resolve with DNS".

On a side note when selecting resolve under Firewall->Log Files->Normal View works as intended.

**Comment by AdSchellevis** [comment]
The whole widget collection needs more attention at some point in time.
For now I fixed it back to the state it was in before, using this commit https://github.com/opnsense/core/commit/d4d07fbb8e484046e1383f15ced8bdd957df65a0
