### ISSUE TITLE
Enabling syncookies breaks traffic that both originates and terminates on the firewall

### ISSUE THREAD

**Issue by no-usernames-left** [opnsense/core#8008]
**Important notices**
- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**
Enabling syncookies breaks traffic both originating and terminating on the firewall (such as when you put Caddy in front of the OPNsense web GUI).

**To Reproduce**
1. Set up Caddy to proxy the OPNsense web GUI according to [the tutorial](https://docs.opnsense.org/manual/how-tos/caddy.html#reverse-proxy-the-opnsense-webui)
2. SSH into the firewall
3. `openssl s_client -connect 127.0.0.1:443` (or `:8443`; both are affected, showing it's neither a Caddy nor a lighttpd issue)
4. See your certificate and be happy
5. `Firewall - Settings - Advanced`, change `Enable syncookies` from `never (default)` to `always`, click Save
6. `openssl s_client -connect 127.0.0.1:443` (or `:8443`)
7. After connection and a delay of many seconds, see `write:errno=54` and be sad

**Expected behavior**
Not this.

**Additional context**
Discovered while troubleshooting [this issue](https://github.com/opnsense/plugins/issues/4024).

**Environment**
OPNsense Business 24.4_8 (amd64)
os-caddy 1.5.4_1

**Comment by AdSchellevis** [comment]
After investigation, an issue was found for IPv6 (https://reviews.freebsd.org/D47257), but when using syncookies in general we apparently run into an implementation limitation.

In order to use syncookies, all [`tcp`] rules need to be stateful, which in our case for loopback (`lo0`) is not the case since https://github.com/opnsense/core/commit/a9a67b42550a083388e9ed5d24033e008cce437d. 

Short term, we can make the loopback rule stateful when syncookies are used, which likely has downsides (certainly when killing states), but is likely less problematic than the current implementation.

Long term, we should decide if we should use `pf` on `lo0` as OpenBSD does seem to recommend skipping loopback (https://www.openbsd.org/faq/pf/filter.html) as best practice. Filtering `lo0` and allowing all with a rule has been the case from the beginning it seems (https://github.com/pfsense/pfsense/blame/349aa28eb1bb7cddc1c369f1536c70f139c4bae3/etc/inc/filter.inc#L876-L880).

A clear note about the state limitations of the feature are likely also a good idea.
