### ISSUE TITLE
Wireguard - Track IPv6 Interface for dynamic GUA prefix delegation to Tunnel Address

### ISSUE THREAD

**Issue by Starkstromkonsument** [opnsense/core#8096]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

I have an internet connection with dynamic IPs (Dual Stack). I use the Track IPv6 Interface feature for all my internal Interfaces for prefix delegation.

I use Wireguard for my Road Warriors and want to provide dual stack internet access to them. Using ULAs as Tunnel Addresses results in IPv4 internet access only, as ULAs are not beeing routed globally and IPv4 is preferred above ULA. 

**Describe the solution you like**

Add the abbility die delegate dynamic GUA prefixes from WAN to WireGuard Tunnel Address using the Track IPv6 Interface feature.

**Describe alternatives you considered**

Get some static GUA prefix from somewere else. Prefix delegation would be way more straight forward though!

**Additional context**

 * https://forum.opnsense.org/index.php?topic=31020.0
 * https://forum.opnsense.org/index.php?topic=21858.0

**Comment by Monviech** [comment]
If it would be dynamic, who would change the IPv6 adresses used by the connecting peers?

There is no push mechanism like in OpenVPN (server push) or IPSec (IKE configuration payload) that tell the connecting peer what to configure as address.

**Comment by Starkstromkonsument** [comment]
I'm not sure, whether this is possible. My idea is:

- Only the prefix is dynamic --> the host part of the tunnel address and allowed IPs could be configured statically, e.g. `::a:b:c:d/128`.
- When a prefix change occurs, the wireguard instance would have to be updated automatically to use the new prefix for tunnel address and allowed IPs.
- The road warriors will have to reconnect anyway, because they loose connection in consequence of the IPv6-Prefix and IPv4-Public change (a client side restart is required, some apps offer a ping mechanism to automate this). They will get the the new endpoint prefix via dynamic DNS.
- I don't know whether it is possible to update the prefix dynamically on the client side though. Is this your point? If it can not be pushed/pulled, it cloud be implemented in the client side app to use the endpoint prefix from the dynamic DNS.

**Comment by Monviech** [comment]
I'm pretty sure that `address` (so the inner tunnel IP) is only allowed to be static. This whole concept would need to be handled with wireguard itself, but the protocol is not designed around this on the inner tunnel (from what I know).

It would be probably more feasible with IPsec, even though it would still need a lot of glue and I am unsure if its a good idea.

https://docs.opnsense.org/manual/how-tos/ipsec-swanctl-rw-ikev2-eap-mschapv2.html#rw-swanctl-method1

Since you can create pools for ipv4 and ipv6 and the IKE configuration payload pushes the IP addresses to the client, it could be dynamic if this pool could be dynamic. That's just a random idea though.
