### ISSUE TITLE
Feature : Automatic updates

### ISSUE THREAD

**Issue by tifredfr** [opnsense/core#814]
Hi,

To apply the days of automatic updates, be notified when an update is available, you can apply the updates if the reboot is not necessary …

System > Firmware > Auto updates
- enabled
- send notification if update available (required configured SMTP see System: Settings: Notifications)
- define the verification period (check daily at 2H or check every Friday at 2H for exemple)
- apply the updates if a restart is not required or apply all updates
- send an update report if updates

**Comment by fraenki** [comment]
I'd go a little further and add the following auto-upgrade settings. This would make the auto-upgrade usable to a wide range of users:

Check for Updates:
( ) Weekly
(*) Daily
( ) Hourly

Update Mode:
(*) Apply only minor updates {default}
( ) Apply minor and major updates
( ) Apply only security-related minor updates

Update Period:
(*) Install updates immediately (after a short random delay) {default}
( ) Only during specific times (cron-like pattern)

Automatic Reboot:
(*) Enable (Required to install all updates) {default}
( ) Disabled (Warning: Some updates may not be installed)

Of course, auto-upgrades are a little risky, especially if many users make use of them. A critical bug may render a many systems unusable. A possible countermeasure: Maybe enabling auto-upgrade should *require* the _automatic_ submission of crash reports (so that the developers may be able to remove a broken update rather sooner than later).

**Comment by thelinuxfr** [comment]
Nice @fraenki 

Indeed, one can also add a timeout. 
For example : If update available, apply in X days. In general, critical problems after an update is corrected after a few days ...

**Comment by fichtner** [comment]
Some of this is already on -devel, with a cron job and auto-update. I'm a bit against further granularity. We can prevent the system from updating if it needs to reboot, but the reporting side will need more code that its worth. ;)

**Comment by fraenki** [comment]
@fichtner I'm OK with the current state. The new `auto-update` command makes it easy to write a custom upgrade script.

**Comment by fichtner** [comment]
You can use the cron page too. :) Will be available in the menu soon enough too. It's already on -devel or access directly via https://FIREWALL/ui/cron/

**Comment by fichtner** [comment]
(Leaving this open, setting target to 17.1)

**Comment by thelinuxfr** [comment]
Nice thx ;)

**Comment by fichtner** [comment]
Time to review...

Check for updates: all done, can chose a cron pattern

Update mode: we could split reboot/non-reboot. Tricky are cases where we go from 16.1 -> 16.7, but we can find a mode there too. That's as far as I would like to go: no reboot, full reboot, major update. Ok?

Update period: cron pattern is enough here, marking it done...

Automatic reboot: taken care of in update mode.

@thelinuxfr  @fraenki  Does that sound reasonable?

**Comment by fraenki** [comment]
@fichtner Sounds reasonable, very satisfying results :)

**Comment by thelinuxfr** [comment]
@fichtner yes I'm fine, thank you for the work

**Comment by fichtner** [comment]
I'm going to simplify this: update per cron work, reboot if necessary. major upgrades will not be available using a "normal" firmware update scheme so we don't have to protect against it. Closing. :D
