### ISSUE TITLE
Proposal: Move /System/Diagnostics/Halt & Reboot system to /System/Runlevel (or similar)

### ISSUE THREAD

**Issue by b2000699** [opnsense/core#837]
I believe that halting and rebooting is not a diagnostic but a command that alters the runlevel of an OS. Thus, I suggest placing it in /System/Runlevel, /System/Control, or some similar named submenu of /System.

Maybe even /Services/Wake on LAN could be sorted in there afterwards, so that all runlevels (power on, power off, reboot) are in one place.

Cheers

**Comment by mschilt** [comment]
+1. My non-IT brother always struggles to find the 'reboot' command.
I think 'Control' would be the better term since runlevels are nonsense for 'non-powerusers'

**Comment by AdSchellevis** [comment]
@mschilt Because chances are very small everybody wants the same menu layout, I'm referencing the other menu issue here https://github.com/opnsense/core/issues/832 , which contains a simple explanation (in the comments) of how to change your menu to exactly your own preference.  

Whatever the end result will be, you can always change things the way you like,  our system is pluggable :)

**Comment by fichtner** [comment]
All under firmware now.
