### ISSUE TITLE
User shell reset on reboot

### ISSUE THREAD

**Issue by pdf** [opnsense/core#93]
There's no method to select a user's shell from the UI, and if an alternative shell is set via `chsh` or editing `/etc/passwd`, it's reset to /bin/csh every boot.

**Comment by StopTrain** [comment]
Curious, why would there be a custom user shell on the command line?

**Comment by pdf** [comment]
Because I don't like csh?

**Comment by fichtner** [comment]
Nobody likes csh, but it is still the default for FreeBSD. Well, are we talking about the root user or some other user on the system? The OPNsense config needs to stay in sync with the system so it enforces its config on reboot, resetting all things so you can port configs to different machines and end up with an exact copy that works.

I see you are referring to rc.d scripts and different shells. You are likely trying to use the system for your purposes as well. Can you tell me more about those?

I can see that we could add an option sh(1), but I don't like the idea of pulling in bash or zsh or anything else...  FWIW, you can probably create a user away from OPNsense on the command line and configure this one in every way you like without OPNsense interfering.

**Comment by pdf** [comment]
Allowing user-configurable shells shouldn't be out of the question I wouldn't think, in fact in #67 you suggested that it should be, @fichtner :wink:.  The list of valid shells is maintained in /etc/shells, so my suggestion would be to allow selection of any binary that both exists in that file, and on the filesystem.  If either doesn't exist at boot/import I guess you just reset it to csh and log a warning.

As for 'other purposes', I just need to run some daemons that aren't catered for by the OPNsense GUI, and I'm a sysadmin by trade, so I use the CLI a lot.

**Comment by fichtner** [comment]
Yes and no. I suggested that as a workaround for the current root shell. Picking shell meaning console menu (yes, it's a shell now) or plain shell instead. The standard shells in FreeBSD are sh, csh and tcsh. We do not supply shell packages. I also do not think I want to maintain that because then somebody will ask for zsh and fish and ksh and then bash. That's a maintenance nightmare waiting to happen. After shellshock I'm also inclined to deny official bash builds for as long as I can.

If you create your own user you can use it in whatever way you like. We can't simply jeopardise maintainability and code clarity as well as security for convenience.

I understand your intentions, but having to bring embedded support up to speed and general spring clean of the code base occupies most of my time and these items are direly required.

**Comment by pdf** [comment]
> I suggested that as a workaround for the current root shell.

Well, specifically:

```
essentially you can pick your shell in the user manager or at least you should be able to
```

> We do not supply shell packages. I also do not think I want to maintain that because then somebody will ask for zsh and fish and ksh and then bash. That's a maintenance nightmare waiting to happen. After shellshock I'm also inclined to deny official bash builds for as long as I can.

There's some discussion in [this forum topic](https://forum.opnsense.org/index.php?topic=42) that's pertinent to problem of lack of available packages on OPNsense, and some options to deal with it.  I'd be inclined to just allow FreeBSD as an overlay, rather than building everything in your own repos.  If the effort you're talking about is maintaining the UI for shell selection, and not the effort of maintaining packages (which should be largely automated?), then the method I've outlined above requires zero modification to deal with any valid shell - the shells file will be kept up to date by the package manager, and the simple subsequent check of the filesystem makes sure that file hasn't been broken somehow.

Denying bash builds because of an exploit that's already been patched, and at the expense of user-preference doesn't seem sensible to me, bugs may be lurking in other shells too.  And if the user has specifically installed something that's not bundled in the base system, the onus is on them to make sensible choices.

I'm not suggesting this should be a priority (it's mainly just an annoyance to have to reset shells every reboot), but user-selectable shells in the UI would appear to be a useful feature, and resetting user shells on reboot manifests like a bug for anyone who tries to use something other than csh for a user that exists in the UI.  So, it's at least documented here for anyone who stumbles over it.

**Comment by fichtner** [comment]
I'm trying to see the OPNsense dev and ops side of this. Essentially, the scope of this request is:

(1) Change a few lines in the core.git to support more shells. That is easy. That is what you have to think about.

But there's more we'll need to make sure:

(2) Add a undefined number of shell packages to the tools.git. (What *is* your favourite shell, I can't tell--what is the favourite shell of everybody else?) That is easy in itself, but increases install media size, build times and broadens the attack surface. True, we'll always have past/present/future security holes, but that is exactly why attack surface should be picked with consideration as opposed to saying "it'll happen anyway".

(3) In the ports.git, pull in all the shell ports as well and keep them up to date. There's a reason why binary FreeBSD ports are experimental in OPNsense, in the scope of ports that is because we do not want to depend on a base OpenSSL and other src.conf modifications, but all FreeBSD ports are built in a very generic way. It *will* eventually clash with our setups, so having a clean OPNsense repository with more ports is the only option that I see at this point. We will eventually move to LibreSSL, which is liked by many, and that further complicates using FreeBSD ports.

(4) In the src.git we have legacy patches that other projects have not pushed upstream for reasons unbeknownst to its community. These patches destroy ABI compatibility with FreeBSD ports. Removing those patches eventually is a long-term effort.

All of those can be solved by using the repositories and building your own version according to your needs. When one can live with all the if and but that's great. When there is a community that expects us to be sane and reasonable that's not a sensible way to force this in.

**Comment by pdf** [comment]
1. This is probably all that needs to change in OPNsense for the foreseeable future, even tcsh would be an improvement over csh.  It would also solve #67, since the menu script is listed in /etc/shells users could switch between that and another valid shell.  Let's concentrate on this as the actual issue, rather than all the following broader stuff. 
2. I don't have a good sense of how your build process works, but I wouldn't expect to include any alternative shells in the install media, or install them by default, so I don't think any of these issues apply.
3. You probably know best if this is true, seems like an unfortunate path to go down.  Doesn't it work currently because OPNsense packages are built against a packaged version of \*SSL, but FreeBSD packages are built against the system SSL?  This segregation makes good sense if it works, and if people are going to run unsupported software, I'd say it's their responsibility to understand any security implications.
4. Well, that certainly may present a problem if there really are ABI breakages in those patches.

As some background, I've been maintaining an x86_64 port of OpenWRT for my purposes, but it's labor-/build-/bandwidth-intensive for similar reasons to the path you're heading down here.  Between that, and the frequent bugs in all their custom daemons and patched software (though I understand why they're used in that project, as it targets really minuscule hardware), I'd hoped to find something with better reliability, less maint overhead and greater flexibility.  It's not sounding likely this project will satisfy all those goals for me sadly.

**Comment by fichtner** [comment]
Change https://github.com/opnsense/core/blob/06881b90fe93475ff89ef88042b29f0a041781be/src/etc/inc/auth.inc#L416 to adapt to a different shell. Won't change away FreeBSD's default shell without a better design.
