### ISSUE TITLE
pfctl: driver does not support altq

### ISSUE THREAD

**Issue by lukepower** [opnsense/core#97]
Hi there,

when setting up Traffic Shaping in my setup with VLAN's, I always get such erorrs:

03-19-15 13:02:16 [ There were error(s) loading the rules: pfctl: em2_vlan20: driver does not support altq - The line in question reads [0]: ]

Any idea how to fix this?

**Comment by fichtner** [comment]
Opening the issue twice won't solve it faster. The actual issue is part of src.git, not core.git or ports.git.

**Comment by lukepower** [comment]
Sorry for that -  I am a bit too fresh on this bugtracker thing.
If I can somehow help in finding the cause and fix it let me know :)

Thanks

**Comment by fichtner** [comment]
No worries. :) It's good to know that it is about em(4) not working as expected. Can you tell me which algorithm you are using? I can dig a little in the commit history. It is a pity that these patches are not freely available in FreeBSD 10.1 though.

**Comment by lukepower** [comment]
Alright, here the details of the driver (it's the same for all interfaces):

em3: <Intel(R) PRO/1000 Network Connection 7.4.2> port 0xc000-0xc01f mem 0xf7cc0000-0xf7cdffff,0xf7c00000-0xf7c7ffff,0xf7ce0000-0xf7ce3fff irq 19 at device 0.0 on pci4

I'm using HFSC as algorithm on this system. I am not sure, looking at the FreeBSD documentation (https://www.freebsd.org/cgi/man.cgi?query=altq&sektion=4) they say one has to enable a few kernel options at compile time...

**Comment by dsbaars** [comment]
+1 for this.
We also have this problem with the OPNsense "A10 Dual Core rack" with OPNsense 15.1.9.

**Comment by AdSchellevis** [comment]
With the intel igb driver it's a legacy support issue, the em driver supports altq, but FreeBSD does not have vlan support for altq (https://forums.freebsd.org/threads/altq-on-vlan.22855/). 

pfSense had a custom patch for that (if_vlan_altq.diff), but it's not very likely that this will make it into standard FreeBSD.
We haven't included all the pfSense kernel patches and this one isn't in it.

**Comment by dsbaars** [comment]
@AdSchellevis Is it possible to add this patch? We have just switched to OPNsense. 
Otherwise we have to switch back to pfSense because we'd like to use traffic shaping in VLANs.

**Comment by AdSchellevis** [comment]
@dsbaars Unfortunately we're not going to reimplement the pfSense patches, because there is a lot of unexpected behaviour in them and we try to revert things back to how they're supposed to work in FreeBSD. However we will reimplement the traffic shaper with dummynet, which will probably be there in 15.7. Depending on your needs, this might deliver the feature set you're looking for.

**Comment by dsbaars** [comment]
Thanks for your quick response, do you have an ETA for this?

**Comment by AdSchellevis** [comment]
It's (almost) on the top of my list, but before 15.7 (July) it will certainly be there. Our next release (this week) contain a lot of kernel cleanups needed to revert behaviour back to standard, there where really weird hacks in the kernel producing issues nobody has using standard FreeBSD. I have confirmed dummynet working on our side using the new kernel, but we still have to glue all the bits and pieces together and put a new shiny gui on top of it.

**Comment by dsbaars** [comment]
Does this mean this is indeed implemented now? If not, I rather see this issue opened again so other contributors can implement this or provide another solution.

**Comment by AdSchellevis** [comment]
No, this is not going to be implemented, because it's not in FreeBSD and very likely will never be in there. The traffic shaper using dummynet will be implemented, but it seemed we didn't had an issue for that one. just opened it : https://github.com/opnsense/core/issues/161

Our main focus is to keep away from non standard hooks, to avoid low level issues which don't exist in the standard kernel (or ports collection).  We try to avoid fixing things that weren't broken in the first place.

**Comment by dsbaars** [comment]
That makes (opn)sense, thanks for explaining!

**Comment by AdSchellevis** [comment]
you're welcome!
