### ISSUE TITLE
Frequent re-login required

### ISSUE THREAD

**Issue by andreas-p** [opnsense/core#988]
Since I'm on 16.1.14 (I might have skipped some versions) I'm frequently required to re-login when navigating to a different menu item. I already cleared the cache, didn't improve.

**Comment by L1ghtn1ng** [comment]
The newest version is 16.1.15 FYI I do recommend that you upgrade however and see what you get on that version then report back if that happens

**Comment by andreas-p** [comment]
Sorry that was a typo: I am already on 16.1.15.

**Comment by L1ghtn1ng** [comment]
Okay then you are on the latest and do you have logout after a certain period? If not will have to wait for Ad or Franco to chip in

**Comment by andreas-p** [comment]
It doesn't look like a timeout. I just went back to a session that's 90min+ untouched, and I was still logged in and could work normally.
OTOH, another session to a different FW I select a different menu, and get redirected to the login.

**Comment by AdSchellevis** [comment]
Can you check your system.log from around the time of the issue?

```
clog /var/log/system.log
```

It could be an issue with your network connection (cabling, network card, etc), causing a reset from time to time.

**Comment by AdSchellevis** [comment]
timeout

**Comment by andreas-p** [comment]
This is NOT fixed.
Nothing in the system log:
Jul 19 10:08:11 firewall2 opnsense: /index.php: Successful login for user 'xxx' from: y.y.y.y
Jul 19 10:10:27 firewall2 opnsense: /services_ntpd.php: Successful login for user 'xxx' from: y.y.y.y

**Comment by andreas-p** [comment]
I have a new observation about this issue: it happens only if the FW is accessed via a rule on the WAN interface (WAN-IP:https -> localhost:https) , if the WAN interface is not connected to the internet directly but cascaded over another firewall (using a private IP transfer net; I don't maintain myself).

Usually, my browser should propose the user name when /index.php is shown, but the proposal list is empty. If I tab to the passwd field and tab back to the user field, the proposal list will be filled.
Accessing the same firewall via LAN interface doesn't show this anomaly.

**Comment by fichtner** [comment]
The first issue sounds like the session ID is lost, I don't know if it's scrubbed or what else happens in the network. A proxy setup could interfere as well. It's difficult to say. There is no apparent or quick fix. Digging through the 16.1.8 to 16.1.14 change logs did not reveal any obvious things.

Worst case this is induced by changed behaviour in PHP itself, although I doubt this as there have been no other reports.

The "proposal" list is part of the browser and we can't do anything about this.

In general, bug reports will consist of the following in order to be able to help effectively: conditions to reproduce (also includes browser versions, access paths, configuration hints), verified known good and bad versions (best the two successive versions that are good and bad).


Thanks,
Franco
